name: brandslabels
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+7

environment:
  sdk: ">=2.15.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  awesome_dialog: ^3.0.2
  bottom_navy_bar: ^6.0.0
  cached_network_image: ^3.2.1
  carousel_slider: ^4.0.0
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.2
  datetime_picker_formfield: ^2.0.1
  device_info_plus: ^8.0.0
  dio: ^4.0.6
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.0.6
  firebase_dynamic_links: ^5.0.6
  firebase_messaging: ^14.1.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_html: ^3.0.0-alpha.6
  flutter_local_notifications: ^12.0.3+1
  flutter_screenutil: ^5.2.0
  flutter_signin_button: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.6
  get: ^4.6.1
  get_storage: ^2.0.3
  http: ^0.13.5
  intl: ^0.17.0
  jiffy: ^5.0.0
  json_annotation: ^4.7.0
  livechatt: ^1.4.0
  lottie: ^2.0.0
  package_info_plus: ^3.0.2
  photo_view: ^0.14.0
  sentry_dio: ^6.13.1
  sentry_flutter: ^6.9.1
  sms_autofill: ^2.2.0
  transparent_image: ^2.0.0
  url_launcher: ^6.1.0
  meta_package:
    path: ../Meta-Package
    # git:
    #   url: https://github.com/MioModaFlutter/Meta-Package.git
    #   ref: master
    # path: Meta-Package
#     git:
#       url: git@github.com:MioModaFlutter/Meta-Package.git
#       ref: master

dev_dependencies:
  build_runner: ^2.1.7
  flutter_gen_runner:

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_foreground: assets/icons/appiconbg.png
  adaptive_icon_background: "#000A60"
  min_sdk_android: 21 # android min sdk min:16, default 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - env
    - assets/images/bag.png
    - assets/images/india_flag.png
    - assets/images/magnifying_glass.png
    - assets/images/menu.png
    - assets/images/user.png
    - assets/images/brands_labels.png
    - assets/images/
    - assets/icons/
    - assets/json/
    - assets/images/header_logo.png
    - assets/images/flag.png
    - assets/icons/cart.png
    - assets/icons/search.svg
    - assets/icons/user.png
    - assets/flags/
    - assets/animations/
    - assets/svgs/
    - assets/images/home/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 900
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 900
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans/OpenSans-ExtraBold.ttf
          weight: 900
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
