const Map<String, String> ar = {
  "language": "إنجليزي",
  "homeText": "الصفحة الرئيسية",
  "searchText": "بحث",
  "designersText": "المصممين",
  "yourEmailText": "بريدك الالكتروني",
  "gdpText": "الناتج المحلي الإجمالي",
  "englishText": "إنجليزي",
  "checkoutText": "الدفع",
  "purchaseText": "الرجاء إدخال التفاصيل الخاصة بك أدناه لإكمال عملية الشراء",
  "shippingAddressText": "عنوان الشحن",
  "shippingMethodText": "طريقة الشحن",
  "paymentMethodText": "طريقة الدفع او السداد",
  "orderSummaryText": "ملخص الطلب",
  "createCheckoutText": "يمكنك إنشاء حساب بعد الخروج.",
  "stLine1": "العنوان (الخط 1",
  "stLine2": "عنوان الشارع: الخط 2",
  "stLine3": "عنوان الشارع: الخط 3",
  "cityText": "مدينة",
  "indiaText": "الهند",
  "stateText": "الرجاء تحديد منطقة أو ولاية أو مقاطعة",
  "zipCodeText": "الرمز البريدي / الرمز البريدي",
  "phoneNumberText": "رقم التليفون",
  "itemInCartText": "عنصر في عربة التسوق",
  "applyDiscountCodeText": "تطبيق كود الخصم",
  "enterDiscountCodeText": "أدخل رمز الخصم",
  "applyDiscountText": "تطبيق الخصم",
  "orderTotalText": "الطلب الكلي",
  "orderCommentText": "طلب التعليق",
  "placeOrderText": "مكان الامر",
  "myAccountText": "حسابي",
  "appNameText": "فيرا لوسو",
  "aboutUsText": "معلومات عنا",
  "aboutUsContain":
      'VERA LUSSO هي أفضل وجهة للأزياء الفاخرة عبر الإنترنت مع 5 ملايين زائر شهريًا والشحن في جميع أنحاء العالم.',
  "aboutUsContain1":
      'يتميز الموقع بأفضل اختيار لأفضل المصممين وكذلك المواهب الناشئة الشابة. تأسست vera lusso في فلورنسا في أوائل ثلاثينيات القرن الماضي ، مع افتتاح متجر مفهوم باسم الشركة في شارع Via Roma. عبر الإنترنت منذ عام 1999 ، تنسب الشركة 90٪ من إجمالي الإيرادات إلى المبيعات عبر الإنترنت. حتى يومنا هذا ، لا تزال شركة عائلية مملوكة للقطاع الخاص بنسبة 100٪ ، حيث يتولى حفيد المؤسس ، أندريا بانكونيسي ، منصب الرئيس التنفيذي وابنته ، أناغريتا بانكونيزي ، مديرة إبداعية.',
  "aboutUsContain2":
      'يقدم الموقع مجموعة واسعة من الملابس والأحذية والحقائب والإكسسوارات والديكورات المنزلية الفاخرة والجمال ، مع منتجات متاحة للرجال والنساء والأطفال من أشهر المصممين مثل Balenciaga و Vetements و Off-White و J.W. Anderson و Balmain و Dolce & Gabbana و Gucci و Saint Laurent و Valentino و Givenchy و Loewe Jacquemus والمزيد.',
  "aboutUsContain3":
      'يوجد حاليًا 200 شخص من 15 دولة مختلفة يعملون على إنتاج وصيانة فيرا لوسو. الموقع متاح بـ 9 لغات: الإنجليزية والإيطالية والألمانية والصينية والروسية والإسبانية والفرنسية والكورية واليابانية. تم إنشاء الموقع داخليًا بالكامل ، من خلال مكتب فلورنسا للتصميم الجرافيكي وتكنولوجيا المعلومات وخدمة العملاء والتسويق والشراء. يعمل المصممون والفرق الصحفية من مكتب فيرا لوسو في عاصمة الموضة في العالم - ميلانو.',
  "aboutUsContain4":
      'يتم شحن جميع الطلبات في جميع أنحاء العالم من المقر الرئيسي لشركة فيرا لوسو في صناديق معدة بأقصى قدر من العناية وتستخدم أجود المواد ، من أكياس الأحذية المميزة إلى الشريط المخصص.',
  "aboutUsContain5":
      'استقبل موقع vera lusso 1.5 مليون زائر فريد من نوعه في عام 2008 ونما إلى 53 مليون زائر فريد في عام 2017. ويتم إنشاء أكثر من 15٪ من المبيعات عبر الإنترنت من الولايات المتحدة ، تليها ألمانيا والمملكة المتحدة وإيطاليا والصين وفرنسا.',
  "aboutUsContain6":
      'تتخطى Vera lusso حدود مشهد البيع بالتجزئة الفاخرة سواء عبر الإنترنت أو خارجها من خلال مجموعة من الخدمات الحصرية ومبادرات العلامات التجارية بما في ذلك Buy It First و Luxury Club و Sneakers Club و LVR Privilege و LVR Editions.',
  "orderConfirm": "شكرا لك على الشراء!",
  "orderIdTitle": '"طلبك # هو:"',
  "orderIdIs": ''' 1490004 ''',
  "orderNumberTitle": 'رقم الطلب:',
  "orderNumberIs": ' 2080004',
  "orderDateTitle": 'تاريخ الطلب:',
  "orderDateIs": ' 7 سبتمبر 2021',
  "image": 'صورة',
  "productName": 'اسم المنتج',
  "sku": 'SKU',
  "price": 'السعر',
  "qty": 'الكمية',
  "subTotal": 'المجموع الفرعي',
  "action": 'عمل',
  "buyBack": 'اعادة شراء',
  "orderContain":
      "سنرسل إليك رسالة إلكترونية لتأكيد الطلب مع التفاصيل ومعلومات التتبع.",
  "referFriendText": "ادع صديق",
  "returnsRefundsText": "العوائد والمردودات",
  "faqText": "التعليمات",
  "contactText": "اتصل",
  "socialText": "اجتماعي",
  "companyText": "شركة",
  "contactUs": "اتصل بنا",
  "myOrders": "طلباتي",
  "myOrderImage": "صورة",
  "quantity": "الكمية",
  "status": "حالة",
  "paymentMethod": " طريقة الدفع او السداد",
  "shippingAddress": "عنوان الشحن",
  "billingAddress": "عنوان وصول الفواتير",
  "continueShopping": "مواصلة التسوق",
  "goToYourAccountText": "اذهب إلى حسابك",
  "emailAddressText": "عنوان بريد الكتروني",
  "passwordText": "كلمة المرور",
  "saveYourFavoriteItemsInAWishListText":
      "احفظ عناصرك المفضلة في قائمة الرغبات",
  "cardsText": "احفظ بطاقاتك وعناوين الشحن المفضلة",
  "shippingText": "تحقق من تفاصيل وحالة طلباتك والمرتجعات",
  "registerText": "تسجيل",
  "registerWithFacebookText": "سجل في الفيسبوك",
  "logInAndEnjoyAPersonalizedShoppingExperienceText":
      "سجّل الدخول واستمتع بتجربة تسوق مخصصة.",
  "dontHaveAnAccountYetText": "لا تملك حسابا حتى الآن؟",
  "loginWithFacebookText": "تسجيل الدخول باستخدام الفيسبوك",
  "loginText": "تسجيل الدخول",
  "forgotYourPasswordText": "نسيت رقمك السري؟",
  "subscribeToOurNewsletterText": "اشترك في نشرتنا الإخبارية",
  "getAllDescriptionText":
      "احصل على أحدث المعلومات حول الأحداث والمبيعات والعروض. اشترك في النشرة الإخبارية اليوم.",
  "enterYourEmailAddressText": "أدخل عنوان بريدك الالكتروني",
  "subscribeText": "الإشتراك",
  "changeTHEWORLDWithYourPurchaseText": "غيّر العالم بشرائك",
  "companyNameText": "شركة",
  "contactsText": "جهات الاتصال",
  "othersText": "الآخرين",
  "createAnAccountText": "إنشاء حساب",
  "createNewCustomerAccountText": "إنشاء حساب عميل جديد",
  "marketingPurposeText":
      "أوافق على أنه يجوز لشركة Veralusso جمع معلوماتي الشخصية لأغراض تسويقية (النشرات الإخبارية والأخبار والعروض الترويجية).",
  "shoppingHabitText":
      "أوافق على أنه يجوز لـ Veralusso جمع معلوماتي الشخصية لإنشاء ملف تعريف لعادات التسوق الخاصة بي.",
  "unitedKingdomText": "المملكة المتحدة",
  "emailText": "بريد الالكتروني",
  "confirmEmailText": "تأكيد عنوان البريد الإلكتروني",
  "confirmPasswordText": "تأكيد كلمة المرور",
  "firstNameText": "الاسم الأول",
  "lastNameText": "الكنية",
  "dateOfBirthText": "تاريخ الولادة",
  "dateOfMarriageText": "تاريخ الزواج",
  "telephoneNoText": "الهاتف لا.",
  "mr": "السيد.",
  "affiliateProgramTitleText": "برنامج شركة VERALUSSO التابعة",
  "whoAreWeLookingTitleText": "الذي نبحث عنه؟",
  "whoAreWeLookingDescriptionOneText":
      "هل لديك موقع إلكتروني ، أو مدونة ، أو ملف تعريف على وسائل التواصل الاجتماعي ، يتسم بالموضة العصرية ، وله نظرة دولية؟ هل تركز على الموضة ونمط الحياة والجمال والتصميم؟ إذا كان الأمر كذلك ، فنحن نبحث عنك!  n \n انضم إلى برنامج الإحالة العالمي الخاص بنا وستتاح لك الفرصة لكسب عمولة في كل مرة يقوم فيها زوارك بالشراء من VERALUSSO.",
  "whatCanYouExpectTitleText": "ماذا يمكنك أن تتوقع؟",
  "expectRuleOneText": "عمولة على صافي المبيعات المعتمدة",
  "expectRuleTwoText": "نافذة ملفات تعريف الارتباط 45 يومًا",
  "expectRuleThreeText": "يتم تحديث تغذية البيانات عدة مرات في اليوم",
  "expectRuleFourText":
      "الوصول إلى لافتات مخصصة وروابط نصية وروابط عميقة وموجز بياناتنا بـ 9 لغات (الإنجليزية والإيطالية والفرنسية والألمانية والكورية والإسبانية والصينية والروسية واليابانية)",
  "expectRuleFiveText": "إمكانية تخصيص يغذي لجميع العملات العالمية",
  "promoteSoloQuestionText": "كيف يمكنك الترويج لـ VERALUSSO (كشركة تابعة)؟",
  "promoteSoloAnswerOneText":
      "إنشاء محتوى عالي الجودة وجذاب يعكس أسلوب VERALUSSO",
  "promoteSoloAnswerTwoText":
      "عرض المحتوى واللافتات والروابط الخاصة بنا لفئات وأحداث متعددة على موقع الويب الخاص بك وقنوات التواصل الاجتماعي",
  "promoteSoloAnswerThreeText": "الترويج للفوائد التي يحبها عملاؤنا",
  "promoteSoloAnswerFourText":
      "مجموعة مختارة من المقالات المحدثة باستمرار من أفضل العلامات التجارية",
  "promoteSoloAnswerFiveText":
      "عوائد مجانية بدون ضرائب إضافية للولايات المتحدة وكندا والمملكة المتحدة و",
  "howApplyTitleText": "كيفية التقديم؟",
  "howApplyAnswerOneText":
      "أرسل إلينا اسم وعنوان URL لموقعك على الويب أو مدونتك أو ملفك الشخصي على وسائل التواصل الاجتماعي والأسواق الرئيسية. سنراجع موقعك ونعود إليك بمزيد من المعلومات حول كيفية الانضمام إلى البرنامج التابع. n \n الرجاء ملاحظة أنه يتم تقييم جميع الطلبات يدويًا وقد تستغرق المعالجة ما يصل إلى 10 أيام. n \n إذا كنت تشعر أن طلبك تم رفضه بشكل خاطئ ، يرجى التواصل مع affates@veralusso.com وسيقوم أحد أعضاء الفريق بمعالجة مخاوفك.",
  "visitorMonthHintText": "حدد الزوار الفريدون / الشهر",
  "viewsMonthHintText": "حدد مشاهدات الصفحة / الشهر",
  "cityHintText": "مدينة",
  "countryHintText": "دولة",
  "addressOneText": "عنوان الشارع 1",
  "addressTwoText": "عنوان الشارع 2",
  "addressText": "عنوان",
  "letsGoText": "دعنا نذهب",
  "postCodeText": "الرمز البريدي",
  "contactNoText": "رقم الاتصال.",
  "websiteUrlText": "رابط الموقع",
  "profileText": "حساب تعريفي",
  "wishListText": "WhistList",
  "myOrdersText": "طلباتي",
  "myWishlistText": "قائمة امنياتي",
  "addressBookText": "دليل العناوين",
  "accountInformationText": "معلومات الحساب",
  "storePaymentText": "طرق الدفع المخزنة",
  "newsLetterText": "اشتراك الرسائل الإخبارية",
};
