const Map<String, String> cn = {
  "language": "英语",
  "homeText": "家",
  "searchText": "搜索",
  "designersText": "设计师",
  "yourEmailText": "你的邮件",
  "gdpText": "国内生产总值",
  "englishText": "英语",
  "checkoutText": "退房",
  "purchaseText": "请在下方输入您的详细信息以完成购买",
  "shippingAddressText": "送货地址",
  "shippingMethodText": "邮寄方式",
  "paymentMethodText": "付款方法",
  "orderSummaryText": "订单摘要",
  "createCheckoutText": "您可以在结帐后创建一个帐户。",
  "stLine1": "街道地址：1号线",
  "stLine2": "街道地址：2号线",
  "stLine3": "街道地址：3号线",
  "cityText": "城市",
  "indiaText": "印度",
  "stateText": "请选择地区、州或省",
  "zipCodeText": "邮编/邮政编码",
  "phoneNumberText": "电话号码",
  "itemInCartText": "购物车中的物品",
  "applyDiscountCodeText": "应用折扣码",
  "enterDiscountCodeText": "输入折扣码",
  "applyDiscountText": "申请折扣",
  "orderTotalText": "合计订单",
  "orderCommentText": "订单评论",
  "placeOrderText": "下订单",
  "myAccountText": "我的账户",
  "appNameText": "维拉·卢索",
  "aboutUsText": "关于我们",
  "aboutUsContain": 'VERA LUSSO 是一个顶级的在线奢侈品时尚目的地，每月有 500 万游客，并在全球范围内运送。',
  "aboutUsContain1":
      '该网站精选了顶级设计师和年轻的新兴人才。 vera lusso 于 1930 年代初在佛罗伦萨成立，该公司的同名概念店在 Via Roma 开业。自 1999 年以来，该公司将 90% 的总收入归功于在线销售。直到今天，它仍然是一个 100% 私有的家族企业，创始人的孙子 Andrea Panconesi 担任首席执行官，他的女儿 Annagreta Panconesi 担任创意总监。',
  "aboutUsContain2":
      '该网站提供各种服装、鞋子、包袋、配饰、豪华家居内饰和美容产品，其中包括来自 Balenciaga、Vetements、Off-White、J.W. 等最负盛名设计师的男士、女士和儿童产品。 Anderson、Balmain、Dolce & Gabbana、Gucci、Saint Laurent、Valentino、Givenchy、Loewe Jacquemus 等等。',
  "aboutUsContain3":
      '目前有来自 15 个不同国家的 200 人致力于生产和维护维拉卢索。该网站提供 9 种语言版本：英语、意大利语、德语、汉语、俄语、西班牙语、法语、韩语和日语。该网站完全由内部创建，佛罗伦萨办公室设有平面设计、IT、客户服务、营销和采购部门。造型师和新闻团队在世界时尚之都米兰的维拉卢索办公室工作。',
  "aboutUsContain4":
      '所有订单都从 vera lusso 总部装在经过精心准备并使用最优质材料的盒子中运送到全球，从标志性的鞋包到个性化的丝带。',
  "aboutUsContain5":
      '2008 年，vera lusso 有 150 万独立访问者访问该网站，并在 2017 年增长到 5300 万独立访问者。超过 15% 的在线销售来自美国，其次是德国、英国、意大利、中国和法国。',
  "aboutUsContain6":
      'vera lusso 通过一系列独家服务和商标计划，包括 Buy It First、Luxury Club、Sneakers Club、LVR Privilege 和 LVR Editions，在线上和线下推动奢侈品零售领域的界限。',
  "orderConfirm": "感谢您的购买！",
  "orderIdTitle": '''您的订单#是：''',
  "orderIdIs": '''1490004''',
  "orderNumberTitle": '订单号：',
  "orderNumberIs": ' 2080004',
  "orderDateTitle": '订购日期：',
  "orderDateIs": ' 2021年9月7日',
  "image": '图片',
  "productName": '产品名称',
  "sku": '库存单位',
  "price": '价钱',
  "qty": '数量',
  "subTotal": '小计',
  "action": '行动',
  "buyBack": '回购',
  "orderContain": "我们将通过电子邮件向您发送包含详细信息和跟踪信息的订单确认信息。",
  "referFriendText": "推荐朋友",
  "returnsRefundsText": "退货和退款",
  "faqText": "常问问题",
  "contactText": "接触",
  "socialText": "社会的",
  "companyText": "公司",
  "contactUs": "联系我们",
  "myOrders": "我的订单",
  "myOrderImage": "图片",
  "quantity": "数量",
  "status": "状态",
  "paymentMethod": " 付款方法",
  "shippingAddress": "送货地址",
  "billingAddress": "帐单地址",
  "continueShopping": "继续购物",
  "goToYourAccountText": "转到您的帐户",
  "emailAddressText": "电子邮件地址",
  "passwordText": "密码",
  "saveYourFavoriteItemsInAWishListText": "将您最喜欢的物品保存在愿望清单中",
  "cardsText": "保存您的卡片和首选送货地址",
  "shippingText": "检查您的订单和退货的详细信息和状态",
  "registerText": "登记",
  "registerWithFacebookText": "注册脸书",
  "logInAndEnjoyAPersonalizedShoppingExperienceText": "登录并享受个性化的购物体验。",
  "dontHaveAnAccountYetText": "还没有账户？",
  "loginWithFacebookText": "使用 Facebook 登录",
  "loginText": "登录",
  "forgotYourPasswordText": "忘记密码了吗？",
  "subscribeToOurNewsletterText": "订阅我们的新闻",
  "getAllDescriptionText": "获取有关活动、销售和优惠的所有最新信息。立即注册时事通讯。",
  "enterYourEmailAddressText": "输入您的电子邮件地址",
  "subscribeText": "订阅",
  "changeTHEWORLDWithYourPurchaseText": "购买改变世界",
  "companyNameText": "公司",
  "contactsText": "联系方式",
  "othersText": "其他",
  "createAnAccountText": "创建一个帐户",
  "createNewCustomerAccountText": "创建新客户帐户",
  "marketingPurposeText": "我同意 Veralusso 可以出于营销目的（通讯、新闻和促销）收集我的个人信息。",
  "shoppingHabitText": "我同意 Veralusso 可以收集我的个人信息来创建我的购物习惯档案。",
  "unitedKingdomText": "英国",
  "emailText": "电子邮件",
  "confirmEmailText": "确认电子邮件",
  "confirmPasswordText": "确认密码",
  "firstNameText": "名",
  "lastNameText": "姓",
  "dateOfBirthText": "出生日期",
  "dateOfMarriageText": "结婚的日期",
  "telephoneNoText": "电话号码。",
  "mr": "先生。",
  "affiliateProgramTitleText": "VERALUSSO 会员计划",
  "whoAreWeLookingTitleText": "我们在找谁？",
  "whoAreWeLookingDescriptionOneText":
      "您是否拥有时尚前卫、以奢侈品为导向的网站、博客、社交媒体资料，了解趋势并具有国际视野？您关注的焦点是时尚、生活方式、美容和设计吗？如果是这样，我们正在寻找您！\n\n加入我们的全球联盟计划，您将有机会在每次访问者从 VERALUSSO 购买时赚取佣金。",
  "whatCanYouExpectTitleText": "你能期待什么？",
  "expectRuleOneText": "所有批准的净销售额的佣金",
  "expectRuleTwoText": "45 天 cookie 窗口",
  "expectRuleThreeText": "数据馈送每天更新多次",
  "expectRuleFourText":
      "以 9 种语言（英语、意大利语、法语、德语、韩语、西班牙语、中文、俄语和日语）访问定制的横幅、文本链接、深度链接和我们的数据源",
  "expectRuleFiveText": "可以将订阅源自定义为所有世界货币",
  "promoteSoloQuestionText": "您如何推广 VERALUSSO（作为会员）？",
  "promoteSoloAnswerOneText": "创建反映 VERALUSSO 风格的高质量和引人入胜的内容",
  "promoteSoloAnswerTwoText": "在您的网站和社交媒体渠道上为多个类别和活动提供我们的内容、横幅和链接",
  "promoteSoloAnswerThreeText": "推广客户喜爱的福利",
  "promoteSoloAnswerFourText": "精选来自最佳品牌的持续更新文章",
  "promoteSoloAnswerFiveText": "美国、加拿大、英国和",
  "howApplyTitleText": "怎样申请？",
  "howApplyAnswerOneText":
      "通过电子邮件将您的网站、博客或社交媒体资料以及您的主要市场的名称和 URL 发送给我们。我们将审核您的网站，并回复您有关如何加入联属网络营销计划的更多信息。\n\n请注意，所有申请均经过人工评估，处理可能需要 10 天时间。\n\n如果您觉得您的申请已被错误拒绝，请联系affiliates@veralusso.com，团队成员将解决您的问题。",
  "visitorMonthHintText": "选择独立访客/月",
  "viewsMonthHintText": "选择页面浏览量/月",
  "cityHintText": "城市",
  "countryHintText": "国家",
  "addressOneText": "街道地址1",
  "addressTwoText": "街道地址2",
  "addressText": "地址",
  "letsGoText": "我们走吧",
  "postCodeText": "邮政编码",
  "contactNoText": "联系方式。",
  "websiteUrlText": "网址",
  "profileText": "轮廓",
  "wishListText": "名单",
  "myOrdersText": "我的订单",
  "myWishlistText": "我的收藏",
  "addressBookText": "地址簿",
  "accountInformationText": "帐户信息",
  "storePaymentText": "存储的付款方式",
  "newsLetterText": "通讯订阅",
};
