const Map<String, String> de = {
  "language": "Englisch",
  "homeText": "Zuhause",
  "searchText": "Suche",
  "designersText": "Designer",
  "yourEmailText": "Deine E-Mail",
  "gdpText": "BIP",
  "englishText": "Englisch",
  "checkoutText": "Kasse",
  "purchaseText":
      "Bitte geben Sie unten Ihre Daten ein, um Ihren Kauf abzuschließen",
  "shippingAddressText": "Lieferanschrift",
  "shippingMethodText": "Versandart",
  "paymentMethodText": "Zahlungsmethode",
  "orderSummaryText": "Bestellübersicht",
  "createCheckoutText": "Sie können nach der Kasse ein Konto erstellen.",
  "stLine1": "Straßenname (Zeile 1",
  "stLine2": "Straße Adresszeile 2",
  "stLine3": "Straße: Zeile 3",
  "cityText": "Stadt",
  "indiaText": "Indien",
  "stateText":
      "Bitte wählen Sie eine Region, ein Bundesland oder eine Provinz aus",
  "zipCodeText": "Postleitzahl",
  "phoneNumberText": "Telefonnummer",
  "itemInCartText": "Artikel im Warenkorb",
  "applyDiscountCodeText": "Rabattcode anwenden",
  "enterDiscountCodeText": "Rabattcode eingeben",
  "applyDiscountText": "RABATT ANWENDEN",
  "orderTotalText": "Auftragssumme",
  "orderCommentText": "Kommentar bestellen",
  "placeOrderText": "BESTELLUNG AUFGEBEN",
  "myAccountText": "Mein Konto",
  "appNameText": "Vera Luso",
  "aboutUsText": "Über uns",
  "aboutUsContain":
      'VERA LUSSO IST MIT 5 MILLIONEN BESUCHERN PRO MONAT UND WELTWEITEM VERSAND EINE TOP ONLINE-LUXUSMODE-DESTINATION.',
  "aboutUsContain1":
      'Die Website bietet die beste Auswahl der besten etablierten Designer sowie junge aufstrebende Talente. vera lusso wurde Anfang der 1930er Jahre in Florenz mit der Eröffnung des gleichnamigen Concept Stores in der Via Roma gegründet. Seit 1999 online, schreibt das Unternehmen 90 % des Gesamtumsatzes dem Online-Verkauf zu. Bis heute ist es ein zu 100 % in Privatbesitz befindliches Familienunternehmen, in dem der Enkel des Gründers, Andrea Panconesi, als CEO und seine Tochter, Annagreta Panconesi, als Creative Director fungieren.',
  "aboutUsContain2":
      'Die Website bietet eine große Auswahl an Kleidung, Schuhen, Taschen, Accessoires, Luxus-Wohninterieur und Schönheit, mit Produkten für Männer, Frauen und Kinder von den renommiertesten Designern wie Balenciaga, Vetements, Off-White, J.W. Anderson, Balmain, Dolce & Gabbana, Gucci, Saint Laurent, Valentino, Givenchy, Loewe Jacquemus und mehr.',
  "aboutUsContain3":
      'Derzeit arbeiten 200 Menschen aus 15 verschiedenen Ländern an der Herstellung und Pflege von vera lusso. Die Seite ist in 9 Sprachen verfügbar: Englisch, Italienisch, Deutsch, Chinesisch, Russisch, Spanisch, Französisch, Koreanisch und Japanisch. Die Website wird vollständig intern erstellt, wobei das Büro in Florenz Grafikdesign, IT, Kundendienst, Marketing und Einkaufsabteilungen beherbergt. Die Stylisten und Presseteams operieren vom vera lusso-Büro in der Modehauptstadt der Welt – Mailand.',
  "aboutUsContain4":
      'Alle Bestellungen werden weltweit von der vera lusso-Zentrale in Kartons versandt, die mit größter Sorgfalt vorbereitet werden und die besten Materialien verwenden, von den charakteristischen Schuhbeuteln bis zum personalisierten Band.',
  "aboutUsContain5":
      '2008 verzeichnete vera lusso 1,5 Millionen Einzelbesucher auf der Website und ist 2017 auf 53 Millionen Einzelbesucher angewachsen. Mehr als 15 % der Online-Verkäufe werden in den Vereinigten Staaten generiert, gefolgt von Deutschland, Großbritannien, Italien, China und Frankreich.',
  "aboutUsContain6":
      'vera lusso erweitert die Grenzen der Luxus-Einzelhandelslandschaft sowohl online als auch offline mit einer Reihe exklusiver Dienstleistungen und Markeninitiativen, darunter Buy It First, Luxury Club, Sneakers Club, LVR Privilege und LVR Editions.',
  "orderConfirm": "DANKE FÜR IHREN EINKAUF!",
  "orderIdTitle": '''Ihre Bestellnummer lautet:''',
  "orderIdIs": ''' 1490004 ''',
  "orderNumberTitle": 'BESTELLNUMMER:',
  "orderNumberIs": ' 2080004',
  "orderDateTitle": 'Auftragsdatum:',
  "orderDateIs": ' 7. September 2021',
  "image": 'BILD',
  "productName": 'PRODUKTNAME',
  "sku": 'Artikelnummer',
  "price": 'PREIS',
  "qty": 'Menge',
  "subTotal": 'ZWISCHENSUMME',
  "action": 'AKTION',
  "buyBack": 'ZURÜCK KAUFEN',
  "orderContain":
      "Wir senden Ihnen eine Bestellbestätigung mit Details und Tracking-Informationen per E-Mail.",
  "referFriendText": "Freund empfehlen",
  "returnsRefundsText": "Rückgabe & Erstattung",
  "faqText": "FAQ",
  "contactText": "Kontakt",
  "socialText": "Sozial",
  "companyText": "Gesellschaft",
  "contactUs": "Kontaktiere uns",
  "myOrders": "Meine Bestellungen",
  "myOrderImage": "Bild",
  "quantity": "Menge",
  "status": "Status",
  "paymentMethod": " Zahlungsmethode",
  "shippingAddress": "Lieferanschrift",
  "billingAddress": "Rechnungsadresse",
  "continueShopping": "Mit dem Einkaufen fortfahren",
  "goToYourAccountText": "Gehen Sie zu Ihrem Konto",
  "emailAddressText": "E-Mail-Addresse",
  "passwordText": "Passwort",
  "saveYourFavoriteItemsInAWishListText":
      "Speichern Sie Ihre Lieblingsartikel in einer Wunschliste",
  "cardsText": "Speichern Sie Ihre Karten und bevorzugten Lieferadressen",
  "shippingText":
      "Überprüfen Sie die Details und den Status Ihrer Bestellungen und Rücksendungen",
  "registerText": "REGISTRIEREN",
  "registerWithFacebookText": "Registrieren Sie sich bei Facebook",
  "logInAndEnjoyAPersonalizedShoppingExperienceText":
      "Melden Sie sich an und genießen Sie ein personalisiertes Einkaufserlebnis.",
  "dontHaveAnAccountYetText": "Sie haben noch kein Konto?",
  "loginWithFacebookText": "Mit Facebook einloggen",
  "loginText": "ANMELDUNG",
  "forgotYourPasswordText": "Haben Sie Ihr Passwort vergessen?",
  "subscribeToOurNewsletterText": "ABONNIERE UNSEREN NEWSLETTER",
  "getAllDescriptionText":
      "Erhalten Sie die neuesten Informationen zu Veranstaltungen, Verkäufen und Angeboten. Melden Sie sich noch heute für den Newsletter an.",
  "enterYourEmailAddressText": "Geben sie ihre E-Mailadresse ein",
  "subscribeText": "ABONNIEREN",
  "changeTHEWORLDWithYourPurchaseText": "VERÄNDERE DIE WELT MIT DEINEM KAUF",
  "companyNameText": "GESELLSCHAFT",
  "contactsText": "KONTAKTE",
  "othersText": "ANDERE",
  "createAnAccountText": "EIN KONTO ERSTELLEN",
  "createNewCustomerAccountText": "NEUES KUNDENKONTO ERSTELLEN",
  "marketingPurposeText":
      "Ich stimme zu, dass Veralusso meine personenbezogenen Daten für Marketingzwecke (Newsletter, Nachrichten und Werbeaktionen) sammeln darf.",
  "shoppingHabitText":
      "Ich stimme zu, dass Veralusso meine persönlichen Daten sammeln darf, um ein Profil meiner Einkaufsgewohnheiten zu erstellen.",
  "unitedKingdomText": "VEREINIGTES KÖNIGREICH",
  "emailText": "Email",
  "confirmEmailText": "Bestätigungs-E-Mail",
  "confirmPasswordText": "Bestätige das Passwort",
  "firstNameText": "Vorname",
  "lastNameText": "Familienname, Nachname",
  "dateOfBirthText": "Geburtsdatum",
  "dateOfMarriageText": "Tag der Hochzeit",
  "telephoneNoText": "Telefonnummer.",
  "mr": "Herr.",
  "affiliateProgramTitleText": "VERALUSSO-PARTNERPROGRAMM",
  "whoAreWeLookingTitleText": "Wen suchen wir?",
  "whoAreWeLookingDescriptionOneText":
      "Haben Sie eine modebewusste, luxusorientierte Website, einen Blog oder ein Social-Media-Profil, das trendbewusst ist und eine internationale Ausrichtung hat? Dein Fokus liegt auf Fashion, Lifestyle, Beauty und Design? Dann suchen wir Sie!\n\nNehmen Sie an unserem globalen Partnerprogramm teil und Sie haben die Möglichkeit, jedes Mal, wenn Ihre Besucher bei VERALUSSO einkaufen, eine Provision zu verdienen.",
  "whatCanYouExpectTitleText": "Was können Sie erwarten?",
  "expectRuleOneText": "Provision auf alle genehmigten Nettoumsätze",
  "expectRuleTwoText": "45 Tage Cookie-Fenster",
  "expectRuleThreeText": "Daten-Feed wird mehrmals täglich aktualisiert",
  "expectRuleFourText":
      "Zugriff auf personalisierte Banner, Textlinks, Deeplinks und unseren Datenfeed in 9 Sprachen (Englisch, Italienisch, Französisch, Deutsch, Koreanisch, Spanisch, Chinesisch, Russisch und Japanisch)",
  "expectRuleFiveText":
      "Die Möglichkeit, Feeds in allen Weltwährungen anzupassen",
  "promoteSoloQuestionText":
      "Wie können Sie VERALUSSO (als Affiliate) bewerben?",
  "promoteSoloAnswerOneText":
      "Erstellung hochwertiger und ansprechender Inhalte, die den Stil von VERALUSSO widerspiegeln",
  "promoteSoloAnswerTwoText":
      "Präsentieren Sie unsere Inhalte, Banner und Links für mehrere Kategorien und Veranstaltungen auf Ihrer Website und Ihren Social-Media-Kanälen",
  "promoteSoloAnswerThreeText":
      "Förderung der Vorteile, die unsere Kunden lieben",
  "promoteSoloAnswerFourText":
      "Eine Auswahl ständig aktualisierter Artikel der besten Marken",
  "promoteSoloAnswerFiveText":
      "Kostenlose Rücksendungen ohne zusätzliche Steuern für die USA, Kanada, das Vereinigte Königreich und",
  "howApplyTitleText": "Wie bewerbe ich mich?",
  "howApplyAnswerOneText":
      "Senden Sie uns den Namen und die URL Ihrer Website, Ihres Blogs oder Ihres Social-Media-Profils und Ihrer Hauptmärkte per E-Mail. Wir werden Ihre Website überprüfen und uns mit weiteren Informationen zur Teilnahme am Partnerprogramm bei Ihnen melden.\n\nBitte beachten Sie, dass alle Bewerbungen manuell bewertet werden und die Bearbeitung bis zu 10 Tage dauern kann.\n\nWenn Sie Ihre Bewerbung finden zu Unrecht abgelehnt wurde, wenden Sie sich bitte an affiliates@veralusso.com und ein Mitglied des Teams wird sich um Ihre Bedenken kümmern.",
  "visitorMonthHintText": "Wählen Sie Eindeutige Besucher/Monat aus",
  "viewsMonthHintText": "Wählen Sie Seitenaufrufe/Monat aus",
  "cityHintText": "Stadt",
  "countryHintText": "Land",
  "addressOneText": "Adresse 1",
  "addressTwoText": "Straße 2",
  "addressText": "Adresse",
  "letsGoText": "Lass uns gehen",
  "postCodeText": "Postleitzahl",
  "contactNoText": "Kontakt-Nr.",
  "websiteUrlText": "Webadresse",
  "profileText": "Profil",
  "wishListText": "WhistList",
  "myOrdersText": "MEINE BESTELLUNGEN",
  "myWishlistText": "Meine Wunschliste",
  "addressBookText": "Adressbuch",
  "accountInformationText": "Kontoinformationen",
  "storePaymentText": "GESPEICHERTE ZAHLUNGSARTEN",
  "newsLetterText": "NEWSLETTER-ABOS",
};
