const Map<String, String> en = {
  "language": "English",
  "homeText": "Home",
  "wishList": "Wishlist",
  "addAll": "Add All",
  "charityTitle": "Your one purchase can change a life.",
  "charityContain1":
      "Veralusso - Works actively to help change the world and every purchase you make on our site - helps us do the same. We have partnered with a few charities and would like your suggestions to add the charities and causes which you feel need our help and those which can make a difference to people lives.",
  "charityContain2":
      "Estimated 11 million children under 5 face extreme hunger or starvation across the world.",
  "charityContain3":
      "Cases of abandoned elderly are on the rise worldwide. The fear of being a burden needs to end.",
  "charityContain4":
      "Yearly statistics. Approximately 7.6 million animals enter animal shelter nationwide. Approximately 2.7 million shelteranimals are euthanized. Only around 2.7 million shelter animals get adopted.",
  "charityContain5":
      "Veralusso will donate 3% of the proceeds of every sale to a charity that you choose or to one on our list if you do not choose one. You can further help with donating any additional amount at checkout .If you choose to add 10 dollars we will add further 10 dollars as our further contribution in additional to our initial 3% ( subject to a maximum of 10% of the order value).",
  "charityContain6":
      "Every cent is accounted for and our team works hard to ensure that the money reaches the right hands.",
  "charityContain7":
      "We update you every step of the way so you can be satisfied when your contributions has changed and improved lives.",
  "menText": "Men",
  "womenText": "Women",
  "faqTitle": "Frequently Asked Questions",
  "newAddressText": "New Address",
  "kidsText": "Kids",
  "searchText": "Search",
  "designersText": "Designers",
  "yourEmailText": "Your E-Mail",
  "gdpText": "GDP",
  "englishText": "English",
  "checkoutText": "Checkout",
  "purchaseText": "Please Enter Your Details Below To Complete Your Purchase",
  "shippingAddressText": "Shipping Address",
  "shippingMethodText": "Shipping Method",
  "paymentMethodText": "Payment Method",
  "orderSummaryText": "Order Summary",
  "createCheckoutText": "You can create an account after checkout.",
  "stLine1": "Street Address: Line 1",
  "stLine2": "Street Address: Line 2",
  "stLine3": "Street Address: Line 3",
  "cityText": "City",
  "indiaText": "India",
  "stateText": "Please select a region, state or province",
  "zipCodeText": "Zip/Postal Code",
  "phoneNumberText": "Phone Number",
  "itemInCartText": "Item in Cart",
  "applyDiscountCodeText": "Apply Discount Code",
  "enterDiscountCodeText": "Enter Discount Code",
  "applyDiscountText": "Apply Discount",
  "orderTotalText": "Order Total",
  "orderCommentText": "Order Comment",
  "placeOrderText": "Place Order",
  "myAccountText": "My Account",
  "appNameText": "Vera Lusso",
  "details": "Details",
  "guaranteedDelivery": "Guaranteed Delivery : Nov 04 - Nov 11",
  "sizeChart": "Size Chart",
  "addTOCart": "Add To Cart",
  "soldOut": "Sold Out",
  "addToWishlist": "Add To Wishlist",
  "whyVeraLusso": "WHY VERALUSSO",
  "knowMore": "Know More",
  "recommendation": "Recommendation",
  "recentlyViewed": "Recently Viewed",
  "returnPolicyTitle": "Return Policy",
  "refundTitle": "Refunds",
  "myBillingShipAddressSameText":
      "My Billing and Shipping Address are the same",
  "returnProcessTitle": "Returns Process",
  "customisedTitle": "Customized, Pre-Owned & Vintage Items",
  "howToReturnTitle": "How To Return",
  "returnPolicyContain1":
      "Returned items must comply with our returns policy:\n",
  "returnPolicyContain2":
      'Items must be returned unworn, undamaged and unused, with all tags attached and the original packaging included.',
  "returnPolicyContain3":
      'Footwear and accessories must be returned with the original branded boxes and dust bags, where provided, and placed inside a protective outer box for shipping.',
  "returnPolicyContain4":
      'When trying on footwear, please take care not to mark the soles or damage the shoe box.',
  "returnPolicyContain5":
      'If an item has a Avoirchic security tag or brand tag attached, it must be returned with the tag in its original.',
  "returnPolicyContain6":
      'Beauty and cosmetic products must be returned unopened and unused, with the seals of any packaging still intact.',
  "returnPolicyContain7":
      'Hosiery, lingerie and swimwear items must be returned with the hygiene seals attached and in unopened and undamaged product packaging, where applicable.',
  "returnPolicyContain8":
      'Lingerie and swimwear must only be tried on over your own undergarments. We will not accept any returns that have been worn or are soiled.',
  "returnPolicyContain9":
      'Face masks must be returned unworn in their original, unopened and undamaged product packaging. Jewellery must be returned in the same condition it arrived in, including all branded packaging and documents provided with it.',
  "returnPolicyContain10":
      "Please take care when trying on your purchases and return them in the same condition you received them. Any returns that do not meet our policy will not be accepted.\n",
  "returnPolicyContain11":
      "If you placed an order as a guest, you can start your return here. To return or cancel an item that has been made to your specifications, please view our ‘ Customised Items’ section below for further information.",
  "aboutUsText": "About us",
  "aboutUsContain":
      'VERA LUSSO IS A TOP ONLINE LUXURY FASHION DESTINATION WITH 5 MILLION VISITORS PER MONTH AND WORLDWIDE SHIPPING.',
  "aboutUsContain1":
      'The website features the best selection of thetop established designers as wellas young emerging talents. vera lusso was founded in Florence in the early 1930s, with the opening of the company’s eponymous concept store on Via Roma. Online since 1999, the company attributes 90% of total revenue to online sales. To this day it remains a 100% privately owned family business, with the founder’s grandson,Andrea Panconesi acting as CEO and his daughter, Annagreta Panconesi as Creative Director.',
  "aboutUsContain2":
      'The site offers a wide selection of clothing, shoes, bags, accessories, luxury home interiors and beauty, with products available for men, women and kids from the most prestigious designerssuch as Balenciaga, Vetements, Off-White, J.W. Anderson, Balmain, Dolce & Gabbana,Gucci, Saint Laurent, Valentino, Givenchy, Loewe Jacquemus and more.',
  "aboutUsContain3":
      'There are currently 200 people from 15 different countries that work to produce and maintain vera lusso. The site is available in 9 languages: English Italian,German, Chinese, Russian, Spanish French, Korean and Japanese. The site is created entirely in-house, with the Florence office housing graphic design, IT, customer service, marketing and buying departments. The stylists and press teams operate from the vera lusso office in the fashion capital of the world – Milan.',
  "aboutUsContain4":
      'All orders are shipped worldwide from the vera lusso headquarters in boxes that are prepared with maximum care and use the finest materials, from the signature shoe bags to the personalized ribbon.',
  "aboutUsContain5":
      'vera lusso had 1.5 million unique visitors access the site in 2008 and has grown to 53 million unique visitors in 2017. More than 15% of online sales are generated from the United States, followed by Germany, UK, Italy, China and France.',
  "aboutUsContain6":
      'vera lusso pushes the boundaries of the luxury retail landscape both on and offline with an array of exclusive services and trademark initiatives including Buy It First, Luxury Club, Sneakers Club, LVR Privilege and LVR Editions.',
  "profile": "Profile",
  "firstNameText": "First Name",
  "lastNameText": "Last Name",
  "emailText": "E-mail",
  "ContactNoText": "Contact no.",
  "websiteUrlText": "Website URL",
  "countryText": "Country",
  "postCodeText": "Post Code",
  "socialLinksText": "Social links",
  "facebookText": "Facebook",
  "instagramText": "Instagram",
  "twitterText": "Twitter",
  "youtubeText": "Youtube",
  "linkendinText": "Linkendin",
  "pinterestText": "Pinterest",
  "followersText": "Followers",
  "mr": "Mr.",
  "letsText": "Submit",
  "orderConfirm": "Thank You For Your Purchase!",
  "orderIdTitle": '''Your order # is:''',
  "orderIdIs": ''' 1490004''',
  "orderNumberTitle": 'ORDER NUMBER:',
  "orderNumberIs": ' 2080004',
  "orderDateTitle": 'Order Date:',
  "orderDateIs": ' September 7,2021',
  "image": 'IMAGE',
  "productName": 'product Name',
  "sku": 'Sku',
  "price": 'price',
  "enterYourEmailText": "Enter your email",
  "qty": 'Qty',
  "subTotal": 'Subtotal',
  "action": 'Action',
  "buyBack": 'Buy Back',
  "myOrdersText": "My Orders",
  "myWishlistText": "My Wish List",
  "addressBookText": "Address Book",
  "newsLettersContain": "You Aren't Subscribed To\nOur Newsletter.",
  "edit": "Edit",
  "newsLetters": "Newsletter",
  "manageAddresses": "Manage Addresses",
  "defaultBillingAddress": "Default Billing Address",
  "editAddress": "Edit Address",
  "defaultShippingAddress": "Default Shipping Address",
  "accountInformationText": "Account Information",
  "myTicketsText": "My Tickets",
  "contactInfo": "Contact Information",
  "newsletters": "Newsletters",
  "myAccountContain": "You aren't subscribed to\nour newsletter.",
  "addressBook": "Address Book",
  "billing": "Billing",
  "shipping": "Shipping",
  "orderContain":
      "We’ll email you an order confirmation with details and tracking info.",
  "referFriendText": "Refer Friend",
  "returnsRefundsText": "Returns & Refunds",
  "faqText": "FAQ",
  "contactText": "Contact",
  "socialText": "Social",
  "companyText": "Company",
  "contactUs": "Contact Us",
  "myOrders": "My Orders",
  "myOrderImage": "Image",
  "quantity": "Qty",
  "status": "Status",
  "paymentMethod": " Payment Method",
  "shippingAddress": "Shipping Address",
  "billingAddress": "Billing Address",
  "continueShopping": "Continue Shopping",
  "goToYourAccountText": "Go to your  account",
  "emailAddressText": "Email Address",
  "passwordText": "Password",
  "saveYourFavoriteItemsInAWishListText":
      "Save your favorite items in a Wish List",
  "cardsText": "Save your cards and preferred shipping addresses",
  "shippingText": "Check the details and status of your orders and returns",
  "registerText": "Register",
  "registerWithFacebookText": "Register with Facebook",
  "logInAndEnjoyAPersonalizedShoppingExperienceText":
      "Log in and enjoy a personalized shopping experience.",
  "dontHaveAnAccountYetText": "Don’t have an account yet?",
  "loginWithFacebookText": "Login with Facebook",
  "loginText": "Login",
  "forgotYourPasswordText": "Forgot Your Password?",
  "subscribeToOurNewsletterText": "SUBSCRIBE TO OUR NEWSLETTER",
  "getAllDescriptionText":
      "Get all the latest information on Events, Sales and Offers. Sign up for newsletter today.",
  "enterYourEmailAddressText": "Enter your email address",
  "subscribeText": "SUBSCRIBE",
  "changeTHEWORLDWithYourPurchaseText": "Change The World With Your Purchase",
  "companyNameText": "Company",
  "contactsText": "Contacts",
  "othersText": "Others",
  "createAnAccountText": "Create An Account",
  "createNewCustomerAccountText": "Create New Customer Account",
  "marketingPurposeText":
      "I agree that Veralusso may collect my personal information for marketing purposes (newsletters, news and promotions).",
  "shoppingHabitText":
      "I agree that Veralusso may collect my personal information to create a profile of my shopping habits.",
  "unitedKingdomText": "UNITED KINGDOM",
  "confirmEmailText": "Confirm Email",
  "confirmPasswordText": "Confirm Password",
  "dateOfBirthText": "Date of birth",
  "dateOfMarriageText": "Date of  marriage",
  "telephoneNoText": "Telephone no.",
  "affiliateProgramTitleText": "Veralusso Affiliate Program",
  "whoAreWeLookingTitleText": "Who Are We Looking For?",
  "whoAreWeLookingDescriptionOneText":
      "Do you have a fashion-forward, luxury oriented website, blog, social media profile that is trend savvy with an international outlook? Is your focus fashion, lifestyle, beauty and design? If so, we are looking for you!\n\nJoin our global Affiliate Program and you will have the opportunity to earn a commission every time your visitors purchase from VERALUSSO.",
  "whatCanYouExpectTitleText": "What Can You Expect?",
  "expectRuleOneText": "Commission On All Approved Net Sales",
  "expectRuleTwoText": "45 days cookie window",
  "expectRuleThreeText": "Data Feed Updated Multiple Times Per Day",
  "expectRuleFourText":
      "Access to customized banners, textlinks, deeplinks and our datafeed in 9 languages (English, Italian, French, German, Korean, Spanish, Chinese,Russian & Japanese)",
  "expectRuleFiveText":
      "The possibility to customize feeds into all world currencies",
  "promoteSoloQuestionText": "How Can You Promote Veralusso (as an affiliate)?",
  "promoteSoloAnswerOneText":
      "Creating high-quality and engaging content that mirrors the style of Veralusso",
  "promoteSoloAnswerTwoText":
      "Featuring our content, banners and links for multiple categories and events on your website and social media channels",
  "promoteSoloAnswerThreeText":
      "Promoting the benefits that our customers love",
  "promoteSoloAnswerFourText":
      "A selection of continuously updated articles from the best brands",
  "promoteSoloAnswerFiveText":
      "Free returns with no added taxes for the US, Canada, the UK and ",
  "howApplyTitleText": "How to apply?",
  "howApplyAnswerOneText":
      "Email us the name and URL of your website, blog or social media profile and your main markets. We’ll review your site and get back to you with further information on how to join the affiliate program.\n\nPlease note that all applications are manually evaluated and processing may take up to 10 days.\n\nIf you feel your application has been wrongfully declined please contact affiliates@veralusso.com and a member of the team will address your concerns.",
  "visitorMonthHintText": "Select Unique Visitors/Month",
  "viewsMonthHintText": "Select Page Views/Month",
  "cityHintText": "City",
  "countryHintText": "Country",
  "addressOneText": "Street Address 1",
  "addressTwoText": "Street Address 2",
  "addressText": "Address",
  "letsGoText": "Let's Go",
  "contactNoText": "Contact no.",
  "profileText": "Profile",
  "accessYourAccountDetailsText": "Access Your Account Details And Rewards",
  "signUpText": "Sign Up",
  "loginMyAccountText": "Login",
  "myOrderText": "My Orders",
  "trackOrderText": "Track Order",
  "careersText": "Careers",
  "helpTheNeedyText": "Help The Needy",
  "secureShoppingText": "Secure Shopping",
  "influencerRegistrationText": "Influencer Registration",
  "affiliateText": "Affiliate Program",
  "advancedSearchText": "Advanced Search",
  "privacyPolicyText": "Privacy Policy",
  "termsConditionsText": "Terms & Conditions",
  "aboutText": "About",
  "aboutUsMyAccountText": "About Us",
  "referFriendMyAccountText": "Refer Friend",
  "returnsText": "Returns And Refunds",
  "contactUsText": "Contact Us",
  "faqMyAccountText": "Faq",
  "liveChatText": "Live Chat",
  "startChatText": "Start The Chat",
  "accountText": "Account",
  "changetheworldwithyourpurchaseText": "Change The World With Your Purchase",
  "defaultAddressesText": "Default Addresses",
  "billingText": "Billing",
  "billingAddressText": "Billing Address",
  "additionalAdressEntriesText": "Additional Address Entries",
  "youhaveNoAddressText":
      "You Have No Other Address Entries In Your Address Book.",
  "addnewAddressText": "Add New Address",
  "subsubcribeText": "Subscribe To Our Newsletter",
  "getAllTheLatestText":
      "Get all the latest information on Events, Sales and Offers. Sign up for newsletter today",
  "saveAdressText": "Save Address",
  "useasMybillingAddresText": "Use As My Default Billing Address",
  "useasMyshippingAddresText": "Use As My Default Shipping Address",
  "yourAppExpericanceText": "Your app experience is set to",
  "englishIsAlsoText":
      "ENGLISH is also available in your\nlocation. Would you like to change?",
  "noThanksText": "No, Thanks",
  "changeText": "CHANGE",
  "myWidhListText": "My Wish List",
  "accountInfoText": "Account Information",
  "storePaymentText": "Store Payment Methods",
  "newsletterSubText": "Newsletter Subscriptions",
  "chooseCountryText": "Choose Your Country",
  "checkYourOrderText": "Check your order",
  "enterYourOrderText":
      "Enter your order reference and email address below to see your order details. From there you can check its shipping status,cancel items or make a return.",
  "howDoIFindText": "How do i find my",
  "orderRefernceText": "Order reference",
  "submitText": "Submit",
  "wishListText": "Wish List",
  "newsLetterText": "NEWSLETTER SUBSCRIPTIONS",
  "welcometoChatText": "Welcome To Our LiveChat!",
  "fillTheFormText": "Please Fill In The Form Below Before Starting The Chat.",
  "nameChatText": "Name",
  "deliveryText": "Delivery",
  "ordersText": "Order",
  "paymentText": "Payment",
  "productText": "Product",
  "promotionText": "Promotion",
  "returnsContactText": "Returns",
  "technicalText": "Technical",
  "typeOfEnquiryText": "Type Of Enquiry",
  "surNameText": "Surname",
  "subjectText": "Subject",
  "whatsonyourmindText": "What's On Your Mind?",
  "orderenquiriesText": "General & Order Enquiries",
  "selectLangCurrText": "Select Language & Currency",
  "selectLangCurrDescText":
      "Please choose from the following Language and currency options available in your country Language",
  "saveText": "Save",
  "cancelText": "Cancel",
  "languageText": "Language",
  "currencyText": "Currency",
  "priceText": "Price",
  "filtersText": "Filters",
  "colorText": "Color",
  "brandText": "Brand",
  "sizeText": "Size",
  "applyFilterText": "Apply",
  "viewCartText": "View Cart",
  "continueShoppingText": "Continue Shopping",
  "youaddCartText": "You Added",
  "youaddCartEndText": "to your shopping cart.",
  "specialSizeCompanyText": "Comapany",
  "specialSizeContactsText": "Contacts",
  "specialSizeOthersText": "Others",
  "specialSizeSubscribeToNewsletterText": "SUBSCRIBE TO OUR NEWSLETTER",
  "specialSizeGetInformationOneText":
      "Get all the latest information on Events,",
  "specialSizeGetInformationTwoText":
      "Sales and Offers. Sign up for newsletter today.",
  "specialSizeEmailAddressText": "Email Address",
  "specialSizeSubscribeText": "SUBSCRIBE",
  "specialSizeRequestsText": "Special Size Requests",
  "specialSizeEnterEmailText": "Enter Email",
  "specialSizeSelectSizeText": "Select Size",
  "specialSizeSubmitText": "Submit",
  "shippingCartText": "Shopping Cart",
  "itemText": "Item",
  "applyText": "Apply",
  "enterDiscountText": "Enter discount code",
  "updateCartText": "Update Cart",
  "summaryText": "Summary",
  "esitamteText": "Estimate Shipping and Tax",
  "subtotalText": "Subtotal",
  "qtyText": "Qty",
  "taxText": "Tax",
  "forgetPassword": "Forgot Your Password?",
  "backToSignInScreen": "Back to sign in screen",
  "idText": "ID",
  "nameText": "Name",
  "actionText": "Action",
  "cancelItemText": "cancel item",
  "reasonCancelText": "Reason to cancel",
  "resetPassword": "reset my password",
  "policyHomeText": "Home",
  "shipping1Text": "Shipping",
  "viewWishListText": "View WishList",
  "logOutText": "LogOut",
  "streetAdd1Text": "Street Address 1",
  "streetAdd2Text": "Street Address 2",
  "updateAdressText": "Update Address",
  "streetAdd3Text": "Street Address 3",
  "policyText": "Privacy Policy",
  "policyHeadingText": "Veralusso Group Privacy Policy",
  "forgotYourPasswordDescriptionText":
      "Please Enter Your Email Address Below To Receive a Password Reset Link.",
  "forgetPasswordContain":
      "We have sent you a Password Reset Link\n This Link is valid for 2 hours  if you \ndid not make this request you can ignore\n this email Please check \nyour spam folder if you do not \nreceive the email  For any assistance\n please",
  "pleaseCheckYourInbox": "Please Check Your Inbox",
  "reasonReturnText": "Reason to return",
  "orderExpectedSDTitle": 'Expected Shipment Date: ',
  "returnItemText": "Return ltem",
  "returnText": "Return",
  "returnRequestText": "Return Request Received",
  "teamVeralussoText": "Team Vera Lusso.",
  "saveInAddressBookText": "Save in address book",
  "shipHereText": "Ship Here",
  "notifyMe": "Notify Me When Available",
  "wehaveRecivedText":
      "We have received your request and your request Id is - Please Check the status of your request at @@@@. contact us at care@veralusso.com - for any query with regards to request.",
  "track_your_order": "Track Your Order",
  "trackYourTicketByEmail": "Track Your Ticket By Email",
  "trackYourRequests": "Track Your Requests",
  "cartContain1": "Support a charity with your donation",
  "cartContain2":
      "15% of the order value will be donated by\nBrands&Labels for donations.",
  "cartContain3": "Please click here to donate now.",
  "cartContain4": "I WANT TO DONATE",
  "cartContain5": "Check Out with Multiple Addresses",
  "textDonationText": "Test Donation Two",
  "chooseYourownText": "Choose your own Amount GBP\n(minimum £1)",
  "theSelectamountText":
      "The selected amount will be added to your\nshopping cart.",
  "iwanttoDonateText": "i want to donate this amount",
  "gbpText": "GBP",
  "e5Text": "£ 5",
  "e10Text": "£ 10",
  "e15Text": "£ 15",
  "e20Text": "£ 20",
  "e25Text": "£ 25",
  "forgotPasswordWrongEmailEnd": "you need any further assistance please",
  "accountDoesNotExist": "Account Does Not Exist",
  "forgotPasswordWrongEmailStart": "There is no Account Associated",
  "WriteAt": "Write to us at",
  "with": "with",
  "sizeChartText": "Size Chart",
  "orderDate": 'Order Date',
  "thankYou": "Thank You",
  "notifyMeWhenThisProductIsInStock":
      "We Will Inform You Once The Product Is In Stock. You Can Also View The Status Of Your Request On",
  "myTicket": "My Tickets.",
  "productAddedTowishList": "Product added to wishList",
  "error": "Error",
  "somethingWentWrongPleaseTryAgain": "Something went wrong. Please try again",
  "authorised": "Authorised",
  "thePaymentWasSuccessful": "The payment was successful.",
  "okay": "Okay",
  "cancel": "Cancel",
  "enterValidEmailAddress": "Enter Valid Email Address",
  "enterEmailAddressNotSame": "Enter Email Address Not Same",
  "forgotPasswordRequestSendedOnYourMailPleaseCheck":
      "Forgot password request sended on your mail please check",
  "pleaseSelectReturnReasonItem": "Please Select Return Reason Item",
  "orderCancelRequest": "Order Cancel Request",
  "orderReturnRequest": "Order Return Request",
  "orderReturnRequestSuccessfullySentYouWillGetUpdatesSoon":
      "Order return request successfully sent, you will get updates soon.",
  "urlOfImage": "URL Of Image",
  "enterURLOfImage": "Enter URL Of Image",
  "enterRemarks": "Enter Remarks",
  "createTicket": "Create Ticket",
  "orderSuccessfullyUpdatedYouWillGetYourTicketIDshortly":
      "Order successfully updated and a Request Ticket has been created, You will get your Ticket ID shortly",
  "someThingWentWrongPleaseTryAgainLater":
      "SomeThing went wrong please try again later",
  "weCannotFindAnyOrdersAssociatedWithThisEmail":
      "We Cannot Find Any Orders Associated \nWith This Email.",
  "pleaseTryWithAnotherEmailAddress":
      "Please Try With Another Email Address \nOr Write To Us At care@veralusso.com For Further Assistance.",
  "weCannotFindAnyRequestAssociatedWithThisEmail":
      "We Cannot Find Any Request Associated \nWith This Email.",
  "itSeemsWeHaveNothingToShowFor": "It Seems We Have Nothing to Show for",
  "ifYouWouldLikeToHaveMoreInformationAbout":
      "If You Would Like To Have More Information About",
  "thenPleaseCreateTicket": "Then Please Create A Ticket",
  "pleaseCheckYourInternetConnection": "Please check your internet connection!",
  "country": "Country",
  "saveAddress": "Save Address",
  "updateAddress": "Update Address",
  "addNew": "Add New",
  "addAddress": "Add Address",
  "defaultShipping": "Default\nShipping",
  "noAddressFound": "No address found",
  "noDataFound": "No data found",
  "shopWithoutWorry": "Shop without Worry",
  "securitySafety100": "100% Security & Safety",
  "buyerProtection": "Buyer Protection",
  "immediateResolution": "Immediate Resolution",
  "fillYourCartText":
      "Fill your cart bursting that all our product are genuine and will be delivered at the time promised. We go further to Secure your shopping with full Insurance",
  "weAimToSatisfyText":
      "We aim to satisfy our clients 100% , however Online shopping is fraught with risks specially when it comes to International Shipping .To give you the peace of mind when you shop from us we have partnered PayPal and Checkout.com , to give you complete security and safety on your purchases.",
  "ifYouPayWithPayPal":
      "If you pay with PayPal you are covered automatically covered under PayPal Buyer Protection you are covered for the full purchase price plus the original shipping charges if the product is delayed or arrives not as what was described on our website.",
  "inAdditionAllOtherPaymentsAreProcessed":
      "In addition all other payments are processed thru Checkout.com - the worlds largest and most reputed payment acquiring platform and any disputes can be raised through your bank for immediate resolution.",
  "noBrandFound": "No Brand found",
  "andMore": "& More...",
  "youHaveNoItemsInYourShoppingCart":
      "You have no items in your shopping cart.",
  "couponCode": "Coupon Code",
  "removeCoupon": "Remove Coupon",
  "availableCouponList": "Available Coupon List",
  "goToCheckOut": "Go To CheckOut",
  "allCouponsList": "All Coupons List",
  "yes": "Yes",
  "no": "No",
  "success": "Success",
  "warning": "Warning",
  "chooseAnOption": "Choose An Option...",
  "youHaveNoProductsInYourWishList": "You Have No Products In Your Wish List.",
  "pleaseEnterYourEmailToTrackYourTicketByEmail":
      "Please Enter Your Email To Track Your Ticket By Email.",
  "areYouSureWantToRemoveThisProductFromCart":
      "Are you sure want to remove this product from cart?",
  "removeProduct": "Remove Product",
  "onceYouAddThisProductToWishlistText":
      "Once you add this product to wishlist then it will be remove from cart",
  "howDoIFindMyOrderReference": "How Do I Find My Order Reference?",
  "pleaseEnterOrderNumberToTrackYourOrder":
      "Please Enter Order Number To Track Your Order.",
  "guestUsers": "Guest Users",
  "ifYouHaveAnAccountSignInWithYourEmailAddress":
      "If you have an account, sign in with your email address.",
  "remarks": "Remarks",
  "balance": "Balance",
  "amount": "Amount",
  "sort": "Sort",
  "youCanViewYourRequestsAtMyTickets":
      "You Can View Your Requests at My Tickets",
  "yourRequestHasBeenReceived": "Your Request Has Been Received.",
  "noProductsFound": "No Products Found",
  "itSeemsWeHaveNothingToShowForThisCategory":
      "It Seems Like We Have Nothing To Show For This Category",
  "filter": "Filter",
  "newestFirst": "Newest First",
  "itSeemsLikeWeHaveNothingToShowForThisBrand":
      "It Seems Like We Have Nothing To Show For This Brand",
  "buyNow": "Buy now",
  "selectSizeFirst": "Select Size First",
  "countryWhereYouWantItShipped": "Country where you want it shipped",
  "priceMatchTicket": "Price Match Ticket",
  "ok": "OK",
  "cancelCoupon": "Cancel Coupon",
  "whateverYourQueryText":
      "Whatever Your Query. Use The Contact Form\nBelow To Get In Touch-OurTeam\nIs Ready To Help 24*7",
  "weWillGetInTouchSoon": "We’ll Get in Touch Soon.",
  "weHaveReceivedYourRequest": "We have received your Request",
  "and": "&",
  "noLanguageCurrencyFound": "No Language/Currency Found",
  "firstNameIsRequired": "First Name is required",
  "thankYouForYourInterestText":
      "Thank you for your Interest in working with Solo Luxury",
  "oneOfOurTeamMembersWillBeInTouchSoon":
      "One of our team members will be in touch soon",
  "forAnyAdditionalQueriesPleaseWriteTo":
      "For any additional queries please write to ",
  "incorrectPassword": "Incorrect Password",
  "thePasswordYouEnteredIsIncorrectText":
      "The password you entered is incorrect.\nPlease try again",
  "pleaseEnterYourEmailAddressText":
      "Please enter your email address below to receive a password re copy",
  "backToLogin": "Back to login",
  "youHaveBeenSuccessfullyLoggedOut": "You Have Been Successfully Logged Out",
  "contactInformation": "Contact Information",
  "changePassword": "Change Password",
  "areYouSureToLogOut": "Are You Sure To Log Out",
  "nameIsRequired": "Name Is Required",
  "emailIsRequired": "Email is Required",
  "couponId": "Coupon Id",
  "couponName": "Coupon Name",
  "expireAt": "Expire At",
  "noCouponsFound": "No Coupons Found!",
  "youHaveNoOrders": "You Have No Orders",
  "toBeUpdated": "To be updated",
  "youHaveNoTickets": "You have no Tickets",
  "createNewTicket": "Create New Ticket",
  "message": "Message",
  "communicationPreference": "Communication Preference",
  "subscribeToBeTheFirstText":
      "Subscribe to be the first with our new arrivals,\nexclusive collections, offers and more.",
  "subscribeToNewsletters": "Subscribe to newsletters..",
  "priceMatch": "Price Match",
  "bestPricePromise": "Best Price Promise",
  "yourBestPriceAlways": "Your Best Price - Always.",
  "ifYourPreferredItemIsLowerPricedText":
      "If your preferred item is lower priced at any other store at the current time we will match the price and offer you 10% additional store credit for your next purchase.",
  "simplyLetUsKnowByClickingHere": "Simply let us know by clicking here.",
  "alreadyMadeYourPurchase": "Already Made your purchase.",
  "dontWorryLetUsKnowByClickingText":
      "Dont worry let us know by clicking here and we our customer support team will refund you the difference if the purchase was made within the last 30 days.",
  "pleaseSeeFAQsByClickingHere": "Please see FAQs by clicking here",
  "attention": "Attention",
  "requiredFields": "All fields are required",
  "contactRequired": "Contact Number is required",
  "couponRemoved": "Coupon Removed Successfully",
  "couponApplied": "COUPON APPLIED SUCCESSFULLY. YOU SAVED",
  "enterFirstName": "Enter First Name",
  "enterLastName": "Enter Last Name",
  "enterEmailAddress": "Enter Email Address",
  "enterWebsiteUrl": "Enter Website Url",
  "enterName": "Enter Name",
  "enterSurName": "Enter Surname",
  "enterSomeText": "Enter Some Text",
  "enterPhoneNumber": "Enter Phone Number",
  "enterAddress1": "Enter Address 1",
  "enterAddress2": "Enter Address 2",
  "enterAddress3": "Enter Address 3",
  "enterPassword": "Enter Password",
  "enterCity": "Enter City",
  "enterZip": "Enter Zip/Postal code",
  "enterPostcode": "Enter Post Code",
  "selectStateOrProvince": "Please select a region, state or province.",
  "findBrands": "Find Brands",
  "orderDetails": "Order Details",
  "addProductToWishlist": "Add product to your wishList",
  "areYouSureWantToRemove": "Are you sure you want to remove %s coupon code?",
  "viewCouponList": "View Coupon List",
  "stateOrProvince": "State/Province",
  "changeLanguageAndCurrency": "Change Language and Currency",
  "thankYouInfluencer1":
      "Thank you for your Interest in working with Veralusso",
  "thankYouInfluencer2": "One of our team members will be in touch soon",
  "thankYouInfluencer3": "For any additional queries please write to ",
  "marriageAnniversary": "Marriage Anniversary",
  "signUpForNewsletter": "Sign Up for Newsletter",
  "notSetDefaultBilling": "You Have Not Set a Default Billing Address.",
  "notSetDefaultShipping": "You Have Not Set a Default Shipping Address.",
  "enterNameRequired": "Enter Name Required",
  "enterStyle": "Enter Style",
  "enterKeyword": "Enter Keyword",
  "websiteUrlForItemCheaper": "URL Website Where This Item Is Cheaper",
  "linkForItemCheaper": "Link To The Cheaper Product",
  "enterLink": "Enter Link",
  "priceIncludingDutiesAndTaxes": "Price Including Duties And Taxes",
  "countryWhereYouShipped": "Country where you want it shipped",
  "isProductAvailableInWebsite":
      "Is The Product Currently Available On The Website?",
  "enterYesOrNo": "Enter Yes or NO",
  "addedToYourCart": "Added To Your Cart",
  "productDetails": "Product Details",
  "notifyMeWhenProductAvailable": "Notify me when this product \nis in stock ",
  "enterDetailsBelowToSend":
      "Enter Details Below To Send A 10% Coupon Code To Your Friend",
  "enterFriendFirstName": "Enter Friend First Name",
  "friendFirstName": "Friend First Name",
  "enterFriendEmailAddress": "Enter Friend Email Address",
  "friendEmailAddress": "Friend Email Address",
  "enterFriendPhoneNumber": "Enter Friend Phone Number",
  "friendPhoneNumber": "Friend Phone Number",
  "enterConfirmEmail": "Enter Confirm Email",
  "enterConfirmPassword": "Enter Confirm Password",
  "enterDateOfBirth": "Enter Date Of Birth",
  "enterDateOfMarriage": "Enter Date Of Marriage",
  "dateOfBirthIsRequired": "Date of Birth is Required.",
  "sizeGuide": "SIZE GUIDE",
  "conversionChart": "CONVERSION CHART",
  "brandNameRequired": "Brand Name is Required",
  "style": "Style",
  "keyword": "Keyword",
  "date": "Date",
  "time": "Time",
  "sentBy": "Sent By",
  "nylonMessenger":
      "Nylon Messenger Backpack By Balenciaga, Front Closure With Hook, Top Handle, Adjustable Shoulder Straps, Front Patch.",
  "imageUrl": "Image URL",
  "imageUrlRequired": "ImageUrl is Required",
  "usernameInvalidTryAgain":
      "Username invalid.Please wait and try again later.",
  "passwordInvalidTryAgain":
      "Password invalid.Please wait and try again later.",
  "pleaseEnterMessage": "Please enter message",
  "typeMessageHere": "Type your message here...",
  "selectProductOption": "Select Product An Option",
  "sizeMissingNotifiedItsBack": "Size missing? Be notified when it is back in",
  "emailNotMatched": "Email Address not matched",
  "passwordNotMatched": "Confirm Password Not Match Password",
  "pleaseAgreeForNewsletter": "Please agree for NewsLetter",
  "alert": "Alert",
  "brandProductQuery": "Brand Product Query",
  "categoryProductQuery": "Category Product Query",
};
