const Map<String, String> es = {
  "language": "inglés",
  "homeText": "Casa",
  "searchText": "Búsqueda",
  "designersText": "Diseñadores",
  "yourEmailText": "Tu correo electrónico",
  "gdpText": "PIB",
  "englishText": "inglés",
  "checkoutText": "Verificar",
  "purchaseText": "Ingrese sus datos a continuación para completar su compra",
  "shippingAddressText": "Dirección de envío",
  "shippingMethodText": "Método de envío",
  "paymentMethodText": "Método de pago",
  "orderSummaryText": "Resumen del pedido",
  "createCheckoutText":
      "Puede crear una cuenta después de finalizar la compra.",
  "stLine1": "Dirección (Línea 1",
  "stLine2": "Dirección de calle Linea 2",
  "stLine3": "Dirección: Línea 3",
  "cityText": "Ciudad",
  "indiaText": "India",
  "stateText": "Seleccione una región, estado o provincia",
  "zipCodeText": "Código postal",
  "phoneNumberText": "Número de teléfono",
  "itemInCartText": "Artículo en el carrito",
  "applyDiscountCodeText": "Aplicar código de descuento",
  "enterDiscountCodeText": "Introduzca el código de descuento",
  "applyDiscountText": "APLICAR DESCUENTO",
  "orderTotalText": "Total del pedido",
  "orderCommentText": "Comentario del pedido",
  "placeOrderText": "REALIZAR PEDIDO",
  "myAccountText": "Mi cuenta",
  "appNameText": "Vera Lusso",
  "aboutUsText": "Sobre nosotros",
  "aboutUsContain":
      'VERA LUSSO ES UN PRINCIPAL DESTINO DE MODA DE LUJO EN LÍNEA CON 5 MILLONES DE VISITANTES AL MES Y ENVÍOS A TODO EL MUNDO.',
  "aboutUsContain1":
      'El sitio web presenta la mejor selección de los mejores diseñadores establecidos, así como jóvenes talentos emergentes. vera lusso se fundó en Florencia a principios de la década de 1930, con la apertura de la tienda conceptual homónima de la compañía en Via Roma. En línea desde 1999, la empresa atribuye el 90% de los ingresos totales a las ventas en línea. A día de hoy sigue siendo una empresa familiar 100% privada, con el nieto del fundador, Andrea Panconesi, como director general y su hija, Annagreta Panconesi, como directora creativa.',
  "aboutUsContain2":
      'El sitio ofrece una amplia selección de ropa, zapatos, bolsos, accesorios, interiores de casas de lujo y belleza, con productos disponibles para hombres, mujeres y niños de los diseñadores más prestigiosos como Balenciaga, Vetements, Off-White, J.W. Anderson, Balmain, Dolce & Gabbana, Gucci, Saint Laurent, Valentino, Givenchy, Loewe Jacquemus y más.',
  "aboutUsContain3":
      'Actualmente hay 200 personas de 15 países diferentes que trabajan para producir y mantener vera lusso. El sitio está disponible en 9 idiomas: inglés, italiano, alemán, chino, ruso, español, francés, coreano y japonés. El sitio se crea completamente internamente, con la oficina de Florencia que alberga los departamentos de diseño gráfico, TI, servicio al cliente, marketing y compras. Los estilistas y los equipos de prensa operan desde la oficina de vera lusso en la capital mundial de la moda: Milán.',
  "aboutUsContain4":
      'Todos los pedidos se envían a todo el mundo desde la sede de vera lusso en cajas que se preparan con el máximo cuidado y utilizan los mejores materiales, desde las bolsas de zapatos de la firma hasta la cinta personalizada.',
  "aboutUsContain5":
      'vera lusso tuvo 1,5 millones de visitantes únicos que accedieron al sitio en 2008 y creció a 53 millones de visitantes únicos en 2017. Más del 15% de las ventas en línea se generan en los Estados Unidos, seguido de Alemania, Reino Unido, Italia, China y Francia.',
  "aboutUsContain6":
      'vera lusso supera los límites del panorama minorista de lujo tanto en línea como fuera de línea con una variedad de servicios exclusivos e iniciativas de marcas registradas que incluyen Buy It First, Luxury Club, Sneakers Club, LVR Privilege y LVR Editions.',
  "orderConfirm": "¡GRACIAS POR SU COMPRA!",
  "orderIdTitle": '''Su orden # es:''',
  "orderIdIs": ''' 1490004 ''',
  "orderNumberTitle": 'NÚMERO DE ORDEN:',
  "orderNumberIs": ' 2080004',
  "orderDateTitle": 'Fecha de orden:',
  "orderDateIs": ' 7 de septiembre de 2021',
  "image": 'IMAGEN',
  "productName": 'NOMBRE DEL PRODUCTO',
  "sku": 'SKU',
  "price": 'PRECIO',
  "qty": 'CANTIDAD',
  "subTotal": 'TOTAL PARCIAL',
  "action": 'ACCIÓN',
  "buyBack": 'RECOMPRAR',
  "orderContain":
      "Le enviaremos por correo electrónico una confirmación del pedido con los detalles y la información de seguimiento.",
  "referFriendText": "Recomendar amigo",
  "returnsRefundsText": "Devoluciones y reembolsos",
  "faqText": "Preguntas más frecuentes",
  "contactText": "Contacto",
  "socialText": "Social",
  "companyText": "Compañía",
  "contactUs": "Contáctenos",
  "myOrders": "Mis ordenes",
  "myOrderImage": "Imagen",
  "quantity": "Cantidad",
  "status": "Estado",
  "paymentMethod": " Método de pago",
  "shippingAddress": "Dirección de envío",
  "billingAddress": "Dirección de Envio",
  "continueShopping": "Seguir comprando",
  "goToYourAccountText": "Ve a tu cuenta",
  "emailAddressText": "Dirección de correo electrónico",
  "passwordText": "Clave",
  "saveYourFavoriteItemsInAWishListText":
      "Guarde sus artículos favoritos en una lista de deseos",
  "cardsText": "Guarde sus tarjetas y direcciones de envío preferidas",
  "shippingText":
      "Consulta los detalles y el estado de tus pedidos y devoluciones",
  "registerText": "REGISTRARSE",
  "registerWithFacebookText": "Regístrese con Facebook",
  "logInAndEnjoyAPersonalizedShoppingExperienceText":
      "Inicia sesión y disfruta de una experiencia de compra personalizada.",
  "dontHaveAnAccountYetText": "¿Aún no tienes una cuenta?",
  "loginWithFacebookText": "Iniciar sesión con Facebook",
  "loginText": "ACCESO",
  "forgotYourPasswordText": "¿Olvidaste tu contraseña?",
  "subscribeToOurNewsletterText": "SUSCRÍBETE A NUESTRO BOLETÍN",
  "getAllDescriptionText":
      "Obtenga toda la información más reciente sobre eventos, ventas y ofertas. Regístrese para recibir el boletín de noticias hoy.",
  "enterYourEmailAddressText": "Ingrese su dirección de correo electrónico",
  "subscribeText": "SUSCRIBIR",
  "changeTHEWORLDWithYourPurchaseText": "CAMBIA EL MUNDO CON TU COMPRA",
  "companyNameText": "EMPRESA",
  "contactsText": "CONTACTOS",
  "othersText": "OTROS",
  "createAnAccountText": "CREA UNA CUENTA",
  "createNewCustomerAccountText": "CREAR NUEVA CUENTA DE CLIENTE",
  "marketingPurposeText":
      "Acepto que Veralusso pueda recopilar mi información personal con fines de marketing (boletines, noticias y promociones).",
  "shoppingHabitText":
      "Acepto que Veralusso pueda recopilar mi información personal para crear un perfil de mis hábitos de compra.",
  "unitedKingdomText": "REINO UNIDO",
  "emailText": "Correo electrónico",
  "confirmEmailText": "Confirmar correo electrónico",
  "confirmPasswordText": "Confirmar contraseña",
  "firstNameText": "Primer nombre",
  "lastNameText": "Apellido",
  "dateOfBirthText": "Fecha de nacimiento",
  "dateOfMarriageText": "Fecha de casamiento",
  "telephoneNoText": "Teléfono no.",
  "mr": "Señor.",
  "affiliateProgramTitleText": "PROGRAMA DE AFILIADOS DE VERALUSSO",
  "whoAreWeLookingTitleText": "¿A quien estamos buscando?",
  "whoAreWeLookingDescriptionOneText":
      "¿Tiene un sitio web, un blog o un perfil de redes sociales orientado al lujo y a la moda que conoce las tendencias con una perspectiva internacional? ¿Tu enfoque es la moda, el estilo de vida, la belleza y el diseño? Si es así, ¡te estamos buscando!\n\nÚnete a nuestro programa global de afiliados y tendrás la oportunidad de ganar una comisión cada vez que tus visitantes compren en VERALUSSO.",
  "whatCanYouExpectTitleText": "¿Qué puedes esperar?",
  "expectRuleOneText": "Comisión sobre todas las ventas netas aprobadas",
  "expectRuleTwoText": "ventana de cookies de 45 días",
  "expectRuleThreeText": "Feed de datos actualizado varias veces al día",
  "expectRuleFourText":
      "Acceso a banners personalizados, enlaces de texto, enlaces profundos y nuestra fuente de datos en 9 idiomas (inglés, italiano, francés, alemán, coreano, español, chino, ruso y japonés)",
  "expectRuleFiveText":
      "La posibilidad de personalizar los feeds en todas las monedas del mundo.",
  "promoteSoloQuestionText": "¿Cómo promocionar VERALUSSO (como afiliado)?",
  "promoteSoloAnswerOneText":
      "Crear contenido atractivo y de alta calidad que refleje el estilo de VERALUSSO",
  "promoteSoloAnswerTwoText":
      "Con nuestro contenido, banners y enlaces para múltiples categorías y eventos en su sitio web y canales de redes sociales",
  "promoteSoloAnswerThreeText":
      "Promoviendo los beneficios que nuestros clientes adoran",
  "promoteSoloAnswerFourText":
      "Una selección de artículos continuamente actualizados de las mejores marcas.",
  "promoteSoloAnswerFiveText":
      "Devoluciones gratuitas sin impuestos adicionales para los EE. UU., Canadá, el Reino Unido y",
  "howApplyTitleText": "¿Cómo aplicar?",
  "howApplyAnswerOneText":
      "Envíenos un correo electrónico con el nombre y la URL de su sitio web, blog o perfil de redes sociales y sus principales mercados. Revisaremos su sitio y nos pondremos en contacto con usted con más información sobre cómo unirse al programa de afiliados.\n\nTenga en cuenta que todas las solicitudes se evalúan manualmente y el procesamiento puede demorar hasta 10 días.\n\nSi cree que su solicitud se ha rechazado indebidamente, comuníquese con affiliates@veralusso.com y un miembro del equipo abordará sus inquietudes.",
  "visitorMonthHintText": "Seleccionar visitantes únicos/mes",
  "viewsMonthHintText": "Seleccionar páginas vistas/mes",
  "cityHintText": "Ciudad",
  "countryHintText": "País",
  "addressOneText": "Dirección Calle 1",
  "addressTwoText": "Dirección de calle 2",
  "addressText": "Habla a",
  "letsGoText": "Vamos",
  "postCodeText": "Código postal",
  "contactNoText": "Número de contacto",
  "websiteUrlText": "URL del sitio web",
  "profileText": "Perfil",
  "wishListText": "WhistList",
  "myOrdersText": "MIS ORDENES",
  "myWishlistText": "Mi lista de deseos",
  "addressBookText": "Directorio",
  "accountInformationText": "Información de la cuenta",
  "storePaymentText": "MÉTODOS DE PAGO ALMACENADOS",
  "newsLetterText": "SUSCRIPCIONES A LOS BOLETINES",
};
