const Map<String, String> fr = {
  "language": "Anglais",
  "homeText": "Maison",
  "searchText": "Rechercher",
  "designersText": "Créateurs",
  "yourEmailText": "Votre e-mail",
  "gdpText": "PIB",
  "englishText": "Anglais",
  "checkoutText": "Vérifier",
  "purchaseText":
      "Veuillez entrer vos coordonnées ci-dessous pour finaliser votre achat",
  "shippingAddressText": "Adresse de livraison",
  "shippingMethodText": "Mode de livraison",
  "paymentMethodText": "Mode de paiement",
  "orderSummaryText": "Récapitulatif de la commande",
  "createCheckoutText": "Vous pouvez créer un compte après le paiement.",
  "stLine1": "Nom de rue (ligne 1",
  "stLine2": "Adresse municipale : Ligne 2",
  "stLine3": "Adresse municipale : Ligne 3",
  "cityText": "Ville",
  "indiaText": "Inde",
  "stateText": "Veuillez sélectionner une région, un état ou une province",
  "zipCodeText": "Zip / code postal",
  "phoneNumberText": "Numéro de téléphone",
  "itemInCartText": "Article dans le panier",
  "applyDiscountCodeText": "Appliquer le code de réduction",
  "enterDiscountCodeText": "Entrez le code de réduction",
  "applyDiscountText": "APPLIQUER LA RÉDUCTION",
  "orderTotalText": "Total de la commande",
  "orderCommentText": "Commentaire de la commande",
  "placeOrderText": "PASSER LA COMMANDE",
  "myAccountText": "Mon compte",
  "appNameText": "Véra Lusso",
  "aboutUsText": "À propos de nous",
  "aboutUsContain":
      'VERA LUSSO EST UNE DESTINATION DE MODE DE LUXE EN LIGNE AVEC 5 MILLIONS DE VISITEURS PAR MOIS ET UNE LIVRAISON DANS LE MONDE ENTIER.',
  "aboutUsContain1":
      '''Le site Web présente la meilleure sélection des meilleurs designers établis ainsi que de jeunes talents émergents. vera lusso a été fondée à Florence au début des années 1930, avec l'ouverture du concept store éponyme de l'entreprise sur la Via Roma. En ligne depuis 1999, l'entreprise attribue 90 % de son chiffre d'affaires total aux ventes en ligne. À ce jour, elle reste une entreprise familiale 100 % privée, avec le petit-fils du fondateur, Andrea Panconesi, en tant que PDG et sa fille, Annagreta Panconesi, en tant que directrice de la création.''',
  "aboutUsContain2":
      'Le site propose une large sélection de vêtements, chaussures, sacs, accessoires, intérieurs de maison de luxe et beauté, avec des produits disponibles pour hommes, femmes et enfants des créateurs les plus prestigieux tels que Balenciaga, Vetements, Off-White, J.W. Anderson, Balmain, Dolce & Gabbana, Gucci, Saint Laurent, Valentino, Givenchy, Loewe Jacquemus et plus encore.',
  "aboutUsContain3":
      'Il y a actuellement 200 personnes de 15 pays différents qui travaillent pour produire et entretenir la vera lusso. Le site est disponible en 9 langues : anglais italien, allemand, chinois, russe, espagnol français, coréen et japonais. Le site est entièrement créé en interne, avec le bureau de Florence abritant les départements de conception graphique, informatique, service client, marketing et achats. Les stylistes et les équipes de presse opèrent depuis le bureau de vera lusso dans la capitale mondiale de la mode - Milan.',
  "aboutUsContain4":
      'Toutes les commandes sont expédiées dans le monde entier depuis le siège social de vera lusso dans des boîtes préparées avec le plus grand soin et utilisant les meilleurs matériaux, des sacs à chaussures emblématiques au ruban personnalisé.',
  "aboutUsContain5":
      '''vera lusso a accueilli 1,5 million de visiteurs uniques sur le site en 2008 et est passé à 53 millions de visiteurs uniques en 2017. Plus de 15 % des ventes en ligne sont générées aux États-Unis, suivis de l'Allemagne, du Royaume-Uni, de l'Italie, de la Chine et de la France.''',
  "aboutUsContain6":
      '''vera lusso repousse les limites du paysage de la vente au détail de luxe à la fois en ligne et hors ligne avec une gamme de services exclusifs et d'initiatives de marque, notamment Buy It First, Luxury Club, Sneakers Club, LVR Privilege et LVR Editions.''',
  "orderConfirm": "MERCI POUR VOTRE ACHAT!",
  "orderIdTitle": '''Votre numéro de commande est :''',
  "orderIdIs": ''' 1490004 ''',
  "orderNumberTitle": 'NUMÉRO DE COMMANDE:',
  "orderNumberIs": ' 2080004',
  "orderDateTitle": 'Date de commande:',
  "orderDateIs": ' 7 septembre 2021',
  "image": 'IMAGE',
  "productName": 'NOM DU PRODUIT',
  "sku": 'UGS',
  "price": 'LE PRIX',
  "qty": 'QTÉ',
  "subTotal": 'TOTAL',
  "action": 'ACTION',
  "buyBack": 'RACHETER',
  "orderContain":
      "Nous vous enverrons par e-mail une confirmation de commande avec les détails et les informations de suivi.",
  "referFriendText": "Référez un ami",
  "returnsRefundsText": "Retours et remboursements",
  "faqText": "FAQ",
  "contactText": "Contact",
  "socialText": "Social",
  "companyText": "Compagnie",
  "contactUs": "Nous contacter",
  "myOrders": "Mes commandes",
  "myOrderImage": "Image",
  "quantity": "Qté",
  "status": "Statut",
  "paymentMethod": " Mode de paiement",
  "shippingAddress": "Adresse de livraison",
  "billingAddress": "Adresse de facturation",
  "continueShopping": "Continuer vos achats",
  "goToYourAccountText": "Accédez à votre compte",
  "emailAddressText": "Adresse e-mail",
  "passwordText": "Mot de passe",
  "saveYourFavoriteItemsInAWishListText":
      "Enregistrez vos articles préférés dans une liste de souhaits",
  "cardsText": "Enregistrez vos cartes et vos adresses de livraison préférées",
  "shippingText":
      "Vérifiez les détails et le statut de vos commandes et retours",
  "registerText": "S'INSCRIRE",
  "registerWithFacebookText": "Inscrivez-vous avec Facebook",
  "logInAndEnjoyAPersonalizedShoppingExperienceText":
      "Connectez-vous et profitez d'une expérience d'achat personnalisée.",
  "dontHaveAnAccountYetText": "Vous n'avez pas encore de compte?",
  "loginWithFacebookText": "Se connecter avec Facebook",
  "loginText": "CONNEXION",
  "forgotYourPasswordText": "Mot de passe oublié?",
  "subscribeToOurNewsletterText": "ABONNEZ-VOUS À NOTRE NEWSLETTER",
  "getAllDescriptionText":
      "Obtenez toutes les dernières informations sur les événements, les ventes et les offres. Inscrivez-vous à la newsletter aujourd'hui.",
  "enterYourEmailAddressText": "Entrez votre adresse email",
  "subscribeText": "S'ABONNER",
  "changeTHEWORLDWithYourPurchaseText": "CHANGEZ LE MONDE AVEC VOTRE ACHAT",
  "companyNameText": "ENTREPRISE",
  "contactsText": "CONTACTS",
  "othersText": "LES AUTRES",
  "createAnAccountText": "CRÉER UN COMPTE",
  "createNewCustomerAccountText": "CRÉER UN NOUVEAU COMPTE CLIENT",
  "marketingPurposeText":
      "J'accepte que Veralusso collecte mes informations personnelles à des fins de marketing (newsletters, actualités et promotions).",
  "shoppingHabitText":
      "J'accepte que Veralusso collecte mes informations personnelles pour créer un profil de mes habitudes d'achat.",
  "unitedKingdomText": "ROYAUME-UNI",
  "emailText": "E-mail",
  "confirmEmailText": "Confirmez votre email",
  "confirmPasswordText": "Confirmez le mot de passe",
  "firstNameText": "Prénom",
  "lastNameText": "Nom de famille",
  "dateOfBirthText": "Date de naissance",
  "dateOfMarriageText": "Date du mariage",
  "telephoneNoText": "N ° de téléphone.",
  "mr": "Monsieur.",
  "affiliateProgramTitleText": "PROGRAMME D'AFFILIATION VERALUSSO",
  "whoAreWeLookingTitleText": "Qui cherchons-nous ?",
  "whoAreWeLookingDescriptionOneText":
      "Avez-vous un site Web, un blog, un profil de médias sociaux axé sur la mode et le luxe, qui est à la pointe des tendances avec une perspective internationale ? Vous vous concentrez sur la mode, le style de vie, la beauté et le design ? Si c'est le cas, nous vous cherchons !\n\nRejoignez notre programme mondial d'affiliation et vous aurez la possibilité de gagner une commission chaque fois que vos visiteurs achètent chez VERALUSSO.",
  "whatCanYouExpectTitleText": "À quoi pouvez-vous vous attendre ?",
  "expectRuleOneText": "Commission sur toutes les ventes nettes approuvées",
  "expectRuleTwoText": "Fenêtre de cookies de 45 jours",
  "expectRuleThreeText": "Flux de données mis à jour plusieurs fois par jour",
  "expectRuleFourText":
      "Accès à des bannières personnalisées, des liens textuels, des liens profonds et notre flux de données en 9 langues (anglais, italien, français, allemand, coréen, espagnol, chinois, russe et japonais)",
  "expectRuleFiveText":
      "La possibilité de personnaliser les flux dans toutes les devises du monde",
  "promoteSoloQuestionText":
      "Comment pouvez-vous promouvoir VERALUSO (en tant qu'affilié) ?",
  "promoteSoloAnswerOneText":
      "Créer un contenu de haute qualité et engageant qui reflète le style de VERALUSSO",
  "promoteSoloAnswerTwoText":
      "Présentant notre contenu, nos bannières et nos liens pour plusieurs catégories et événements sur votre site Web et vos canaux de médias sociaux",
  "promoteSoloAnswerThreeText":
      "Promouvoir les avantages que nos clients adorent",
  "promoteSoloAnswerFourText":
      "Une sélection d'articles continuellement mis à jour parmi les meilleures marques",
  "promoteSoloAnswerFiveText":
      "Retours gratuits sans taxes supplémentaires pour les États-Unis, le Canada, le Royaume-Uni et",
  "howApplyTitleText": "Comment s'inscrire?",
  "howApplyAnswerOneText":
      "Envoyez-nous par e-mail le nom et l'URL de votre site Web, blog ou profil de réseau social et vos principaux marchés. Nous examinerons votre site et reviendrons vers vous avec de plus amples informations sur la manière de rejoindre le programme d'affiliation.\n\nVeuillez noter que toutes les candidatures sont évaluées manuellement et que le traitement peut prendre jusqu'à 10 jours.\n\nSi vous pensez que votre candidature a été refusé à tort, veuillez contacteraffiliations@veralusso.com et un membre de l'équipe répondra à vos préoccupations.",
  "visitorMonthHintText": "Sélectionner les visiteurs uniques/mois",
  "viewsMonthHintText": "Sélectionnez Pages vues/mois",
  "cityHintText": "Ville",
  "countryHintText": "De campagne",
  "addressOneText": "adresse 1",
  "addressTwoText": "Adresse municipale 2",
  "addressText": "Adresse",
  "letsGoText": "Allons-y",
  "postCodeText": "Code postal",
  "contactNoText": "N° de contact",
  "websiteUrlText": "URL de site web",
  "profileText": "Profil",
  "wishListText": "WhistListe",
  "myOrdersText": "MES COMMANDES",
  "myWishlistText": "Ma liste d'envies",
  "addressBookText": "Carnet d'adresses",
  "accountInformationText": "Information sur le compte",
  "storePaymentText": "MÉTHODES DE PAIEMENT MÉMORISÉES",
  "newsLetterText": "ABONNEMENT À LA NEWSLETTER",
};
