const Map<String, String> it = {
  "language": "inglese",
  "homeText": "Casa",
  "searchText": "Ricerca",
  "designersText": "Designer",
  "yourEmailText": "La tua email",
  "gdpText": "PIL",
  "englishText": "inglese",
  "checkoutText": "Guardare",
  "purchaseText":
      "Inserisci i tuoi dettagli qui sotto per completare l'acquisto",
  "shippingAddressText": "indirizzo di spedizione",
  "shippingMethodText": "metodo di spedizione",
  "paymentMethodText": "Metodo di pagamento",
  "orderSummaryText": "Riepilogo ordine",
  "createCheckoutText": "Puoi creare un account dopo il checkout.",
  "stLine1": "Indirizzo (linea 1",
  "stLine2": "Indirizzo: linea 2",
  "stLine3": "Indirizzo: linea 3",
  "cityText": "Città",
  "indiaText": "India",
  "stateText": "Seleziona una regione, uno stato o una provincia",
  "zipCodeText": "Zip / Codice postale",
  "phoneNumberText": "Numero di telefono",
  "itemInCartText": "Articolo nel carrello",
  "applyDiscountCodeText": "Applicare il codice sconto",
  "enterDiscountCodeText": "Inserisci il codice sconto",
  "applyDiscountText": "APPLICA SCONTO",
  "orderTotalText": "Ordine totale",
  "orderCommentText": "Commento dell'ordine",
  "placeOrderText": "INVIA ORDINE",
  "myAccountText": "Il mio conto",
  "appNameText": "Vera Lusso",
  "aboutUsText": "Chi siamo",
  "aboutUsContain":
      'VERA LUSSO È UNA MASSIMA DESTINAZIONE DELLA MODA DI LUSSO ONLINE CON 5 MILIONI DI VISITATORI AL MESE E SPEDIZIONI IN TUTTO IL MONDO.',
  "aboutUsContain1":
      '''Il sito web presenta la migliore selezione dei migliori designer affermati e giovani talenti emergenti. vera lusso nasce a Firenze nei primi anni '30, con l'apertura dell'omonimo concept store dell'azienda in via Roma. Online dal 1999, l'azienda attribuisce il 90% dei ricavi totali alle vendite online. Ad oggi rimane un'azienda familiare al 100% di proprietà privata, con il nipote del fondatore, Andrea Panconesi in qualità di CEO e sua figlia, Annagreta Panconesi come Direttore Creativo.''',
  "aboutUsContain2":
      '''Il sito offre un'ampia selezione di abbigliamento, scarpe, borse, accessori, interni di lusso per la casa e bellezza, con prodotti disponibili per uomo, donna e bambino dei designer più prestigiosi come Balenciaga, Vetements, Off-White, J.W. Anderson, Balmain, Dolce & Gabbana, Gucci, Saint Laurent, Valentino, Givenchy, Loewe Jacquemus e altri.''',
  "aboutUsContain3":
      '''Attualmente sono 200 le persone provenienti da 15 diversi paesi che lavorano per produrre e mantenere il vero lusso. Il sito è disponibile in 9 lingue: inglese italiano, tedesco, cinese, russo, spagnolo, francese, coreano e giapponese. Il sito è realizzato interamente in house, con la sede di Firenze che ospita gli uffici di progettazione grafica, IT, customer service, marketing e buying. Gli stilisti ei team stampa operano dall'ufficio di vera lusso nella capitale mondiale della moda – Milano.''',
  "aboutUsContain4":
      'Tutti gli ordini vengono spediti in tutto il mondo dalla sede di vera lusso in scatole preparate con la massima cura e utilizzando i migliori materiali, dalle esclusive borse per scarpe al nastro personalizzato.',
  "aboutUsContain5":
      'vera lusso ha avuto accesso al sito da 1,5 milioni di visitatori unici nel 2008 ed è cresciuta fino a raggiungere i 53 milioni di visitatori unici nel 2017. Oltre il 15% delle vendite online è generato dagli Stati Uniti, seguiti da Germania, Regno Unito, Italia, Cina e Francia.',
  "aboutUsContain6":
      'vera lusso spinge i confini del panorama del retail di lusso sia online che offline con una serie di servizi esclusivi e iniziative di marchio tra cui Buy It First, Luxury Club, Sneakers Club, LVR Privilege e LVR Editions.',
  "orderConfirm": "GRAZIE PER IL VOSTRO ACQUISTO!",
  "orderIdTitle": '''Il tuo ordine n. è:''',
  "orderIdIs": '''1490004''',
  "orderNumberTitle": '''NUMERO D'ORDINE:''',
  "orderNumberIs": ' 2080004',
  "orderDateTitle": '''Data dell'ordine:''',
  "orderDateIs": ' 7 settembre 2021',
  "image": 'IMMAGINE',
  "productName": 'NOME DEL PRODOTTO',
  "sku": 'SKU',
  "price": 'PREZZO',
  "qty": 'QTÀ',
  "subTotal": 'TOTALE PARZIALE',
  "action": 'AZIONE',
  "buyBack": 'RIACQUISTARE',
  "orderContain":
      "Ti invieremo un'e-mail di conferma dell'ordine con i dettagli e le informazioni di tracciamento.",
  "referFriendText": "Segnala amico",
  "returnsRefundsText": "Resi e rimborsi",
  "faqText": "FAQ",
  "contactText": "Contatto",
  "socialText": "Sociale",
  "companyText": "Azienda",
  "contactUs": "Contattaci",
  "myOrders": "i miei ordini",
  "myOrderImage": "Immagine",
  "quantity": "Qtà",
  "status": "Stato",
  "paymentMethod": " Metodo di pagamento",
  "shippingAddress": "indirizzo di spedizione",
  "billingAddress": "Indirizzo Di Fatturazione",
  "continueShopping": "Continua a fare acquisti",
  "goToYourAccountText": "Vai al tuo account",
  "emailAddressText": "Indirizzo e-mail",
  "passwordText": "Parola d'ordine",
  "saveYourFavoriteItemsInAWishListText":
      "Salva i tuoi articoli preferiti in una Wish List",
  "cardsText": "Salva le tue carte e gli indirizzi di spedizione preferiti",
  "shippingText": "Controlla i dettagli e lo stato dei tuoi ordini e resi",
  "registerText": "REGISTRATI",
  "registerWithFacebookText": "Registrati con Facebook",
  "logInAndEnjoyAPersonalizedShoppingExperienceText":
      "Accedi e goditi un'esperienza di acquisto personalizzata.",
  "dontHaveAnAccountYetText": "Non hai ancora un conto?",
  "loginWithFacebookText": "Fai il login con facebook",
  "loginText": "ACCEDERE",
  "forgotYourPasswordText": "Hai dimenticato la password?",
  "subscribeToOurNewsletterText": "ISCRIVITI ALLA NOSTRA NEWSLETTER",
  "getAllDescriptionText":
      "Ricevi tutte le ultime informazioni su Eventi, Saldi e Offerte. Iscriviti oggi alla newsletter.",
  "enterYourEmailAddressText": "Inserisci il tuo indirizzo email",
  "subscribeText": "SOTTOSCRIVI",
  "changeTHEWORLDWithYourPurchaseText": "CAMBIA IL MONDO CON IL TUO ACQUISTO",
  "companyNameText": "AZIENDA",
  "contactsText": "CONTATTI",
  "othersText": "ALTRI",
  "createAnAccountText": "CREARE UN ACCOUNT",
  "createNewCustomerAccountText": "CREA UN NUOVO ACCOUNT CLIENTE",
  "marketingPurposeText":
      "Accetto che Veralusso possa raccogliere le mie informazioni personali per scopi di marketing (newsletter, novità e promozioni).",
  "shoppingHabitText":
      "Accetto che Veralusso possa raccogliere le mie informazioni personali per creare un profilo delle mie abitudini di acquisto.",
  "unitedKingdomText": "REGNO UNITO",
  "emailText": "E-mail",
  "confirmEmailText": "Conferma email",
  "confirmPasswordText": "Conferma password",
  "firstNameText": "Nome di battesimo",
  "lastNameText": "Cognome",
  "dateOfBirthText": "Data di nascita",
  "dateOfMarriageText": "Data di matrimonio",
  "telephoneNoText": "Telefono n.",
  "mr": "Sig.",
  "affiliateProgramTitleText": "PROGRAMMA DI AFFILIAZIONE VERALUSSO",
  "whoAreWeLookingTitleText": "Chi stiamo cercando?",
  "whoAreWeLookingDescriptionOneText":
      "Hai un sito web, un blog, un profilo sui social media alla moda e orientato al lusso, esperto di tendenze con una prospettiva internazionale? Il tuo obiettivo è la moda, lo stile di vita, la bellezza e il design? Se è così, stiamo cercando te!\n\nUnisciti al nostro programma di affiliazione globale e avrai l'opportunità di guadagnare una commissione ogni volta che i tuoi visitatori acquistano da VERALUSSO.",
  "whatCanYouExpectTitleText": "Cosa puoi aspettarti?",
  "expectRuleOneText": "Commissione su tutte le vendite nette approvate",
  "expectRuleTwoText": "Finestra dei cookie di 45 giorni",
  "expectRuleThreeText": "Feed di dati aggiornato più volte al giorno",
  "expectRuleFourText":
      "Accesso a banner personalizzati, textlink, deeplink e al nostro datafeed in 9 lingue (inglese, italiano, francese, tedesco, coreano, spagnolo, cinese, russo e giapponese)",
  "expectRuleFiveText":
      "La possibilità di personalizzare i feed in tutte le valute mondiali",
  "promoteSoloQuestionText": "Come puoi promuovere VERALUSSO (come affiliato)?",
  "promoteSoloAnswerOneText":
      "Creazione di contenuti di alta qualità e coinvolgenti che rispecchiano lo stile di VERALUSSO",
  "promoteSoloAnswerTwoText":
      "Con i nostri contenuti, banner e collegamenti per più categorie ed eventi sul tuo sito Web e sui canali dei social media",
  "promoteSoloAnswerThreeText":
      "Promuovere i vantaggi che i nostri clienti amano",
  "promoteSoloAnswerFourText":
      "Una selezione di articoli in continuo aggiornamento delle migliori marche",
  "promoteSoloAnswerFiveText":
      "Resi gratuiti senza tasse aggiuntive per Stati Uniti, Canada, Regno Unito e",
  "howApplyTitleText": "Come applicare?",
  "howApplyAnswerOneText":
      "Inviaci un'e-mail con il nome e l'URL del tuo sito Web, blog o profilo sui social media e dei tuoi mercati principali. Esamineremo il tuo sito e ti ricontatteremo con ulteriori informazioni su come aderire al programma di affiliazione.\n\nTieni presente che tutte le domande vengono valutate manualmente e l'elaborazione potrebbe richiedere fino a 10 giorni.\n\nSe ritieni che la tua candidatura è stato ingiustamente rifiutato, contatta affiliates@veralusso.com e un membro del team risponderà alle tue preoccupazioni.",
  "visitorMonthHintText": "Seleziona Visitatori unici/Mese",
  "viewsMonthHintText": "Seleziona Visualizzazioni pagina/Mese",
  "cityHintText": "Città",
  "countryHintText": "Paese",
  "addressOneText": "Indirizzo 1",
  "addressTwoText": "Indirizzo 2",
  "addressText": "Indirizzo",
  "letsGoText": "Andiamo",
  "postCodeText": "Codice postale",
  "contactNoText": "Contatto n.",
  "websiteUrlText": "URL del sito",
  "profileText": "Profilo",
  "wishListText": "Whist List",
  "myOrdersText": "I MIEI ORDINI",
  "myWishlistText": "La mia lista dei desideri",
  "addressBookText": "Rubrica",
  "accountInformationText": "Informazioni account",
  "storePaymentText": "METODI DI PAGAMENTO MEMORIZZATI",
  "newsLetterText": "ABBONAMENTI ALLA NEWSLETTER",
};
