const Map<String, String> ja = {
  "language": "英語",
  "homeText": "家",
  "searchText": "検索",
  "designersText": "デザイナー",
  "yourEmailText": "あなたのEメール",
  "gdpText": "GDP",
  "englishText": "英語",
  "checkoutText": "チェックアウト",
  "purchaseText": "購入を完了するには、以下に詳細を入力してください",
  "shippingAddressText": "お届け先の住所",
  "shippingMethodText": "配送方法",
  "paymentMethodText": "支払方法",
  "orderSummaryText": "注文の概要",
  "createCheckoutText": "チェックアウト後にアカウントを作成できます。",
  "stLine1": "番地：1号線",
  "stLine2": "住所：2号線",
  "stLine3": "住所：3号線",
  "cityText": "市",
  "indiaText": "インド",
  "stateText": "地域、州、または州を選択してください",
  "zipCodeText": "郵便番号/郵便番号",
  "phoneNumberText": "電話番号",
  "itemInCartText": "カート内のアイテム",
  "applyDiscountCodeText": "割引コードを適用する",
  "enterDiscountCodeText": "割引コードを入力してください",
  "applyDiscountText": "割引を適用する",
  "orderTotalText": "注文合計",
  "orderCommentText": "注文コメント",
  "placeOrderText": "注文する",
  "myAccountText": "マイアカウント",
  "appNameText": "ベラ・ルッソ",
  "aboutUsText": "私たちに関しては",
  "aboutUsContain":
      'VERA LUSSOは、月に500万人の訪問者がおり、世界中に出荷されている、トップのオンラインラグジュアリーファッションデスティネーションです。',
  "aboutUsContain1":
      'このウェブサイトには、一流のデザイナーと若くて新しい才能の最高のセレクションが掲載されています。 vera lussoは、1930年代初頭にフィレンツェで設立され、ローマ通りに同社の名を冠したコンセプトストアがオープンしました。 1999年以来オンラインで、同社は総収益の90％をオンライン販売に帰しています。現在でも、創業者の孫であるAndrea PanconesiがCEOを務め、娘のAnnagreta Panconesiがクリエイティブディレクターを務める、100％個人経営の家族経営の会社です。',
  "aboutUsContain2":
      'このサイトでは、バレンシアガ、ベテメンツ、オフホワイト、J.W。などの最も有名なデザイナーの男性、女性、子供向けの製品を取り揃え、衣料品、靴、バッグ、アクセサリー、高級住宅のインテリア、美容を幅広く取り揃えています。アンダーソン、バルマン、ドルチェ＆ガッバーナ、グッチ、サンローラン、バレンチノ、ジバンシィ、ロエベジャックムスなど。',
  "aboutUsContain3":
      '現在、ベラルッソの生産と維持に取り組んでいる15カ国から200人がいます。このサイトは、英語、イタリア語、ドイツ語、中国語、ロシア語、スペイン語、フランス語、韓国語、日本語の9か国語で利用できます。このサイトは完全に社内で作成されており、フィレンツェのオフィスにはグラフィックデザイン、IT、カスタマーサービス、マーケティング、購入の各部門があります。スタイリストとプレスチームは、世界のファッションの中心地であるミラノのベラルッソオフィスで活動しています。',
  "aboutUsContain4":
      'すべての注文は、ベラルッソ本社から、シグネチャーシューズバッグからパーソナライズされたリボンまで、細心の注意を払って準備され、最高の素材を使用したボックスで世界中に発送されます。',
  "aboutUsContain5":
      'vera lussoは、2008年に150万人のユニークビジターがサイトにアクセスし、2017年には5,300万人のユニークビジターに成長しました。オンライン売上の15％以上が米国からのもので、ドイツ、英国、イタリア、中国、フランスがそれに続きます。',
  "aboutUsContain6":
      'vera lussoは、Buy It First、Luxury Club、Sneakers Club、LVR Privilege、LVR Editionsなどの一連の独占的なサービスと商標イニシアチブにより、オンラインとオフラインの両方で高級小売業界の境界を押し広げています。',
  "orderConfirm": "ご購入いただきありがとうございます！",
  "orderIdTitle": '「ご注文番号は次のとおりです：」',
  "orderIdIs": ''' 1490004''',
  "orderNumberTitle": '注文番号：',
  "orderNumberIs": ' 2080004',
  "orderDateTitle": '注文日：',
  "orderDateIs": ' 2021年9月7日',
  "image": '画像',
  "productName": '商品名',
  "sku": 'SKU',
  "price": '価格',
  "qty": '数量',
  "subTotal": '小計',
  "action": 'アクション',
  "buyBack": '買い戻す',
  "orderContain": "詳細と追跡情報が記載された注文確認メールをお送りします。",
  "referFriendText": "友達を紹介する",
  "returnsRefundsText": "返品と返金",
  "faqText": "よくある質問",
  "contactText": "連絡先",
  "socialText": "社交",
  "companyText": "会社",
  "contactUs": "お問い合わせ",
  "myOrders": "私の注文",
  "myOrderImage": "画像",
  "quantity": "数量",
  "status": "スターテス",
  "paymentMethod": " 支払方法",
  "shippingAddress": "お届け先の住所",
  "billingAddress": "請求先住所",
  "continueShopping": "ショッピングを続ける",
  "goToYourAccountText": "アカウントに移動します",
  "emailAddressText": "電子メールアドレス",
  "passwordText": "パスワード",
  "saveYourFavoriteItemsInAWishListText": "お気に入りのアイテムをウィッシュリストに保存します",
  "cardsText": "カードと優先配送先住所を保存します",
  "shippingText": "ご注文と返品の詳細とステータスを確認してください",
  "registerText": "登録",
  "registerWithFacebookText": "Facebookに登録する",
  "logInAndEnjoyAPersonalizedShoppingExperienceText":
      "ログインして、パーソナライズされたショッピング体験をお楽しみください。",
  "dontHaveAnAccountYetText": "まだアカウントをお持ちではありませんか？",
  "loginWithFacebookText": "Facebookでログイン",
  "loginText": "ログインする",
  "forgotYourPasswordText": "パスワードをお忘れですか？",
  "subscribeToOurNewsletterText": "ニュースレターを購読する",
  "getAllDescriptionText":
      "イベント、販売、オファーに関するすべての最新情報を入手してください。今日のニュースレターにサインアップしてください。",
  "enterYourEmailAddressText": "メールアドレスを入力してください",
  "subscribeText": "購読",
  "changeTHEWORLDWithYourPurchaseText": "あなたの購入で世界を変える",
  "companyNameText": "会社",
  "contactsText": "連絡先",
  "othersText": "その他",
  "createAnAccountText": "アカウントを作成する",
  "createNewCustomerAccountText": "新しい顧客アカウントを作成する",
  "marketingPurposeText":
      "Veralussoがマーケティング目的（ニュースレター、ニュース、プロモーション）で私の個人情報を収集する場合があることに同意します。",
  "shoppingHabitText":
      "Veralussoが私の個人情報を収集して、私の買い物習慣のプロファイルを作成する場合があることに同意します。",
  "unitedKingdomText": "イギリス",
  "emailText": "Eメール",
  "confirmEmailText": "Eメール確認",
  "confirmPasswordText": "パスワードを認証する",
  "firstNameText": "ファーストネーム",
  "lastNameText": "苗字",
  "dateOfBirthText": "生年月日",
  "dateOfMarriageText": "結婚日",
  "telephoneNoText": "電話番号",
  "mr": "氏。",
  "affiliateProgramTitleText": "VERALUSSOアフィリエイトプログラム",
  "whoAreWeLookingTitleText": "誰を探していますか？",
  "whoAreWeLookingDescriptionOneText":
      "あなたは、国際的な展望を持ったトレンドに精通した、流行に敏感で贅沢なウェブサイト、ブログ、ソーシャルメディアのプロフィールを持っていますか？あなたの焦点はファッション、ライフスタイル、美容、デザインですか？もしそうなら、私たちはあなたを探しています！\n n私たちのグローバルアフィリエイトプログラムに参加すると、訪問者がVERALUSSOから購入するたびにコミッションを獲得する機会があります。",
  "whatCanYouExpectTitleText": "あなたは何を期待できますか？",
  "expectRuleOneText": "承認されたすべての純売上高の手数料",
  "expectRuleTwoText": "45日間のCookieウィンドウ",
  "expectRuleThreeText": "データフィードは1日に複数回更新されます",
  "expectRuleFourText":
      "カスタマイズされたバナー、テキストリンク、ディープリンク、および9か国語（英語、イタリア語、フランス語、ドイツ語、韓国語、スペイン語、中国語、ロシア語、日本語）のデータフィードへのアクセス",
  "expectRuleFiveText": "フィードをすべての世界通貨にカスタマイズする可能性",
  "promoteSoloQuestionText": "VERALUSSOを（アフィリエイトとして）どのように宣伝できますか？",
  "promoteSoloAnswerOneText": "VERALUSSOのスタイルを反映した高品質で魅力的なコンテンツを作成する",
  "promoteSoloAnswerTwoText":
      "ウェブサイトやソーシャルメディアチャネルでの複数のカテゴリやイベントのコンテンツ、バナー、リンクを紹介する",
  "promoteSoloAnswerThreeText": "お客様が愛するメリットを促進する",
  "promoteSoloAnswerFourText": "最高のブランドから継続的に更新される記事の選択",
  "promoteSoloAnswerFiveText": "米国、カナダ、英国、および",
  "howApplyTitleText": "適用する方法？",
  "howApplyAnswerOneText":
      "あなたのウェブサイト、ブログまたはソーシャルメディアのプロフィールとあなたの主な市場の名前とURLを私達に電子メールで送ってください。サイトを確認し、アフィリエイトプログラムへの参加方法の詳細についてご連絡いたします。\n nすべての申し込みは手動で評価され、処理には最大10日かかる場合があります。\n\n申し込みを感じた場合不当に拒否された場合は、affiliates@veralusso.comまでご連絡ください。チームのメンバーが懸念事項に対応します。",
  "visitorMonthHintText": "ユニークビジター/月を選択",
  "viewsMonthHintText": "ページビュー/月を選択",
  "cityHintText": "市",
  "countryHintText": "国",
  "addressOneText": "住所1",
  "addressTwoText": "番地2",
  "addressText": "住所",
  "letsGoText": "さあ行こう",
  "postCodeText": "郵便番号",
  "contactNoText": "連絡先番号。",
  "websiteUrlText": "ウェブサイトのURL",
  "profileText": "プロフィール",
  "wishListText": "WhistList",
  "myOrdersText": "私の注文",
  "myWishlistText": "私のウィッシュリスト",
  "addressBookText": "住所録",
  "accountInformationText": "口座情報",
  "storePaymentText": "保管された支払い方法",
  "newsLetterText": "ニュースレターの購読",
};
