const Map<String, String> ko = {
  "language": "영어",
  "homeText": "집",
  "searchText": "검색",
  "designersText": "디자이너",
  "yourEmailText": "귀하의 이메일",
  "gdpText": "GDP",
  "englishText": "영어",
  "checkoutText": "점검",
  "purchaseText": "구매를 완료하려면 아래에 세부 정보를 입력하십시오",
  "shippingAddressText": "배송 주소",
  "shippingMethodText": "배송 방법",
  "paymentMethodText": "지불 방법",
  "orderSummaryText": "주문 요약",
  "createCheckoutText": "결제 후 계정을 생성할 수 있습니다.",
  "stLine1": "주소: 1호선",
  "stLine2": "주소: 2호선",
  "stLine3": "주소: 3호선",
  "cityText": "도시",
  "indiaText": "인도",
  "stateText": "지역, 주 또는 도를 선택하세요.",
  "zipCodeText": "우편번호",
  "phoneNumberText": "전화 번호",
  "itemInCartText": "장바구니에 담긴 상품",
  "applyDiscountCodeText": "할인 코드 적용",
  "enterDiscountCodeText": "할인 코드 입력",
  "applyDiscountText": "할인 적용",
  "orderTotalText": "주문 합계",
  "orderCommentText": "주문 코멘트",
  "placeOrderText": "주문하기",
  "myAccountText": "내 계정",
  "appNameText": "베라 루소",
  "aboutUsText": "회사 소개",
  "aboutUsContain":
      'VERA LUSSO는 월 500만 방문자와 전 세계 배송이 가능한 최고의 온라인 럭셔리 패션 명소입니다.',
  "aboutUsContain1":
      '이 웹사이트는 최고의 기성 디자이너와 젊은 신진 재능을 엄선하여 제공합니다. vera lusso는 1930년대 초 피렌체에서 Via Roma에 회사의 이름을 딴 컨셉 스토어를 오픈하면서 설립되었습니다. 1999년부터 온라인으로 시작한 이 회사는 총 수익의 90%를 온라인 판매로 돌립니다. 오늘날까지 창립자의 손자 Andrea Panconesi가 CEO로, 그의 딸 Annagreta Panconesi가 크리에이티브 디렉터로 활동하는 100% 개인 소유 가족 기업으로 남아 있습니다.',
  "aboutUsContain2":
      '이 사이트는 Balenciaga, Vetements, Off-White, J.W. Anderson, Balmain, Dolce & Gabbana, Gucci, Saint Laurent, Valentino, Givenchy, Loewe Jacquemus 등.',
  "aboutUsContain3":
      '현재 15개국에서 200명이 베라 루소를 생산하고 유지하기 위해 일하고 있습니다. 이 사이트는 영어 이탈리아어, 독일어, 중국어, 러시아어, 스페인어 프랑스어, 한국어 및 일본어의 9개 언어로 제공됩니다. 이 사이트는 그래픽 디자인, IT, 고객 서비스, 마케팅 및 구매 부서가 있는 Florence 사무실과 함께 완전히 사내에서 만들어졌습니다. 스타일리스트와 언론팀은 세계 패션의 중심지인 밀라노에 있는 베라 루소 사무실에서 일합니다.',
  "aboutUsContain4":
      '모든 주문은 시그니처 신발 가방에서 맞춤형 리본에 이르기까지 최고의 자재를 사용하고 최대한 주의를 기울여 준비된 상자에 담아 베라 루소 본사에서 전 세계로 배송됩니다.',
  "aboutUsContain5":
      'vera lusso는 2008년에 150만 명의 고유 방문자가 사이트에 액세스했으며 2017년에는 5,300만 명의 고유 방문자로 성장했습니다. 온라인 판매의 15% 이상이 미국에서 발생하고 독일, 영국, 이탈리아, 중국 및 프랑스가 그 뒤를 잇습니다.',
  "aboutUsContain6":
      'vera lusso는 Buy It First, Luxury Club, Sneakers Club, LVR Privilege 및 LVR Editions를 포함한 일련의 독점 서비스 및 상표 이니셔티브를 통해 온라인과 오프라인 모두에서 럭셔리 소매 환경의 경계를 확장합니다.',
  "orderConfirm": "구입 주셔서 감사합니다!",
  "orderIdTitle": '''주문 번호:''',
  "orderIdIs": ''' 1490004''',
  "orderNumberTitle": '주문 번호:',
  "orderNumberIs": ' 2080004',
  "orderDateTitle": '주문 날짜:',
  "orderDateIs": ' 2021년 9월 7일',
  "image": '영상',
  "productName": '상품명',
  "sku": 'SKU',
  "price": '가격',
  "qty": '수량',
  "subTotal": '소계',
  "action": '동작',
  "buyBack": '다시 구입',
  "orderContain": "세부 정보 및 추적 정보가 포함된 주문 확인 이메일을 보내드립니다.",
  "referFriendText": "친구 추천",
  "returnsRefundsText": "반품 및 환불",
  "faqText": "자주하는 질문",
  "contactText": "연락하다",
  "socialText": "사회의",
  "companyText": "회사",
  "contactUs": "문의하기",
  "myOrders": "내 주문",
  "myOrderImage": "영상",
  "quantity": "수량",
  "status": "상태",
  "paymentMethod": " 지불 방법",
  "shippingAddress": "배송 주소",
  "billingAddress": "청구 지 주소",
  "continueShopping": "쇼핑을 계속",
  "goToYourAccountText": "계정으로 이동",
  "emailAddressText": "이메일 주소",
  "passwordText": "비밀번호",
  "saveYourFavoriteItemsInAWishListText": "마음에 드는 아이템을 위시리스트에 저장",
  "cardsText": "카드와 선호하는 배송 주소를 저장하십시오",
  "shippingText": "주문 및 반품 내역 및 상태 확인",
  "registerText": "등록하다",
  "registerWithFacebookText": "페이스북에 등록",
  "logInAndEnjoyAPersonalizedShoppingExperienceText":
      "로그인하고 개인화된 쇼핑 경험을 즐기십시오.",
  "dontHaveAnAccountYetText": "아직 계정이 없으신가요?",
  "loginWithFacebookText": "페이스북으로 로그인",
  "loginText": "로그인",
  "forgotYourPasswordText": "비밀번호를 잊어 버렸습니까?",
  "subscribeToOurNewsletterText": "뉴스레터 구독",
  "getAllDescriptionText": "이벤트, 판매 및 제안에 대한 모든 최신 정보를 얻으십시오. 오늘 뉴스레터에 가입하세요.",
  "enterYourEmailAddressText": "당신의 이메일 주소를 입력 해주세요",
  "subscribeText": "구독하다",
  "changeTHEWORLDWithYourPurchaseText": "당신의 구매로 세상을 바꾸십시오",
  "companyNameText": "회사",
  "contactsText": "콘택트 렌즈",
  "othersText": "기타",
  "createAnAccountText": "계정 만들기",
  "createNewCustomerAccountText": "새 고객 계정 만들기",
  "marketingPurposeText":
      "나는 Veralusso가 마케팅 목적(뉴스레터, 뉴스 및 판촉)을 위해 내 개인 정보를 수집할 수 있다는 데 동의합니다.",
  "shoppingHabitText":
      "Veralusso가 내 쇼핑 습관에 대한 프로필을 작성하기 위해 내 개인 정보를 수집할 수 있다는 데 동의합니다.",
  "unitedKingdomText": "영국",
  "emailText": "이메일",
  "confirmEmailText": "이메일 확인",
  "confirmPasswordText": "비밀번호 확인",
  "firstNameText": "이름",
  "lastNameText": "성",
  "dateOfBirthText": "생일",
  "dateOfMarriageText": "결혼 날짜",
  "telephoneNoText": "전화번호",
  "mr": "씨.",
  "affiliateProgramTitleText": "VERALUSSO 제휴 프로그램",
  "whoAreWeLookingTitleText": "우리는 누구를 찾고 있습니까?",
  "whoAreWeLookingDescriptionOneText":
      "유행을 선도하고 럭셔리 지향적인 웹사이트, 블로그, 소셜 미디어 프로필이 있고 국제적 시각을 갖고 있습니까? 당신의 초점은 패션, 라이프 스타일, 뷰티 및 디자인입니까? 그렇다면 우리는 당신을 찾고 있습니다!\n\n글로벌 제휴 프로그램에 가입하면 방문자가 VERALUSSO에서 구매할 때마다 수수료를 받을 수 있는 기회가 주어집니다.",
  "whatCanYouExpectTitleText": "무엇을 기대할 수 있습니까?",
  "expectRuleOneText": "승인된 모든 순매출에 대한 수수료",
  "expectRuleTwoText": "45일 쿠키 기간",
  "expectRuleThreeText": "데이터 피드는 하루에 여러 번 업데이트됨",
  "expectRuleFourText":
      "9개 언어(영어, 이탈리아어, 프랑스어, 독일어, 한국어, 스페인어, 중국어, 러시아어 및 일본어)로 맞춤형 배너, 텍스트 링크, 딥링크 및 데이터 피드에 액세스",
  "expectRuleFiveText": "피드를 모든 세계 통화로 사용자 정의할 수 있는 가능성",
  "promoteSoloQuestionText": "VERALUSSO(제휴사)를 어떻게 홍보할 수 있습니까?",
  "promoteSoloAnswerOneText": "VERALUSSO 스타일을 반영한 고품질의 매력적인 콘텐츠 제작",
  "promoteSoloAnswerTwoText":
      "귀하의 웹사이트 및 소셜 미디어 채널에 다양한 카테고리 및 이벤트에 대한 콘텐츠, 배너 및 링크를 제공합니다.",
  "promoteSoloAnswerThreeText": "고객이 좋아하는 혜택 홍보",
  "promoteSoloAnswerFourText": "최고의 브랜드에서 지속적으로 업데이트되는 기사 선택",
  "promoteSoloAnswerFiveText": "미국, 캐나다, 영국 및 기타 국가에 대해 세금이 추가되지 않은 무료 반품",
  "howApplyTitleText": "신청 방법?",
  "howApplyAnswerOneText":
      "웹사이트, 블로그 또는 소셜 미디어 프로필 및 주요 시장의 이름과 URL을 이메일로 보내주십시오. 귀하의 사이트를 검토한 후 제휴 프로그램에 가입하는 방법에 대한 추가 정보를 알려 드리겠습니다.\n\n모든 신청서는 수동으로 평가되며 처리에는 최대 10일이 소요될 수 있습니다.\n\n신청이 마음에 드시면 잘못 거부된 경우 제휴사@veralusso.com으로 연락하시면 팀원이 귀하의 우려 사항을 해결할 것입니다.",
  "visitorMonthHintText": "순 방문자수/월 선택",
  "viewsMonthHintText": "페이지 조회수/월 선택",
  "cityHintText": "도시",
  "countryHintText": "국가",
  "addressOneText": "주소 1",
  "addressTwoText": "거리 주소 2",
  "addressText": "주소",
  "letsGoText": "갑시다",
  "postCodeText": "우편번호",
  "contactNoText": "연락처",
  "websiteUrlText": "웹 사이트 주소",
  "profileText": "프로필",
  "wishListText": "WhistList",
  "myOrdersText": "내 주문",
  "myWishlistText": "내 위시리스트",
  "addressBookText": "주소록",
  "accountInformationText": "계정 정보",
  "storePaymentText": "저장된 결제 방법",
  "newsLetterText": "뉴스레터 구독",
};
