const Map<String, String> nl = {
  "language": "Engels",
  "homeText": "Thuis",
  "searchText": "Zoekopdracht",
  "designersText": "Ontwerpers",
  "yourEmailText": "Jouw email",
  "gdpText": "BBP",
  "englishText": "Engels",
  "checkoutText": "Uitchecken",
  "purchaseText": "Voer hieronder uw gegevens in om uw aankoop te voltooien:",
  "shippingAddressText": "Verzendingsadres",
  "shippingMethodText": "Verzendmethode:",
  "paymentMethodText": "Betalingswijze",
  "orderSummaryText": "overzicht van de bestelling",
  "createCheckoutText": "Na het afrekenen kun je een account aanmaken.",
  "stLine1": "Straat Adres: Lijn 1",
  "stLine2": "Straat adres lijn 2",
  "stLine3": "Straat Adres: Lijn 3",
  "cityText": "Stad",
  "indiaText": "India",
  "stateText": "Selecteer een regio, staat of provincie",
  "zipCodeText": "Postcode/postcode",
  "phoneNumberText": "Telefoonnummer",
  "itemInCartText": "Artikel in winkelwagen",
  "applyDiscountCodeText": "Kortingscode toepassen",
  "enterDiscountCodeText": "Voer kortingscode in",
  "applyDiscountText": "KORTING TOEPASSEN",
  "orderTotalText": "totale bestelling",
  "orderCommentText": "Bestelling Opmerking",
  "placeOrderText": "PLAATS BESTELLING",
  "myAccountText": "Mijn rekening",
  "appNameText": "Vera Lusso",
  "aboutUsText": "Over ons",
  "aboutUsContain":
      'VERA LUSSO IS EEN TOP ONLINE LUXE MODEBESTEMMING MET 5 MILJOEN BEZOEKERS PER MAAND EN WERELDWIJDE VERZENDING.',
  "aboutUsContain1":
      'De website biedt de beste selectie van de beste gevestigde ontwerpers en jonge opkomende talenten. vera lusso werd begin jaren dertig in Florence opgericht met de opening van de gelijknamige conceptstore van het bedrijf aan de Via Roma. Online sinds 1999 schrijft het bedrijf 90% van de totale omzet toe aan online verkopen. Tot op de dag van vandaag blijft het een 100% particulier familiebedrijf, met de kleinzoon van de oprichter, Andrea Panconesi, die optreedt als CEO en zijn dochter, Annagreta Panconesi als creatief directeur.',
  "aboutUsContain2":
      'De site biedt een brede selectie van kleding, schoenen, tassen, accessoires, luxe interieurs en beauty, met producten voor mannen, vrouwen en kinderen van de meest prestigieuze ontwerpers zoals Balenciaga, Vetements, Off-White, J.W. Anderson, Balmain, Dolce & Gabbana, Gucci, Saint Laurent, Valentino, Givenchy, Loewe Jacquemus en meer.',
  "aboutUsContain3":
      'Er zijn momenteel 200 mensen uit 15 verschillende landen die werken aan de productie en het onderhoud van vera lusso. De site is beschikbaar in 9 talen: Engels Italiaans, Duits, Chinees, Russisch, Spaans Frans, Koreaans en Japans. De site is volledig in eigen beheer gemaakt, met de afdelingen grafisch ontwerp, IT, klantenservice, marketing en inkoop in Florence. De stylisten en persteams opereren vanuit het vera lusso-kantoor in de modehoofdstad van de wereld - Milaan.',
  "aboutUsContain4":
      'Alle bestellingen worden wereldwijd verzonden vanuit het hoofdkantoor van vera lusso in dozen die met maximale zorg zijn voorbereid en de beste materialen gebruiken, van de kenmerkende schoenentassen tot het gepersonaliseerde lint.',
  "aboutUsContain5":
      'vera lusso had in 2008 1,5 miljoen unieke bezoekers op de site en is in 2017 gegroeid tot 53 miljoen unieke bezoekers. Meer dan 15% van de online verkopen wordt gegenereerd in de Verenigde Staten, gevolgd door Duitsland, het VK, Italië, China en Frankrijk.',
  "aboutUsContain6":
      'vera lusso verlegt de grenzen van het luxe retaillandschap, zowel online als offline met een scala aan exclusieve diensten en handelsmerkinitiatieven, waaronder Buy It First, Luxury Club, Sneakers Club, LVR Privilege en LVR Editions.',
  "orderConfirm": "DANK VOOR UW AANKOOP!",
  "orderIdTitle": '''Uw bestelling # is:''',
  "orderIdIs": ''' 1490004''',
  "orderNumberTitle": 'BESTELLINGSNUMMER:',
  "orderNumberIs": ' 2080004',
  "orderDateTitle": 'Besteldatum:',
  "orderDateIs": ' 7 september 2021',
  "image": 'AFBEELDING',
  "productName": 'PRODUCTNAAM',
  "sku": 'Artikelnummer',
  "price": 'PRIJS',
  "qty": 'AANTAL',
  "subTotal": 'SUBTOTAAL',
  "action": 'ACTIE',
  "buyBack": 'TERUGKOPEN',
  "orderContain":
      "We sturen je een orderbevestiging met details en trackinginformatie.",
  "referFriendText": "Verwijs vriend",
  "returnsRefundsText": "Retourneren & Terugbetalingen",
  "faqText": "FAQ",
  "contactText": "Contact",
  "socialText": "sociaal",
  "companyText": "Bedrijf",
  "contactUs": "Neem contact op",
  "myOrders": "mijn bestellingen",
  "myOrderImage": "Afbeelding",
  "quantity": "aantal",
  "status": "Toestand",
  "paymentMethod": " Betalingswijze",
  "shippingAddress": "Verzendingsadres",
  "billingAddress": "factuur adres",
  "continueShopping": "Doorgaan met winkelen",
  "goToYourAccountText": "Ga naar je account",
  "emailAddressText": "E-mailadres",
  "passwordText": "Wachtwoord",
  "saveYourFavoriteItemsInAWishListText":
      "Bewaar je favoriete items in een verlanglijst",
  "cardsText": "Bewaar uw kaarten en gewenste verzendadressen",
  "shippingText": "Bekijk de details en status van je bestellingen en retouren",
  "registerText": "REGISTER",
  "registerWithFacebookText": "Registreer met Facebook",
  "logInAndEnjoyAPersonalizedShoppingExperienceText":
      "Log in en geniet van een gepersonaliseerde winkelervaring.",
  "dontHaveAnAccountYetText": "Heb je nog geen account?",
  "loginWithFacebookText": "Inloggen met Facebook",
  "loginText": "LOG IN",
  "forgotYourPasswordText": "Uw wachtwoord vergeten?",
  "subscribeToOurNewsletterText": "ABONNEER OP ONZE NIEUWSBRIEF",
  "getAllDescriptionText":
      "Ontvang de laatste informatie over evenementen, verkopen en aanbiedingen. Meld u vandaag nog aan voor de nieuwsbrief.",
  "enterYourEmailAddressText": "Vul je e-mailadres in",
  "subscribeText": "ABONNEREN",
  "changeTHEWORLDWithYourPurchaseText": "VERANDER DE WERELD MET UW AANKOOP",
  "companyNameText": "BEDRIJF",
  "contactsText": "CONTACTEN",
  "othersText": "ANDEREN",
  "createAnAccountText": "ACCOUNT AANMAKEN",
  "createNewCustomerAccountText": "MAAK EEN NIEUWE KLANTENACCOUNT",
  "marketingPurposeText":
      "Ik ga ermee akkoord dat Veralusso mijn persoonlijke gegevens mag verzamelen voor marketingdoeleinden (nieuwsbrieven, nieuws en promoties).",
  "shoppingHabitText":
      "Ik ga ermee akkoord dat Veralusso mijn persoonlijke gegevens mag verzamelen om een ​​profiel van mijn winkelgewoonten te maken.",
  "unitedKingdomText": "VERENIGD KONINKRIJK",
  "emailText": "E-mail",
  "confirmEmailText": "Bevestig Email",
  "confirmPasswordText": "bevestig wachtwoord",
  "firstNameText": "Voornaam",
  "lastNameText": "Achternaam",
  "dateOfBirthText": "Geboortedatum",
  "dateOfMarriageText": "Huwelijksdatum",
  "telephoneNoText": "Telefoon Nee.",
  "mr": "Dhr.",
  "affiliateProgramTitleText": "VERALUSSO AFFILIATE PROGRAMMA",
  "whoAreWeLookingTitleText": "Wie zoeken we?",
  "whoAreWeLookingDescriptionOneText":
      "Heb je een fashion-forward, luxe georiënteerde website, blog, social media profiel dat trendgevoelig is met een internationale kijk? Ligt jouw focus op fashion, lifestyle, beauty en design? Dan zijn we op zoek naar jou!\n\nWord lid van ons wereldwijde partnerprogramma en je krijgt de mogelijkheid om commissie te verdienen elke keer dat je bezoekers iets kopen bij VERALUSSO.",
  "whatCanYouExpectTitleText": "Wat kunt u verwachten?",
  "expectRuleOneText": "Commissie op alle goedgekeurde netto-omzet",
  "expectRuleTwoText": "Cookievenster van 45 dagen",
  "expectRuleThreeText": "Gegevensfeed meerdere keren per dag bijgewerkt",
  "expectRuleFourText":
      "Toegang tot aangepaste banners, tekstlinks, deeplinks en onze datafeed in 9 talen (Engels, Italiaans, Frans, Duits, Koreaans, Spaans, Chinees, Russisch en Japans)",
  "expectRuleFiveText":
      "De mogelijkheid om feeds in alle wereldvaluta's aan te passen",
  "promoteSoloQuestionText": "Hoe kun je VERALUSSO promoten (als affiliate)?",
  "promoteSoloAnswerOneText":
      "Het creëren van hoogwaardige en boeiende inhoud die de stijl van VERALUSSO . weerspiegelt",
  "promoteSoloAnswerTwoText":
      "Met onze inhoud, banners en links voor meerdere categorieën en evenementen op uw website en sociale mediakanalen",
  "promoteSoloAnswerThreeText":
      "De voordelen promoten waar onze klanten dol op zijn",
  "promoteSoloAnswerFourText":
      "Een selectie van continu bijgewerkte artikelen van de beste merken",
  "promoteSoloAnswerFiveText":
      "Gratis retourneren zonder toegevoegde belastingen voor de VS, Canada, het VK en",
  "howApplyTitleText": "Hoe aanvragen?",
  "howApplyAnswerOneText":
      "E-mail ons de naam en URL van uw website, blog of social media-profiel en uw belangrijkste markten. We zullen uw site beoordelen en contact met u opnemen met meer informatie over hoe u zich bij het partnerprogramma kunt aansluiten.\n\nHoud er rekening mee dat alle aanvragen handmatig worden beoordeeld en dat de verwerking tot 10 dagen kan duren.\n\nAls u denkt dat uw aanvraag ten onrechte is geweigerd, neem dan contact op met affiliates@veralusso.com en een lid van het team zal uw zorgen behandelen.",
  "visitorMonthHintText": "Selecteer Unieke Bezoekers/Maand",
  "viewsMonthHintText": "Selecteer Paginaweergaven/Maand",
  "cityHintText": "Stad",
  "countryHintText": "Land",
  "addressOneText": "Straatnaam 1",
  "addressTwoText": "Straatadres 2",
  "addressText": "Adres",
  "letsGoText": "Laten we gaan",
  "postCodeText": "Postcode",
  "contactNoText": "Contactnr.",
  "websiteUrlText": "Website URL",
  "profileText": "Profiel",
  "wishListText": "WhistLijst",
  "myOrdersText": "MIJN BESTELLINGEN",
  "myWishlistText": "Mijn wenslijst",
  "addressBookText": "Adresboek",
  "accountInformationText": "Account Informatie",
  "storePaymentText": "OPGESLAGEN BETAALMETHODEN",
  "newsLetterText": "NIEUWSBRIEF ABONNEMENTEN",
};
