const Map<String, String> ar = {
  "language": "إنجليزي",
  "appNameText": "فاخر منفرد",
  "aboutUsText": "معلومات عنا",
  "referFriendText": "ادع صديق",
  "returnsRefundsText": "العوائد والمردودات",
  "faqText": "التعليمات",
  "contactText": "اتصل",
  "socialText": "اجتماعي",
  "companyText": "شركة",
  "contactUs": "اتصل بنا",
  "myOrders": "طلباتي",
  "myOrderImage": "صورة",
  "productName": "اسم المنتج",
  "sku": "SKU",
  "price": "السعر",
  "quantity": "الكمية",
  "status": "حالة",
  "action": "عمل",
  "paymentMethod": " طريقة الدفع او السداد",
  "shippingAddress": "عنوان الشحن",
  "billingAddress": "عنوان وصول الفواتير",
  "continueShopping": "مواصلة التسوق",
  "freuentlyAskedQueText": "أسئلة مكررة",
  "shopAndPlaceOrder": "كيف تتسوق وتضع طلب؟",
  "accountToPlaceOrderQues": "هل أحتاج إلى حساب لتقديم طلب؟",
  "accountToPlaceOrderAns":
      "لا ، كل ما تحتاجه هو عنوان بريد إلكتروني. نوصيك بالتسجيل للحصول على حساب لبدء إضافة قطع إلى قائمة الرغبات الخاصة بك ، ولكن يمكنك أيضًا تقديم الطلبات وتتبعها كضيف والاشتراك في الوقت الذي يناسبك.",
  "registeredCustomersText": "العملاء المسجلين",
  "registeredCustomersDescriptionText":
      "إذا كان لديك حساب ، قم بتسجيل الدخول باستخدام \n عنوان بريدك الإلكتروني.",
  "usernameText": "اسم المستخدم",
  "passwordText": "كلمة المرور",
  "signInText": "تسجيل الدخول",
  "forgotYourPasswordText": "نسيت رقمك السري؟",
  "newCustomersText": "زبائن الجدد",
  "loginDescriptionText":
      "إنشاء حساب له فوائد عديدة: تحقق \n بشكل أسرع ، واحتفظ بأكثر من عنوان واحد \n تتبع الطلبات والمزيد.",
  "createAccountText": "إنشاء حساب",
  "firstNameText": "الاسم الأول",
  "lastNameText": "الكنية",
  "dateOfBirthText": "تاريخ الميلاد",
  "pleaseSelectValidDateText": "الرجاء تحديد تاريخ صالح",
  "marriageAnniversaryText": "ذكرى الزواج",
  "emailText": "بريد الالكتروني",
  "confirmPasswordText": "تأكيد كلمة المرور",
  "signUpForNewsletterText": "الاشتراك في النشرة الإخبارية",
  "forgotYourPasswordDescriptionText":
      "الرجاء إدخال عنوان بريدك الإلكتروني أدناه لتلقي \n ارتباط إعادة تعيين كلمة المرور",
  "enterYourEmailText": "أدخل بريدك الإلكتروني",
  "resetMyPasswordText": "إعادة تعيين كلمة المرور الخاصة بي",
  "accessYourAccountDetailsText": "الوصول إلى تفاصيل حسابك والمكافآت",
  "signUpText": "اشتراك",
  "myOrdersText": "طلباتي",
  "myWishlistText": "قائمة امنياتي",
  "addressBookText": "دليل العناوين",
  "accountInformationText": "معلومات الحساب",
  "myTicketsText": "تذاكري",
  "trackOrderText": "ترتيب المسار",
  "companyMyAccountText": "شركة",
  "contactUsText": "اتصل بنا",
  "secureShoppingText": "تسوق آمن",
  "advancedSearchText": "البحث المتقدم",
  "testimonialsText": "الشهادات - التوصيات",
  "socialMyAccountText": "اجتماعي",
  "hopeText": "آمل أن",
  "affiliateProgramText": "إنضم لبرنامج",
  "influencerRegistrationText": "تسجيل المؤثر",
  "exchangeText": "التبادل والإرجاع",
  "contactMyAccountText": "جهات الاتصال",
  "privacyPolicyText": "سياسة خاصة",
  "termsConditionsText": "البنود و الظروف",
  "shippingText": "شحن",
  "aboutText": "حول",
  "aboutUsMyAccountText": "معلومات عنا",
  "referFriendMyAccountText": "ادع صديق",
  "returnsText": "العوائد والمردودات",
  "faqMyAccountText": "التعليمات",
  "myAccountText": "حسابي",
  "filtersText": "المرشحات",
  "priceText": "السعر",
  "colorText": "اللون",
  "brandText": "ماركة",
  "sizeText": "بحجم",
  "applyText": "تطبيق",
  "searchText": "بحث..",
  "aboutUsContain1":
      "SOLO هي أفضل وجهة للأزياء الفاخرة عبر الإنترنت مع 5 ملايين زائر شهريًا وشحن عالمي.",
  "aboutUsContain2":
      'Tيتميز موقعه الإلكتروني بأفضل اختيار لأفضل المصممين بالإضافة إلى المواهب الناشئة الشابة. تأسست Solo في فلورنسا في أوائل ثلاثينيات القرن الماضي ، مع افتتاح متجر مفهوم مسمى للشركة في Via Roma.Online منذ عام 1999 ، تنسب الشركة 90٪ من إجمالي الإيرادات إلى المبيعات عبر الإنترنت. حتى يومنا هذا ، لا تزال شركة عائلية مملوكة للقطاع الخاص بنسبة 100٪ ، حيث يتولى حفيد المؤسس ، أندريا بانكونيسي ، منصب الرئيس التنفيذي وابنته ، أناغريتا بانكونيزي ، مديرة إبداعية.',
  "aboutUsContain3":
      'Tيقدم الموقع مجموعة واسعة من الملابس والأحذية والحقائب والإكسسوارات والديكورات المنزلية الفاخرة والجمال ، مع منتجات متاحة للرجال والنساء والأطفال من أشهر المصممين مثل Balenciaga و Vetements و Off-White و J.W. Anderson و Balmain و Dolce & Gabbana و Gucci و Saint Laurent و Valentino و Givenchy و Loewe و Jacquemus والمزيد.',
  "aboutUsContain4":
      'يوجد حاليًا 200 شخص من 15 دولة مختلفة يعملون على إنتاج Solo وصيانته. الموقع متاح بـ 9 لغات: الإنجليزية والإيطالية والألمانية والصينية والروسية والإسبانية والفرنسية والكورية واليابانية. تم إنشاء الموقع داخليًا بالكامل ، من خلال مكتب فلورنسا للتصميم الجرافيكي وتكنولوجيا المعلومات وخدمة العملاء والتسويق والشراء. يعمل المصممون والفرق الصحفية من مكتب Solo في عاصمة الموضة في العالم - ميلان.',
  "aboutUsContain5":
      'يتم شحن جميع الطلبات في جميع أنحاء العالم من المقر الرئيسي لشركة Solo في صناديق يتم إعدادها بأقصى قدر من العناية وتستخدم أفضل المواد ، من أكياس الأحذية المميزة إلى الشريط المخصص.',
  "aboutUsContain6":
      'كان لدى سولو 1.5 مليون زائر فريد يصلون إلى الموقع في عام 2008 ونما إلى 53 مليون زائر فريد في عام 2017. ويتم إنشاء أكثر من 15٪ من المبيعات عبر الإنترنت من الولايات المتحدة ، تليها ألمانيا والمملكة المتحدة وإيطاليا والصين وفرنسا.',
  "aboutUsContain7":
      'يدفع Solo حدود مشهد البيع بالتجزئة الفاخرة سواء عبر الإنترنت أو بدونه من خلال مجموعة من الخدمات الحصرية ومبادرات العلامات التجارية بما في ذلك Buy It First و Luxury Club و Sneakers Club و LVR Privilege و LVR Editions.',
  "profile": "Pملف",
  "ContactNoText": "رقم الاتصال.",
  "websiteUrlText": "رابط الموقع",
  "countryText": "دولة",
  "postCodeText": "الرمز البريدي",
  "socialLinksText": "روابط اجتماعية",
  "facebookText": "فيسبوك",
  "instagramText": "إنستغرام",
  "twitterText": "تويتر",
  "youtubeText": "موقع يوتيوب",
  "linkendinText": "لينكيندين",
  "pinterestText": "بينتيريست",
  "followersText": "متابعون",
  "workedOnText": "عملت المشاريع",
  "mr": "السيد.",
  "yourEmail1Text": "بريدك الالكتروني",
  "subscribeText": "الإشتراك",
  "menuText": "قائمة",
  "accountText": "حساب",
  "checkOutText": "الدفع",
  "purchaseText": "الرجاء إدخال التفاصيل الخاصة بك أدناه لإكمال عملية الشراء",
  "shippingAddressText": "عنوان الشحن",
  "shippingMethodText": "طريقة الشحن",
  "paymentMethodText": "طريقة الدفع او السداد",
  "orderSummaryText": "ملخص الطلب",
  "alreadyAcText": "لديك بالفعل حساب معنا. تسجيل الدخول أو الاستمرار كضيف.",
  "loginText": "تسجيل الدخول",
  "forgotText": "نسيت رقمك السري؟",
  "stLineText": "العنوان (الخط 1",
  "cityText": "مدينة",
  "japanText": "اليابان",
  "stateText": "الولاية / المقاطعة",
  "zipPostalText": "الرمز البريدي / الرمز البريدي",
  "phoneNumberText": "رقم التليفون",
  "itemInCartText": "عنصر في عربة التسوق",
  "qtyText": "الكمية",
  "viewDetailsText": "عرض التفاصيل",
  "applyDisCodeText": "تطبيق كود الخصم",
  "enterDisCodeText": "أدخل رمز الخصم",
  "applyDiscountText": "تطبيق الخصم",
  "orderTotalText": "الطلب الكلي",
  "placeOrderText": "مكان الامر",
  "homeText": "الصفحة الرئيسية",
  "search1Text": "بحث",
  "designersText": "المصممون",
  "wishListText": "قائمة الرغبات",
  "storePaymentText": "طرق الدفع المخزنة",
  "newsLetterText": "اشتراك الرسائل الإخبارية",
  "enterEmailAddress": "أدخل عنوان البريد الالكتروني",
  "enterPhoneNumber": "أدخل رقم الهاتف",
  "enterValidEmailAddress": "أدخل عنوان بريد إلكتروني صالح",
  "phoneNumberIsRequired": "رقم الهاتف مطلوب",
  "phoneNumberIsNotValid": "رقم الهاتف غير صالح",
  "emailIsRequired": "البريد الالكتروني مطلوب",
  "invalidEmail": "بريد إلكتروني خاطئ",
  "passwordIsRequired": "كلمة المرور مطلوبة",
  "passwordRegExp":
      "يجب أن يكون طول كلمة المرور ما لا يقل عن 8 أحرف وتحتوي على مزيج من الأحرف الكبيرة والصغيرة ، وعدد واحد على الأقل وحرف خاص واحد (على سبيل المثال ،! @ #؟).",
  "email": "البريد الإلكتروني",
  "confirmPasswordIsRequired": "تأكيد كلمة المرور مطلوب",
  "mrs": "سيدة.",
  "tearmsAndCondition": "الشروط والأحكام",
  "nylonMessengerBackpackMsg":
      "حقيبة ظهر Messenger من النايلون بواسطة Balenziaga ، الإغلاق الأمامي مع الخطاف ، المقبض العلوي ، أحزمة الكتف القابلة للتعديل ، جيب الرمز البريدي الأمامي مع شعار التباين ، والسنانير كعناصر زخرفية.",
  "ourServices": "خدماتنا",
  "ourWebsite": "موقعنا الكتروني",
  "productDetails": "تفاصيل المنتج",
  "composition": "تكوين",
  "sortBy": "صنف حسب",
  "enterFirstName": "أدخل الاسم الأول",
  "enterLastName": "إدخال اسم آخر",
  "enterStreetAddress1": "أدخل عنوان الشارع 1",
  "enterStreetAddress2": "أدخل عنوان الشارع 2",
  "enterStreetAddress3": "أدخل عنوان الشارع 3",
  "streetAddress3": "عنوان الشارع 3",
  "enterCityName": "أدخل اسم المدينة",
  "enterZipPostalCode": "أدخل الرمز البريدي الرمز البريدي",
  "enterStateProvince": "أدخل الدولة/المقاطعة",
  "emailAddressRequired": "عنوان البريد الإلكتروني: (مطلوب",
  "viewCouponList": "عرض قائمة القسيمة",
  "changeLanguageAndCurrency": "تغيير اللغة والعملة",
  "friendFirstName": "الصديق الاسم الأول",
  "friendEmailAddress": "عنوان البريد الإلكتروني صديق",
  "friendPhoneNumber": "رقم هاتف صديق",
  "register": "يسجل",
  "surnameIsRequired": "اللقب مطلوب",
  "enterCouponCode": "أدخل رمز القسيمة",
  "addProductToYourWishList": "أضف منتجًا إلى قائمة الأمنيات الخاصة بك",
  "brandNameIsRequired": "اسم العلامة التجارية مطلوب",
  "styleIsRequired": "النمط مطلوب",
  "keywordIsRequired": "الكلمة الرئيسية مطلوبة",
  "remarkIsRequired": "الملاحظة مطلوبة",
  "enteryOurOrderNumberHere": "أدخل رقم طلبك هنا",
  "enterCity": "أدخل المدينة",
  "Alert": "انذار",
  "requiredVal": "مطلوب",
  "entervalid": "أدخل صالح",
  "mustbemorethan2characters": "يجب أن يكون أكثر من حرفين",
  "confirmpasswordshouldbematchwithpassword":
      "تأكيد كلمة المرور يجب أن تكون مطابقة بكلمة المرور",
  "lastNameIsRequired": "إسم العائلة مطلوب",
  "imageUrlIsRequired": "رابط الصورة مطلوب",
  "enterValidText": "أدخل نص صالح",
  "searchForPiesSushiTacos": "ابحث عن الفطائر ، السوشي ، سندويشات التاكو ...",
  "enterStreetAddress": "أدخل عنوان الشارع",
  "enterAddress1": "أدخل العنوان 1",
  "enterAddress2": "أدخل العنوان 2",
  "cOUPONAPPLIEDSUCCESSFULLYYOUSAVED": "تم تطبيق القسيمة بنجاح. لقد أنقذت",
  "oNTHISORDER": "على هذا الترتيب",
  "areYouSureYouWantToRemove": "هل أنت متأكد من أنك تريد إزالة",
  "ifyouwouldlikeUsSendYouTheCollectionFrom":
      "إذا كنت تريد منا أن نرسل لك المجموعة من",
  "plsCreateATicketBelow": "الرجاء. إنشاء تذكرة أدناه",
  "orderNumberIsRequired": "رقم الطلب مطلوب",
  "addressDetails": "تفاصيل العنوان",
  "enterZipProvince": "أدخل ZIP/المقاطعة",
  "zipProvince": "الرمز البريدي/المقاطعة",
  "emailAddress": "عنوان البريد الالكترونى",
  "passwordsdonotmatch": "كلمة المرور غير مطابقة",
  "passwordsYouHaveEnteredDoNotMatch": "كلمات المرور التي أدخلتها لا تتطابق مع",
  "invalidPassword": "رمز مرور خاطئ",
  "registerWithGoogle": "سجل مع Google",
  "registerWithFacebook": "سجل في Facebook",
  "registerwithTwitter": "سجل مع Twitter",
  "imageurl": "رابط الصورة",
  "findCountry": "ابحث عن البلد ...",
  "orderReference": "ترتيب المرجعي",
  "contactNumberIsRequired": "رقم الاتصال مطلوب",
  "headOffice": "المكتب الرئيسي",
  "soloLuxuryOLablesLtd": "Solo Luxury ، O Labels Ltd ،",
  "WenlockRoad": "20-22 Wenlock Road ، لندن ، N1 7GU",
  "youCanViewResponsesOnYourEmail": "يمكنك عرض الردود على بريدك الإلكتروني",
  "underMyTickets": "تحت تذاكر بلدي.",
  "friendFirstNameRequired": "الصديق الاسم الأول المطلوب",
  "friendEmailAddressIsRequired": "عنوان البريد الإلكتروني صديق مطلوب",
  "friendPhoneNumberIsRequired": "رقم هاتف صديق مطلوب",
  "selectProductAnOption": "حدد المنتج خيارًا",
  "pleaseEnterYourEmailToTrackYourTicketByEmail":
      "الرجاء إدخال بريدك الإلكتروني لتتبع تذكرتك عن طريق البريد الإلكتروني.",
  "Pleaseagreefornewsletter": "يرجى الاتفاق على النشرة الإخبارية",
  "referAFriend": "أوص أحد الأصدقاء",
  "shipTo": "سافر على متن سفينة لِـ",
  "brandProductQuery": "استعلام منتج العلامة التجارية",
  "categoryProductQuery": "استعلام المنتج فئة",
  "cartDetails": "تفاصيل العربة",
  "date": "تاريخ",
  "ConfirmationEmailRequired": "البريد الإلكتروني التأكيد مطلوب",
  "pleaseentermessage": "الرجاء إدخال الرسالة",
  "typeyourmessagehere": "اكتب رسالتك هنا...",
  "goterrorpleasetryagain": "حصلت على خطأ ، يرجى المحاولة مرة أخرى.",
  "internalservererror": "خطأ في الخادم الداخلي",
  "oopssomethingwentwrong": "تبا شيء ما حدث بشكل خاطئ",
  "SigninwithGoogle": "الدخول مع جوجل",
  "SignnwithApple": "تسجيل الدخول مع Apple",
  "SigninwithTwitter": "تسجيل الدخول مع Twitter",
  "SigninwithFacebook": "قم بتسجيل الدخول باستخدام الفيسبوك",
  "Requestcancelled": "طلب إلغاء",
  "Requesttimeout": "طلب المهلة",
  "Get": "احصل على",
  "peroff": "خصم 10",
  "onyourfirstpurchaseonAPPUSECode":
      " في أول عملية شراء على التطبيق. استخدم الكود:",
  "SOLOAPP10": "soloapp10",
  "TnCApply": "  *T & C تطبيق",
};
