const Map<String, String> de = {
  "language": "Englisch",
  "appNameText": "Solo-Luxus",
  "registerwithApple": "Register With Apple",
  "aboutUsText": "Über uns",
  "referFriendText": "Freund empfehlen",
  "returnsRefundsText": "Rückgabe & Erstattung",
  "faqText": "FAQ",
  "contactText": "Kontakt",
  "socialText": "Sozial",
  "companyText": "Gesellschaft",
  "contactUs": "Kontaktiere uns",
  "myOrders": "Meine Bestellungen",
  "myOrderImage": "Bild",
  "productName": "Produktname",
  "sku": "Artikelnummer",
  "price": "Preis",
  "quantity": "Menge",
  "status": "Status",
  "action": "Aktion",
  "paymentMethod": " Zahlungsmethode",
  "shippingAddress": "Lieferanschrift",
  "billingAddress": "Rechnungsadresse",
  "continueShopping": "Mit dem Einkaufen fortfahren",
  "freuentlyAskedQueText": "Häufig gestellte Fragen",
  "shopAndPlaceOrder": "Wie kaufe ich ein und gebe eine Bestellung auf?",
  "accountToPlaceOrderQues":
      "Benötige ich ein Konto, um eine Bestellung aufzugeben?",
  "accountToPlaceOrderAns":
      "Nein, Sie benötigen lediglich eine E-Mail-Adresse. Wir empfehlen Ihnen, sich für ein Konto zu registrieren, um mit dem Hinzufügen von Artikeln zu Ihrer Wunschliste zu beginnen, aber Sie können auch Bestellungen als Gast aufgeben und verfolgen und sich zu einem für Sie passenden Zeitpunkt anmelden.",
  "registeredCustomersText": "Registrierte Kunden",
  "registeredCustomersDescriptionText":
      "Wenn Sie ein Konto haben, melden Sie sich mit Ihrer\nE-Mail-Adresse an.",
  "usernameText": "Nutzername",
  "passwordText": "Passwort",
  "signInText": "Anmelden",
  "forgotYourPasswordText": "Haben Sie Ihr Passwort vergessen?",
  "newCustomersText": "neue Kunden",
  "loginDescriptionText":
      "Das Erstellen eines Kontos hat viele Vorteile: Bezahlen\nschneller, mehr als eine Adresse behalten\nBestellungen verfolgen und mehr.",
  "createAccountText": "Benutzerkonto erstellen",
  "firstNameText": "Vorname",
  "lastNameText": "Familienname, Nachname",
  "dateOfBirthText": "Geburtsdatum",
  "pleaseSelectValidDateText": "Bitte gültiges Datum auswählen",
  "marriageAnniversaryText": "Hochzeitstag",
  "emailText": "Email",
  "confirmPasswordText": "Bestätige das Passwort",
  "signUpForNewsletterText": "Anmeldung für Newsletter",
  "forgotYourPasswordDescriptionText":
      "Bitte geben Sie unten Ihre E-Mail-Adresse ein, um\neinen Link zum Zurücksetzen des Passworts zu erhalten",
  "enterYourEmailText": "Geben sie ihre E-Mail Adresse ein",
  "resetMyPasswordText": "Setze mein Passwort zurück",
  "accessYourAccountDetailsText":
      "Greifen Sie auf Ihre Kontodaten und Prämien zu",
  "signUpText": "ANMELDUNG",
  "myOrdersText": "Meine Bestellungen",
  "myWishlistText": "Meine Wunschliste",
  "addressBookText": "Adressbuch",
  "accountInformationText": "Kontoinformationen",
  "myTicketsText": "Meine Tickets",
  "trackOrderText": "Bestellung verfolgen",
  "companyMyAccountText": "Gesellschaft",
  "contactUsText": "Kontaktiere uns",
  "secureShoppingText": "Sicher einkaufen",
  "advancedSearchText": "Erweiterte Suche",
  "testimonialsText": "Referenzen",
  "socialMyAccountText": "Sozial",
  "hopeText": "Hoffen",
  "affiliateProgramText": "Partnerprogramm",
  "influencerRegistrationText": "Influencer-Registrierung",
  "exchangeText": "Umtausch und Rückgabe",
  "contactMyAccountText": "Kontakte",
  "privacyPolicyText": "Datenschutz-Bestimmungen",
  "termsConditionsText": "Terms & amp; Bedingungen",
  "shippingText": "Versand",
  "aboutText": "Über",
  "aboutUsMyAccountText": "Über uns",
  "referFriendMyAccountText": "Freund empfehlen",
  "returnsText": "Rückgabe & Erstattung",
  "faqMyAccountText": "FAQ",
  "myAccountText": "Mein Konto",
  "filtersText": "Filter",
  "priceText": "Preis",
  "colorText": "Farbe",
  "brandText": "Marke",
  "sizeText": "Größe",
  "applyText": "Anwenden",
  "searchText": "Suche..",
  "aboutUsContain1":
      "SOLO IST MIT 5 MILLIONEN BESUCHERN PRO MONAT UND WELTWEITEM VERSAND EIN TOP ONLINE-LUXURYFASHION-ZIEL.",
  "aboutUsContain2":
      "Die Website bietet die beste Auswahl der besten etablierten Designer sowie junge aufstrebende Talente. Solo wurde Anfang der 1930er Jahre in Florenz gegründet, mit der Eröffnung des gleichnamigen Concept Stores des Unternehmens in der Via Roma.Online seit 1999 schreibt das Unternehmen 90 % des Gesamtumsatzes dem Online-Verkauf zu. Bis heute ist es ein zu 100 % in Privatbesitz befindliches Familienunternehmen, in dem der Enkel des Gründers, Andrea Panconesi, als CEO und seine Tochter, Annagreta Panconesi, als Creative Director fungieren.",
  "aboutUsContain3":
      "Die Website bietet eine große Auswahl an Kleidung, Schuhen, Taschen, Accessoires, Luxus-Wohninterieur und Schönheit, mit Produkten für Männer, Frauen und Kinder von den renommiertesten Designern wie Balenciaga, Vetements, Off-White, J.W. Anderson, Balmain, Dolce & Gabbana, Gucci, Saint Laurent, Valentino, Givenchy, Loewe, Jacquemus und mehr.",
  "aboutUsContain4":
      'Derzeit arbeiten 200 Menschen aus 15 verschiedenen Ländern daran, Solo zu produzieren und zu pflegen. Die Seite ist in 9 Sprachen verfügbar: Englisch, Italienisch, Deutsch, Chinesisch, Russisch, Spanisch, Französisch, Koreanisch und Japanisch. Die Website wird vollständig intern erstellt, wobei das Büro in Florenz Grafikdesign, IT, Kundendienst, Marketing und Einkaufsabteilungen beherbergt. Die Stylisten und Presseteams operieren vom Solo-Büro in der Modehauptstadt der Welt – Mailand.',
  "aboutUsContain5":
      'Alle Bestellungen werden weltweit von der Solo-Zentrale in Kartons versandt, die mit größter Sorgfalt vorbereitet werden und die besten Materialien verwenden, von den charakteristischen Schuhbeuteln bis zum personalisierten Band.',
  "aboutUsContain6":
      'Solo hatte 2008 1,5 Millionen Einzelbesucher auf der Website und ist 2017 auf 53 Millionen Einzelbesucher angewachsen. Mehr als 15 % der Online-Verkäufe werden in den Vereinigten Staaten generiert, gefolgt von Deutschland, Großbritannien, Italien, China und Frankreich.',
  "aboutUsContain7":
      'Solo erweitert die Grenzen der Luxus-Einzelhandelslandschaft sowohl online als auch offline mit einer Reihe exklusiver Dienstleistungen und Markeninitiativen, darunter Buy It First, Luxury Club, Sneakers Club, LVR Privilege und LVR Editions.',
  "profile": "Profil",
  "ContactNoText": "Kontakt Nr.",
  "websiteUrlText": "Webadresse",
  "countryText": "Land",
  "postCodeText": "Postleitzahl",
  "socialLinksText": "Soziale Verbindungen",
  "facebookText": "Facebook",
  "instagramText": "Instagram",
  "twitterText": "Zwitschern",
  "youtubeText": "Youtube",
  "linkendinText": "Linkendin",
  "pinterestText": "Pinterest",
  "followersText": "Anhänger",
  "workedOnText": "Projekte bearbeitet",
  "mr": "Herr.",
  "yourEmail1Text": "Deine E-Mail",
  "subscribeText": "ABONNIEREN",
  "menuText": "Speisekarte",
  "accountText": "Konto",
  "checkOutText": "Kasse",
  "purchaseText":
      "Bitte geben Sie unten Ihre Daten ein, um Ihren Kauf abzuschließen",
  "shippingAddressText": "Lieferanschrift",
  "shippingMethodText": "Versandart",
  "paymentMethodText": "Zahlungsmethode",
  "orderSummaryText": "Bestellübersicht",
  "alreadyAcText":
      "Sie haben bereits ein Konto bei uns. Melden Sie sich an oder fahren Sie als Gast fort.",
  "loginText": "ANMELDUNG",
  "forgotText": "Haben Sie Ihr Passwort vergessen?",
  "stLineText": "Straßenname (Zeile 1",
  "cityText": "Stadt",
  "japanText": "Japan",
  "stateText": "Staat/Provinz",
  "zipPostalText": "Postleitzahl",
  "phoneNumberText": "Telefonnummer",
  "itemInCartText": "Artikel im Warenkorb",
  "qtyText": "Menge",
  "viewDetailsText": "Details anzeigen",
  "applyDisCodeText": "Rabattcode anwenden",
  "enterDisCodeText": "Rabattcode eingeben",
  "applyDiscountText": "Rabatt anwenden",
  "orderTotalText": "Auftragssumme",
  "placeOrderText": "BESTELLUNG AUFGEBEN",
  "storePaymentText": "GESPEICHERTE ZAHLUNGSARTEN",
  "newsLetterText": "NEWSLETTER-ABOS",
  "enterEmailAddress": "E-Mail Adresse eingeben",
  "enterPhoneNumber": "Telefonnummer eingeben",
  "enterValidEmailAddress": "Geben Sie eine gültige E -Mail -Adresse ein",
  "phoneNumberIsRequired": "Telefonnummer ist erforderlich",
  "phoneNumberIsNotValid": "Die Telefonnummer ist nicht gültig",
  "emailIsRequired": "E-Mail ist erforderlich",
  "invalidEmail": "Ungültige E-Mail",
  "passwordIsRequired": "Passwort wird benötigt",
  "passwordRegExp":
      "Das Passwort muss mindestens 8 Zeichen lang sein und eine Mischung aus Großbuchstaben und Kleinbuchstaben enthalten, mindestens eine Nummer und ein spezielles Zeichen (z. B.! @ #?).",
  "email": "Email",
  "confirmPasswordIsRequired": "ConfirmPassword ist erforderlich",
  "mrs": "Frau.",
  "tearmsAndCondition": "ALLGEMEINE GESCHÄFTSBEDINGUNGEN",
  "nylonMessengerBackpackMsg":
      "Nylon Messenger -Rucksack von Balenziaga, Frontschließung mit Haken, oberem Griff, verstellbare Schultergurte, Reißverschlusspocke vordere Patch mit Kontrastlogo, Haken als dekorative Elemente.",
  "ourServices": "Unsere Dienstleistungen",
  "ourWebsite": "Unsere Website",
  "productDetails": "Produktdetails",
  "composition": "Zusammensetzung",
  "sortBy": "Sortieren nach",
  "enterFirstName": "Bitte Vornamen eingeben",
  "enterLastName": "Nachnamen eingeben",
  "enterStreetAddress1": "Geben Sie Straßenadresse 1 ein",
  "enterStreetAddress2": "Geben Sie Straßenadresse 2 ein",
  "enterStreetAddress3": "Geben Sie Straßenadresse 3 ein",
  "streetAddress3": "Straßenadresse 3",
  "enterCityName": "Geben Sie den Stadtnamen ein",
  "enterZipPostalCode": "Geben Sie die Postleitzahl der ZIP ein",
  "enterStateProvince": "Geben Sie den Staat/die Provinz ein",
  "emailAddressRequired": "E-Mail-Adresse: (Pflichtfeld",
  "viewCouponList": "Gutscheinliste anzeigen",
  "changeLanguageAndCurrency": "Sprache und Währung ändern",
  "friendFirstName": "Freund Vorname",
  "friendEmailAddress": "Freunden -E -Mail -Adresse",
  "friendPhoneNumber": "Freundliche Telefonnummer",
  "register": "Registrieren",
  "surnameIsRequired": "Nachname ist erforderlich",
  "enterCouponCode": "Gutschein-Code eingeben",
  "addProductToYourWishList": "Fügen Sie Produkt in Ihre Wunschliste hinzu",
  "brandNameIsRequired": "Markenname ist erforderlich",
  "styleIsRequired": "Stil ist erforderlich",
  "keywordIsRequired": "Schlüsselwort ist erforderlich",
  "remarkIsRequired": "Bemerkung ist erforderlich",
  "enteryOurOrderNumberHere": "Geben Sie hier Ihre Bestellnummer ein",
  "enterCity": "Stadt betreten",
  "Alert": "Alarm",
  "requiredVal": "ist nötig",
  "entervalid": "Geben Sie gültig ein",
  "mustbemorethan2characters": "Muss mehr als 2 Zeichen sein",
  "confirmpasswordshouldbematchwithpassword":
      "Bestätigen Sie das Passwort sollte mit dem Passwort übereinstimmen",
  "lastNameIsRequired": "Nachname ist erforderlich",
  "imageUrlIsRequired": "Bildverbindung ist erforderlich",
  "enterValidText": "Geben Sie einen gültigen Text ein",
  "searchForPiesSushiTacos": "Suche nach Kuchen, Sushi, Tacos ...",
  "enterStreetAddress": "Geben Sie die Straßenadresse ein",
  "enterAddress1": "Geben Sie die Adresse 1 ein",
  "enterAddress2": "Geben Sie die Adresse 2 ein",
  "cOUPONAPPLIEDSUCCESSFULLYYOUSAVED":
      "Gutschein erfolgreich angewendet. DU HAST GESPEICHERT",
  "oNTHISORDER": "Auf diese Bestellung",
  "areYouSureYouWantToRemove":
      "Sind Sie sich sicher, dass Sie das entfernen wollen",
  "ifyouwouldlikeUsSendYouTheCollectionFrom":
      "Wenn Sie möchten, dass wir Ihnen die Sammlung aus schicken",
  "plsCreateATicketBelow": "PLS. Erstellen Sie unten ein Ticket",
  "orderNumberIsRequired": "Bestellnummer ist erforderlich",
  "addressDetails": "Adressen Details",
  "enterZipProvince": "Geben Sie ZIP/Provinz ein",
  "zipProvince": "ZIP/Provinz",
  "emailAddress": "E-Mail-Addresse",
  "passwordsdonotmatch": "Passwörter stimmen nicht überein",
  "passwordsYouHaveEnteredDoNotMatch": "Passwörter, die Sie eingegeben haben",
  "invalidPassword": "Ungültiges Passwort",
  "registerWithGoogle": "Registrieren Sie sich bei Google",
  "registerWithFacebook": "Registrieren Sie sich bei Facebook",
  "registerwithTwitter": "Registrieren Sie sich bei Twitter",
  "imageurl": "Bild URL",
  "findCountry": "Land finden ...",
  "orderReference": "Bestellnummer",
  "contactNumberIsRequired": "Kontaktnummer ist erforderlich",
  "headOffice": "Hauptbüro",
  "soloLuxuryOLablesLtd": "Solo -Luxus, o Labels Ltd,",
  "WenlockRoad": "20-22 Wenlock Road, London, N1 7gu",
  "youCanViewResponsesOnYourEmail":
      "Sie können Antworten auf Ihrer E -Mail anzeigen",
  "underMyTickets": "unter meinen Tickets.",
  "friendFirstNameRequired": "Freund Vorname erforderlich",
  "friendEmailAddressIsRequired": "Freundes E -Mail -Adresse ist erforderlich",
  "friendPhoneNumberIsRequired":
      "Die Telefonnummer des Freundes ist erforderlich",
  "selectProductAnOption": "Wählen Sie das Produkt eine Option aus",
  "pleaseEnterYourEmailToTrackYourTicketByEmail":
      "Bitte geben Sie Ihre E -Mail ein, um Ihr Ticket per E -Mail zu verfolgen.",
  "Pleaseagreefornewsletter": "Bitte stimmen Sie dem Newsletter zu",
  "referAFriend": "Verweisen Sie einen Freund",
  "shipTo": "Ausliefern",
  "brandProductQuery": "Markenproduktabfrage",
  "categoryProductQuery": "Kategorie Produktabfrage",
  "cartDetails": "Wagendetails",
  "date": "Datum",
  "ConfirmationEmailRequired": "Bestätigungs -E -Mail ist erforderlich",
  "pleaseentermessage": "Bitte geben Sie eine Nachricht ein",
  "typeyourmessagehere": "Schreiben Sie ihre Nachricht hier...",
  "goterrorpleasetryagain": "Ich habe Fehler, bitte versuchen Sie es erneut.",
  "internalservererror": "Interner Serverfehler",
  "oopssomethingwentwrong": "Ups! Irgendwas lief schief",
  "SigninwithGoogle": "Anmeldung mit Google",
  "SignnwithApple": "Melden Sie sich mit Apple an",
  "SigninwithTwitter": "Mit Twitter anmelden",
  "SigninwithFacebook": "Mit Facebook anmelden",
  "Requestcancelled": "Anfrage storniert",
  "Requesttimeout": "Zeitüberschreitung der Anforderung",
  "Get": "Erhalten",
  "peroff": "10% reduziert",
  "onyourfirstpurchaseonAPPUSECode":
      " Bei Ihrem ersten Kauf auf App. Code verwenden:",
  "SOLOAPP10": "Soloapp10",
  "TnCApply": "  *T & C bewerben",
};
