const Map<String, String> fr = {
  "language": "Anglais",
  "appNameText": "Luxe en solitaire",
  "aboutUsText": "À propos de nous",
  "referFriendText": "Référez un ami",
  "returnsRefundsText": "Retours et remboursements",
  "faqText": "FAQ",
  "contactText": "Contact",
  "socialText": "Social",
  "companyText": "Compagnie",
  "contactUs": "Nous contacter",
  "myOrders": "Mes commandes",
  "myOrderImage": "Image",
  "productName": "Nom du produit",
  "sku": "UGS",
  "price": "Prix",
  "quantity": "Qté",
  "status": "Statut",
  "action": "action",
  "paymentMethod": " Mode de paiement",
  "shippingAddress": "Adresse de livraison",
  "billingAddress": "Adresse de facturation",
  "continueShopping": "Continuer vos achats",
  "freuentlyAskedQueText": "Questions fréquemment posées",
  "shopAndPlaceOrder": "Comment magasiner et passer une commande?",
  "accountToPlaceOrderQues":
      "Ai-je besoin d'un compte pour passer une commande?",
  "accountToPlaceOrderAns":
      "Non, tout ce dont vous avez besoin est une adresse e-mail. Nous vous recommandons de créer un compte pour commencer à ajouter des pièces à votre liste de souhaits, mais vous pouvez également passer et suivre des commandes en tant qu'invité et vous inscrire au moment qui vous convient.",
  "registeredCustomersText": "Clients enregistrés",
  "registeredCustomersDescriptionText":
      "Si vous avez un compte, connectez-vous avec votre\nadresse e-mail.",
  "usernameText": "Nom d'utilisateur",
  "passwordText": "Mot de passe",
  "signInText": "S'identifier",
  "forgotYourPasswordText": "Mot de passe oublié?",
  "newCustomersText": "nouveaux clients",
  "loginDescriptionText":
      "La création d'un compte présente de nombreux avantages : paiement\nplus rapide, conservation de plusieurs adresses\nsuivi des commandes, etc.",
  "createAccountText": "Créer un compte",
  "firstNameText": "Prénom",
  "lastNameText": "Nom de famille",
  "dateOfBirthText": "Date de naissance",
  "pleaseSelectValidDateText": "Veuillez sélectionner une date valide",
  "marriageAnniversaryText": "Anniversaire de mariage",
  "emailText": "E-mail",
  "confirmPasswordText": "Confirmez le mot de passe",
  "signUpForNewsletterText": "S'inscrire aux Newsletters",
  "forgotYourPasswordDescriptionText":
      "Veuillez saisir votre adresse e-mail ci-dessous pour recevoir\nun lien de réinitialisation du mot de passe",
  "enterYourEmailText": "Entrer votre Email",
  "resetMyPasswordText": "Réinitialiser mon mot de passe",
  "accessYourAccountDetailsText":
      "Accéder aux détails de votre compte et aux récompenses",
  "signUpText": "S'INSCRIRE",
  "myOrdersText": "Mes commandes",
  "myWishlistText": "Ma liste d'envies",
  "addressBookText": "Carnet d'adresses",
  "accountInformationText": "Information sur le compte",
  "myTicketsText": "Mes billets",
  "trackOrderText": "Suivi de commande",
  "companyMyAccountText": "Compagnie",
  "contactUsText": "Nous contacter",
  "secureShoppingText": "Achats sécurisés",
  "advancedSearchText": "Recherche Avancée",
  "testimonialsText": "Témoignages",
  "socialMyAccountText": "Social",
  "hopeText": "Espérer",
  "affiliateProgramText": "Programme d'affiliation",
  "influencerRegistrationText": "Inscription des influenceurs",
  "exchangeText": "Échange et retours",
  "contactMyAccountText": "Contacts",
  "privacyPolicyText": "Politique de confidentialité",
  "termsConditionsText": "termes et conditions",
  "shippingText": "Expédition",
  "aboutText": "Sur",
  "aboutUsMyAccountText": "À propos de nous",
  "referFriendMyAccountText": "Référez un ami",
  "returnsText": "Retours et remboursements",
  "faqMyAccountText": "FAQ",
  "myAccountText": "Mon compte",
  "filtersText": "Filtres",
  "priceText": "Prix",
  "colorText": "Couleur",
  "brandText": "Marque",
  "sizeText": "Taille",
  "applyText": "Appliquer",
  "searchText": "Rechercher..",
  "aboutUsContain1":
      "SOLO EST UNE DESTINATION DE MODE DE LUXE EN LIGNE AVEC 5 MILLIONS DE VISITEURS PAR MOIS ET UNE EXPÉDITION DANS LE MONDE ENTIER.",
  "aboutUsContain2":
      "Le site Web présente la meilleure sélection des meilleurs designers établis ainsi que de jeunes talents émergents. Solo a été fondée à Florence au début des années 1930, avec l'ouverture du concept store éponyme de l'entreprise sur la Via Roma. En ligne depuis 1999, l'entreprise attribue 90 % de son chiffre d'affaires total aux ventes en ligne. À ce jour, elle reste une entreprise familiale 100 % privée, avec le petit-fils du fondateur, Andrea Panconesi, en tant que PDG et sa fille, Annagreta Panconesi, en tant que directrice de la création.",
  "aboutUsContain3":
      "Le site propose une large sélection de vêtements, chaussures, sacs, accessoires, intérieurs de luxe et beauté, avec des produits disponibles pour hommes, femmes et enfants des créateurs les plus prestigieux tels que Balenciaga, Vetements, Off-White, J.W. Anderson, Balmain, Dolce & Gabbana, Gucci, Saint Laurent, Valentino, Givenchy, Loewe, Jacquemus et plus encore.",
  "aboutUsContain4":
      'Il y a actuellement 200 personnes de 15 pays différents qui travaillent pour produire et maintenir Solo. Le site est disponible en 9 langues : anglais, italien, allemand, chinois, russe, espagnol, français, coréen et japonais. Le site est entièrement créé en interne, avec les bureaux de Florence abritant les départements de conception graphique, informatique, service client, marketing et achats. Les stylistes et les équipes de presse opèrent depuis le bureau de Solo dans la capitale mondiale de la mode - Milan.',
  "aboutUsContain5":
      'Toutes les commandes sont expédiées dans le monde entier depuis le siège social de Solo dans des boîtes préparées avec le plus grand soin et utilisant les meilleurs matériaux, des sacs à chaussures emblématiques au ruban personnalisé.',
  "aboutUsContain6":
      '''Solo comptait 1,5 million de visiteurs uniques sur le site en 2008 et est passé à 53 millions de visiteurs uniques en 2017. Plus de 15 % des ventes en ligne sont générées aux États-Unis, suivis de l'Allemagne, du Royaume-Uni, de l'Italie, de la Chine et de la France.''',
  "aboutUsContain7":
      '''Solo repousse les limites du paysage de la vente au détail de luxe à la fois en ligne et hors ligne avec une gamme de services exclusifs et d'initiatives de marque, notamment Buy It First, Luxury Club, Sneakers Club, LVR Privilege et LVR Editions.''',
  "profile": "Profil",
  "ContactNoText": "Numéro de contact.",
  "websiteUrlText": "URL de site web",
  "countryText": "De campagne",
  "postCodeText": "Code postal",
  "socialLinksText": "Liens sociaux",
  "facebookText": "Facebook",
  "instagramText": "Instagram",
  "twitterText": "Twitter",
  "youtubeText": "Youtube",
  "linkendinText": "Linkendin",
  "pinterestText": "Pinterest",
  "followersText": "Suiveurs",
  "workedOnText": "Les projets travaillés",
  "mr": "Monsieur.",
  "yourEmail1Text": "Votre e-mail",
  "subscribeText": "S'ABONNER",
  "menuText": "Menu",
  "accountText": "Compte",
  "checkOutText": "Vérifier",
  "purchaseText":
      "Veuillez entrer vos coordonnées ci-dessous pour finaliser votre achat",
  "shippingAddressText": "Adresse de livraison",
  "shippingMethodText": "Mode de livraison",
  "paymentMethodText": "Mode de paiement",
  "orderSummaryText": "Récapitulatif de la commande",
  "alreadyAcText":
      "Vous avez déjà un compte chez nous. Connectez-vous ou continuez en tant qu'invité.",
  "loginText": "CONNEXION",
  "forgotText": "Mot de passe oublié?",
  "stLineText": "Nom de rue (ligne 1",
  "cityText": "Ville",
  "japanText": "Japon",
  "stateText": "État/Province",
  "zipPostalText": "Zip / code postal",
  "phoneNumberText": "Numéro de téléphone",
  "itemInCartText": "Article dans le panier",
  "qtyText": "Qté",
  "viewDetailsText": "Voir les détails",
  "applyDisCodeText": "Appliquer le code de réduction",
  "enterDisCodeText": "Entrez le code de réduction",
  "applyDiscountText": "Appliquer la réduction",
  "orderTotalText": "Total de la commande",
  "placeOrderText": "PASSER LA COMMANDE",
  "storePaymentText": "MÉTHODES DE PAIEMENT MÉMORISÉES",
  "newsLetterText": "ABONNEMENT À LA NEWSLETTER",
  "enterEmailAddress": "Entrer l'adresse e-mail",
  "enterPhoneNumber": "Entrez le numéro de téléphone",
  "enterValidEmailAddress": "Entrez l'adresse e-mail valide",
  "phoneNumberIsRequired": "Le numéro de téléphone est requis",
  "phoneNumberIsNotValid": "Le numéro de téléphone n'est pas valide",
  "emailIsRequired": "Un e-mail est requis",
  "invalidEmail": "Email invalide",
  "passwordIsRequired": "Mot de passe requis",
  "passwordRegExp":
      "Le mot de passe doit comporter au moins 8 caractères et contenir un mélange de lettres majuscules et minuscules, au moins un numéro et un caractère spécial (par exemple ,! @ #?).",
  "email": "E-mail",
  "confirmPasswordIsRequired": "ConfirmPassword est requis",
  "mrs": "Madame.",
  "tearmsAndCondition": "TERMES ET CONDITIONS",
  "nylonMessengerBackpackMsg":
      "Sac à dos en nylon messager par Balenziaga, fermeture avant avec crochet, poignée supérieure, bretelles réglables, poche zippée de patch avant avec logo de contraste, crochets comme éléments décoratifs.",
  "ourServices": "Nos services",
  "ourWebsite": "Notre site web",
  "productDetails": "Détails du produit",
  "composition": "Composition",
  "sortBy": "Trier par",
  "enterFirstName": "Entrez votre prénom",
  "enterLastName": "Entrer le nom de famille",
  "enterStreetAddress1": "Entrez l'adresse de la rue 1",
  "enterStreetAddress2": "Entrez l'adresse de la rue 2",
  "enterStreetAddress3": "Entrez l'adresse de la rue 3",
  "streetAddress3": "Adresse de la rue 3",
  "enterCityName": "Entrez le nom de la ville",
  "enterZipPostalCode": "Entrez le code postal zip",
  "enterStateProvince": "Entrez l'État / la province",
  "emailAddressRequired": "Adresse mail: (requis",
  "viewCouponList": "Voir la liste des coupons",
  "changeLanguageAndCurrency": "Changer la langue et la monnaie",
  "friendFirstName": "Prénom ami",
  "friendEmailAddress": "Adresse e-mail d'ami",
  "friendPhoneNumber": "Numéro de téléphone d'ami",
  "register": "S'inscrire",
  "surnameIsRequired": "Le nom de famille est requis",
  "enterCouponCode": "Entrer le code de réduction",
  "addProductToYourWishList": "Ajouter un produit à votre liste de souhaits",
  "brandNameIsRequired": "Le nom de marque est requis",
  "styleIsRequired": "Le style est requis",
  "keywordIsRequired": "Un mot-clé est requis",
  "remarkIsRequired": "Une remarque est requise",
  "enteryOurOrderNumberHere": "Entrez votre numéro de commande ici",
  "enterCity": "Entrer dans la ville",
  "Alert": "Alerte",
  "requiredVal": "est requis",
  "entervalid": "Entrer valide",
  "mustbemorethan2characters": "Doit être plus de 2 caractères",
  "confirmpasswordshouldbematchwithpassword":
      "Confirmer le mot de passe devrait correspondre avec le mot de passe",
  "lastNameIsRequired": "Le nom de famille est requis",
  "imageUrlIsRequired": "Le lien d'image est requis",
  "enterValidText": "Entrez le texte valide",
  "searchForPiesSushiTacos": "Rechercher des tartes, des sushis, des tacos ...",
  "enterStreetAddress": "Entrez l'adresse de la rue",
  "enterAddress1": "Entrez l'adresse 1",
  "enterAddress2": "Entrez l'adresse 2",
  "cOUPONAPPLIEDSUCCESSFULLYYOUSAVED":
      "Le coupon s'est appliqué avec succès. TU AS SAUVEGARDÉ",
  "oNTHISORDER": "Sur cette commande",
  "areYouSureYouWantToRemove": "Êtes-vous sûr de vouloir désinstaller",
  "ifyouwouldlikeUsSendYouTheCollectionFrom":
      "Si vous souhaitez que nous vous envoyions la collection de",
  "plsCreateATicketBelow": "Pls. Créer un billet ci-dessous",
  "orderNumberIsRequired": "Le numéro de commande est requis",
  "addressDetails": "Détails de l'adresse",
  "enterZipProvince": "Entrez Zip / Province",
  "zipProvince": "Zip / province",
  "emailAddress": "Adresse e-mail",
  "passwordsdonotmatch": "Les mots de passe ne correspondent pas",
  "passwordsYouHaveEnteredDoNotMatch":
      "Les mots de passe que vous avez entrés ne correspondent pas",
  "invalidPassword": "Mot de passe incorrect",
  "registerWithGoogle": "Inscrivez-vous avec Google",
  "registerWithFacebook": "Inscrivez-vous avec Facebook",
  "registerwithTwitter": "Inscrivez-vous avec Twitter",
  "imageurl": "URL de l'images",
  "findCountry": "Trouver le pays ...",
  "orderReference": "Référence de l'achat",
  "contactNumberIsRequired": "Le numéro de contact est requis",
  "headOffice": "Siège social",
  "soloLuxuryOLablesLtd": "Solo Luxury, O Labels Ltd,",
  "WenlockRoad": "20-22 Wenlock Road, Londres, N1 7gu",
  "youCanViewResponsesOnYourEmail":
      "Vous pouvez afficher les réponses sur votre e-mail",
  "underMyTickets": "sous mes billets.",
  "friendFirstNameRequired": "Prénom d'ami requis",
  "friendEmailAddressIsRequired": "L'adresse e-mail d'ami est requise",
  "friendPhoneNumberIsRequired": "Le numéro de téléphone de l'ami est requis",
  "selectProductAnOption": "Sélectionnez le produit une option",
  "pleaseEnterYourEmailToTrackYourTicketByEmail":
      "Veuillez saisir votre e-mail pour suivre votre billet par e-mail.",
  "Pleaseagreefornewsletter": "Veuillez être d'accord pour la newsletter",
  "referAFriend": "Référez un ami",
  "shipTo": "Envoyez à",
  "brandProductQuery": "Requête de produit de marque",
  "categoryProductQuery": "Catégorie Requête de produit",
  "cartDetails": "Détails du panier",
  "date": "Date",
  "ConfirmationEmailRequired": "Un e-mail de confirmation est requis",
  "pleaseentermessage": "Veuillez saisir le message",
  "typeyourmessagehere": "Tapez votre message ici...",
  "goterrorpleasetryagain": "J'ai une erreur, veuillez réessayer.",
  "internalservererror": "Erreur interne du serveur",
  "oopssomethingwentwrong": "Oups quelque chose a mal tourné",
  "SigninwithGoogle": "Connectez-vous avec Google",
  "SignnwithApple": "Connectez-vous avec Apple",
  "SigninwithTwitter": "Connectez-vous avec Twitter",
  "SigninwithFacebook": "Connectez-vous avec Facebook",
  "Requestcancelled": "Demande annulée",
  "Requesttimeout": "Demander le délai d'expiration",
  "Get": "Obtenir",
  "peroff": "10% de réduction",
  "onyourfirstpurchaseonAPPUSECode":
      " Sur votre premier achat sur l'application. Utiliser le code:",
  "SOLOAPP10": "Soloapp10",
  "TnCApply": "  * T&C s'appliquer",
};
