const Map<String, String> it = {
  "language": "inglese",
  "appNameText": "Lusso da solista",
  "aboutUsText": "Chi siamo",
  "referFriendText": "Segnala amico",
  "returnsRefundsText": "Resi e rimborsi",
  "faqText": "FAQ",
  "contactText": "Contatto",
  "socialText": "Sociale",
  "companyText": "Azienda",
  "contactUs": "Contattaci",
  "myOrders": "i miei ordini",
  "myOrderImage": "Immagine",
  "productName": "nome del prodotto",
  "sku": "SKU",
  "price": "Prezzo",
  "quantity": "Qtà",
  "status": "Stato",
  "action": "Azione",
  "paymentMethod": " Metodo di pagamento",
  "shippingAddress": "indirizzo di spedizione",
  "billingAddress": "Indirizzo Di Fatturazione",
  "continueShopping": "Continua a fare acquisti",
  "freuentlyAskedQueText": "Domande frequenti",
  "shopAndPlaceOrder": "Come acquistare e effettuare un ordine?",
  "accountToPlaceOrderQues":
      "Ho bisogno di un account per effettuare un ordine?",
  "accountToPlaceOrderAns":
      "No, tutto ciò che serve è un indirizzo email. Ti consigliamo di registrare un account per iniziare ad aggiungere pezzi alla tua lista dei desideri, ma puoi anche effettuare e monitorare gli ordini come ospite e iscriverti all'orario che preferisci.",
  "registeredCustomersText": "Clienti registrati",
  "registeredCustomersDescriptionText":
      "Se hai un account, accedi con il tuo\nindirizzo email.",
  "usernameText": "Nome utente",
  "passwordText": "Parola d'ordine",
  "signInText": "Registrazione",
  "forgotYourPasswordText": "Hai dimenticato la password?",
  "newCustomersText": "nuovi clienti",
  "loginDescriptionText":
      "La creazione di un account ha molti vantaggi: check\noout più veloce, mantenere più di un indirizzo\ntracciare gli ordini e altro ancora.",
  "createAccountText": "Creare un profilo",
  "firstNameText": "Nome di battesimo",
  "lastNameText": "Cognome",
  "dateOfBirthText": "Data di nascita",
  "pleaseSelectValidDateText": "Seleziona una data valida",
  "marriageAnniversaryText": "Anniversario di matrimonio",
  "emailText": "E-mail",
  "confirmPasswordText": "Conferma password",
  "signUpForNewsletterText": "Iscriviti alla Newsletter",
  "forgotYourPasswordDescriptionText":
      "Inserisci il tuo indirizzo e-mail qui sotto per ricevere\nun link per la reimpostazione della password",
  "enterYourEmailText": "Inserisci la tua email",
  "resetMyPasswordText": "Reimposta la mia password",
  "accessYourAccountDetailsText":
      "Accedi ai dettagli del tuo account e ai premi",
  "signUpText": "ISCRIZIONE",
  "myOrdersText": "i miei ordini",
  "myWishlistText": "La mia lista dei desideri",
  "addressBookText": "Rubrica",
  "accountInformationText": "Informazioni account",
  "myTicketsText": "I miei biglietti",
  "trackOrderText": "Ordine dei brani",
  "companyMyAccountText": "Azienda",
  "contactUsText": "Contattaci",
  "secureShoppingText": "Acquisti sicuri",
  "advancedSearchText": "Ricerca Avanzata",
  "testimonialsText": "Testimonianze",
  "socialMyAccountText": "Sociale",
  "hopeText": "Sperare",
  "affiliateProgramText": "programma affiliato",
  "influencerRegistrationText": "Registrazione influencer",
  "exchangeText": "Cambio e Resi",
  "contactMyAccountText": "Contatti",
  "privacyPolicyText": "politica sulla riservatezza",
  "termsConditionsText": "Termini & Condizioni",
  "shippingText": "Spedizione",
  "aboutText": "Di",
  "aboutUsMyAccountText": "Chi siamo",
  "referFriendMyAccountText": "Segnala amico",
  "returnsText": "Resi e rimborsi",
  "faqMyAccountText": "FAQ",
  "myAccountText": "Il mio conto",
  "filtersText": "Filtri",
  "priceText": "Prezzo",
  "colorText": "Colore",
  "brandText": "Marca",
  "sizeText": "Dimensione",
  "applyText": "Applicare",
  "searchText": "Ricerca..",
  "aboutUsContain1":
      "SOLO È UNA MIGLIORE DESTINAZIONE DELLA MODA DI LUSSO ONLINE CON 5 MILIONI DI VISITATORI AL MESE E SPEDIZIONI IN TUTTO IL MONDO.",
  "aboutUsContain2":
      "Il sito web presenta la migliore selezione dei migliori designer affermati e giovani talenti emergenti. Solo nasce a Firenze nei primi anni '30, con l'apertura dell'omonimo concept store in Via Roma.Online dal 1999, l'azienda attribuisce il 90% dei ricavi totali alle vendite online. Ad oggi rimane un'azienda familiare al 100% privata, con il nipote del fondatore, Andrea Panconesi in qualità di CEO e sua figlia, Annagreta Panconesi come Direttore Creativo.",
  "aboutUsContain3":
      "Il sito offre un'ampia selezione di abbigliamento, scarpe, borse, accessori, interni di lusso e bellezza, con prodotti disponibili per uomo, donna e bambino dei designer più prestigiosi come Balenciaga, Vetements, Off-White, J.W. Anderson, Balmain, Dolce & Gabbana, Gucci, Saint Laurent, Valentino, Givenchy, Loewe, Jacquemus e altri.",
  "aboutUsContain4":
      'Attualmente ci sono 200 persone provenienti da 15 paesi diversi che lavorano per produrre e mantenere Solo. Il sito è disponibile in 9 lingue: inglese, italiano, tedesco, cinese, russo, spagnolo, francese, coreano e giapponese. Il sito è realizzato interamente in house, con la sede di Firenze che ospita gli uffici di progettazione grafica, informatica, servizio clienti, marketing e acquisti. Gli stilisti e i team stampa operano dalla sede di Solo nella capitale mondiale della moda – Milano.',
  "aboutUsContain5":
      'Tutti gli ordini vengono spediti in tutto il mondo dalla sede di Solo in scatole preparate con la massima cura e utilizzando i migliori materiali, dalle esclusive borse per scarpe al nastro personalizzato.',
  "aboutUsContain6":
      'Solo ha avuto 1,5 milioni di visitatori unici che accedono al sito nel 2008 ed è cresciuta fino a raggiungere i 53 milioni di visitatori unici nel 2017. Oltre il 15% delle vendite online è generato dagli Stati Uniti, seguiti da Germania, Regno Unito, Italia, Cina e Francia.',
  "aboutUsContain7":
      'Solo spinge i confini del panorama della vendita al dettaglio di lusso sia online che offline con una serie di servizi esclusivi e iniziative di marchio tra cui Buy It First, Luxury Club, Sneakers Club, LVR Privilege e LVR Editions.',
  "profile": "Profilo",
  "ContactNoText": "Contattare n.",
  "websiteUrlText": "URL del sito",
  "countryText": "Paese",
  "postCodeText": "Codice postale",
  "socialLinksText": "Collegamenti sociali",
  "facebookText": "Facebook",
  "instagramText": "Instagram",
  "twitterText": "Twitter",
  "youtubeText": "Youtube",
  "linkendinText": "Linkendin",
  "pinterestText": "Pinterest",
  "followersText": "Seguaci",
  "workedOnText": "Progetti lavorati",
  "mr": "Sig.",
  "yourEmail1Text": "La tua email",
  "subscribeText": "SOTTOSCRIVI",
  "menuText": "Menù",
  "accountText": "Account",
  "checkOutText": "Guardare",
  "purchaseText":
      "Inserisci i tuoi dettagli qui sotto per completare l'acquisto",
  "shippingAddressText": "indirizzo di spedizione",
  "shippingMethodText": "metodo di spedizione",
  "paymentMethodText": "Metodo di pagamento",
  "orderSummaryText": "Riepilogo ordine",
  "alreadyAcText": "Hai già un account con noi. Accedi o continua come ospite.",
  "loginText": "ACCEDERE",
  "forgotText": "Hai dimenticato la password?",
  "stLineText": "Indirizzo (linea 1",
  "cityText": "Città",
  "japanText": "Giappone",
  "stateText": "Stato/Provincia",
  "zipPostalText": "Zip / Codice postale",
  "phoneNumberText": "Numero di telefono",
  "itemInCartText": "Articolo nel carrello",
  "qtyText": "Qtà",
  "viewDetailsText": "Visualizza dettagli",
  "applyDisCodeText": "Applicare il codice sconto",
  "enterDisCodeText": "Inserisci il codice sconto",
  "applyDiscountText": "Applicare lo sconto",
  "orderTotalText": "Ordine totale",
  "placeOrderText": "INVIA ORDINE",
  "storePaymentText": "METODI DI PAGAMENTO MEMORIZZATI",
  "newsLetterText": "ABBONAMENTI ALLA NEWSLETTER",
  "enterEmailAddress": "Inserisci l'indirizzo email",
  "enterPhoneNumber": "Inserisci il numero di telefono",
  "enterValidEmailAddress": "Inserisci indirizzo email valido",
  "phoneNumberIsRequired": "È richiesto il numero di telefono",
  "phoneNumberIsNotValid": "Il numero di telefono non è valido",
  "emailIsRequired": "È richiesta la posta elettronica",
  "invalidEmail": "E-mail non valido",
  "passwordIsRequired": "E 'richiesta la password",
  "passwordRegExp":
      "La password deve essere lunga almeno 8 caratteri e contenere una miscela di lettere maiuscole e minuscole, almeno un numero e un carattere speciale (ad esempio ,! @ #?).",
  "email": "E-mail",
  "confirmPasswordIsRequired": "ConfirmPassword è obbligatorio",
  "mrs": "Signora.",
  "tearmsAndCondition": "TERMINI E CONDIZIONI",
  "nylonMessengerBackpackMsg":
      "Lo zaino in nylon Messenger di Balenziaga, chiusura anteriore con gancio, maniglia superiore, spalline regolabili, tasca con zip con patch anteriore con logo a contrasto, ganci come elementi decorativi.",
  "ourServices": "I nostri servizi",
  "ourWebsite": "Il nostro sito web",
  "productDetails": "Dettagli del prodotto",
  "composition": "Composizione",
  "sortBy": "Ordina per",
  "enterFirstName": "Immettere il nome",
  "enterLastName": "Immettere il cognome",
  "enterStreetAddress1": "Inserisci l'indirizzo di strada 1",
  "enterStreetAddress2": "Inserisci l'indirizzo di strada 2",
  "enterStreetAddress3": "Inserisci l'indirizzo di strada 3",
  "streetAddress3": "Indirizzo di strada 3",
  "enterCityName": "Immettere il nome della città",
  "enterZipPostalCode": "Immettere il codice postale zip",
  "enterStateProvince": "Entra in stato/provincia",
  "emailAddressRequired": "Indirizzo e -mail richiesto",
  "viewCouponList": "Visualizza elenco coupon",
  "changeLanguageAndCurrency": "Cambia lingua e valuta",
  "friendFirstName": "Nome amico",
  "friendEmailAddress": "Indirizzo e -mail amico",
  "friendPhoneNumber": "Numero di telefono amico",
  "register": "Registrati",
  "surnameIsRequired": "È richiesto il cognome",
  "enterCouponCode": "Immettere il codice coupon",
  "addProductToYourWishList":
      "Aggiungi il prodotto alla tua lista dei desideri",
  "brandNameIsRequired": "È richiesto il marchio",
  "styleIsRequired": "È richiesto lo stile",
  "keywordIsRequired": "È richiesta la parola chiave",
  "remarkIsRequired": "È richiesta l'osservazione",
  "enteryOurOrderNumberHere": "Inserisci il tuo numero di ordine qui",
  "enterCity": "Entra in città",
  "Alert": "Mettere in guardia",
  "requiredVal": "è obbligatorio",
  "entervalid": "Immettere valido",
  "mustbemorethan2characters": "Deve essere più di 2 caratteri",
  "confirmpasswordshouldbematchwithpassword":
      "Confermare che la password dovrebbe essere abbinata alla password",
  "lastNameIsRequired": "È richiesto cognome",
  "imageUrlIsRequired": "È richiesto il collegamento dell'immagine",
  "enterValidText": "Immettere il testo valido",
  "searchForPiesSushiTacos": "Cerca torte, sushi, tacos ...",
  "enterStreetAddress": "Inserisci l'indirizzo di strada",
  "enterAddress1": "Immettere l'indirizzo 1",
  "enterAddress2": "Immettere l'indirizzo 2",
  "cOUPONAPPLIEDSUCCESSFULLYYOUSAVED":
      "Coupon applicato con successo. HAI SALVATO",
  "oNTHISORDER": "Su questo ordine",
  "areYouSureYouWantToRemove": "Sei sicuro di voler rimuovere",
  "ifyouwouldlikeUsSendYouTheCollectionFrom":
      "Se desideri che ti mandassimo la collezione da",
  "plsCreateATicketBelow": "pls. Crea un biglietto qui sotto",
  "orderNumberIsRequired": "È richiesto il numero dell'ordine",
  "addressDetails": "dettagli dell'indirizzo",
  "enterZipProvince": "Inserisci Zip/Province",
  "zipProvince": "Zip/Provincia",
  "emailAddress": "Indirizzo e-mail",
  "passwordsdonotmatch": "le passwords non corrispondono",
  "passwordsYouHaveEnteredDoNotMatch":
      "Le password che hai inserito non corrispondono",
  "invalidPassword": "Password non valida",
  "registerWithGoogle": "Registrati con Google",
  "registerWithFacebook": "Registrati con Facebook",
  "registerwithTwitter": "Registrati con Twitter",
  "imageurl": "URL dell'immagine",
  "findCountry": "Trova il paese ...",
  "orderReference": "Riferenza dell'ordine",
  "contactNumberIsRequired": "È richiesto il numero di contatto",
  "headOffice": "Capoufficio",
  "soloLuxuryOLablesLtd": "Solo Luxury, O Labels Ltd,",
  "WenlockRoad": "20-22 Wenlock Road, Londra, N1 7gu",
  "youCanViewResponsesOnYourEmail":
      "Puoi visualizzare le risposte sulla tua email",
  "underMyTickets": "Sotto i miei biglietti.",
  "friendFirstNameRequired": "Nome amico richiesto",
  "friendEmailAddressIsRequired": "È richiesto l'indirizzo e -mail amico",
  "friendPhoneNumberIsRequired": "È richiesto il numero di telefono dell'amico",
  "selectProductAnOption": "Seleziona il prodotto un'opzione",
  "pleaseEnterYourEmailToTrackYourTicketByEmail":
      "Inserisci la tua email per tenere traccia del ticket tramite e -mail.",
  "Pleaseagreefornewsletter": "Si prega di accettare la newsletter",
  "referAFriend": "Fare riferimento a un amico",
  "shipTo": "Spedire a",
  "brandProductQuery": "Query del prodotto del marchio",
  "categoryProductQuery": "Categoria query sul prodotto",
  "cartDetails": "Dettagli del carrello",
  "date": "Data",
  "ConfirmationEmailRequired": "È richiesta la posta elettronica di conferma",
  "pleaseentermessage": "Inserisci il messaggio",
  "typeyourmessagehere": "Scrivi qui il tuo messaggio...",
  "goterrorpleasetryagain": "Ho ricevuto un errore, riprova.",
  "internalservererror": "Errore interno del server",
  "oopssomethingwentwrong": "Oops! Qualcosa è andato storto",
  "SigninwithGoogle": "Accedi con Google",
  "SignnwithApple": "Accedi con Apple",
  "SigninwithTwitter": "Iscriviti con Twitter",
  "SigninwithFacebook": "Accedi con Facebook",
  "Requestcancelled": "Richiesta annullata",
  "Requesttimeout": "Richiedi timeout",
  "Get": "Ottenere",
  "peroff": "10% di sconto",
  "onyourfirstpurchaseonAPPUSECode":
      " al tuo primo acquisto sull'app. Usa il codice:",
  "SOLOAPP10": "SoloApp10",
  "TnCApply": "  *T&C applica",
};
