const Map<String, String> ar = {
  "language": "إنجليزي",
  "appNameText": "العلامات التجارية والتسميات",
  "aboutUsText": "معلومات عنا",
  "aboutUsTitle": 'نحن الماركات والملصقات',
  "aboutUsContain": 'اكتشف 100 من أفضل العلامات التجارية في العالم',
  "aboutUsContain1":
      'العلامات التجارية والملصقات هي أفضل وجهة للأزياء الفاخرة عبر الإنترنت مع 5 ملايين زائر شهريًا وشحن عالمي.',
  "aboutUsContain2":
      'يتميز موقع الويب بأفضل اختيار لأفضل المصممين المعتمدين وكذلك المواهب الناشئة الناشئة. تم تأسيس العلامات التجارية في فلورنسا في أوائل ثلاثينيات القرن الماضي ، مع افتتاح متجر مفهوم EPONYMOUS التابع للشركة عبر VIA ROMA. عبر الإنترنت منذ عام 1999 ، تخصص الشركة 90٪ من إجمالي الإيرادات للمبيعات عبر الإنترنت. حتى هذا اليوم ، لا تزال الشركة مملوكة ملكية خاصة للأسرة بنسبة 100٪ ، حيث يعمل حفيد المؤسس ، أندريا بانكونيسي بصفته الرئيس التنفيذي وابنته ، ANNAGRETA PANCONESI كمدير إبداعي.',
  "aboutUsContain3":
      'يقدم الموقع مجموعة واسعة من الملابس والأحذية والحقائب والإكسسوارات والديكورات الداخلية الفاخرة والجمال ، مع المنتجات المتوفرة للرجال والنساء والأطفال من أكثر المصممين شهرة مثل BALENCIAGA ، VETEMENTS ، WH-WHITE أندرسون ، بالمين ، دولتشي آند غابانا ، غوتشي ، سان لوران ، فالنتينو ، جيفنشي ، لوي ، جاكيموس وغيرها.',
  "aboutUsContain4":
      'يوجد حاليًا 200 شخص من 15 دولة مختلفة يعملون على إنتاج العلامات التجارية والحفاظ عليها. الموقع متاح في 9 لغات: الإنجليزية والإيطالية والألمانية والصينية والروسية والإسبانية والفرنسية والكورية واليابانية. تم إنشاء الموقع بالكامل داخل المنزل ، من خلال مكتب فلورنسا للتصميم الجرافيكي ، وتكنولوجيا المعلومات ، وخدمة العملاء ، والتسويق والشراء. تعمل فرق الأناقة والصحافة من مكتب العلامات التجارية في عاصمة الموضة في العالم - ميلان.',
  "aboutUsContain5":
      'يتم شحن جميع الطلبات في جميع أنحاء العالم من المربعات الرئيسية لملصقات العلامات التجارية في صناديق مُجهزة بأقصى قدر من العناية واستخدام أفضل المواد ، من حقائب الأحذية المميزة إلى الشريط المخصص.',
  "aboutUsContain6":
      'استطاعت العلامات التجارية الوصول إلى الموقع 1.5 مليون زائر فريد من نوعه في عام 2008 وتزايد عددهم إلى 53 مليون زائر فريد في عام 2017. يتم إنتاج أكثر من 15٪ من المبيعات عبر الإنترنت من الولايات المتحدة ، تليها ألمانيا والمملكة المتحدة وإيطاليا والصين وفرنسا.',
  "aboutUsContain7":
      'تعمل العلامات التجارية على دفع حدود المناظر الطبيعية للبيع بالتجزئة الفاخرة سواء على الإنترنت أو بدون اتصال بالإنترنت مع مجموعة من الخدمات الحصرية ومبادرات العلامات التجارية بما في ذلك شراء النادي الأول والفاخر ونادي snEAKERS و LVR والصلاحيات الخاصة.',
  "profile": "حساب تعريفي",
  "firstNameText": "الاسم الأول",
  "lastNameText": "الكنية",
  "emailText": "بريد الالكتروني",
  "ContactNoText": "رقم الاتصال.",
  "websiteUrlText": "رابط الموقع",
  "cityText": "مدينة",
  "countryText": "دولة",
  "postCodeText": "الرمز البريدي",
  "socialLinksText": "روابط اجتماعية",
  "facebookText": "فيسبوك",
  "instagramText": "انستغرام",
  "twitterText": "تويتر",
  "youtubeText": "موقع يوتيوب",
  "linkendinText": "لينكيندين",
  "pinterestText": "بينتيريست",
  "followersText": "متابعون",
  "mr": "السيد.",
  "letsText": "دعنا نذهب",
  "orderIdTitle": 'رقم طلبك هو: ',
  "orderDateTitle": 'تاريخ الطلب: 15 سبتمبر 2021',
  "orderNumberTitle": 'رقم الطلب: ',
  "orderConfirm": "شكرا لك على الشراء!",
  "name": "اسم",
  "sku": "SKU",
  "price": "السعر",
  "qty": "الكمية",
  "subTotal": "المجموع الفرعي",
  "action": "عمل",
  "addressBook": "دليل العناوين",
  "billing": "الفواتير",
  "shipping": "شحن",
  "orderContain":
      'سنرسل إليك رسالة إلكترونية لتأكيد الطلب مع التفاصيل ومعلومات التتبع.',
  "referFriendText": "ادع صديق",
  "returnsRefundsText": "العوائد والمردودات",
  "faqText": "التعليمات",
  "contactText": "اتصل",
  "socialText": "اجتماعي",
  "companyText": "شركة",
  "myOrders": "طلباتي",
  "myOrderImage": "صورة",
  "productName": "اسم المنتج",
  "quantity": "الكمية",
  "status": "حالة",
  "paymentMethod": " طريقة الدفع او السداد",
  "shippingAddress": "عنوان الشحن",
  "billingAddress": "عنوان وصول الفواتير",
  "continueShopping": "مواصلة التسوق",
  "generalAndOrderEnquiriesText": "استفسارات عامة وطلبات",
  "gdpText": "الناتج المحلي الإجمالي",
  "engText": "م",
  "nameText": "اسم*",
  "surNameText": "اسم العائلة*",
  "emailAddressText": "عنوان بريد الكتروني*",
  "confirmEmailAddressText": "أكد عنوانك الإلكتروني*",
  "subjectText": "موضوعات*",
  "phoneNumberText": "رقم التليفون",
  "whatsOnYourMindText": "ماذا يدور بعقلك؟*",
  "queryDescription":
      "مهما كان استفسارك ، استخدم نموذج الاتصال أدناه للتواصل ، فريقنا جاهز للمساعدة على مدار الساعة طوال أيام الأسبوع",
  "submitText": "إرسال",
  "typeOfEnquiryText": "نوع الاستفسار *",
  "registeredCustomersText": "العملاء المسجلين",
  "signInDescriptionText":
      "إذا كان لديك حساب ، قم بتسجيل الدخول باستخدام  n عنوان بريدك الإلكتروني.",
  "forgotYourPasswordText": "نسيت رقمك السري؟",
  "signInText": "تسجيل الدخول",
  "newCustomersText": "زبائن الجدد",
  "newCustomersDescriptionText":
      "إنشاء حساب له فوائد عديدة:  n تحقق بشكل أسرع ، واحتفظ بأكثر من عنوان ،  n تتبع الطلبات والمزيد.",
  "createAccountText": "إنشاء حساب",
  "aboutProjectNameText": "حول العلامات التجارية والتسميات",
  "helpAndInformationText": "المساعدة والمعلومات",
  "moreFromProjectText": "المزيد من العلامات التجارية والتسميات",
  "newsLetterText": "النشرة الإخبارية",
  "subscribeText": "الإشتراك",
  "passwordText": "كلمة المرور",
  "homeText": "الصفحة الرئيسية",
  "searchText": "بحث",
  "designersText": "المصممين",
  "wishListText": "قائمة الرغبات",
  "loginText": "تسجيل الدخول",
  "myAccountText": "حسابي",
  "yourEmailText": "بريدك الالكتروني",
  "checkoutText": "الدفع",
  "purchaseText": "الرجاء إدخال التفاصيل الخاصة بك أدناه لإكمال عملية الشراء",
  "shippingAddressText": "عنوان الشحن",
  "shippingMethodText": "طريقة الشحن",
  "paymentMethodText": "طريقة الدفع او السداد",
  "orderSummaryText": "ملخص الطلب",
  "addressText":
      "منتج admin admintast ، منتج الاختبار ، منتج اختبار المنتج ، b12345 302006Russia 1234567890",
  "newAddressText": "عنوان جديد",
  "itemInCartText": "عنصر في عربة التسوق",
  "qtyText": "الكمية",
  "applyDiscountCodeText": "تطبيق كود الخصم",
  "enterDiscountCodeText": "أدخل رمز الخصم",
  "applyDiscountText": "تطبيق الخصم",
  "orderTotalText": "الطلب الكلي",
  "orderCommentText": "طلب التعليق",
  "placeOrderText": "مكان الامر",
  "myOrdersText": "طلباتي",
  "myWishlistText": "قائمة امنياتي",
  "addressBookText": "دليل العناوين",
  "accountInformationText": "معلومات الحساب",
  "storePaymentText": "طرق الدفع المخزنة",
  "newsLetter1Text": "اشتراك الرسائل الإخبارية",
  "enterEmailAddress": "أدخل عنوان البريد الإلكتروني",
  "enterConfirmEmailAddress": "أدخل تأكيدعنوان البريد الإلكتروني",
  "enterPhoneNumber": "أدخل رقم الهاتف",
  "enterValidEmailAddress": "أدخل عنوان بريد إلكتروني صالح",
  "confirmEmailNotMatch":
      "تأكيد عدم تطابق البريد الإلكتروني مع عنوان البريد الإلكتروني",
  "phoneNumberIsRequired": "رقم الهاتف مطلوب",
  "phoneNumberIsNotValid": "رقم الهاتف غير صالح",
  "gstIdentificationNumber":
      "رقم تعريف ضريبة السلع والخدمات غير صالح. يجب أن يكون بتنسيق 11AAAAA1111Z1A1 هذا",
  "emailRequired": "البريد الإلكتروني مطلوب",
  "invalidEmail": "بريد إلكتروني غير صالح",
  "confirmEmailIsRequired": "تأكيد البريد الإلكتروني مطلوب",
  "confirmEmailShouldBeMatchWithEmail":
      "يجب أن يكون تأكيد تطابق البريد الإلكتروني مع البريد الإلكتروني",
  "youHaveReachedYourMaximumLimit":
      "لقد وصلت إلى الحد الأقصى المسموح به من الأحرف",
  "passwordIsRequired": "كلمة المرور مطلوبة",
  "successfullyLoggedOut": "لقد تم تسجيل خروجك بنجاح",
  "emailAddress": "عنوان البريد الإلكتروني",
  "enterEmailToTrackRequest.": "يرجى إدخال بريدك الإلكتروني لتتبع طلبك.",
  "firstName": "الاسم الأول",
  "lastName": "اسم العائلة",
  "dateOfBirth.": "تاريخ الميلاد",
  "dateOfMarriage": "ذكرى الزواج",
  "signUpForNewsletter": "اشترك في النشرة الإخبارية",
  "email": "البريد الإلكتروني",
  "password": "شعار",
  "confirmPassword": "تأكيد كلمة المرور",
  "typesOfEnquiry": "أنواع الاستفسارات",
  "confirmPasswordIsRequired.": "تأكيد كلمة المرور مطلوب",
  "orderDetails": "تفاصيل الطلب",
  "noDataAvailable": "لا توجد بيانات متاحة",
  "myAccount": "حسابي",
  "mrs": "سيدة.",
  "communicationPrefences.": "تفضيلات الاتصال",
  "subscribeNewsletters": "اشترك في النشرات الإخبارية للأناص..",
  "aboutUs": "من نحن",
  "sms": "الرسائل القصيرة",
  "save": "أنقذ",
  "tearmsAndCondition": "الشروط والأحكام",
  "subscribeOffersAndMore":
      "اشترك لتكون الأول مع الوافدين الجدد والمجموعات الحصرية والعروض وأكثر من ذلك.",
  "ourServices": "خدماتنا",
  "delivery": "تسليم",
  "ourWebsite": "موقعنا الكتروني",
  "addToCart": "اضف الى سلة التسوق",
  "subscribe": "اشترك",
  "productDetails": "تفاصيل المنتج",
  "priceMatch": "مطابقة السعر",
  "composition": "تكوين",
  "color": "لون",
  "chooseAnOption": "اختر خيارا...",
  "buyNow": "اشتري الآن",
  "notifyMeWhenThisProductIsInStock1":
      "أبلغني عندما يكون هذا المنتج في المخزون",
  "yourBestPriceAlways": "أفضل سعر لك - دائما.",
  "IfYourPreferredItemIsLowerMsg":
      "إذا كان العنصر المفضل لديك أقل سعرًا في أي متجر آخر في الوقت الحالي ، فسنطابق السعر ونقدم لك ائتمان متجر إضافي بنسبة 10 ٪ لشراءك التالي.",
  "simplyLetUsKnowByClickingHere": "ببساطة أخبرنا بالنقر هنا.",
  "alreadyMadeYourPurchase": "قمت بالفعل بعملية الشراء.",
  "dontWorryLetUsKnowByClickingMsg":
      "لا تقلق ، أخبرنا عن طريق النقر هنا وسنقوم فريق دعم العملاء لدينا باسترداد الفرق إذا تم إجراء عملية الشراء خلال الـ 30 يومًا الماضية.",
  "pleaseSeeFAQsByClickingHere": "يرجى الاطلاع على الأسئلة الشائعة بالنقر هنا",
  "filter": "منقي",
  "sort": "فرز",
  "sortBy": "صنف حسب",
  "noProductsFound": "لم يتم العثور على منتجات",
  "createTicket": "إنشاء تذكرة",
  "more": "& أكثر...",
  "bgbp": "GBP",
  "findBrand": "العثور على العلامات التجارية",
  "itSeemsWeHaveNothingToShowFor": "يبدو أنه ليس لدينا ما نظهره",
  "ifYouWouldLikeToHaveMoreInformationAbout":
      "إذا كنت ترغب في الحصول على مزيد من المعلومات حول",
  "thenPleaseCreateATicket": "ثم يرجى إنشاء تذكرة",
  "contactInformation": "معلومات التواصل",
  "edit": "يحرر",
  "changePassword": "غير كلمة السر",
  "youHaveNoProductsInYourWishList": "ليس لديك منتجات في قائمة أمنياتك.",
  "toBbeUpdated": "ليتم تحديثه",
  "youHaveNoSavedAddressAddnewAddressToContinueWithCheckout":
      "ليس لديك عنوان محفوظ أضف عنوانًا جديدًا للمتابعة مع الخروج",
  "shipHere": "شحن هنا",
  "enterFirstName": "أدخل الاسم الأول",
  "enterLastName": "إدخال اسم آخر",
  "enterStreetAddress1": "أدخل عنوان الشارع 1",
  "streetAddress1": "عنوان الشارع 1",
  "enterStreetAdress2": "أدخل الشارع Adress 2",
  "streetAddress2": "عنوان الشارع 2",
  "enterStreetAddress3": "أدخل عنوان الشارع 3",
  "streetAddress3": "عنوان الشارع 3",
  "enterCityName": "أدخل اسم المدينة",
  "city": "مدينة",
  "country": "دولة",
  "enterZipPostalCode": "أدخل الرمز البريدي الرمز البريدي",
  "zipPostalCode": "الرمز البريدي / الرمز البريدي",
  "stateProvince": "الدولة/المقاطعة",
  "enterStateProvince": "أدخل الدولة/المقاطعة",
  "emailAddressRequired": "عنوان البريد الإلكتروني: (مطلوب",
  "cancelCoupon": "إلغاء القسيمة",
  "apply": "يتقدم",
  "viewCouponList": "عرض قائمة القسيمة",
  "coupons": "كوبونات",
  "changeLanguageAndCurrency": "تغيير اللغة والعملة",
  "youHaveNoOrders": "ليس لديك أوامر",
  "youHaveNoTickets": "ليس لديك تذاكر",
  "category": "فئة",
  "createNewTicket": "إنشاء تذكرة جديدة",
  "positiveImpactSustainability": "التأثير الإيجابي + الاستدامة",
  "thereAreStillMoreThanMSG":
      "لا يزال هناك أكثر من مليار شخص حول العالم الذين يعيشون في فقر شديد على أقل من 1.25 دولار في اليوم. في تايلاند وحدها ، نفى أكثر من مليون عضو من قبائل التل على هوامش المجتمع - المواطنة ، وإغلاقها من سوق العمل الرسمي ووضعهم في الاستغلال والاتجار.",
  "atYellowLeafHammocksMsg":
      "في أرجوحة الأوراق الصفراء ، نعتقد أن خلق فرص العمل الأخلاقي هو حل طويل الأجل للفقر الشديد.",
  "insteadOfOrganizingMsg":
      "بدلاً من تنظيم مجموعة من التبرعات الخيرية لتوفير المياه والتغذية والملابس ، وما إلى ذلك ، نعمل مباشرة مع العائلات لبناء استراتيجية شاملة وكريمة وطويلة الأجل نحو مستقبل أكثر إشراقًا. الأسباب وراء الفقر الجهازي معقدة ، ولكن الاستقرار المالي طويل الأجل في متناول اليد.",
  "toPutItSimplyMsg":
      "بعبارة ببساطة: من خلال التركيز على سبل العيش ، يمكننا قطع الرجل الأوسط ، والحصول على المال مباشرة في أيدي الأمهات الذكية + الحيلة وتمكين العائلات من معالجة مشاكلهن الخاصة (دون أن نخضع لجدول أعمال أي شخص آخر).",
  "acrossThreeWeavingCommunitiesMsg":
      "\"عبر ثلاث مجتمعات نسج ، نعمل على خلق فرص عمل للأمهات وبناء أساس لتحول المجتمع الإيجابي. من خلال أعمال النسيج المرنة والآمنة \"\"للأجور\"\" ، يمكن للحرفيين لدينا رفع أسرهم من الفقر وعبودية الديون إلى الطبقة الوسطى.\"",
  "creatingJobsForWomenMsg":
      "** إن خلق فرص عمل للنساء أمر مهم بشكل خاص لتحول المجتمع - يظهر الأبحاث أن النساء سوف ينفقن ما يصل إلى 90 ٪ من أرباحهن على الصحة والتغذية وتعليم أسرهن. يحول تحويل النساء إلى عيلنز إلى تحسين وضعهن في المجتمع ، ويبني احترامهم للذات ويمكّنهن من تجميع الموارد لتحسين البنية التحتية.",
  "theFoundationForABrighterFuter": "الأساس لمستودع أكثر إشراقًا",
  "theSecurityOfAStableMsg":
      "كان لأمن مصدر الإيرادات المستقر والمتزايد تأثير هائل على القرية. تمكن Mlabri من بدء مدرسة وبناء مركز مجتمعي للنسج والتواصل الاجتماعي. أنشأوا واحدة من صناديق البطالة الأولى في تايلاند. مع زيادة القوة الاقتصادية ، نجحوا في الضغط على الجنسية والحقوق المدنية ، والتي مُنحت لأول مرة في عام 2001. إن نسج الأرجوحة هو عمل مرن ، وهو مثالي للأمهات اللائي يمكنهم العمل من المنزل ووضع جداولهم الخاصة. لسوء الحظ ، دون الوصول إلى الأسواق العالمية ، اقتصر الطلب على الأراجيح على موسم السياحة التايلاندي ولم تكن هناك طريقة لضمان عمل على مدار السنة.",
  "spreadingLastingChangeTheHammockRrevolution":
      "تغيير دائم: نهر أرجوحة الثورة",
  "thisIsAboutWhereMsg":
      "هذا هو المكان الذي تنضم فيه Leafe Leaf إلى القصة! على مدار السنوات القليلة الماضية ، عملنا على تطوير قنوات مبيعات متسقة ، وبناء شراكات دولية وتثبيت عمليات الاستقرار داخل القرى.",
  "corollaryEconomicMsg":
      "نشأت الفرص الاقتصادية الطبيعية ، مثل مكتب البريد ، وإعداد الطعام ، وزراعة القهوة المستدامة لتوظيف أولئك الذين لا ينسجون. حفزت شراكتنا مع KIVA التدريب المالي والتخطيط المالي ، حيث افتتح العديد من النساجين حسابات مصرفية لأول مرة في حياتهم!",
  "wWithOurGrowthMsg":
      "مع استمرار نمونا في التسارع ، لن نتمكن فقط من توظيف جميع نساج Mlabri على مدار السنة ، سنكون قادرين أيضًا على مواصلة التوسع وتوفير التدريب والعمالة المستمرة لمجتمعات قبيلة هيل في المنطقة المحيطة. إلى أن تتوفر أعمال النسيج والوظائف المستدامة في جميع أنحاء المنطقة ، ستستمر الممارسات الزراعية المدمرة ولن تنتهي الدورة الاستغلالية للعبودية المحتوية.",
  "throughTheEstablishmentMsg":
      "من خلال إنشاء Leaf Leaf كعلامة تجارية عالمية لأسلوب الحياة ، ستتمكن قرى Hill Tribe التي نتشارك معها من الحفاظ على هذا التأثير الإيجابي ومواصلة وضع الأساس لمستقبل أكثر إشراقًا.",
  "enterWebsite": "أدخل موقع الويب",
  "enterPostCode": "أدخل رمز البريد",
  "thankYouForYourInterest": "شكرًا لك على اهتمامك بالعمل مع العلامات التجارية",
  "oneOfOurTeamMembersWillBeInTouchSoon":
      "سيكون أحد أعضاء فريقنا على اتصال قريبًا",
  "forAnyAdditionalQueriesPleaseWriteTo ":
      "لأي استفسارات إضافية يرجى الكتابة إلى",
  "theProductIsOutOfStock": "المنتج خارج المخزون.",
  "whateverYourQueryUseTheContactFormBelowMsg":
      "مهما كان استفسارك. استخدم نموذج الاتصال أدناه للوصول إلى Touch-Oorteam جاهز لمساعدة 24*7",
  "enterSubject": "أدخل الموضوع",
  "enterSomeText": "أدخل بعض النص",
  "enterDetailsBelowToSend":
      "أدخل التفاصيل أدناه لإرسال رمز قسيمة بنسبة 10 ٪ إلى صديقك",
  "enterFriendName": "إدخال اسم صديق",
  "friendFirstName": "الصديق الاسم الأول",
  "enterFirstEmailAddress": "أدخل عنوان البريد الإلكتروني الأول",
  "friendEmailAddress": "عنوان البريد الإلكتروني صديق",
  "enterFirstPhoneNumber": "أدخل رقم الهاتف الأول",
  "friendPhoneNumber": "رقم هاتف صديق",
  "register": "يسجل",
  "dateOfBirthIsRequired": "تاريخ الميلاد مطلوب",
  "marriageAnniversaryIsRequired": "ذكرى الزواج مطلوبة",
  "surnameIsRequired": "اللقب مطلوب",
  "date": "تاريخ",
  "showDialog": "عرض الحوار",
  "removeProduct": "إزالة المنتج",
  "areYouSureWantToRemoveThisProductFromCart":
      "هل أنت متأكد من إزالة هذا المنتج من العربة؟",
  "yes": "نعم",
  "no": "رقم",
  "addToWishlist": "أضف إلى قائمة الامنيات",
  "onceYouAddThisProductToWishlistThenItWillBeRemoveFromAart":
      "بمجرد إضافة هذا المنتج إلى قائمة الرغبات ، سيتم إزالته من العربة",
  "ok": "نعم",
  "nouHaveNoItemsInYourShoppingCart":
      "لا يوجد لديك عناصر في سلة التسوق الخاصة بك.",
  "Discount": "تخفيض",
  "enterCouponCode": "أدخل رمز القسيمة",
  "removeCoupon": "إزالة القسيمة",
  "availableCouponList": "قائمة القسيمة المتاحة",
  "allCouponsList": "قائمة جميع القسائم",
  "addProductToYourWishList": "أضف منتجًا إلى قائمة الأمنيات الخاصة بك",
  "configurable": "قابل للتكوين",
  "Missing": "مفقود",
  "Amount": "مقدار",
  "Balance": "الرصيد",
  "Remarks": "ملاحظات",
  "myAddresses": "عناويني",
  "noAddressFound": "لم يتم العثور على عنوان",
  "addAddress": "اضف عنوان",
  "updateAddress": "تحديث العنوان",
  "expectedShipmentDate": "تاريخ الشحن المتوقع",
  "brandNameIsRequired": "اسم العلامة التجارية مطلوب",
  "styleIsRequired": "النمط مطلوب",
  "keywordIsRequired": "الكلمة الرئيسية مطلوبة",
  "remarkIsRequired": "الملاحظة مطلوبة",
  "couponId": "معرف القسيمة",
  "couponName": "اسم القسيمة",
  "expireAt": "تنتهي في",
  "noCouponsFound": "لم يتم العثور على كوبونات!",
  "yourRequestHasBeenReceived": "تم استلام طلبك.",
  "youCanViewYourRequestsatMyTickets": "يمكنك عرض طلباتك في التذاكر الخاصة بي",
  "incorrectPassword": "كلمة سر خاطئة",
  "thePasswordYouenteredisincorrectPleasetryagain":
      "كلمة المرور التي أدخلتها غير صحيحة. حاول مرة اخرى",
  "registeredCustomers": "العملاء المسجلين",
  "ifYouHaveAnAccountSignInWithYourEmailAddress":
      "إذا كان لديك حساب ، فقم بتسجيل الدخول مع عنوان بريدك الإلكتروني",
  "pleaseEnterOrderNumberToTrackYourOrder":
      "الرجاء إدخال رقم الطلب لتتبع طلبك.",
  "enterOrderNumber": "أدخل رقم الطلب",
  "enteryOurOrderNumberHere": "أدخل رقم طلبك هنا",
  "howDoIFindMyOrderReference": "كيف أجد مرجع طلبي؟",
  "passwordRegExp":
      "يجب أن يكون طول كلمة المرور ما لا يقل عن 8 أحرف وتحتوي على مزيج من الأحرف الكبيرة والصغيرة ، وعدد واحد على الأقل وحرف خاص واحد (على سبيل المثال ،! @ #؟).",
  "nylonMessengerBackpackMsg":
      "حقيبة ظهر Messenger من النايلون من Balenziaga ، الإغلاق الأمامي مع الخطاف ، المقبض العلوي ، أحزمة الكتف القابلة للتعديل ، جيب الرمز البريدي الأمامي مع شعار التباين ، والسنانير كعناصر زخرفية.",
  "priceMatchTicket": "تذكرة تطابق السعر",
  "enterAddress3": "أدخل العنوان 3",
  "enterCity": "أدخل المدينة",
  "pleaseTryWithAnotherEmaiAddressMsg":
      "يرجى المحاولة مع عنوان بريد إلكتروني آخر أو الكتابة إلينا على care@brandslabels.com لمزيد من المساعدة.",
  "Alert": "انذار",
  "requiredVal": "مطلوب",
  "mustbeof": "يجب أن يكون من",
  "digits": "الأرقام",
  "mustbeanumberExample100": "يجب أن يكون رقما. مثال: 100",
  "character": "حرف",
  "isinvalid": "غير صالح!",
  "mustbemorethan2characters": "يجب أن يكون أكثر من حرفين",
  "entervalid": "أدخل صالح",
  "musthaveatleast2characters": "يجب أن يكون لديك شخصان على الأقل",
  "confirmpasswordshouldbematchwithpassword":
      "تأكيد كلمة المرور يجب أن تكون مطابقة بكلمة المرور",
  "pleaseenterPassword": "الرجاء إدخال كلمة المرور",
  "mustbemorethan8characters": "يجب أن يكون أكثر من 8 أحرف",
  "mobileisRequired": "مطلوب الهاتف المحمول",
  "mobilenumbermust10digits": "يجب أن يكون رقم الهاتف المحمول 10 أرقام",
  "mobileNumbermustbedigits": "يجب أن يكون رقم الهاتف المحمول أرقامًا",
  "yearmustbenumberonly": "يجب أن يكون العام فقط",
  "establishedYearisRequired": "مطلوب السنة المحددة",
  "yearmustbebetween1850and": "يجب أن يكون العام بين عام 1850 و",
  "licenseNoisRequired": "لا يلزم ترخيص رقم",
  "numberofemployeeisRequired": "عدد الموظف مطلوب",
  "numberofemployeeisnotmorethan9999": "عدد الموظف ليس أكثر من 9999",
  "numberofemployeemustbedigits": "يجب أن يكون عدد الموظف أرقامًا",
  "dateisRequired": "التاريخ مطلوب",
  "pleaseentervaliddate": "الرجاء إدخال تاريخ صالح",
  "licenseIssuingAuthorityisRequired": "مطلوب سلطة إصدار الترخيص",
  "licenseIssuingAuthoritymustbeazandAZ":
      "يجب أن تكون سلطة إصدار الترخيص A-Z و A-Z",
  "firstNameIsRequired": "الإسم الأول مطلوب",
  "lastNameIsRequired": "إسم العائلة مطلوب",
  "imageUrlIsRequired": "رابط الصورة مطلوب",
  "enterValidText": "أدخل نص صالح",
  "pleaseCheckYourInternetConnection":
      "الرجاء التحقق من اتصال الانترنت الخاص بك!",
  "searchForPiesSushiTacos": "ابحث عن الفطائر ، السوشي ، سندويشات التاكو ...",
  "enterSurname": "أدخل اللقب",
  "enterStreetAddress": "أدخل عنوان الشارع",
  "addNew": "اضف جديد",
  "enterAddress1": "أدخل العنوان 1",
  "enterAddress2": "أدخل العنوان 2",
  "noBrandFound": "لم يتم العثور على علامة تجارية",
  "COUPONAPPLIEDSUCCESSFULLYYOUSAVED": "تم تطبيق القسيمة بنجاح. لقد أنقذت",
  "ONTHISORDER": "على هذا الترتيب",
  "areYouSureYouWantToRemove": "هل أنت متأكد من أنك تريد إزالة",
  "couponCode": "رمز الكوبون؟",
  "cancel": "يلغي",
  "itSeemsLikeWeHaveNothingToShowForThisBrand":
      "يبدو أنه ليس لدينا ما نظهره لهذه العلامة التجارية",
  "ifyouwouldlikeUsSendYouTheCollectionFrom":
      "إذا كنت تريد منا أن نرسل لك المجموعة من",
  "plsCreateATicketBelow": "الرجاء. إنشاء تذكرة أدناه",
  "itSeemsLikeWeHaveNothingToShowForThisCategory":
      "يبدو أنه ليس لدينا ما نظهره لهذه الفئة",
  "enterName": "أدخل الاسم",
  "description": "وصف",
};
