const Map<String, String> cn = {
  "language": "英语",
  "appNameText": "品牌和标签",
  "aboutUsText": "关于我们",
  "aboutUsTitle": '我们是品牌和标签',
  "aboutUsContain": '探索 100 多个世界最佳品牌',
  "aboutUsContain1": 'Brands & LABELS 是顶级在线奢侈品时尚目的地，每月有 500 万访客，并在全球范围内运送。',
  "aboutUsContain2":
      '该网站精选了顶级知名设计师以及年轻的新兴人才。品牌品牌于 1930 年代初期在佛罗伦萨成立，并在 VIA ROMA 开设了公司的同名概念店。在线 自 1999 年以来，公司将 90% 的总收入归功于在线销售。直到今天，它仍然是一家 100% 私有的家族企业，创始人的孙子 ANDREA Panconesi 担任首席执行官，他的女儿 ANNAGRETA Panconesi 担任创意总监。',
  "aboutUsContain3":
      '该网站提供各种服装、鞋子、包袋、配饰、豪华家居内饰和美容产品，包括来自 BALENCIAGA、VETEMENTS、OFF-WHITE、J.W. 等最负盛名设计师的男士、女士和儿童产品。 ANDERSON、BALMAIN、DOLCE & GABBANA、GUCCI、SAINT LAURENT、VALENTINO、GIVENCHY、LOEWE、JACQUEMUS 等等。',
  "aboutUsContain4":
      '目前有来自 15 个不同国家的 200 人致力于生产和维护品牌标签。该网站提供 9 种语言版本：英语、意大利语、德语、汉语、俄语、西班牙语、法语、韩语和日语。该网站完全在内部创建，佛罗伦萨办公室设有平面设计、IT、客户服务、营销和采购部门。造型师和新闻团队在世界时尚之都米兰的品牌办公室工作。',
  "aboutUsContain5": '从签名鞋包到个性化丝带，所有订单均从品牌标签总部装在精心准备并使用最优质材料的盒子中向全球发货。',
  "aboutUsContain6":
      '品牌标签在 2008 年有 150 万唯一身份访问者访问该网站，并在 2017 年增长到 5300 万唯一身份访问者。超过 15% 的在线销售来自美国，其次是德国、英国、意大利、中国和法国。',
  "aboutUsContain7":
      '品牌通过一系列独家服务和商标计划（包括“先买”、“LUXURY CLUB”、“SNEAKERS CLUB”、“LVR PRIVILEGE”和“LVR 版本”）在线上和线下推动奢侈品零售格局的边界。',
  "profile": "轮廓",
  "firstNameText": "名",
  "lastNameText": "姓",
  "emailText": "电子邮件",
  "ContactNoText": "联系方式。",
  "websiteUrlText": "网址",
  "cityText": "城市",
  "countryText": "国家",
  "postCodeText": "邮政编码",
  "socialLinksText": "社交链接",
  "facebookText": "Facebook",
  "instagramText": "Instagram",
  "twitterText": "推特",
  "youtubeText": "YouTube",
  "linkendinText": "林肯",
  "pinterestText": "Pinterest",
  "followersText": "追随者",
  "mr": "先生。",
  "letsText": "我们走吧",
  "orderIdTitle": '''您的订单号是：''',
  "orderDateTitle": '订购日期：2021 年 9 月 15 日',
  "orderNumberTitle": '订单号：',
  "orderConfirm": "感谢您的购买！",
  "name": "姓名",
  "sku": "库存单位",
  "price": "价钱",
  "qty": "数量",
  "subTotal": "小计",
  "action": "行动",
  "addressBook": "地址簿",
  "billing": "计费",
  "shipping": "船运",
  "orderContain": '我们将通过电子邮件向您发送包含详细信息和跟踪信息的订单确认信息。',
  "referFriendText": "推荐朋友",
  "returnsRefundsText": "退货和退款",
  "faqText": "常问问题",
  "contactText": "接触",
  "socialText": "社会的",
  "companyText": "公司",
  "myOrders": "我的订单",
  "myOrderImage": "图片",
  "productName": "产品名称",
  "quantity": "数量",
  "status": "状态",
  "paymentMethod": " 付款方法",
  "shippingAddress": "送货地址",
  "billingAddress": "帐单地址",
  "continueShopping": "继续购物",
  "generalAndOrderEnquiriesText": "一般和订单查询",
  "gdpText": "国内生产总值",
  "engText": "英文",
  "nameText": "姓名*",
  "surNameText": "姓*",
  "emailAddressText": "电子邮件地址*",
  "confirmEmailAddressText": "确认电邮地址*",
  "subjectText": "主题*",
  "phoneNumberText": "电话号码",
  "whatsOnYourMindText": "你在想什么？*",
  "queryDescription": "无论您有什么疑问，请使用下面的联系表格与我们联系，我们的团队随时准备 24/7 提供帮助",
  "submitText": "提交",
  "typeOfEnquiryText": "查询类型*",
  "registeredCustomersText": "注册客户",
  "signInDescriptionText": "如果您有帐户，请使用您的\nemail 地址登录。",
  "forgotYourPasswordText": "忘记密码了吗？",
  "signInText": "登入",
  "newCustomersText": "新客户",
  "newCustomersDescriptionText": "创建帐户有很多好处：\n结账速度更快、保留多个地址、\n跟踪订单等等。",
  "createAccountText": "创建一个帐户",
  "aboutProjectNameText": "关于品牌和标签",
  "helpAndInformationText": "帮助和信息",
  "moreFromProjectText": "更多来自品牌和标签",
  "newsLetterText": "通讯",
  "subscribeText": "订阅",
  "passwordText": "密码",
  "homeText": "家",
  "searchText": "搜索",
  "designersText": "设计师",
  "wishListText": "愿望清单",
  "loginText": "登录",
  "myAccountText": "我的账户",
  "yourEmailText": "你的邮件",
  "checkoutText": "退房",
  "purchaseText": "请在下方输入您的详细信息以完成购买",
  "shippingAddressText": "送货地址",
  "shippingMethodText": "邮寄方式",
  "paymentMethodText": "付款方法",
  "orderSummaryText": "订单摘要",
  "addressText":
      "admin admintast 产品, 测试产品, 测试产品 测试产品, b12345 302006Russia 1234567890",
  "newAddressText": "新地址",
  "itemInCartText": "购物车中的物品",
  "qtyText": "数量",
  "applyDiscountCodeText": "应用折扣码",
  "enterDiscountCodeText": "输入折扣码",
  "applyDiscountText": "申请折扣",
  "orderTotalText": "合计订单",
  "orderCommentText": "订单评论",
  "placeOrderText": "下订单",
  "myOrdersText": "我的订单",
  "myWishlistText": "我的收藏",
  "addressBookText": "地址簿",
  "accountInformationText": "帐户信息",
  "storePaymentText": "存储的付款方式",
  "newsLetter1Text": "通讯订阅",
  "enterEmailAddress": "输入电子邮件地址",
  "enterConfirmEmailAddress": "输入确认电子邮件地址",
  "enterPhoneNumber": "输入电话号码",
  "enterValidEmailAddress": "输入有效的电子邮件地址",
  "confirmEmailNotMatch": "确认电子邮件与电子邮件地址不匹配",
  "phoneNumberIsRequired": "电话号码为必填项",
  "phoneNumberIsNotValid": "电话号码无效",
  "gstIdentificationNumber": "消费税识别号无效。它应该是这个 11AAAAA1111Z1A1 格式",
  "emailRequired": "电子邮件为必填项",
  "invalidEmail": "无效的电子邮件",
  "confirmEmailIsRequired": "确认电子邮件为必填项",
  "confirmEmailShouldBeMatchWithEmail": "确认电子邮件应与电子邮件匹配",
  "youHaveReachedYourMaximumLimit": "您已达到允许的最大字符数限制",
  "passwordIsRequired": "密码为必填项",
  "successfullyLoggedOut": "您已成功注销",
  "emailAddress": "电子邮件地址",
  "enterEmailToTrackRequest.": "请输入您的电子邮件以跟踪您的请求。",
  "firstName": "名字",
  "lastName": "姓",
  "dateOfBirth.": "出生日期",
  "dateOfMarriage": "结婚纪念日",
  "signUpForNewsletter": "订阅时事通讯",
  "email": "电子邮件",
  "password": "密码",
  "confirmPassword": "确认密码",
  "typesOfEnquiry": "查询类型",
  "confirmPasswordIsRequired.": "确认密码为必填项",
  "orderDetails": "订单详情",
  "noDataAvailable": "无可用数据",
  "myAccount": "我的帐户",
  "mrs": "太太。",
  "communicationPrefences.": "通信首选项",
  "subscribeNewsletters": "订阅时事通讯..",
  "aboutUs": "关于我们",
  "sms": "短信",
  "save": "救",
  "tearmsAndCondition": "条款与条件",
  "subscribeOffersAndMore": "订阅成为第一个，享受我们的新品、独家系列、优惠等。",
  "ourServices": "我们的服务",
  "delivery": "交货",
  "ourWebsite": "我们的网站",
  "addToCart": "加入购物车",
  "subscribe": "订阅",
  "productDetails": "产品详情",
  "priceMatch": "价格匹配",
  "composition": "组成",
  "color": "颜色",
  "chooseAnOption": "选择一个选项...",
  "buyNow": "立即购买",
  "notifyMeWhenThisProductIsInStock1": "该产品有库存时通知我",
  "yourBestPriceAlways": "您的最佳价格 - 永远。",
  "IfYourPreferredItemIsLowerMsg":
      "如果您的首选商品在当前的任何其他商店的价格较低，我们将与价格相匹配，并为您提供下一次购买的10％额外商店信用额。",
  "simplyLetUsKnowByClickingHere": "只需单击此处，让我们知道。",
  "alreadyMadeYourPurchase": "已经进行了购买。",
  "dontWorryLetUsKnowByClickingMsg":
      "不用担心，请单击此处，我​​们的客户支持团队将退还您的差额，如果购买是在过去30天内进行的。",
  "pleaseSeeFAQsByClickingHere": "请单击此处查看常见问题解答",
  "filter": "筛选",
  "sort": "种类",
  "sortBy": "排序方式",
  "noProductsFound": "找不到产品",
  "createTicket": "创建票",
  "more": "＆ 更多的...",
  "bgbp": "英镑",
  "findBrand": "查找品牌",
  "itSeemsWeHaveNothingToShowFor": "似乎我们没有什么可显示的",
  "ifYouWouldLikeToHaveMoreInformationAbout": "如果您想获得有关的更多信息",
  "thenPleaseCreateATicket": "然后请创建票",
  "contactInformation": "联系信息",
  "edit": "编辑",
  "changePassword": "更改密码",
  "youHaveNoProductsInYourWishList": "您的愿望清单中没有产品。",
  "toBbeUpdated": "要被更新",
  "youHaveNoSavedAddressAddnewAddressToContinueWithCheckout":
      "您没有保存的地址添加新地址以继续结帐",
  "shipHere": "在这里运送",
  "enterFirstName": "输入名字",
  "enterLastName": "输入姓氏",
  "enterStreetAddress1": "输入街道地址1",
  "streetAddress1": "街道地址1",
  "enterStreetAdress2": "进入街道地址2",
  "streetAddress2": "街道地址2",
  "enterStreetAddress3": "输入街道地址3",
  "streetAddress3": "街道地址3",
  "enterCityName": "输入城市名称",
  "city": "城市",
  "country": "国家",
  "enterZipPostalCode": "输入邮政编码",
  "zipPostalCode": "邮编/邮政编码",
  "stateProvince": "州/省",
  "enterStateProvince": "进入州/省",
  "emailAddressRequired": "需要电子邮件地址",
  "cancelCoupon": "取消优惠券",
  "apply": "申请",
  "viewCouponList": "查看优惠券列表",
  "coupons": "优惠券",
  "changeLanguageAndCurrency": "改变语言和货币",
  "youHaveNoOrders": "你没有订单",
  "youHaveNoTickets": "你没有门票",
  "category": "类别",
  "createNewTicket": "创建新票",
  "positiveImpactSustainability": "积极影响 +可持续性",
  "thereAreStillMoreThanMSG":
      "每天不到1.25美元，全世界仍然有超过十亿人在世界各地生活。仅在泰国，社会边缘就存在超过一百万的希尔部落成员 - 被拒绝公民身份，被拒之门外的就业市场，容易受到剥削和贩运。",
  "atYellowLeafHammocksMsg": "在黄叶吊床上，我们认为，道德创造就业是一种长期解决极端贫困的能力。",
  "insteadOfOrganizingMsg":
      "我们没有组织慈善捐款的拼凑而成，以提供水，营养，衣服等。我们直接与家人合作，建立一种全面，有尊严，长期的策略，以实现更美好的未来。系统性贫困背后的原因很复杂，但是长期的财务稳定性已经达到。",
  "toPutItSimplyMsg":
      "简而言之：通过关注生计，我们可以削减中间人，将钱直接掌握在聪明的 +机智的母亲的手中，并赋予家庭权力解决自己的问题（而不受其他任何人的议程的约束）。",
  "acrossThreeWeavingCommunitiesMsg":
      "在三个编织社区中，我们正在努力为母亲创造就业机会，并为积极的社区转型奠定基础。通过灵活，安全的 繁荣工资 编织工作，我们的工匠能够将他们的家人从贫困和债务奴隶制升至中产阶级。",
  "creatingJobsForWomenMsg":
      "**为妇女创造就业机会对于社区转型尤为重要 - 研究表明，妇女将在家庭的健康，营养和教育上花费多达90％的收入。将妇女变成养家糊口的人改善了她们在社区中的地位，建立自尊心，并使她们能够集中资源以改善基础设施。",
  "theFoundationForABrighterFuter": "更亮的料理的基础",
  "theSecurityOfAStableMsg":
      "稳定，增长的收入来源的安全对村庄产生了巨大影响。 Mlabri能够成立一所学校，并建立一个社区中心进行编织和社交。他们建立了泰国最早的失业资金之一。随着经济能力的增加，他们成功游说了公民身份和公民权利，这是2001年最初授予的。吊床编织是灵活的工作，非常适合可以在家工作并制定自己的日程安排的母亲。不幸的是，如果没有进入全球市场的机会，对吊床的需求仅限于泰国旅游季节，并且无法确保全年就业。",
  "spreadingLastingChangeTheHammockRrevolution": "传播持久的变化：吊床rrevolution",
  "thisIsAboutWhereMsg":
      "这是关于黄色叶子加入故事的地方！在过去的几年中，我们一直致力于建立一致的销售渠道，建立国际合作伙伴关系并稳定村庄内的运营。",
  "corollaryEconomicMsg":
      "邮局，食品准备和可持续咖啡种植等推论的经济机会已经涌现为雇用那些不编织的人。我们与Kiva的合作伙伴关系刺激了财务培训和财务计划，许多编织者一生中首次开设银行帐户！",
  "wWithOurGrowthMsg":
      "随着我们的增长持续加速，我们不仅能够全年雇用所有Mlabri Weavers，而且我们还将能够继续扩展并为周围地区的Hill Tribe社区提供培训和持续的就业。在整个地区的编织工作和可持续性工作之前，将继续进行破坏性的农业实践，并且契约奴役的剥削周期将无法真正结束。",
  "throughTheEstablishmentMsg":
      "通过将黄叶作为全球生活方式品牌建立，我们与我们合作的Hill Tribe村庄将能够维持这种积极的影响，并继续为更美好的未来奠定基础。",
  "enterWebsite": "输入网站",
  "enterPostCode": "输入邮政编码",
  "thankYouForYourInterest": "感谢您对与品牌标签合作的兴趣",
  "oneOfOurTeamMembersWillBeInTouchSoon": "我们的团队成员很快就会与",
  "forAnyAdditionalQueriesPleaseWriteTo ": "有关其他查询，请写信给",
  "theProductIsOutOfStock": "该产品缺货。",
  "whateverYourQueryUseTheContactFormBelowMsg":
      "无论您的查询如何。使用下面的触点表格进入接触式启动可以帮助24*7",
  "enterSubject": "输入主题",
  "enterSomeText": "输入一些文字",
  "enterDetailsBelowToSend": "在下面输入详细信息，向您的朋友发送10％的优惠券代码",
  "enterFriendName": "输入朋友名称",
  "friendFirstName": "朋友名字",
  "enterFirstEmailAddress": "输入第一个电子邮件地址",
  "friendEmailAddress": "朋友电子邮件地址",
  "enterFirstPhoneNumber": "输入第一个电话号码",
  "friendPhoneNumber": "朋友电话号码",
  "register": "登记",
  "dateOfBirthIsRequired": "需要dateofth",
  "marriageAnniversaryIsRequired": "需要结婚周年纪念日",
  "surnameIsRequired": "需要姓氏",
  "date": "日期",
  "showDialog": "显示对话框",
  "removeProduct": "删除产品",
  "areYouSureWantToRemoveThisProductFromCart": "您确定要从购物车中删除此产品吗？",
  "yes": "是的",
  "no": "不",
  "addToWishlist": "添加到愿望清单",
  "onceYouAddThisProductToWishlistThenItWillBeRemoveFromAart":
      "将此产品添加到愿望清单后，将从购物车中删除",
  "ok": "好的",
  "nouHaveNoItemsInYourShoppingCart": "您的购物车中没有商品。",
  "Discount": "折扣",
  "enterCouponCode": "输入优惠券代码",
  "removeCoupon": "删除优惠券",
  "availableCouponList": "可用优惠券列表",
  "allCouponsList": "所有优惠券清单",
  "addProductToYourWishList": "将产品添加到您的愿望清单",
  "configurable": "可配置",
  "Missing": "失踪",
  "Amount": "数量",
  "Balance": "平衡",
  "Remarks": "评论",
  "myAddresses": "我的地址",
  "noAddressFound": "找不到地址",
  "addAddress": "添加地址",
  "updateAddress": "更新地址",
  "expectedShipmentDate": "预期货物日期",
  "brandNameIsRequired": "需要品牌名称",
  "styleIsRequired": "需要样式",
  "keywordIsRequired": "需要关键字",
  "remarkIsRequired": "需要备注",
  "couponId": "优惠券ID",
  "couponName": "优惠券名称",
  "expireAt": "到期",
  "noCouponsFound": "找不到优惠券！",
  "yourRequestHasBeenReceived": "您的要求已收到。",
  "youCanViewYourRequestsatMyTickets": "您可以在我的门票上查看您的要求",
  "incorrectPassword": "密码错误",
  "thePasswordYouenteredisincorrectPleasetryagain": "您输入密码不正确。请再试一次",
  "registeredCustomers": "注册客户",
  "ifYouHaveAnAccountSignInWithYourEmailAddress": "如果您有帐户，请登录您的电子邮件地址",
  "pleaseEnterOrderNumberToTrackYourOrder": "请输入订单号以跟踪您的订单。",
  "enterOrderNumber": "输入订单号",
  "enteryOurOrderNumberHere": "在此处输入您的订单号",
  "howDoIFindMyOrderReference": "我如何找到我的订单参考？",
  "passwordRegExp": "密码必须至少8个字符，并且包含大写字母和小写字母的混合物，至少一个数字和一个特殊字符（例如，！ @＃？）。",
  "nylonMessengerBackpackMsg":
      "Balenziaga的尼龙信使背包，带钩子，顶部手柄，可调节的肩带，带鲜明对比徽标的前贴片拉链口袋，挂钩作为装饰元件。",
  "priceMatchTicket": "价格匹配票",
  "enterAddress3": "输入地址3",
  "enterCity": "进入城市",
  "pleaseTryWithAnotherEmaiAddressMsg":
      "请尝试使用另一个电子邮件地址或通过Care@brandslabels.com写信给我们，以获取进一步的帮助。",
  "Alert": "警报",
  "requiredVal": "是必须的",
  "mustbeof": "必须是",
  "digits": "数字",
  "mustbeanumberExample100": "必须是一个数字。示例：100",
  "character": "特点",
  "isinvalid": "是无效的！",
  "mustbemorethan2characters": "必须超过2个字符",
  "entervalid": "输入有效",
  "musthaveatleast2characters": "必须至少有2个字符",
  "confirmpasswordshouldbematchwithpassword": "确认密码应与密码匹配",
  "pleaseenterPassword": "请输入密码",
  "mustbemorethan8characters": "必须超过8个字符",
  "mobileisRequired": "需要移动",
  "mobilenumbermust10digits": "手机号必须10位数字",
  "mobileNumbermustbedigits": "手机号必须是数字",
  "yearmustbenumberonly": "年必须只有数字",
  "establishedYearisRequired": "需要建立年份",
  "yearmustbebetween1850and": "年必须在1850年至",
  "licenseNoisRequired": "许可证不需要",
  "numberofemployeeisRequired": "需要员工人数",
  "numberofemployeeisnotmorethan9999": "员工人数不超过9999",
  "numberofemployeemustbedigits": "员工人数必须是数字",
  "dateisRequired": "需要日期",
  "pleaseentervaliddate": "请输入有效日期",
  "licenseIssuingAuthorityisRequired": "要求发放许可证",
  "licenseIssuingAuthoritymustbeazandAZ": "许可颁发机构必须是A-Z和A-Z",
  "firstNameIsRequired": "需要名字",
  "lastNameIsRequired": "需要姓氏",
  "imageUrlIsRequired": "需要图像链接",
  "enterValidText": "输入有效文本",
  "pleaseCheckYourInternetConnection": "请检查您的互联网连接！",
  "searchForPiesSushiTacos": "搜索馅饼，寿司，炸玉米饼...",
  "enterSurname": "输入姓氏",
  "enterStreetAddress": "输入街道地址",
  "addNew": "添新",
  "enterAddress1": "输入地址1",
  "enterAddress2": "输入地址2",
  "noBrandFound": "找不到品牌",
  "COUPONAPPLIEDSUCCESSFULLYYOUSAVED": "优惠券成功应用。你救了",
  "ONTHISORDER": "在此订单上",
  "areYouSureYouWantToRemove": "你确定要删除吗",
  "couponCode": "优惠券代码？",
  "cancel": "取消",
  "itSeemsLikeWeHaveNothingToShowForThisBrand": "似乎我们没有什么可为这个品牌展示的",
  "ifyouwouldlikeUsSendYouTheCollectionFrom": "如果您希望我们向您发送收藏",
  "plsCreateATicketBelow": "请在下面创建票",
  "itSeemsLikeWeHaveNothingToShowForThisCategory": "似乎我们没有什么可显示的",
  "enterName": "输入名字",
  "description": "描述",
};
