const Map<String, String> de = {
  "language": "Englisch",
  "appNameText": "Marken und Labels",
  "aboutUsText": "Über uns",
  "aboutUsTitle": 'WIR SIND MARKE & LABEL',
  "aboutUsContain": 'ENTDECKEN SIE 100 DER BESTEN MARKEN DER WELT',
  "aboutUsContain1":
      'BRANDS & LABELS IST MIT 5 MILLIONEN BESUCHERN PRO MONAT UND WELTWEITEM VERSAND EINE TOP ONLINE-LUXUS-MODE-DESTINATION.',
  "aboutUsContain2":
      'DIE WEBSITE BIETET DIE BESTE AUSWAHL DER BESTEN ETABLIERTEN DESIGNER SOWIE JUNGE ENTSTEHENDE TALENTE. BRANDSLABELS WURDE IN FLORENZ IN DEN FRÜHEN 1930ER JAHREN MIT DER ERÖFFNUNG DES NAMENSBEZEICHNETEN CONCEPT STORE DES UNTERNEHMENS IN DER VIA ROMA GEGRÜNDET. ONLINE SEIT 1999 SCHREIBT DAS UNTERNEHMEN 90 % DES GESAMTUMSATZES AUF ONLINE-VERKÄUFE ZU. BIS HEUTE BLEIBT ES ZU 100 % IN PRIVATBESITZ, MIT DEM ENKEL DES GRÜNDERS ANDREA PANCONESI ALS CEO UND SEINER TOCHTER ANNAGRETA PANCONESI ALS CREATIVE DIRECTOR.',
  "aboutUsContain3":
      'DIE WEBSITE BIETET EINE BREITE AUSWAHL AN KLEIDUNG, SCHUHEN, TASCHEN, ACCESSOIRES, LUXURIÖSER WOHNEINRICHTUNG UND SCHÖNHEIT, MIT PRODUKTEN FÜR MÄNNER, DAMEN UND KINDER VON DEN RENOMMIERTESTEN DESIGNERN WIE BALENCIAGA, VETEMENTS, OFF-WHITE, J.W. ANDERSON, BALMAIN, DOLCE & GABBANA, GUCCI, SAINT LAURENT, VALENTINO, GIVENCHY, LOEWE, JACQUEMUS UND MEHR.',
  "aboutUsContain4":
      'DERZEIT ARBEITEN 200 MENSCHEN AUS 15 VERSCHIEDENEN LÄNDERN AN DER HERSTELLUNG UND PFLEGE VON MARKENLABELN. DIE SEITE IST IN 9 SPRACHEN VERFÜGBAR: ENGLISCH, ITALIENISCH, DEUTSCH, CHINESISCH, RUSSISCH, SPANISCH, FRANZÖSISCH, KOREANISCH UND JAPANISCH. DIE WEBSITE WIRD VOLLSTÄNDIG IM HAUS ERSTELLT, MIT DEN ABTEILUNGEN FÜR GRAFIKDESIGN, IT, KUNDENDIENST, MARKETING UND EINKAUF DES FLORENCE OFFICE HOUSING. DIE STYLISTEN UND PRESSE-TEAMS ARBEITEN VOM BRANDSLABELS-BÜRO IN DER WELTHAUPTSTADT DER MODE – MAILAND.',
  "aboutUsContain5":
      'ALLE BESTELLUNGEN WERDEN WELTWEIT VOM HAUPTSITZ DER BRANDS LABELS IN KARTONS VERSENDET, DIE MIT HÖCHSTER SORGFALT VORBEREITET WERDEN UND DIE BESTEN MATERIALIEN VERWENDEN, VON DEN SIGNATURE-SCHUHTASCHEN BIS ZUM PERSONALISIERTEN BAND.',
  "aboutUsContain6":
      'BRANDSLABELS HAT 2008 1,5 MILLIONEN EINZELBESUCHER AUF DIE WEBSITE ZUGANGEN UND IST 2017 AUF 53 MILLIONEN EINZELBESUCHER ANGEWACHSEN. MEHR ALS 15 % DER ONLINE-UMSÄTZE WERDEN IN DEN VEREINIGTEN STAATEN ERZIELT, GEFOLGT VON DEUTSCHLAND, GROSSBRITANNIEN, ITALIEN, CHINA UND FRANKREICH.',
  "aboutUsContain7":
      'BRANDSLABELS VERSCHIEBT DIE GRENZEN DER LUXUS-EINZELHANDELSLANDSCHAFT ON- UND OFFLINE MIT EINER REIHE VON EXKLUSIVEN DIENSTLEISTUNGEN UND MARKENINITIATIVEN, EINSCHLIESSLICH BUY IT FIRST, LUXURY CLUB, SNEAKERS CLUB, LVR PRIVILEGE UND LVR EDITIONS.',
  "profile": "Profil",
  "firstNameText": "Vorname",
  "lastNameText": "Familienname, Nachname",
  "emailText": "Email",
  "ContactNoText": "Kontakt-Nr.",
  "websiteUrlText": "Webadresse",
  "cityText": "Stadt",
  "countryText": "Land",
  "postCodeText": "Postleitzahl",
  "socialLinksText": "Soziale Verbindungen",
  "facebookText": "Facebook",
  "instagramText": "Instagram",
  "twitterText": "Twitter",
  "youtubeText": "Youtube",
  "linkendinText": "Linkendin",
  "pinterestText": "Pinterest",
  "followersText": "Anhänger",
  "mr": "Herr.",
  "letsText": "Lass uns gehen",
  "orderIdTitle": '''Ihre Bestellnummer lautet: ''',
  "orderDateTitle": 'Bestelldatum: 15. September 2021',
  "orderNumberTitle": 'BESTELLNUMMER: ',
  "orderConfirm": "DANKE FÜR IHREN EINKAUF!",
  "name": "NAME",
  "sku": "Artikelnummer",
  "price": "PREIS",
  "qty": "Menge",
  "subTotal": "ZWISCHENSUMME",
  "action": "AKTION",
  "addressBook": "Adressbuch",
  "billing": "Abrechnung",
  "shipping": "Versand",
  "orderContain":
      'Wir senden Ihnen eine Bestellbestätigung mit Details und Tracking-Informationen per E-Mail.',
  "referFriendText": "Freund empfehlen",
  "returnsRefundsText": "Rückgabe & Erstattung",
  "faqText": "FAQ",
  "contactText": "Kontakt",
  "socialText": "Sozial",
  "companyText": "Gesellschaft",
  "myOrders": "Meine Bestellungen",
  "myOrderImage": "Bild",
  "productName": "Produktname",
  "quantity": "Menge",
  "status": "Status",
  "paymentMethod": " Zahlungsmethode",
  "shippingAddress": "Lieferanschrift",
  "billingAddress": "Rechnungsadresse",
  "continueShopping": "Mit dem Einkaufen fortfahren",
  "generalAndOrderEnquiriesText": "ALLGEMEINE & BESTELLANFRAGEN",
  "gdpText": "BIP",
  "engText": "ENG",
  "nameText": "Name*",
  "surNameText": "Nachname*",
  "emailAddressText": "E-Mail-Addresse*",
  "confirmEmailAddressText": "E-Mail-Adresse bestätigen*",
  "subjectText": "Fach*",
  "phoneNumberText": "Telefonnummer",
  "whatsOnYourMindText": "Was haben Sie auf dem Herzen?*",
  "queryDescription":
      "Was auch immer Ihre Frage ist, verwenden Sie das unten stehende Kontaktformular, um sich mit uns in Verbindung zu setzen. Unser Team ist rund um die Uhr für Sie da",
  "submitText": "EINREICHEN",
  "typeOfEnquiryText": "Art der Anfrage*",
  "registeredCustomersText": "Registrierte Kunden",
  "signInDescriptionText":
      "Wenn Sie ein Konto haben, melden Sie sich mit Ihrer\nE-Mail-Adresse an.",
  "forgotYourPasswordText": "Haben Sie Ihr Passwort vergessen?",
  "signInText": "Anmelden",
  "newCustomersText": "neue Kunden",
  "newCustomersDescriptionText":
      "Das Erstellen eines Kontos hat viele Vorteile:\nBezahle schneller, behalte mehr als eine Adresse,\nverfolge Bestellungen und mehr.",
  "createAccountText": "Ein Konto erstellen",
  "aboutProjectNameText": "Über Marken und Labels",
  "helpAndInformationText": "Hilfe und Informationen",
  "moreFromProjectText": "Mehr von Brands&Labels",
  "newsLetterText": "Newsletter",
  "subscribeText": "Abonnieren",
  "passwordText": "Passwort",
  "homeText": "Zuhause",
  "searchText": "Suche",
  "designersText": "Designer",
  "wishListText": "Wunschzettel",
  "loginText": "Anmeldung",
  "myAccountText": "Mein Konto",
  "yourEmailText": "Deine E-Mail",
  "checkoutText": "Kasse",
  "purchaseText":
      "Bitte geben Sie unten Ihre Daten ein, um Ihren Kauf abzuschließen",
  "shippingAddressText": "Lieferanschrift",
  "shippingMethodText": "Versandart",
  "paymentMethodText": "Zahlungsmethode",
  "orderSummaryText": "Bestellübersicht",
  "addressText":
      "admin admintast Produkt, Testprodukt, Testprodukt Testprodukt, b12345 302006Russland 1234567890",
  "newAddressText": "Neue Adresse",
  "itemInCartText": "Artikel im Warenkorb",
  "qtyText": "Menge",
  "applyDiscountCodeText": "Rabattcode anwenden",
  "enterDiscountCodeText": "Rabattcode eingeben",
  "applyDiscountText": "Rabatt anwenden",
  "orderTotalText": "Auftragssumme",
  "orderCommentText": "Kommentar bestellen",
  "placeOrderText": "BESTELLUNG AUFGEBEN",
  "myOrdersText": "MEINE BESTELLUNGEN",
  "myWishlistText": "Meine Wunschliste",
  "addressBookText": "Adressbuch",
  "accountInformationText": "Kontoinformationen",
  "storePaymentText": "GESPEICHERTE ZAHLUNGSARTEN",
  "newsLetter1Text": "NEWSLETTER-ABOS",
  "enterEmailAddress": "E-Mail-Adresse eingeben",
  "enterConfirmEmailAddress": "Bestätigungs-E-Mail-Adresse eingeben",
  "enterPhoneNumber": "Telefonnummer eingeben",
  "enterValidEmailAddress": "Geben Sie eine gültige E-Mail-Adresse ein",
  "confirmEmailNotMatch":
      "Bestätigen Sie, dass E-Mail nicht mit E-Mail-Adresse übereinstimmt",
  "phoneNumberIsRequired": "Telefonnummer ist erforderlich",
  "phoneNumberIsNotValid": "Telefonnummer ist ungültig",
  "gstIdentificationNumber":
      "Die GST-Identifikationsnummer ist ungültig. Es sollte in diesem 11AAAAA1111Z1A1-Format vorliegen",
  "emailRequired": "E-Mail ist erforderlich",
  "invalidEmail": "Ungültige E-Mail-Adresse",
  "confirmEmailIsRequired": "Bestätigen Sie, dass E-Mail erforderlich ist",
  "confirmEmailShouldBeMatchWithEmail":
      "Bestätigen Sie, dass E-Mail mit E-Mail übereinstimmen sollte",
  "youHaveReachedYourMaximumLimit":
      "Sie haben Ihre maximal zulässige Zeichenbegrenzung erreicht",
  "passwordIsRequired": "Passwort ist erforderlich",
  "successfullyLoggedOut": "Sie wurden erfolgreich abgemeldet",
  "emailAddress": "E-Mail-Adresse",
  "enterEmailToTrackRequest.":
      "Bitte geben Sie Ihre E-Mail-Adresse ein, um Ihre Anfrage zu verfolgen.",
  "firstName": "Vorname",
  "lastName": "Nachname",
  "dateOfBirth.": "Geburtsdatum",
  "dateOfMarriage": "Hochzeitstag",
  "signUpForNewsletter": "Melden Sie sich für den Newsletter an",
  "email": "E-Mail",
  "password": "Passwort",
  "confirmPassword": "Passwort bestätigen",
  "typesOfEnquiry": "Arten der Anfrage",
  "confirmPasswordIsRequired.": "ConfirmPassword ist erforderlich",
  "orderDetails": "Bestelldetails",
  "noDataAvailable": "Keine Daten verfügbar",
  "myAccount": "Mein Konto",
  "mrs": "Frau.",
  "communicationPrefences.": "Kommunikationspräferenzen",
  "subscribeNewsletters": "Abonnieren Sie den Newsletter von ounass.",
  "aboutUs": "Über uns",
  "sms": "SMS",
  "save": "Retten",
  "tearmsAndCondition": "ALLGEMEINE GESCHÄFTSBEDINGUNGEN",
  "subscribeOffersAndMore":
      "Melden Sie sich an, um der Erste mit unseren Neuheiten, exklusiven Kollektionen, Angeboten und mehr zu sein.",
  "ourServices": "Unsere Dienstleistungen",
  "delivery": "Lieferung",
  "ourWebsite": "Unsere Website",
  "addToCart": "In den Warenkorb",
  "subscribe": "Abonnieren",
  "productDetails": "Produktdetails",
  "priceMatch": "Preisanpassung",
  "composition": "Zusammensetzung",
  "color": "Farbe",
  "chooseAnOption": "Wählen Sie eine Option...",
  "buyNow": "Kaufe jetzt",
  "notifyMeWhenThisProductIsInStock1":
      "Benachrichtigen Sie mich, wenn dieses Produkt auf Lager ist",
  "yourBestPriceAlways": "Ihr bester Preis - immer.",
  "IfYourPreferredItemIsLowerMsg":
      "Wenn Ihr bevorzugter Artikel zum aktuellen Zeitpunkt in einem anderen Geschäft günstiger ist, werden wir mit dem Preis übereinstimmen und Ihnen 10% zusätzliche Geschäftskredite für Ihren nächsten Kauf anbieten.",
  "simplyLetUsKnowByClickingHere":
      "Lassen Sie es uns einfach wissen, indem Sie hier klicken.",
  "alreadyMadeYourPurchase": "Bereits Ihren Kauf gemacht.",
  "dontWorryLetUsKnowByClickingMsg":
      "Mach dir keine Sorgen, lass uns wissen, indem wir hier klicken und wir unser Kundenunterstützungsteam den Unterschied zurückerstattet, ob der Kauf innerhalb der letzten 30 Tage getätigt wurde.",
  "pleaseSeeFAQsByClickingHere":
      "Bitte beachten Sie die FAQs, indem Sie hier klicken",
  "filter": "Filter",
  "sort": "Sortieren",
  "sortBy": "Sortieren nach",
  "noProductsFound": "Keine Produkte gefunden",
  "createTicket": "Ticket erstellen",
  "more": "& Mehr...",
  "bgbp": "Britisches Pfund",
  "findBrand": "Marken finden",
  "itSeemsWeHaveNothingToShowFor":
      "Es scheint, dass wir nichts zu zeigen haben",
  "ifYouWouldLikeToHaveMoreInformationAbout":
      "Wenn Sie weitere Informationen darüber haben möchten",
  "thenPleaseCreateATicket": "Dann erstellen Sie bitte ein Ticket",
  "contactInformation": "Kontaktinformationen",
  "edit": "Bearbeiten",
  "changePassword": "Passwort ändern",
  "youHaveNoProductsInYourWishList":
      "Sie haben keine Produkte in Ihrer Wunschliste.",
  "toBbeUpdated": "Aktualisiert werden",
  "youHaveNoSavedAddressAddnewAddressToContinueWithCheckout":
      "Sie haben keine gespeicherte Adresse hinzuzufügen, um eine neue Adresse hinzuzufügen, um die Kasse fortzusetzen",
  "shipHere": "Versenden Sie hier",
  "enterFirstName": "Bitte Vornamen eingeben",
  "enterLastName": "Nachnamen eingeben",
  "enterStreetAddress1": "Geben Sie Straßenadresse 1 ein",
  "streetAddress1": "Adresse 1",
  "enterStreetAdress2": "Geben Sie Straßenadress 2 ein",
  "streetAddress2": "Straßenadresse 2",
  "enterStreetAddress3": "Geben Sie Straßenadresse 3 ein",
  "streetAddress3": "Straßenadresse 3",
  "enterCityName": "Geben Sie den Stadtnamen ein",
  "city": "Stadt",
  "country": "Land",
  "enterZipPostalCode": "Geben Sie die Postleitzahl der ZIP ein",
  "zipPostalCode": "Postleitzahl/Postleitzahl",
  "stateProvince": "Staat/Provinz",
  "enterStateProvince": "Geben Sie den Staat/die Provinz ein",
  "emailAddressRequired": "E-Mail-Adresse: (Pflichtfeld",
  "cancelCoupon": "Coupon abbrechen",
  "apply": "Sich bewerben",
  "viewCouponList": "Gutscheinliste anzeigen",
  "coupons": "Gutscheine",
  "changeLanguageAndCurrency": "Sprache und Währung ändern",
  "youHaveNoOrders": "Sie haben keine Bestellungen",
  "youHaveNoTickets": "Sie haben keine Tickets",
  "category": "Kategorie",
  "createNewTicket": "Neues Ticket erstellen",
  "positiveImpactSustainability": "Positive Auswirkungen + Nachhaltigkeit",
  "thereAreStillMoreThanMSG":
      "Es gibt immer noch mehr als eine Milliarde Menschen auf der ganzen Welt, die in extremer Armut mit weniger als 1,25 US -Dollar pro Tag leben. Allein in Thailand existieren mehr als eine Million Mitglieder von Hill -Stämmen am Rande der Gesellschaft - die Staatsbürgerschaft verweigert, aus dem formellen Arbeitsmarkt ausgeschlossen und anfällig für Ausbeutung und Handel.",
  "atYellowLeafHammocksMsg":
      "Bei Yellow Leaf Hängematten glauben wir, dass die Schaffung von ethischen Arbeitsplätzen eine ermächtigende langfristige Lösung für extreme Armut ist.",
  "insteadOfOrganizingMsg":
      "Anstatt ein Flickenteppich von gemeinnützigen Spenden zu organisieren, um Wasser, Ernährung, Kleidung usw. bereitzustellen, arbeiten wir direkt mit Familien zusammen, um eine umfassende, würdige und langfristige Strategie für eine bessere Zukunft aufzubauen. Die Ursachen hinter systemischer Armut sind kompliziert, aber langfristige finanzielle Stabilität ist in Reichweite.",
  "toPutItSimplyMsg":
      "Um es einfach auszudrücken: Indem wir uns auf den Lebensunterhalt konzentrieren, können wir den mittleren Mann ausschneiden, Geld direkt in die Hände von Smart + einfallsreichen Müttern bringen und Familien befähigen, ihre eigenen Probleme anzugehen (ohne der Agenda eines anderen anderen zu unterliegen).",
  "acrossThreeWeavingCommunitiesMsg":
      "In drei Webgemeinschaften arbeiten wir daran, Arbeitsplätze für Mütter zu schaffen und eine Grundlage für eine positive Gemeinschaftsumwandlung aufzubauen. Durch flexible, sichere „Wohlstandslohn -Webenarbeit können unsere Handwerker ihre Familien von Armut und Schuldensklaverei in die Mittelschicht heben.",
  "creatingJobsForWomenMsg":
      "** Die Schaffung von Arbeitsplätzen für Frauen ist besonders wichtig für die Transformation der Gemeinschaft - Untersuchungen zeigen, dass Frauen bis zu 90% ihres Einkommens für die Gesundheit, Ernährung und Bildung ihrer Familien ausgeben werden. Das Umwandeln von Frauen in Ernährer verbessert ihren Status in der Gemeinde, baut Selbstwertgefühl auf und ermöglicht es ihnen, Ressourcen zu bündeln, um die Infrastruktur zu verbessern.",
  "theFoundationForABrighterFuter": "Die Grundlage für einen helleren Fvere",
  "theSecurityOfAStableMsg":
      "Die Sicherheit einer stabilen, wachsenden Einnahmequelle hatte einen enormen Einfluss auf das Dorf. Die MLABRI konnten eine Schule gründen und ein Gemeindezentrum zum Weben und Geselligkeit aufbauen. Sie gründeten eines der ersten Arbeitslosenfonds Thailands. Mit zunehmender wirtschaftlicher Macht setzten sie sich erfolgreich für Staatsbürgerschaft und Bürgerrechte ein, die sie erstmals 2001 gewährt haben. Das Hängemattenweben ist eine flexible Arbeit, ideal für Mütter, die von zu Hause aus arbeiten und ihre eigenen Zeitpläne erstellen können. Leider beschränkte sich ohne Zugang zu den globalen Märkten die Nachfrage nach Hängematten auf die thailändische Tourismussaison, und es gab keine Möglichkeit, das ganze Jahr über eine Beschäftigung zu gewährleisten.",
  "spreadingLastingChangeTheHammockRrevolution":
      "Verbreitung dauerhafter Veränderung: Die Hängematten -Entfernung",
  "thisIsAboutWhereMsg":
      "Hier geht es darum, wo das gelbe Blatt der Geschichte verbindet! In den letzten Jahren haben wir daran gearbeitet, konsistente Vertriebskanäle zu entwickeln, internationale Partnerschaften aufzubauen und den Betrieb in den Dörfern zu stabilisieren.",
  "corollaryEconomicMsg":
      "Wirtschaftliche Möglichkeiten, wie ein Postamt, die Zubereitung von Speisen und eine nachhaltige Kaffeezucht, haben diejenigen, die nicht weben, eingebrochen. Unsere Partnerschaft mit Kiva hat die Finanzausbildung und die Finanzplanung angeregt. Viele Weber eröffnen zum ersten Mal in ihrem Leben Bankkonten!",
  "wWithOurGrowthMsg":
      "Da unser Wachstum weiterhin beschleunigt wird, werden wir nicht nur das ganze Jahr über alle Mlabri-Weavers einsetzen, sondern auch in der Lage sein, weiter zu expandieren und Schulungen und eine kontinuierliche Beschäftigung für die Gemeinden der Hill-Stammes in der umliegenden Region anzubieten. Bis zum Weben von Arbeiten und nachhaltigen Arbeitsplätzen im gesamten Gebiet verfügbar sind, werden destruktive landwirtschaftliche Praktiken fortgesetzt und der ausbeuterische Zyklus der indentierten Knechtschaft wird nicht wirklich enden.",
  "throughTheEstablishmentMsg":
      "Durch die Einrichtung von Yellow Leaf als globale Lifestyle -Marke wird die Hill Tribe -Dörfer, mit denen wir zusammenarbeiten, diese positiven Auswirkungen aufrechterhalten und weiterhin die Grundlage für eine bessere Zukunft legen.",
  "enterWebsite": "Geben Sie die Website ein",
  "enterPostCode": "Geben Sie die Postleitzahl ein",
  "thankYouForYourInterest":
      "Vielen Dank für Ihr Interesse an der Arbeit mit Brands-Labels",
  "oneOfOurTeamMembersWillBeInTouchSoon":
      "Eines unserer Teammitglieder wird bald in Kontakt sein",
  "forAnyAdditionalQueriesPleaseWriteTo ":
      "Für weitere Fragen schreiben Sie bitte an",
  "theProductIsOutOfStock": "Das Produkt ist nicht vorrätig.",
  "whateverYourQueryUseTheContactFormBelowMsg":
      "Was auch immer Ihre Frage. Verwenden Sie das folgende Kontaktformular, um in Touch-Opfer-Orientam zu helfen, um 24*7 zu helfen",
  "enterSubject": "Betreff eingeben",
  "enterSomeText": "Geben Sie einen Text ein",
  "enterDetailsBelowToSend":
      "Geben Sie unten Details ein, um einen 10% igen Gutscheincode an Ihren Freund zu senden",
  "enterFriendName": "Geben Sie den Namen des Freundes ein",
  "friendFirstName": "Freund Vorname",
  "enterFirstEmailAddress": "Geben Sie die erste E -Mail -Adresse ein",
  "friendEmailAddress": "Freunden -E -Mail -Adresse",
  "enterFirstPhoneNumber": "Geben Sie die erste Telefonnummer ein",
  "friendPhoneNumber": "Freundliche Telefonnummer",
  "register": "Registrieren",
  "dateOfBirthIsRequired": "Datum ist erforderlich",
  "marriageAnniversaryIsRequired": "Heiratsjubiläum ist erforderlich",
  "surnameIsRequired": "Nachname ist erforderlich",
  "date": "Datum",
  "showDialog": "Dialog anzeigen",
  "removeProduct": "Produkt entfernen",
  "areYouSureWantToRemoveThisProductFromCart":
      "Möchten Sie dieses Produkt sicher aus dem Warenkorb entfernen?",
  "yes": "JAWOHL",
  "no": "NEIN",
  "addToWishlist": "Zur Wunschliste hinzufügen",
  "onceYouAddThisProductToWishlistThenItWillBeRemoveFromAart":
      "Sobald Sie dieses Produkt zur Wunschliste hinzufügen, wird es aus dem Wagen entfernt",
  "ok": "OK",
  "nouHaveNoItemsInYourShoppingCart":
      "Sie haben keine Artikel in Ihrem Einkaufswagen.",
  "Discount": "Rabatt",
  "enterCouponCode": "Gutschein-Code eingeben",
  "removeCoupon": "Gutschein entfernen",
  "availableCouponList": "Verfügbare Gutscheinliste",
  "allCouponsList": "Alle Gutscheine",
  "addProductToYourWishList": "Fügen Sie Produkt in Ihre Wunschliste hinzu",
  "configurable": "Konfigurierbar",
  "Missing": "Fehlen",
  "Amount": "Menge",
  "Balance": "Gleichgewicht",
  "Remarks": "Bemerkungen",
  "myAddresses": "Meine Adressen",
  "noAddressFound": "Keine Adresse gefunden",
  "addAddress": "Adresse hinzufügen",
  "updateAddress": "Adresse aktualisieren",
  "expectedShipmentDate": "Erwarteter Versanddatum",
  "brandNameIsRequired": "Markenname ist erforderlich",
  "styleIsRequired": "Stil ist erforderlich",
  "keywordIsRequired": "Schlüsselwort ist erforderlich",
  "remarkIsRequired": "Bemerkung ist erforderlich",
  "couponId": "Gutschein -ID",
  "couponName": "Gutscheinname",
  "expireAt": "Verfallen bei",
  "noCouponsFound": "Keine Gutscheine gefunden!",
  "yourRequestHasBeenReceived": "Ihre Anfrage wurde empfangen.",
  "youCanViewYourRequestsatMyTickets":
      "Sie können Ihre Anfragen in meinen Tickets anzeigen",
  "incorrectPassword": "Falsches Passwort",
  "thePasswordYouenteredisincorrectPleasetryagain":
      "Das eingegebene Passwort ist falsch. Bitte versuche es erneut",
  "registeredCustomers": "Registrierte Kunden",
  "ifYouHaveAnAccountSignInWithYourEmailAddress":
      "Wenn Sie ein Konto haben, melden Sie sich bei Ihrer E -Mail -Adresse an",
  "pleaseEnterOrderNumberToTrackYourOrder":
      "Bitte geben Sie die Bestellnummer ein, um Ihre Bestellung zu verfolgen.",
  "enterOrderNumber": "Bestellnummer eingeben",
  "enteryOurOrderNumberHere": "Geben Sie hier Ihre Bestellnummer ein",
  "howDoIFindMyOrderReference": "Wie finde ich meine Bestellreferenz?",
  "passwordRegExp":
      "Das Passwort muss mindestens 8 Zeichen lang sein und eine Mischung aus Großbuchstaben und Kleinbuchstaben enthalten, mindestens eine Nummer und ein spezielles Zeichen (z. B.! @ #?).",
  "nylonMessengerBackpackMsg":
      "Nylon Messenger -Rucksack von Balenziaga, Frontschließung mit Haken, oberem Griff, verstellbare Schultergurte, Reißverschlusspocke vordere Patch mit Kontrastlogo, Haken als dekorative Elemente.",
  "priceMatchTicket": "Preis Match Ticket",
  "enterAddress3": "Geben Sie die Adresse 3 ein",
  "enterCity": "Stadt betreten",
  "pleaseTryWithAnotherEmaiAddressMsg":
      "Bitte versuchen Sie es mit einer anderen E -Mail -Adresse oder schreiben Sie uns an care@brandslabels.com, um weitere Unterstützung zu erhalten.",
  "Alert": "Alarm",
  "requiredVal": "ist nötig",
  "mustbeof": "Muss von sein",
  "digits": "Ziffern",
  "mustbeanumberExample100": "muss eine Nummer sein. Beispiel: 100",
  "character": "Charakter",
  "isinvalid": "ist ungültig!",
  "mustbemorethan2characters": "Muss mehr als 2 Zeichen sein",
  "entervalid": "Geben Sie gültig ein",
  "musthaveatleast2characters": "Muss mindestens 2 Zeichen haben",
  "confirmpasswordshouldbematchwithpassword":
      "Bestätigen Sie das Passwort sollte mit dem Passwort übereinstimmen",
  "pleaseenterPassword": "Bitte Passwort eingeben",
  "mustbemorethan8characters": "Muss mehr als 8 Zeichen sein",
  "mobileisRequired": "Mobile ist erforderlich",
  "mobilenumbermust10digits": "Mobiltelefonnummer muss 10 Ziffern",
  "mobileNumbermustbedigits": "Die Mobilfunknummer muss Ziffern sein",
  "yearmustbenumberonly": "Das Jahr muss nur die Nummer sein",
  "establishedYearisRequired": "Das etablierte Jahr ist erforderlich",
  "yearmustbebetween1850and": "Jahr muss zwischen 1850 und sein",
  "licenseNoisRequired": "Lizenz Nein ist erforderlich",
  "numberofemployeeisRequired": "Anzahl der Mitarbeiter ist erforderlich",
  "numberofemployeeisnotmorethan9999":
      "Anzahl der Mitarbeiter ist nicht mehr als 9999",
  "numberofemployeemustbedigits":
      "Die Anzahl der Mitarbeiter muss Ziffern sein",
  "dateisRequired": "Datum ist erforderlich",
  "pleaseentervaliddate": "Bitte geben Sie ein gültiges Datum ein",
  "licenseIssuingAuthorityisRequired":
      "Die Lizenzausstellungsbehörde ist erforderlich",
  "licenseIssuingAuthoritymustbeazandAZ":
      "Lizenzausstellungsbehörde muss A-Z und A-Z sein",
  "firstNameIsRequired": "Vorname ist erforderlich",
  "lastNameIsRequired": "Nachname ist erforderlich",
  "imageUrlIsRequired": "Bildverbindung ist erforderlich",
  "enterValidText": "Geben Sie einen gültigen Text ein",
  "pleaseCheckYourInternetConnection":
      "Bitte überprüfe deine Internetverbindung!",
  "searchForPiesSushiTacos": "Suche nach Kuchen, Sushi, Tacos ...",
  "enterSurname": "Geben Sie den Nachnamen ein",
  "enterStreetAddress": "Geben Sie die Straßenadresse ein",
  "addNew": "Neue hinzufügen",
  "enterAddress1": "Geben Sie die Adresse 1 ein",
  "enterAddress2": "Geben Sie die Adresse 2 ein",
  "noBrandFound": "Keine Marke gefunden",
  "COUPONAPPLIEDSUCCESSFULLYYOUSAVED":
      "Gutschein erfolgreich angewendet. DU HAST GESPEICHERT",
  "ONTHISORDER": "Auf diese Bestellung",
  "areYouSureYouWantToRemove":
      "Sind Sie sich sicher, dass Sie das entfernen wollen",
  "couponCode": "Gutscheincode?",
  "cancel": "Absagen",
  "itSeemsLikeWeHaveNothingToShowForThisBrand":
      "Es scheint, als hätten wir für diese Marke nichts zu zeigen",
  "ifyouwouldlikeUsSendYouTheCollectionFrom":
      "Wenn Sie möchten, dass wir Ihnen die Sammlung aus schicken",
  "plsCreateATicketBelow": "PLS. Erstellen Sie unten ein Ticket",
  "itSeemsLikeWeHaveNothingToShowForThisCategory":
      "Es scheint, als hätten wir für diese Kategorie nichts zu zeigen",
  "enterName": "Name eingeben",
  "description": "Beschreibung",
};
