const Map<String, String> en = {
  "language": "English",
  "appNameText": "Brands and Labels",
  "faqTitle": "FREQUENTLY ASKED QUESTIONS",
  "charityTitle": "Positive Impact + Sustainability",
  "charityContain1":
      "There are still more than a billion people round the world living in extreme poverty on less than \$1.25 a day. In Thailand alone, more than a million members of hill tribes exist on the margins of society - denied citizenship, shut out of the formal job market and vulnerable to exploitation and trafficking.",
  "charityContain2":
      "At Yellow Leaf Hammocks we believe that ethical job creation is an empowering long-term solution to extreme poverty.",
  "charityContain3":
      "Instead of organizing a patchwork of charitable donations to provide water, nutrition, clothing, etc., we are working directly with families to build a comprehensive, dignified, long-term strategy toward a brighter future. The causes behind systemic poverty are complicated, but long-term financial stability is within reach.",
  "charityContain4":
      "To put it simply: By focusing on livelihoods, we can cut out the middle man, get money directly into the hands of smart + resourceful mothers and empower families to tackle their own problems (without being subject to anyone else's agenda).",
  "charityContain5":
      "Across three weaving communities, we are working to create jobs for mothers and build a foundation for positive community transformation. Through flexible, safe “prosperity wage” weaving work, our artisans are able to lift their families from poverty and debt slavery to the middle class.",
  "charityContain6":
      "** Creating jobs for women is especially important to community transformation - research shows that women will spend up to 90% of their earnings on the health, nutrition and education of their families. Turning women into breadwinners improves their status in the community, builds self-esteem and enables them to pool resources to improve infrastructure.",
  "menText": "Men",
  "womenText": "Women",
  "addToCart": "Add To Cart",
  "soldOut": "Sold Out",
  "kidsText": "Kids",
  "signInInfo": "Sign-IN-Information",
  "signUpContain": "Sign Up For Newsletter",
  "details": "Details",
  "description": "Description",
  "estimatedDelivery": "Estimated Delivery",
  "guaranteedDelivery": "Guaranteed Delivery : Nov 04 - Nov 11",
  "sizeChart": "Size Chart",
  "size": "Size",
  "addTOCart": "Add To Cart",
  "addToWishlist": "Add To Wishlist",
  "whyVeraLusso": "WHY VERALUSSO",
  "knowMore": "Know More",
  "applyText": "Apply",
  "recommendation": "Recommendation",
  "recentlyViewed": "Recently Viewed",
  "returnPolicyTitle": "Return Policy",
  "refundTitle": "Refunds",
  "returnProcessTitle": "Returns Process",
  "customisedTitle": "CUSTOMISED, PRE-OWNED & VINTAGE ITEMS",
  "howToReturnTitle": "HOW TO RETURN",
  "returnPolicyContain1":
      "Returned items must comply with our returns policy:\n",
  "returnPolicyContain2":
      'Items must be returned unworn, undamaged and unused, with all tags attached and the original packaging included.',
  "returnPolicyContain3":
      'Footwear and accessories must be returned with the original branded boxes and dust bags, where provided, and placed inside a protective outer box for shipping.',
  "returnPolicyContain4":
      'When trying on footwear, please take care not to mark the soles or damage the shoe box.',
  "returnPolicyContain5":
      'If an item has a Avoirchic security tag or brand tag attached, it must be returned with the tag in its original.',
  "returnPolicyContain6":
      'Beauty and cosmetic products must be returned unopened and unused, with the seals of any packaging still intact.',
  "returnPolicyContain7":
      'Hosiery, lingerie and swimwear items must be returned with the hygiene seals attached and in unopened and undamaged product packaging, where applicable.',
  "returnPolicyContain8":
      'Lingerie and swimwear must only be tried on over your own undergarments. We will not accept any returns that have been worn or are soiled.',
  "returnPolicyContain9":
      'Face masks must be returned unworn in their original, unopened and undamaged product packaging. Jewellery must be returned in the same condition it arrived in, including all branded packaging and documents provided with it.',
  "returnPolicyContain10":
      "Please take care when trying on your purchases and return them in the same condition you received them. Any returns that do not meet our policy will not be accepted.\n",
  "returnPolicyContain11":
      "If you placed an order as a guest, you can start your return here. To return or cancel an item that has been made to your specifications, please view our ‘ Customised Items’ section below for further information.",
  "aboutUsText": "About us",
  "aboutUsTitle": 'WE ARE BRAND & LABELS',
  "aboutUsContain": 'EXPLORE 100’S OF THE WORLDS BEST BRANDS',
  "aboutUsContain1":
      'BRANDS & LABELS IS A TOP ONLINE LUXURY FASHION DESTINATION WITH 5 MILLION VISITORS PER MONTH AND WORLDWIDE SHIPPING.',
  "aboutUsContain2":
      'THE WEBSITE FEATURES THE BEST SELECTION OF THE TOP ESTABLISHED DESIGNERS AS WELL AS YOUNG EMERGING TALENTS. BRANDSLABELS WAS FOUNDED IN FLORENCE IN THE EARLY 1930S, WITH THE OPENING OF THE COMPANY’S EPONYMOUS CONCEPT STORE ON VIA ROMA. ONLINE SINCE 1999, THE COMPANY ATTRIBUTES 90% OF TOTAL REVENUE TO ONLINE SALES. TO THIS DAY IT REMAINS A 100% PRIVATELY OWNED FAMILY BUSINESS, WITH THE FOUNDER’S GRANDSON, ANDREA PANCONESI ACTING AS CEO AND HIS DAUGHTER, ANNAGRETA PANCONESI AS CREATIVE DIRECTOR.',
  "aboutUsContain3":
      'THE SITE OFFERS A WIDE SELECTION OF CLOTHING, SHOES, BAGS, ACCESSORIES, LUXURY HOME INTERIORS AND BEAUTY, WITH PRODUCTS AVAILABLE FOR MEN, WOMEN AND KIDS FROM THE MOST PRESTIGIOUS DESIGNERS SUCH AS BALENCIAGA, VETEMENTS, OFF-WHITE, J.W. ANDERSON,BALMAIN, DOLCE & GABBANA, GUCCI, SAINT LAURENT, VALENTINO, GIVENCHY, LOEWE, JACQUEMUS AND MORE.',
  "aboutUsContain4":
      'THERE ARE CURRENTLY 200 PEOPLE FROM 15 DIFFERENT COUNTRIES THAT WORK TO PRODUCE AND MAINTAIN BRANDSLABELS. THE SITE IS AVAILABLE IN 9 LANGUAGES: ENGLISH, ITALIAN, GERMAN, CHINESE, RUSSIAN, SPANISH, FRENCH, KOREAN AND JAPANESE. THE SITE IS CREATED ENTIRELY IN-HOUSE, WITH THE FLORENCE OFFICE HOUSING GRAPHIC DESIGN, IT, CUSTOMER SERVICE, MARKETING AND BUYING DEPARTMENTS. THE STYLISTS AND PRESS TEAMS OPERATE FROM THE BRANDSLABELS OFFICE IN THE FASHION CAPITAL OF THE WORLD – MILAN.',
  "aboutUsContain5":
      'ALL ORDERS ARE SHIPPED WORLDWIDE FROM THE BRANDS LABELS HEADQUARTERS IN BOXES THAT ARE PREPARED WITH MAXIMUM CARE AND USE THE FINEST MATERIALS, FROM THE SIGNATURE SHOE BAGS TO THE PERSONALIZED RIBBON.',
  "aboutUsContain6":
      'BRANDSLABELS HAD 1.5 MILLION UNIQUE VISITORS ACCESS THE SITE IN 2008 AND HAS GROWN TO 53 MILLION UNIQUE VISITORS IN 2017. MORE THAN 15% OF ONLINE SALES ARE GENERATED FROM THE UNITED STATES, FOLLOWED BY GERMANY, UK, ITALY, CHINA AND FRANCE.',
  "aboutUsContain7":
      'BRANDSLABELS PUSHES THE BOUNDARIES OF THE LUXURY RETAIL LANDSCAPE BOTH ON AND OFFLINE WITH AN ARRAY OF EXCLUSIVE SERVICES AND TRADEMARK INITIATIVES INCLUDING BUY IT FIRST, LUXURY CLUB, SNEAKERS CLUB, LVR PRIVILEGE AND LVR EDITIONS.',
  "profile": "Profile",
  "newsLettersContain": "You Aren't Subscribed To\nOur Newsletter.",
  "edit": "EDIT",
  "newsLetters": "Newsletter",
  "manageAddresses": "Manage Addresses",
  "defaultBillingAddress": "Default Billing Address",
  "editAddress": "Edit Address",
  "defaultShippingAddress": "Default Shipping Address",
  "firstNameText": "First Name",
  "lastNameText": "Last Name",
  "emailText": "E-mail",
  "confirmPasswordAddressText": "Confirm Password",
  "dateOfBirth": "Date of Birth",
  "marriage": "Marriage",
  "ContactNoText": "Contact no.",
  "websiteUrlText": "Website URL",
  "cityText": "City",
  "stateAndProvienText": "State/Provien",
  "countryText": "Country",
  "postCodeText": "Post Code",
  "socialLinksText": "Social links",
  "facebookText": "Facebook",
  "instagramText": "Instagram",
  "twitterText": "Twitter",
  "youtubeText": "Youtube",
  "linkendinText": "Linkendin",
  "pinterestText": "Pinterest",
  "followersText": "Followers",
  "mr": "Mr.",
  "storeCreditText": "My Store Credit",
  "letsText": "Let’s Go",
  "orderIdTitle": '''Your order # is: ''',
  "orderDateTitle": 'Order Date: ',
  "orderNumberTitle": 'Order number: ',
  "orderConfirm": "Thank You For Your Purchase!",
  "name": "Name",
  "sku": "Sku",
  "price": "Price",
  "qty": "Qty",
  "subTotal": "Subtotal",
  "action": "Action",
  "addressBook": "Address Book",
  "billing": "Billing",
  "shipping": "Shipping",
  "myOrdersText": "My Orders",
  "myWishlistText": "My Wish List",
  "wishList": "Wishlist",
  "addAll": "Add All",
  "accountInformationText": "Account Information",
  "myTicketsText": "My Tickets",
  "myAccountText": "My Account",
  "contactInfo": "Contact Information",
  "manageAddress": "Manage Address",
  "newsletters": "Newsletters",
  "myAccountContain": "You aren't subscribed to our newsletter.",
  "changePassword": "Change Password",
  "orderContain":
      'We’ll email you an order confirmation with details and tracking info.',
  "referFriendText": "Refer Friend",
  "returnsRefundsText": "Returns & Refunds",
  "faqText": "FAQ",
  "contactText": "Contact",
  "socialText": "Social",
  "companyText": "Company",
  "myOrders": "My Orders",
  "myOrderImage": "Image",
  "productName": "Product Name",
  "quantity": "Qty",
  "status": "Status",
  "paymentMethod": " Payment Method",
  "shippingAddress": "Shipping Address",
  "billingAddress": "Billing Address",
  "continueShopping": "Continue Shopping",
  "generalAndOrderEnquiriesText": "GENERAL & ORDER ENQUIRIES",
  "gdpText": "GDP",
  "engText": "ENG",
  "nameText": "Name*",
  "surNameText": "Surname*",
  "emailAddressText": "Email Address*",
  "confirmEmailAddressText": "Confirm Email Address*",
  "subjectText": "Subject*",
  "phoneNumberText": "Phone Number",
  "whatsOnYourMindText": "What’s on your mind?*",
  "queryDescription":
      "Whatever your query,use the contact form below to get in touch,Our team is ready to help 24/7",
  "submitText": "Submit",
  "typeOfEnquiryText": "Type Of Enquiry*",
  "registeredCustomersText": "Registered Customers",
  "signInDescriptionText":
      "If You Have An Account, Sign In With Your\nEmail Address.",
  "forgotYourPasswordText": "Forgot Your Password?",
  "signInText": "Sign In",
  "newCustomersText": "New Customers",
  "newCustomersDescriptionText":
      "Creating An Account Has Many Benefits:\nCheck Out Faster, Keep More Than One Address,\nTrack Orders And More.",
  "createAccountText": "Create An Account",
  "aboutProjectNameText": "About Brands and Labels",
  "helpAndInformationText": "Help and Information",
  "moreFromProjectText": "More From Brands&Labels",
  "newsLetterText": "NewsLetter",
  "subscribeText": "Subscribe",
  "passwordText": "Password",
  "accessYourAccountDetailsText": "Access Your Account Details And Rewards",
  "signUpText": "Sign Up",
  "loginMyAccountText": "Login",
  "myOrderText": "My Orders",
  "addressBookText": "Address Book",
  "trackOrderText": "Track Order",
  "careersText": "Careers",
  "helpTheNeedyText": "Help The Needy",
  "secureShoppingText": "Secure Shopping",
  "influencerRegistrationText": "Influencer Registration",
  "affiliateText": "Affiliate Program",
  "advancedSearchText": "Advanced Search",
  "privacyPolicyText": "Privacy Policy",
  "termsConditionsText": "Terms & Conditions",
  "aboutText": "About",
  "aboutUsMyAccountText": "About Us",
  "referFriendMyAccountText": "Refer A Friend And Earn Discount",
  "returnsText": "Returns And Refunds",
  "contactUsText": "Contact Us",
  "faqMyAccountText": "Faq",
  "liveChatText": "Live Chat",
  "startChatText": "Start the chat",
  "accountText": "Account",
  "giftVouchersText": "Gift Vouchers",
  "ourSocialInitiativeText": "Our Social Initiative",
  "bloggerRegistrationText": "Blogger Registration",
  "addressesText": "Addresses",
  "billingText": "Billing",
  "shippingText": "Shipping",
  "aboutBrandsTxxt": "About Brands And Labels",
  "helpAndInfoText": "Help and Information",
  "morefromBrandsText": "More from Brands&Labels",
  "newsletterText": "NEWSLETTER",
  "chooseCountryText": "Choose Your Country",
  "saveAddressText": "Save Address",
  "onSocialText": "Our Social Initiatives",
  "bloggerText": "Blogger Registration",
  "referText": "Refer A Friends And Earn Discounts",
  "getAllText":
      "Get all the latest information on Event, Sales and Offers. Sign",
  "exploreText": "Explore 100’s of Brands at Special Prices",
  "yourAppExpericanceText": "Your app experience is set to",
  "indiaText": "INDIA (IND) - ENGLISH (IND)",
  "englishIsAlsoText":
      "ENGLISH is also available in your\nlocation. Would you like to change?",
  "noThanksText": "No, Thanks",
  "changeText": "CHANGE",
  "myWidhListText": "My Wish List",
  "accountInfoText": "Account Information",
  "storePaymentText": "Store Payment Methods",
  "newsletterSubText": "Newsletter Subscriptions",
  "youaddCartText": "You have added",
  "toShoopingCartText": "to shopping cart.",
  "gotoCartText": "Go To The Cart",
  "continueShoppingText": "Continue Shopping",
  "totalText": "Total",
  "itemCartText": "Items In your cart",
  "affiliateProgramTitleText": "Brand&Labels Affiliate Program",
  "whoAreWeLookingTitleText": "Who are we looking for?",
  "whoAreWeLookingDescriptionOneText":
      "Do you have a fashion-forward, luxury oriented website, blog, social media profile that is trend savvy with an international outlook? Is your focus fashion, lifestyle, beauty and design? If so, we are looking for you!\n\nJoin our global Affiliate Program and you will have the opportunity to earn a commission every time your visitors purchase from BRAND&LABELS.",
  "whatCanYouExpectTitleText": "What can you expect?",
  "expectRuleOneText": "Commission on all approved net sales",
  "expectRuleTwoText": "45 days cookie window",
  "expectRuleThreeText": "Data feed updated multiple times per day",
  "expectRuleFourText":
      "Access to customized banners, textlinks, deeplinks and our datafeed in 9 languages (English, Italian, French, German, Korean, Spanish, Chinese,Russian & Japanese)",
  "expectRuleFiveText":
      "The possibility to customize feeds into all world currencies",
  "promoteSoloQuestionText":
      "How can you promote BRAND&LABELS (as an affiliate)?",
  "promoteSoloAnswerOneText":
      "Creating high-quality and engaging content that mirrors the style of BRAND&LABELS",
  "promoteSoloAnswerTwoText":
      "Featuring our content, banners and links for multiple categories and events on your website and social media channels",
  "promoteSoloAnswerThreeText":
      "Promoting the benefits that our customers love",
  "promoteSoloAnswerFourText":
      "A selection of continuously updated articles from the best brands",
  "promoteSoloAnswerFiveText":
      "Free returns with no added taxes for the US, Canada, the UK and ",
  "howApplyTitleText": "How to apply?",
  "howApplyAnswerOneText":
      "Email us the name and URL of your website, blog or social media profile and your main markets. We’ll review your site and get back to you with further information on how to join the affiliate program.\n\nPlease note that all applications are manually evaluated and processing may take up to 10 days.\n\nIf you feel your application has been wrongfully declined please contact affiliates@brands&labels.com and a member of the team will address your concerns.",
  "visitorMonthHintText": "Select Unique Visitors/Month",
  "viewsMonthHintText": "Select Page Views/Month",
  "cityHintText": "City",
  "countryHintText": "Country",
  "addressOneText": "Street Address 1",
  "addressTwoText": "Street Address 2",
  "addressThreeText": "Street Address 3",
  "addressText": "Address",
  "letsGoText": "Let's Go",
  "homeText": "Home",
  "searchText": "Search",
  "designersText": "Designers",
  "wishListText": "WishList",
  "loginText": "Login",
  "yourEmailText": "Your E-Mail",
  "checkoutText": "Checkout",
  "purchaseText": "Please Enter Your Details Below To Complete Your Purchase",
  "shippingAddressText": "Shipping Address",
  "shippingMethodText": "Shipping Method",
  "paymentMethodText": "Payment Method",
  "orderSummaryText": "Order Summary",
  "newAddressText": "New Address",
  "itemInCartText": "Item in Cart",
  "qtyText": "Qty",
  "applyDiscountCodeText": "Apply Discount Code",
  "enterDiscountCodeText": "Enter Discount Code",
  "applyDiscountText": "Apply Discount",
  "orderTotalText": "Order Total",
  "orderCommentText": "Order Comment",
  "placeOrderText": "PLACE ORDER",
  "newsLetter1Text": "NEWSLETTER SUBSCRIPTIONS",
  "welcometoChatText": "Welcome to our LiveChat!",
  "fillTheFormText": "Please fill in the form below before starting the chat.",
  "nameChatText": "Name",
  "deliveryText": "Delivery",
  "ordersText": "Order",
  "paymentText": "Payment",
  "productText": "Product",
  "promotionText": "Promotion",
  "returnsContactText": "Returns",
  "technicalText": "Technical",
  "whatsonyourmindText": "What's On Your Mind?",
  "orderenquiriesText": "General & Order Enquiries",
  "selectLangCurrText": "Select Language & Currency",
  "selectLangCurrDescText":
      "Please choose from the following Language and currency options available in your country Language",
  "saveText": "Save",
  "cancelText": "Cancel",
  "languageText": "Language",
  "currencyText": "Currency",
  "idText": "ID",
  "notifyMe": "Notify Me When Available",
  "actionText": "Action",
  "specialSizeText": "Special Size Requests",
  "priceText": "Price",
  "filtersText": "Filters",
  "colorText": "Color",
  "brandText": "Brand",
  "sizeText": "Size",
  "applyFilterText": "Apply",
  "enterEmail": "Enter Your Email",
  "resetPassword": "Reset My Password ",
  "forgetPasswordContain1":
      "Please Enter Your Email Address Below To Receive A Password Reset Link",
  "forgetPassword": "Forgot Your Password?",
  "backToSignInScreen": "Back to sign in screen",
  "forgetPasswordContain":
      "We Have Sent You A Password Reset Link\n This Link Is Valid For 2 Hours \n If You Did Not Make This Request\n You Can Ignore This Email \n Please Check Your Spam Folder\n If You Do Not Receive The Email \n For Any Assistance Please",
  "shippingCart": "Shopping Cart",
  "itemText": "Item",
  "subTotalText": "Subtotal",
  "updateCartText": "Update Cart",
  "cartSummaryTxet": "Cart Summary",
  "taxText": "Tax",
  "gotoCheckOutText": "Go to CheckOut",
  "checkOutMultipleAddressText": "Check Out with Multiple Addresses",
  "aboutBrandsAndText": "About Brands and Labels",
  "helpandInfoText": "Help and Infomation",
  "morefromBrandslabelsText": "More From Brands&Labels",
  "newsltterText": "Newsletter",
  "emailAddreessText": "Email Address",
  "policyHomeText": "HOME",
  "policyText": "PRIVACY POLICY",
  "policyHeadingText": "Brands & Labels Group Privacy Policy",
  "logOutText": "LogOut",
  "gotoWishListText": "Go To The Wishlist",
  "reasonReturnText": "Reason to return",
  "returnItemText": "Return ltem",
  "returnText": "Return",
  "returnRequestText": "Return Request Received",
  "teamSoloLuxuryText": "Team Solo Luxury.",
  "shipHereText": "Ship Here",
  "saveInAddressBookText": "Save in address book",
  "specialSizeSelectSizeText": "Select Size",
  "checkYourOrderText": "Check your order",
  "enterYourOrderText":
      "Enter your order reference and email address below to see your order details. From there you can check its shipping status,cancel items or make a return.",
  "howDoIFindText": "How do i find my",
  "orderRefernceText": "Order reference?",
  "wehaveRecivedText":
      "We have received your request and your request Id is - Please Check the status of your request at @@@@. contact us at care@sololuxury.com - for any query with regards to request.",
  "myBillingShipAddressSameText":
      "My Billing and Shipping Address are the same",
  "testDonationText": "Test Donation Two",
  "youAddedTestText":
      "You added Test Donation your shopping cart.\nThe page will be refreshed.",
  "chooseYourOwmText": "Choose your own Amount GBP(minimum €1)",
  "theSelectedAmountText":
      "The selected amount will be added to your\nshopping cart.",
  "iwantToDonateText": "i want to donate this amount",
  "e5Text": "£ 5",
  "e10Text": "£ 10",
  "e15Text": "£ 15",
  "e20Text": "£ 20",
  "e25Text": "£ 25",
  "gbpText": "GBP",
  "cartContain1": "Support a charity with your docation",
  "cartContain2":
      "15% of the order value will be donated by\nBrands&Labels for donations.",
  "cartContain3": "Please click here to donate now.",
  "cartContain4": "I WANT TO DONATE",
  "cartContain5": "Check Out with Multiple Addresses",
  "myCouponsText": "My Coupons",
  "searchCountry": "Search country",
  "brandName": "Brand Name",
  "style": "Style",
  "keyword": "Keyword",
  "imageURL": "Image URL",
  "remark": "Remark",
  "accountDoesNotExist": "Account Does Not Exist",
  "forgotPasswordWrongEmailStart": "There is no Account Associated",
  "forgotPasswordWrongEmailEnd": "you need any further assistance please",
  "WriteAt": "Write to us at",
  "trackYourTicketByEmail": "Track Your Ticket By Email",
  "trackYourRequests": "Track Your Requests",
  "viewCartText": "View Cart",
  "with": "with",
  "pleaseCheckYourInbox": "Please Check Your Inbox",
  "track_your_order": "Track Your Order",
  "thankYou": "Thank You",
  "notifyMeWhenThisProductIsInStock":
      "We Will Inform You Once The Product Is In Stock. You Can Also View The Status Of Your Request On",
  "myTicket": "My Tickets.",
  "enterEmailAddress": "Enter Email Address",
  "enterConfirmEmailAddress": "Enter ConfirmEmail Address",
  "enterPhoneNumber": "Enter Phone Number",
  "enterValidEmailAddress": "Enter Valid Email Address",
  "confirmEmailNotMatch": "Confirm Email Not Match To Email Address",
  "phoneNumberIsRequired": "Phone number is Required",
  "phoneNumberIsNotValid": "Phone number is not valid",
  "gstIdentificationNumber":
      "GST Identification Number is not valid. It should be in this 11AAAAA1111Z1A1 format",
  "emailRequired": "Email is Required",
  "invalidEmail": "Invalid Email",
  "confirmEmailIsRequired": "Confirm Email is Required",
  "confirmEmailShouldBeMatchWithEmail":
      "Confirm email should be match with email",
  "youHaveReachedYourMaximumLimit":
      "You have reached your maximum limit of characters allowed",
  "passwordIsRequired": "Password is Required",
  "successfullyLoggedOut": "You Have Been Successfully Logged Out",
  "emailAddress": "E-Mail Address",
  "enterEmailToTrackRequest.": "Please Enter Your Email To Track Your Request.",
  "lastName": "Last Name",
  "dateOfBirth.": "Date of Birth",
  "dateOfMarriage": "Marriage Anniversary",
  "signUpForNewsletter": "Sign Up for Newsletter",
  "email": "Email",
  "password": "Password",
  "confirmPassword": "Confirm Password",
  "typesOfEnquiry": "Types of Enquiry",
  "confirmPasswordIsRequired.": "ConfirmPassword Is Required",
  "orderDetails": "Order Details",
  "noDataAvailable": "No Data Available",
  "myAccount": "My Account",
  "mrs": "Mrs.",
  "communicationPrefences.": "Communication Preferences",
  "subscribeNewsletters": "Subscribe to ounass newsletters..",
  "aboutUs": "About Us",
  "sms": "Sms",
  "save": "Save",
  "tearmsAndCondition": "TERMS AND CONDITION",
  "subscribeOffersAndMore":
      "Subscribe to be the first with our new arrivals,exclusive collections, offers and more.",
  "ourServices": "Our Services",
  "delivery": "Delivery",
  "ourWebsite": "Our Website",
  "subscribe": "Subscribe",
  "productDetails": "Product Details",
  "priceMatch": "Price Match",
  "composition": "Composition",
  "color": "Color",
  "chooseAnOption": "Choose An Option...",
  "buyNow": "Buy Now",
  "notifyMeWhenThisProductIsInStock1":
      "Notify Me When This Product Is In Stock ",
  "yourBestPriceAlways": "Your Best Price - Always.",
  "IfYourPreferredItemIsLowerMsg":
      "If your preferred item is lower priced at any other store at the current time we will match the price and offer you 10% additional store credit for your next purchase.",
  "simplyLetUsKnowByClickingHere": "Simply let us know by clicking here.",
  "alreadyMadeYourPurchase": "Already Made your purchase.",
  "dontWorryLetUsKnowByClickingMsg":
      "Dont worry let us know by clicking here and we our customer support team will refund you the difference if the purchase was made within the last 30 days.",
  "pleaseSeeFAQsByClickingHere": "Please See FAQs By Clicking Here",
  "filter": "Filter",
  "sort": "Sort",
  "sortBy": "Sort by",
  "noProductsFound": "No Products Found",
  "createTicket": "Create Ticket",
  "more": "& More...",
  "bgbp": "GBP",
  "findBrand": "Find Brands",
  "itSeemsWeHaveNothingToShowFor": "It Seems We Have Nothing To Show For ",
  "ifYouWouldLikeToHaveMoreInformationAbout":
      "If You Would Like To Have More Information About ",
  "thenPleaseCreateATicket": "Then Please Create A Ticket",
  "contactInformation": "Contact Information",
  "youHaveNoProductsInYourWishList": "You Have No Products In Your Wish List.",
  "toBbeUpdated": "To be updated",
  "youHaveNoSavedAddressAddnewAddressToContinueWithCheckout":
      "You have no Saved Address Add new Address to continue with Checkout",
  "shipHere": "Ship Here",
  "enterFirstName": "Enter First Name",
  "enterLastName": "Enter Last Name",
  "enterStreetAddress1": "Enter Street Address 1",
  "streetAddress1": "Street Address 1",
  "enterStreetAdress2": "Enter Street Adress 2",
  "streetAddress2": "Street Address 2",
  "enterStreetAddress3": "Enter Street Address 3",
  "streetAddress3": "Street Address 3",
  "enterCityName": "Enter City Name",
  "city": "City",
  "country": "Country",
  "enterZipPostalCode": "Enter Zip Postal Code",
  "zipPostalCode": "Zip/Postal Code",
  "stateProvince": "State/Province",
  "enterStateProvince": "Enter State/Province",
  "emailAddressRequired": "Email Address required",
  "cancelCoupon": "Cancel Coupon",
  "apply": "Apply",
  "viewCouponList": "View Coupon List",
  "coupons": "Coupons",
  "changeLanguageAndCurrency": "Change language and Currency",
  "youHaveNoOrders": "You Have No Orders",
  "youHaveNoTickets": "You Have No Tickets",
  "category": "Category",
  "createNewTicket": "Create New Ticket",
  "positiveImpactSustainability": "Positive Impact + Sustainability",
  "thereAreStillMoreThanMSG":
      "There are still more than a billion people round the world living in extreme poverty on less than \$1.25 a day. In Thailand alone, more than a million members of hill tribes exist on the margins of society - denied citizenship, shut out of the formal job market and vulnerable to exploitation and trafficking.",
  "atYellowLeafHammocksMsg":
      "At Yellow Leaf Hammocks we believe that ethical job creation is an empowering long-term solution to extreme poverty.",
  "insteadOfOrganizingMsg":
      "Instead of organizing a patchwork of charitable donations to provide water, nutrition, clothing, etc., we are working directly with families to build a comprehensive, dignified, long-term strategy toward a brighter future. The causes behind systemic poverty are complicated, but long-term financial stability is within reach.",
  "toPutItSimplyMsg":
      "To put it simply: By focusing on livelihoods, we can cut out the middle man, get money directly into the hands of smart + resourceful mothers and empower families to tackle their own problems (without being subject to anyone else's agenda).",
  "acrossThreeWeavingCommunitiesMsg":
      "Across three weaving communities, we are working to create jobs for mothers and build a foundation for positive community transformation. Through flexible, safe “prosperity wage” weaving work, our artisans are able to lift their families from poverty and debt slavery to the middle class.",
  "creatingJobsForWomenMsg":
      "** Creating jobs for women is especially important to community transformation - research shows that women will spend up to 90% of their earnings on the health, nutrition and education of their families. Turning women into breadwinners improves their status in the community, builds self-esteem and enables them to pool resources to improve infrastructure.",
  "theFoundationForABrighterFuter": "The Foundation For a Brighter Futer",
  "theSecurityOfAStableMsg":
      "The security of a stable, growing revenue source had a tremendous impact on the village. The Mlabri were able to start a school and build a community center for weaving and socializing. They established one of Thailand’s first unemployment funds. With increased economic power, they successfully lobbied for citizenship and civil rights, which they were first granted in 2001. Hammock weaving is flexible work, ideal for mothers who can work from home and make their own schedules. Unfortunately, without access to global markets, the demand for hammocks was limited to the Thai tourism season and there was no way to ensure year-round employment.",
  "spreadingLastingChangeTheHammockRrevolution":
      "Spreading Lasting Change: The Hammock Rrevolution",
  "thisIsAboutWhereMsg":
      "THIS IS about where Yellow Leaf joins the story! Over the past few years, we have worked to develop consistent sales channels, build international partnerships and stabilize operations within the villages.",
  "corollaryEconomicMsg":
      "Corollary economic opportunities, like a post office, food preparation and sustainable coffee farming have sprung up to employ those who are not weaving. Our partnership with Kiva has spurred financial training and financial planning, with many weavers opening bank accounts for the first time in their lives!",
  "wWithOurGrowthMsg":
      "With our growth continuing to accelerate, we will not only be able to employ all Mlabri weavers year-round, we will also be able to continue to expand and provide training and ongoing employment to hill tribe communities in the surrounding region. Until weaving work and sustainable jobs are available throughout the area, destructive agricultural practices will continue and the exploitative cycle of indentured servitude will not truly end.",
  "throughTheEstablishmentMsg":
      "Through the establishment of Yellow Leaf as a global lifestyle brand, the hill tribe villages we partner with will be able to sustain this positive impact and continue to lay the foundation for a brighter future.",
  "enterWebsite": "Enter Website",
  "enterPostCode": "Enter Post Code",
  "thankYouForYourInterest":
      "Thank you for your Interest in working with Brands-Labels",
  "oneOfOurTeamMembersWillBeInTouchSoon":
      "One of our team members will be in touch soon",
  "forAnyAdditionalQueriesPleaseWriteTo ":
      "For any additional queries please write to ",
  "theProductIsOutOfStock": "The product is out of stock.",
  "whateverYourQueryUseTheContactFormBelowMsg":
      "Whatever Your Query. Use The Contact Form Below To Get In Touch-OurTeam Is Ready To Help 24*7",
  "enterSubject": "Enter Subject",
  "enterSomeText": "Enter Some Text",
  "enterDetailsBelowToSend":
      "Enter Details Below To Send A 10% Coupon Code To Your Friend",
  "enterFriendName": "Enter Friend Name",
  "friendFirstName": "Friend First Name",
  "enterFirstEmailAddress": "Enter First Email Address",
  "friendEmailAddress": "Friend Email Address",
  "enterFirstPhoneNumber": "Enter First Phone Number",
  "friendPhoneNumber": "Friend Phone Number",
  "register": "Register",
  "dateOfBirthIsRequired": "DateOfBirth Is Required",
  "marriageAnniversaryIsRequired": "Marriage Anniversary Is Required",
  "surnameIsRequired": "Surname Is required",
  "date": "Date",
  "showDialog": "Show Dialog",
  "removeProduct": "Remove Product",
  "areYouSureWantToRemoveThisProductFromCart":
      "Are you sure want to remove this product from cart?",
  "yes": "YES",
  "no": "NO",
  "onceYouAddThisProductToWishlistThenItWillBeRemoveFromAart":
      "Once you add this product to wishlist then it will be remove from cart",
  "ok": "OK",
  "nouHaveNoItemsInYourShoppingCart":
      "You have no items in your shopping cart.",
  "Discount": "Discount",
  "enterCouponCode": "Enter Coupon Code",
  "removeCoupon": "Remove Coupon",
  "availableCouponList": "Available Coupon List",
  "allCouponsList": "All Coupons List",
  "addProductToYourWishList": "Add product to your wishList",
  "configurable": "configurable",
  "Missing": "Missing",
  "Amount": "Amount",
  "Balance": "Balance",
  "Remarks": "Remarks",
  "myAddresses": "My Addresses",
  "noAddressFound": "No address found",
  "addAddress": "Add Address",
  "updateAddress": "Update Address",
  "expectedShipmentDate": "Expected Shipment Date",
  "brandNameIsRequired": "Brand Name is Required",
  "styleIsRequired": "Style is Required",
  "keywordIsRequired": "Keyword is Required",
  "remarkIsRequired": "Remark is Required",
  "couponId": "Coupon Id",
  "couponName": "Coupon Name",
  "expireAt": "Expire At",
  "noCouponsFound": "No Coupons Found!",
  "yourRequestHasBeenReceived": "Your Request Has Been Received.",
  "youCanViewYourRequestsatMyTickets":
      "You Can View Your Requests at My Tickets",
  "incorrectPassword": "Incorrect Password",
  "thePasswordYouenteredisincorrectPleasetryagain":
      "The password you entered is incorrect. Please try again",
  "registeredCustomers": "Registered Customers",
  "ifYouHaveAnAccountSignInWithYourEmailAddress":
      "If You Have An Account, Sign In With Your Email Address",
  "pleaseEnterOrderNumberToTrackYourOrder":
      "Please Enter Order Number To Track Your Order.",
  "enterOrderNumber": "Enter Order Number",
  "enteryOurOrderNumberHere": "Enter your order number here",
  "howDoIFindMyOrderReference": "How Do I Find My Order Reference?",
  "passwordRegExp":
      "The password must be at least 8 characters long and contain a mixture of both uppercase and lowercase letters, at least one number and one special character (e.g.,! @ # ?).",
  "nylonMessengerBackpackMsg":
      "Nylon Messenger Backpack By Balenziaga, Front Closure With Hook, Top Handle, Adjustable Shoulder Straps, Front Patch Zip Pocket With Contrast Logo, Hooks As Decorative Elements.",
  "priceMatchTicket": "Price Match Ticket",
  "enterAddress3": "Enter Address 3",
  "enterCity": "Enter City",
  "pleaseTryWithAnotherEmaiAddressMsg":
      "Please Try With Another Email Address Or Write To Us At care@brandslabels.com For Further Assistance.",
  "Alert": "Alert",
  "requiredVal": "is Required",
  "mustbeof": "must be of",
  "digits": "digits",
  "mustbeanumberExample100": "must be a number. Example: 100",
  "character": "character",
  "isinvalid": "is invalid!",
  "mustbemorethan2characters": "must be more than 2 characters",
  "entervalid": "Enter valid",
  "musthaveatleast2characters": "must have at least 2 characters",
  "confirmpasswordshouldbematchwithpassword":
      "Confirm password should be match with password",
  "pleaseenterPassword": "Please enter Password",
  "mustbemorethan8characters": "Must be more than 8 characters",
  "mobileisRequired": "Mobile is Required",
  "mobilenumbermust10digits": "Mobile number must 10 digits",
  "mobileNumbermustbedigits": "Mobile Number must be digits",
  "yearmustbenumberonly": "Year must be number only",
  "establishedYearisRequired": "Established Year is Required",
  "yearmustbebetween1850and": "Year must be between 1850 and",
  "licenseNoisRequired": "License No is Required",
  "numberofemployeeisRequired": "Number of employee is Required",
  "numberofemployeeisnotmorethan9999":
      "Number of employee is not more than 9999",
  "numberofemployeemustbedigits": "Number of employee must be digits",
  "dateisRequired": "Date is Required",
  "pleaseentervaliddate": "Please enter valid date",
  "licenseIssuingAuthorityisRequired": "License Issuing Authority is Required",
  "licenseIssuingAuthoritymustbeazandAZ":
      "License Issuing Authority must be a-z and A-Z",
  "firstNameIsRequired": "First Name is Required",
  "lastNameIsRequired": "Last Name is Required",
  "imageUrlIsRequired": "Image link is Required",
  "enterValidText": "Enter Valid Text",
  "pleaseCheckYourInternetConnection": "Please check your internet connection!",
  "searchForPiesSushiTacos": "Search for Pies, Sushi, Tacos...",
  "enterSurname": "Enter Surname",
  "enterStreetAddress": "Enter Street Address",
  "addNew": "Add New",
  "enterAddress1": "Enter Address 1",
  "enterAddress2": "Enter Address 2",
  "noBrandFound": "No Brand found",
  "COUPONAPPLIEDSUCCESSFULLYYOUSAVED": "COUPON APPLIED SUCCESSFULLY. YOU SAVED",
  "ONTHISORDER": "ON THIS ORDER",
  "areYouSureYouWantToRemove": "Are you sure you want to remove",
  "couponCode": "coupon code?",
  "cancel": "Cancel",
  "itSeemsLikeWeHaveNothingToShowForThisBrand":
      "It Seems Like We Have Nothing To Show For This Brand",
  "ifyouwouldlikeUsSendYouTheCollectionFrom":
      "If you would like us send you the collection from",
  "plsCreateATicketBelow": "pls. Create a ticket below",
  "itSeemsLikeWeHaveNothingToShowForThisCategory":
      "It Seems Like We Have Nothing To Show For This Category",
  "enterName": "Enter Name",
};
