const Map<String, String> es = {
  "language": "inglés",
  "appNameText": "Marcas y Etiquetas",
  "aboutUsText": "Sobre nosotros",
  "aboutUsTitle": 'SOMOS MARCA Y ETIQUETAS',
  "aboutUsContain": 'EXPLORA 100 DE LAS MEJORES MARCAS DEL MUNDO',
  "aboutUsContain1":
      'BRANDS & LABELS ES UN PRINCIPAL DESTINO DE MODA DE LUJO EN LÍNEA CON 5 MILLONES DE VISITANTES AL MES Y ENVÍOS A TODO EL MUNDO.',
  "aboutUsContain2":
      'EL SITIO WEB CUENTA CON LA MEJOR SELECCIÓN DE LOS MEJORES DISEÑADORES ESTABLECIDOS ASÍ COMO DE JÓVENES TALENTOS EMERGENTES. BRANDSLABELS SE FUNDÓ EN FLORENCIA A PRINCIPIOS DE LA DÉCADA DE 1930, CON LA APERTURA DE LA TIENDA CONCEPTUAL DEL mismo nombre DE LA COMPAÑÍA EN VIA ROMA. EN LÍNEA DESDE 1999, LA COMPAÑÍA ATRIBUYE EL 90% DEL TOTAL DE INGRESOS A LAS VENTAS EN LÍNEA. A HOY SIGUE SIENDO UNA EMPRESA FAMILIAR DE PROPIEDAD 100% PRIVADA, CON EL NIETO DEL FUNDADOR, ANDREA PANCONESI COMO DIRECTOR GENERAL Y SU HIJA, ANNAGRETA PANCONESI COMO DIRECTORA CREATIVA.',
  "aboutUsContain3":
      'EL SITIO OFRECE UNA AMPLIA SELECCIÓN DE ROPA, ZAPATOS, BOLSOS, ACCESORIOS, INTERIORES DE LUJO PARA EL HOGAR Y BELLEZA, CON PRODUCTOS DISPONIBLES PARA HOMBRES, MUJERES Y NIÑOS DE LOS DISEÑADORES MÁS PRESTIGIOSOS COMO BALENCIAGA, VETEMENTS, OFF-WHITE, J.W. ANDERSON,BALMAIN, DOLCE & GABBANA, GUCCI, SAINT LAURENT, VALENTINO, GIVENCHY, LOEWE, JACQUEMUS Y MÁS.',
  "aboutUsContain4":
      'ACTUALMENTE HAY 200 PERSONAS DE 15 PAÍSES DIFERENTES QUE TRABAJAN PARA PRODUCIR Y MANTENER MARCAS. EL SITIO ESTÁ DISPONIBLE EN 9 IDIOMAS: INGLÉS, ITALIANO, ALEMÁN, CHINO, RUSO, ESPAÑOL, FRANCÉS, COREANO Y JAPONÉS. EL SITIO ESTÁ CREADO TOTALMENTE EN LA CASA, CON LOS DEPARTAMENTOS DE DISEÑO GRÁFICO DE LA VIVIENDA DE LA OFICINA DE FLORENCIA, TI, SERVICIO AL CLIENTE, MARKETING Y COMPRAS. LOS EQUIPOS DE ESTILISTAS Y PRENSA OPERAN DESDE LA OFICINA DE MARCAS EN LA CAPITAL MUNDIAL DE LA MODA: MILÁN.',
  "aboutUsContain5":
      'TODOS LOS PEDIDOS SE ENVÍAN A TODO EL MUNDO DESDE LA SEDE CENTRAL DE BRANDS LABELS EN CAJAS PREPARADAS CON EL MÁXIMO CUIDADO Y UTILIZANDO LOS MEJORES MATERIALES, DESDE LAS BOLSAS DE ZAPATOS DE FIRMA HASTA LA CINTA PERSONALIZADA.',
  "aboutUsContain6":
      'BRANDSLABELS TUVO 1,5 MILLONES DE VISITANTES ÚNICOS QUE ACCEDIERON AL SITIO EN 2008 Y HA CRECIDO A 53 MILLONES DE VISITANTES ÚNICOS EN 2017. MÁS DEL 15 % DE LAS VENTAS EN LÍNEA SE GENERAN EN LOS ESTADOS UNIDOS, SEGUIDOS POR ALEMANIA, REINO UNIDO, ITALIA, CHINA Y FRANCIA.',
  "aboutUsContain7":
      'BRANDSLABELS EMPUJA LOS LÍMITES DEL PANORAMA DE LA VENTA AL POR MENOR DE LUJO TANTO EN INTERNET COMO FUERA DE LÍNEA CON UNA GAMA DE SERVICIOS EXCLUSIVOS E INICIATIVAS DE MARCAS COMERCIALES QUE INCLUYEN BUY IT FIRST, LUXURY CLUB, SNEAKERS CLUB, LVR PRIVILEGE Y LVR EDITIONS.',
  "profile": "Perfil",
  "firstNameText": "Primer nombre",
  "lastNameText": "Apellido",
  "emailText": "Correo electrónico",
  "ContactNoText": "Número de contacto",
  "websiteUrlText": "URL del sitio web",
  "cityText": "Ciudad",
  "countryText": "País",
  "postCodeText": "Código postal",
  "socialLinksText": "Vínculos sociales",
  "facebookText": "Facebook",
  "instagramText": "Instagram",
  "twitterText": "Gorjeo",
  "youtubeText": "YouTube",
  "linkendinText": "Linkendín",
  "pinterestText": "Pinterest",
  "followersText": "Seguidores",
  "mr": "Señor.",
  "letsText": "Vamos",
  "orderIdTitle": '''Su orden # es: ''',
  "orderDateTitle": 'Fecha de pedido: 15 de septiembre de 2021',
  "orderNumberTitle": 'NÚMERO DE PEDIDO: ',
  "orderConfirm": "¡GRACIAS POR SU COMPRA!",
  "name": "NOMBRE",
  "sku": "SKU",
  "price": "PRECIO",
  "qty": "CANTIDAD",
  "subTotal": "TOTAL PARCIAL",
  "action": "ACCIÓN",
  "addressBook": "Directorio",
  "billing": "Facturación",
  "shipping": "Transporte",
  "orderContain":
      'Le enviaremos por correo electrónico una confirmación del pedido con los detalles y la información de seguimiento.',
  "referFriendText": "Recomendar amigo",
  "returnsRefundsText": "Devoluciones y reembolsos",
  "faqText": "Preguntas más frecuentes",
  "contactText": "Contacto",
  "socialText": "Social",
  "companyText": "Compañía",
  "myOrders": "Mis ordenes",
  "myOrderImage": "Imagen",
  "productName": "nombre del producto",
  "quantity": "Cantidad",
  "status": "Estado",
  "paymentMethod": " Método de pago",
  "shippingAddress": "Dirección de envío",
  "billingAddress": "Dirección de Envio",
  "continueShopping": "Seguir comprando",
  "generalAndOrderEnquiriesText": "CONSULTAS GENERALES Y DE PEDIDOS",
  "gdpText": "PIB",
  "engText": "ESP",
  "nameText": "Nombre*",
  "surNameText": "Apellido*",
  "emailAddressText": "Dirección de correo electrónico*",
  "confirmEmailAddressText": "Confirmar el correo*",
  "subjectText": "Tema*",
  "phoneNumberText": "Número de teléfono",
  "whatsOnYourMindText": "¿Qué tienes en mente?*",
  "queryDescription":
      "Cualquiera que sea su consulta, utilice el formulario de contacto a continuación para ponerse en contacto. Nuestro equipo está listo para ayudarlo las 24 horas del día, los 7 días de la semana.",
  "submitText": "ENVIAR",
  "typeOfEnquiryText": "Tipo de Consulta*",
  "registeredCustomersText": "Clientes Registrados",
  "signInDescriptionText":
      "Si tiene una cuenta, inicie sesión con su\ndirección de correo electrónico.",
  "forgotYourPasswordText": "¿Olvidaste tu contraseña?",
  "signInText": "Iniciar sesión",
  "newCustomersText": "nuevos clientes",
  "newCustomersDescriptionText":
      "Crear una cuenta tiene muchos beneficios:\npague más rápido, mantenga más de una dirección,\nseguimiento de pedidos y más.",
  "createAccountText": "Crea una cuenta",
  "aboutProjectNameText": "Sobre Marcas y Etiquetas",
  "helpAndInformationText": "Ayuda e Información",
  "moreFromProjectText": "Más de Marcas y Etiquetas",
  "newsLetterText": "Boletin informativo",
  "subscribeText": "Suscribir",
  "passwordText": "Clave",
  "homeText": "Casa",
  "searchText": "Búsqueda",
  "designersText": "Diseñadores",
  "wishListText": "lista de deseos",
  "loginText": "Acceso",
  "myAccountText": "Mi cuenta",
  "yourEmailText": "Tu correo electrónico",
  "checkoutText": "Verificar",
  "purchaseText": "Ingrese sus datos a continuación para completar su compra",
  "shippingAddressText": "Dirección de envío",
  "shippingMethodText": "Método de envío",
  "paymentMethodText": "Método de pago",
  "orderSummaryText": "Resumen del pedido",
  "addressText":
      "admin admintast producto, producto de prueba, producto de prueba producto de prueba, b12345 302006Rusia 1234567890",
  "newAddressText": "Nueva direccion",
  "itemInCartText": "Artículo en el carrito",
  "qtyText": "Cantidad",
  "applyDiscountCodeText": "Aplicar código de descuento",
  "enterDiscountCodeText": "Introduzca el código de descuento",
  "applyDiscountText": "Aplicar descuento",
  "orderTotalText": "Total del pedido",
  "orderCommentText": "Comentario del pedido",
  "placeOrderText": "REALIZAR PEDIDO",
  "myOrdersText": "MIS ORDENES",
  "myWishlistText": "Mi lista de deseos",
  "addressBookText": "Directorio",
  "accountInformationText": "Información de la cuenta",
  "storePaymentText": "MÉTODOS DE PAGO ALMACENADOS",
  "newsLetter1Text": "SUSCRIPCIONES A LOS BOLETINES",
  "enterEmailAddress": "Introduzca la dirección de correo electrónico",
  "enterConfirmEmailAddress":
      "Introduzca la dirección de correo electrónico de confirmación",
  "enterPhoneNumber": "Introduzca el número de teléfono",
  "enterValidEmailAddress":
      "Introduzca una dirección de correo electrónico válida",
  "confirmEmailNotMatch":
      "Confirmar que el correo electrónico no coincide con la dirección de correo electrónico",
  "phoneNumberIsRequired": "Se requiere número de teléfono",
  "phoneNumberIsNotValid": "El número de teléfono no es válido",
  "gstIdentificationNumber":
      "El número de identificación de GST no es válido. Debe estar en este formato 11AAAAA1111Z1A1",
  "emailRequired": "Se requiere correo electrónico",
  "invalidEmail": "Correo electrónico no válido",
  "confirmEmailIsRequired": "Confirmar que se requiere correo electrónico",
  "confirmEmailShouldBeMatchWithEmail":
      "Confirmar que el correo electrónico debe coincidir con el correo electrónico",
  "youHaveReachedYourMaximumLimit":
      "Has alcanzado tu límite máximo de caracteres permitidos",
  "passwordIsRequired": "Se requiere contraseña",
  "successfullyLoggedOut": "Se ha cerrado la sesión correctamente",
  "emailAddress": "Dirección de correo electrónico",
  "enterEmailToTrackRequest.":
      "Por favor, introduzca su correo electrónico para realizar un seguimiento de su solicitud.",
  "firstName": "Nombre",
  "lastName": "Apellido",
  "dateOfBirth.": "Fecha de nacimiento",
  "dateOfMarriage": "Aniversario de matrimonio",
  "signUpForNewsletter": "Regístrese para recibir el boletín",
  "email": "Correo electrónico",
  "password": "Contraseña",
  "confirmPassword": "Confirmar contraseña",
  "typesOfEnquiry": "Tipos de consulta",
  "confirmPasswordIsRequired.": "Se requiere ConfirmPassword",
  "orderDetails": "Detalles del pedido",
  "noDataAvailable": "No hay datos disponibles",
  "myAccount": "Mi cuenta",
  "mrs": "Sra.",
  "communicationPrefences.": "Preferencias de comunicación",
  "subscribeNewsletters": "Suscríbete a los boletines de ounass.",
  "aboutUs": "Sobre nosotros",
  "sms": "SMS",
  "save": "Salvar",
  "tearmsAndCondition": "TÉRMINOS Y CONDICIONES",
  "subscribeOffersAndMore":
      "Suscríbete para ser el primero con nuestras novedades, colecciones exclusivas, ofertas y más.",
  "ourServices": "Nuestros Servicios",
  "delivery": "Entrega",
  "ourWebsite": "Nuestro sitio web",
  "addToCart": "Añadir al carrito",
  "subscribe": "Subscribir",
  "productDetails": "Detalles del producto",
  "priceMatch": "Igualación de precios",
  "composition": "Composición",
  "color": "Color",
  "chooseAnOption": "Elija una opción...",
  "buyNow": "купить сейчас",
  "notifyMeWhenThisProductIsInStock1":
      "Уведомить меня, когда этот продукт будет в наличии",
  "yourBestPriceAlways": "Tu mejor precio, siempre.",
  "IfYourPreferredItemIsLowerMsg":
      "Si su artículo preferido t iene un precio más bajo en cualquier otra tienda en el momento actual, coincidiremos con el precio y le ofreceremos un 10% de crédito adicional de la tienda para su próxima compra.",
  "simplyLetUsKnowByClickingHere":
      "Simplemente háganos saber haciendo clic aquí.",
  "alreadyMadeYourPurchase": "Ya hice tu compra.",
  "dontWorryLetUsKnowByClickingMsg":
      "No se preocupe, avísenos haciendo clic aquí y nuestro equipo de atención al cliente le reembolsará la diferencia si la compra se realizó en los últimos 30 días.",
  "pleaseSeeFAQsByClickingHere":
      "Consulte las preguntas frecuentes haciendo clic aquí",
  "filter": "Filtrar",
  "sort": "Clasificar",
  "sortBy": "Ordenar por",
  "noProductsFound": "No se encuentran productos",
  "createTicket": "Crear Ticket",
  "more": "& Más...",
  "bgbp": "GBP",
  "findBrand": "Encuentra marcas",
  "itSeemsWeHaveNothingToShowFor": "Parece que no tenemos nada que mostrar",
  "ifYouWouldLikeToHaveMoreInformationAbout":
      "Si desea tener más información sobre",
  "thenPleaseCreateATicket": "Entonces crea un boleto",
  "contactInformation": "Información del contacto",
  "edit": "Editar",
  "changePassword": "Cambia la contraseña",
  "youHaveNoProductsInYourWishList":
      "No tiene productos en su lista de deseos.",
  "toBbeUpdated": "Para actualizarse",
  "youHaveNoSavedAddressAddnewAddressToContinueWithCheckout":
      "No tiene dirección guardada Agregue nueva dirección para continuar con el pago",
  "shipHere": "Enviar aquí",
  "enterFirstName": "Ingrese el primer nombre",
  "enterLastName": "Introduzca el apellido",
  "enterStreetAddress1": "Ingrese la dirección de la calle 1",
  "streetAddress1": "Dirección Calle 1",
  "enterStreetAdress2": "Entra en la calle calle 2",
  "streetAddress2": "Dirección de la calle 2",
  "enterStreetAddress3": "Ingrese la dirección de la calle 3",
  "streetAddress3": "Dirección de la calle 3",
  "enterCityName": "Ingrese el nombre de la ciudad",
  "city": "Ciudad",
  "country": "País",
  "enterZipPostalCode": "Ingrese el código postal zip",
  "zipPostalCode": "Código postal/postal",
  "stateProvince": "Provincia del estado",
  "enterStateProvince": "Ingrese el estado/provincia",
  "emailAddressRequired": "Dirección de correo electrónico: (obligatorio",
  "cancelCoupon": "Cancelar cupón",
  "apply": "Aplicar",
  "viewCouponList": "Ver Lista de cupones",
  "coupons": "Cupones",
  "changeLanguageAndCurrency": "Cambiar el idioma y la moneda",
  "youHaveNoOrders": "No tienes pedidos",
  "youHaveNoTickets": "No tienes entradas",
  "category": "Categoría",
  "createNewTicket": "Crear nuevo boleto",
  "positiveImpactSustainability": "Impacto positivo + sostenibilidad",
  "thereAreStillMoreThanMSG":
      "Todavía hay más de mil millones de personas alrededor del mundo que viven en la pobreza extrema en menos de \$ 1.25 por día. Solo en Tailandia, existen más de un millón de miembros de las tribus de Hill en los márgenes de la sociedad, negó la ciudadanía, excluyeron el mercado laboral formal y vulnerable a la explotación y la trata.",
  "atYellowLeafHammocksMsg":
      "En las hamacas de hoja amarilla creemos que la creación ética de empleo es una solución a largo plazo para la pobreza extrema.",
  "insteadOfOrganizingMsg":
      "En lugar de organizar un mosaico de donaciones de caridad para proporcionar agua, nutrición, ropa, etc., estamos trabajando directamente con las familias para construir una estrategia integral, digna y a largo plazo hacia un futuro más brillante. Las causas detrás de la pobreza sistémica son complicadas, pero la estabilidad financiera a largo plazo está al alcance.",
  "toPutItSimplyMsg":
      "En pocas palabras: al centrarnos en los medios de vida, podemos eliminar al intermediario, obtener dinero directamente en manos de madres inteligentes + ingeniosas y capacitar a las familias para abordar sus propios problemas (sin estar sujetos a la agenda de nadie más).",
  "acrossThreeWeavingCommunitiesMsg":
      "\"En tres comunidades de tejido, estamos trabajando para crear empleos para las madres y construir una base para la transformación de la comunidad positiva. A través del trabajo flexible y seguro de tejido de \"\"salario de prosperidad\"\", nuestros artesanos pueden levantar a sus familias de la pobreza y la esclavitud de la deuda a la clase media.\"",
  "creatingJobsForWomenMsg":
      "** Crear empleos para mujeres es especialmente importante para la transformación comunitaria: la investigación muestra que las mujeres gastarán hasta el 90% de sus ganancias en la salud, la nutrición y la educación de sus familias. Convertir a las mujeres en sostén de la familia mejora su estatus en la comunidad, desarrolla autoestima y les permite agrupar recursos para mejorar la infraestructura.",
  "theFoundationForABrighterFuter": "La base de un futuro más brillante",
  "theSecurityOfAStableMsg":
      "La seguridad de una fuente de ingresos estable y creciente tuvo un tremendo impacto en la aldea. Los Mlabri pudieron comenzar una escuela y construir un centro comunitario para tejer y socializar. Establecieron uno de los primeros fondos de desempleo de Tailandia. Con un mayor poder económico, presionaron con éxito la ciudadanía y los derechos civiles, que se les otorgó por primera vez en 2001. El tejido de hamaca es un trabajo flexible, ideal para madres que pueden trabajar desde casa y hacer sus propios horarios. Desafortunadamente, sin acceso a los mercados globales, la demanda de hamacas se limitaba a la temporada de turismo tailandés y no había forma de garantizar un empleo durante todo el año.",
  "spreadingLastingChangeTheHammockRrevolution":
      "Difundir un cambio duradero: la rrevolución de la hamaca",
  "thisIsAboutWhereMsg":
      "¡Aquí se trata de donde Yellow Leaf se une a la historia! En los últimos años, hemos trabajado para desarrollar canales de ventas consistentes, crear asociaciones internacionales y estabilizar operaciones dentro de las aldeas.",
  "corollaryEconomicMsg":
      "Las oportunidades económicas del corolario, como una oficina de correos, la preparación de alimentos y el cultivo de café sostenible han surgido para emplear a los que no están tejiendo. Nuestra asociación con Kiva ha estimulado la capacitación financiera y la planificación financiera, ¡y muchos tejedores abren cuentas bancarias por primera vez en sus vidas!",
  "wWithOurGrowthMsg":
      "Con nuestro crecimiento continuando acelerando, no solo podremos emplear a todos los tejedores de Mlabri durante todo el año, sino que también podremos continuar expandiéndonos y brindando capacitación y empleo continuo a las comunidades de tribu Hill en la región circundante. Hasta que el trabajo de tejido y los trabajos sostenibles estén disponibles en toda el área, las prácticas agrícolas destructivas continuarán y el ciclo de explotación de servidumbre por contrato no terminará realmente.",
  "throughTheEstablishmentMsg":
      "A través del establecimiento de la hoja amarilla como una marca de estilo de vida global, los pueblos de las tribus de Hill con las que nos asociamos podrán mantener este impacto positivo y continuará sentando las bases para un futuro más brillante.",
  "enterWebsite": "Ingrese el sitio web",
  "enterPostCode": "Ingrese el código postal",
  "thankYouForYourInterest":
      "Gracias por su interés en trabajar con Brands-Labels",
  "oneOfOurTeamMembersWillBeInTouchSoon":
      "Uno de los miembros de nuestro equipo se pondrá en contacto pronto",
  "forAnyAdditionalQueriesPleaseWriteTo ":
      "Para cualquier consulta adicional, escriba a",
  "theProductIsOutOfStock": "El producto está agotado.",
  "whateverYourQueryUseTheContactFormBelowMsg":
      "Cualquiera que sea su consulta. Use el formulario de contacto a continuación para ponerse en contacto con el tiempo está listo para ayudar 24*7",
  "enterSubject": "Entrar en el sujeto",
  "enterSomeText": "Ingrese algún texto",
  "enterDetailsBelowToSend":
      "Ingrese los detalles a continuación para enviar un código de cupón del 10% a su amigo",
  "enterFriendName": "Introduzca el nombre de su amigo",
  "friendFirstName": "Amigo Nombre",
  "enterFirstEmailAddress":
      "Ingrese la primera dirección de correo electrónico",
  "friendEmailAddress": "Dirección de correo electrónico de amigo",
  "enterFirstPhoneNumber": "Ingrese el primer número de teléfono",
  "friendPhoneNumber": "Número de teléfono de un amigo",
  "register": "Registro",
  "dateOfBirthIsRequired": "Se requiere fecha de cerveza",
  "marriageAnniversaryIsRequired": "Se requiere aniversario de matrimonio",
  "surnameIsRequired": "Se requiere el apellido",
  "date": "Fecha",
  "showDialog": "Diálogo de espectáculos",
  "removeProduct": "Eliminar el producto",
  "areYouSureWantToRemoveThisProductFromCart":
      "¿Está seguro de que quiere eliminar este producto del carrito?",
  "yes": "SÍ",
  "no": "NO",
  "addToWishlist": "Añadir a la lista de deseos",
  "onceYouAddThisProductToWishlistThenItWillBeRemoveFromAart":
      "Una vez que agregue este producto a la lista de deseos, se eliminará del carrito",
  "ok": "OK",
  "nouHaveNoItemsInYourShoppingCart":
      "No tiene artículos en su carrito de compras.",
  "Discount": "Descuento",
  "enterCouponCode": "Introduce el código de cupón",
  "removeCoupon": "Eliminar cupón",
  "availableCouponList": "Lista de cupón disponible",
  "allCouponsList": "Lista de todos los cupones",
  "addProductToYourWishList": "Agregue el producto a su lista de deseos",
  "configurable": "configurable",
  "Missing": "Perdido",
  "Amount": "Monto",
  "Balance": "Balance",
  "Remarks": "Observaciones",
  "myAddresses": "Mis direcciones",
  "noAddressFound": "No se encontró la dirección",
  "addAddress": "Añadir dirección",
  "updateAddress": "Dirección de actualización",
  "expectedShipmentDate": "Fecha de envío esperada",
  "brandNameIsRequired": "Se requiere marca",
  "styleIsRequired": "Se requiere estilo",
  "keywordIsRequired": "Se requiere una palabra clave",
  "remarkIsRequired": "Se requiere un comentario",
  "couponId": "ID de cupón",
  "couponName": "Nombre de cupón",
  "expireAt": "Expirar a",
  "noCouponsFound": "¡No se encontraron cupones!",
  "yourRequestHasBeenReceived": "Su petición ha sido recibida.",
  "youCanViewYourRequestsatMyTickets":
      "Puedes ver tus solicitudes en mis boletos",
  "incorrectPassword": "Contraseña incorrecta",
  "thePasswordYouenteredisincorrectPleasetryagain":
      "La contraseña que ha ingresado es incorrecta. Inténtalo de nuevo",
  "registeredCustomers": "Clientes Registrados",
  "ifYouHaveAnAccountSignInWithYourEmailAddress":
      "Si tiene una cuenta, inicie sesión con su dirección de correo electrónico",
  "pleaseEnterOrderNumberToTrackYourOrder":
      "Ingrese el número de pedido para rastrear su pedido.",
  "enterOrderNumber": "Ingrese el número de pedido",
  "enteryOurOrderNumberHere": "Ingrese su número de pedido aquí",
  "howDoIFindMyOrderReference": "¿Cómo encuentro mi referencia de pedido?",
  "passwordRegExp":
      "La contraseña debe tener al menos 8 caracteres y contener una mezcla de letras mayúsculas y minúsculas, al menos un número y un carácter especial (por ejemplo ,! @ #?).",
  "nylonMessengerBackpackMsg":
      "Mochila Nylon Messenger de Balenziaga, cierre delantero con gancho, manija superior, correas de hombro ajustables, bolsillo de cremallera de parche delantero con logotipo de contraste, ganchos como elementos decorativos.",
  "priceMatchTicket": "Boleto de partido de precio",
  "enterAddress3": "Ingrese la dirección 3",
  "enterCity": "Entrar en la ciudad",
  "pleaseTryWithAnotherEmaiAddressMsg":
      "Pruebe con otra dirección de correo electrónico o escríbanos a care@brandslabels.com para obtener más ayuda.",
  "Alert": "Alerta",
  "requiredVal": "es requerido",
  "mustbeof": "debe ser de",
  "digits": "dígitos",
  "mustbeanumberExample100": "Tiene que ser un número. Ejemplo: 100",
  "character": "personaje",
  "isinvalid": "¡es inválido!",
  "mustbemorethan2characters": "Debe ser más de 2 caracteres",
  "entervalid": "Entrar válido",
  "musthaveatleast2characters": "Debe tener al menos 2 caracteres",
  "confirmpasswordshouldbematchwithpassword":
      "Confirmar que la contraseña debe coincidir con la contraseña",
  "pleaseenterPassword": "Por favor, ingrese contraseña",
  "mustbemorethan8characters": "Debe ser más de 8 caracteres",
  "mobileisRequired": "Se requiere móvil",
  "mobilenumbermust10digits": "Número de móvil debe 10 dígitos",
  "mobileNumbermustbedigits": "El número de móvil debe ser dígitos",
  "yearmustbenumberonly": "El año solo debe ser número",
  "establishedYearisRequired": "Se requiere un año establecido",
  "yearmustbebetween1850and": "El año debe ser entre 1850 y",
  "licenseNoisRequired": "Licencia no se requiere",
  "numberofemployeeisRequired": "Se requiere el número de empleados",
  "numberofemployeeisnotmorethan9999":
      "El número de empleados no es más de 9999",
  "numberofemployeemustbedigits": "El número de empleados debe ser dígitos",
  "dateisRequired": "Se requiere fecha",
  "pleaseentervaliddate": "Ingrese la fecha válida",
  "licenseIssuingAuthorityisRequired":
      "Se requiere autoridad emisora ​​de licencias",
  "licenseIssuingAuthoritymustbeazandAZ":
      "La autoridad emisora ​​de licencias debe ser A-Z y A-Z",
  "firstNameIsRequired": "Se requiere el primer nombre",
  "lastNameIsRequired": "Se requiere apellido",
  "imageUrlIsRequired": "Se requiere un enlace de imagen",
  "enterValidText": "Ingrese un texto válido",
  "pleaseCheckYourInternetConnection":
      "¡Por favor revise su conexion a internet!",
  "searchForPiesSushiTacos": "Buscar pasteles, sushi, tacos ...",
  "enterSurname": "Ingrese el apellido",
  "enterStreetAddress": "Ingrese la dirección de la calle",
  "addNew": "Agregar nuevo",
  "enterAddress1": "Ingrese la dirección 1",
  "enterAddress2": "Ingrese la dirección 2",
  "noBrandFound": "No se encontró marca",
  "COUPONAPPLIEDSUCCESSFULLYYOUSAVED": "Cupón aplicado con éxito. SALVASTE",
  "ONTHISORDER": "En este orden",
  "areYouSureYouWantToRemove": "Estás seguro de que desea eliminar",
  "couponCode": "¿Código promocional?",
  "cancel": "Cancelar",
  "itSeemsLikeWeHaveNothingToShowForThisBrand":
      "Parece que no tenemos nada que mostrar para esta marca",
  "ifyouwouldlikeUsSendYouTheCollectionFrom":
      "Si desea que le enviemos la colección desde",
  "plsCreateATicketBelow": "pls. Crea un boleto a continuación",
  "itSeemsLikeWeHaveNothingToShowForThisCategory":
      "Parece que no tenemos nada que mostrar para esta categoría",
  "enterName": "Ingrese su nombre",
  "description": "Descripción",
};
