const Map<String, String> fr = {
  "language": "Anglais",
  "appNameText": "Marques et Labels",
  "aboutUsText": "À propos de nous",
  "aboutUsTitle": 'NOUS SOMMES MARQUE & LABELS',
  "aboutUsContain": 'EXPLOREZ LES 100 MEILLEURES MARQUES DU MONDE',
  "aboutUsContain1":
      'BRANDS & LABELS EST UNE DESTINATION DE MODE DE LUXE EN LIGNE AVEC 5 MILLIONS DE VISITEURS PAR MOIS ET DES LIVRAISONS DANS LE MONDE ENTIER.',
  "aboutUsContain2":
      '''LE SITE WEB PRÉSENTE LA MEILLEURE SÉLECTION DES MEILLEURS DESIGNERS ÉTABLIS AINSI QUE DES JEUNES TALENTS ÉMERGENTS. BRANDSLABELS A ÉTÉ CRÉÉ À FLORENCE AU DÉBUT DES ANNÉES 1930, AVEC L'OUVERTURE DU CONCEPT STORE ÉPONYME DE L'ENTREPRISE SUR LA VIA ROMA. EN LIGNE DEPUIS 1999, LA SOCIÉTÉ AFFECTE 90 % DE SES REVENUS AUX VENTES EN LIGNE. À CE JOUR, ELLE RESTE UNE ENTREPRISE FAMILIALE 100 % PRIVÉE, AVEC LE PETIT-FILS DU FONDATEUR, ANDREA PANCONESI AGISSANT EN TANT QUE PDG ET SA FILLE, ANNAGRETA PANCONESI EN TANT QUE DIRECTRICE CRÉATIVE.''',
  "aboutUsContain3":
      'LE SITE PROPOSE UN LARGE CHOIX DE VÊTEMENTS, CHAUSSURES, SACS, ACCESSOIRES, INTÉRIEURS DE LUXE ET BEAUTÉ, AVEC DES PRODUITS DISPONIBLES POUR HOMME, FEMME ET ENFANT DES CRÉATEURS LES PLUS PRESTIGIEUX TELS QUE BALENCIAGA, VETEMENTS, OFF-WHITE, J.W. ANDERSON, BALMAIN, DOLCE & GABBANA, GUCCI, SAINT LAURENT, VALENTINO, GIVENCHY, LOEWE, JACQUEMUS ET PLUS.',
  "aboutUsContain4":
      'IL Y A ACTUELLEMENT 200 PERSONNES DE 15 PAYS DIFFÉRENTS QUI TRAVAILLENT POUR PRODUIRE ET MAINTENIR DES ÉTIQUETTES DE MARQUE. LE SITE EST DISPONIBLE EN 9 LANGUES : ANGLAIS, ITALIEN, ALLEMAND, CHINOIS, RUSSE, ESPAGNOL, FRANÇAIS, CORÉEN ET JAPONAIS. LE SITE EST CRÉÉ ENTIÈREMENT EN INTERNE, AVEC LES DÉPARTEMENTS FLORENCE OFFICE HOUSING DESIGN GRAPHIQUE, INFORMATIQUE, SERVICE CLIENTÈLE, MARKETING ET ACHAT. LES STYLISTES ET LES ÉQUIPES DE PRESSE OPÉRENT DEPUIS LE BUREAUX BRANDSLABELS DANS LA CAPITALE MONDIALE DE LA MODE – MILAN.',
  "aboutUsContain5":
      'TOUTES LES COMMANDES SONT EXPÉDIÉES DANS LE MONDE ENTIER DEPUIS LE SIÈGE DES BRANDS LABELS DANS DES BOÎTES PRÉPARÉES AVEC UN MAXIMUM DE SOIN ET UTILISANT LES MEILLEURS MATÉRIAUX, DES SACS À CHAUSSURES SIGNATURE AU RUBAN PERSONNALISÉ.',
  "aboutUsContain6":
      '''BRANDSLABELS A ACCÉDÉ À 1,5 MILLION DE VISITEURS UNIQUES SUR LE SITE EN 2008 ET A PASSÉ À 53 MILLIONS DE VISITEURS UNIQUES EN 2017. PLUS DE 15 % DES VENTES EN LIGNE SONT GÉNÉRÉES À PARTIR DES ÉTATS-UNIS, SUIVI DE L'ALLEMAGNE, DU ROYAUME-UNI, DE L'ITALIE, DE LA CHINE ET DE LA FRANCE.''',
  "aboutUsContain7":
      '''BRANDSLABELS REPOUSSE LES LIMITES DU PAYSAGE DE LA VENTE AU DÉTAIL DE LUXE EN LIGNE ET HORS LIGNE AVEC UNE GAMME DE SERVICES EXCLUSIFS ET D'INITIATIVES DE MARQUE COMME ACHETEZ D'ABORD, LUXURY CLUB, SNEAKERS CLUB, LVR PRIVILEGE ET LVR EDITIONS.''',
  "profile": "Profil",
  "firstNameText": "Prénom",
  "lastNameText": "Nom de famille",
  "emailText": "E-mail",
  "ContactNoText": "N° de contact",
  "websiteUrlText": "URL de site web",
  "cityText": "Ville",
  "countryText": "De campagne",
  "postCodeText": "Code postal",
  "socialLinksText": "Liens sociaux",
  "facebookText": "Facebook",
  "instagramText": "Instagram",
  "twitterText": "Twitter",
  "youtubeText": "Youtube",
  "linkendinText": "Linkendin",
  "pinterestText": "Pinterest",
  "followersText": "Suiveurs",
  "mr": "Monsieur.",
  "letsText": "Allons-y",
  "orderIdTitle": '''Votre numéro de commande est : ''',
  "orderDateTitle": 'Date de commande : 15 septembre 2021',
  "orderNumberTitle": 'NUMÉRO DE COMMANDE : ',
  "orderConfirm": "MERCI POUR VOTRE ACHAT!",
  "name": "NOM",
  "sku": "UGS",
  "price": "LE PRIX",
  "qty": "QTÉ",
  "subTotal": "Total",
  "action": "Action",
  "addressBook": "Carnet d'adresses",
  "billing": "Facturation",
  "shipping": "Expédition",
  "orderContain":
      'Nous vous enverrons par e-mail une confirmation de commande avec les détails et les informations de suivi.',
  "referFriendText": "Référez un ami",
  "returnsRefundsText": "Retours et remboursements",
  "faqText": "FAQ",
  "contactText": "Contact",
  "socialText": "Social",
  "companyText": "Compagnie",
  "myOrders": "Mes commandes",
  "myOrderImage": "Image",
  "productName": "Nom du produit",
  "quantity": "Qté",
  "status": "Statut",
  "paymentMethod": " Mode de paiement",
  "shippingAddress": "Adresse de livraison",
  "billingAddress": "Adresse de facturation",
  "continueShopping": "Continuer vos achats",
  "generalAndOrderEnquiriesText": "RENSEIGNEMENTS GÉNÉRAUX ET DE COMMANDE",
  "gdpText": "PIB",
  "engText": "FR",
  "nameText": "Nom*",
  "surNameText": "Nom de famille*",
  "emailAddressText": "Adresse e-mail*",
  "confirmEmailAddressText": "Confirmez votre adresse email*",
  "subjectText": "Sujet*",
  "phoneNumberText": "Numéro de téléphone",
  "whatsOnYourMindText": "Qu'est-ce qui préoccupe votre esprit?*",
  "queryDescription":
      "Quelle que soit votre demande, utilisez le formulaire de contact ci-dessous pour nous contacter, notre équipe est prête à vous aider 24h/24 et 7j/7",
  "submitText": "NOUS FAIRE PARVENIR",
  "typeOfEnquiryText": "Type de demande*",
  "registeredCustomersText": "Clients enregistrés",
  "signInDescriptionText":
      "Si vous avez un compte, connectez-vous avec votre\nadresse e-mail.",
  "forgotYourPasswordText": "Mot de passe oublié?",
  "signInText": "S'identifier",
  "newCustomersText": "nouveaux clients",
  "newCustomersDescriptionText":
      "La création d'un compte présente de nombreux avantages :\npaiement plus rapide, conservation de plusieurs adresses,\nsuivi des commandes, etc.",
  "createAccountText": "Créer un compte",
  "aboutProjectNameText": "À propos des marques et labels",
  "helpAndInformationText": "Aide et informations",
  "moreFromProjectText": "Plus de Brands&Labels",
  "newsLetterText": "Bulletin",
  "subscribeText": "S'abonner",
  "passwordText": "Mot de passe",
  "homeText": "Maison",
  "searchText": "Rechercher",
  "designersText": "Créateurs",
  "wishListText": "Liste de souhaits",
  "loginText": "Connexion",
  "myAccountText": "Mon compte",
  "yourEmailText": "Votre e-mail",
  "checkoutText": "Vérifier",
  "purchaseText":
      "Veuillez entrer vos coordonnées ci-dessous pour finaliser votre achat",
  "shippingAddressText": "Adresse de livraison",
  "shippingMethodText": "Mode de livraison",
  "paymentMethodText": "Mode de paiement",
  "orderSummaryText": "Récapitulatif de la commande",
  "addressText":
      "admin produit admintast, produit test, produit test produit test, b12345 302006Russie 1234567890",
  "newAddressText": "Nouvelle adresse",
  "itemInCartText": "Article dans le panier",
  "qtyText": "Qté",
  "applyDiscountCodeText": "Appliquer le code de réduction",
  "enterDiscountCodeText": "Entrez le code de réduction",
  "applyDiscountText": "Appliquer la remise",
  "orderTotalText": "Total de la commande",
  "orderCommentText": "Commentaire de la commande",
  "placeOrderText": "PASSER LA COMMANDE",
  "myOrdersText": "MES COMMANDES",
  "myWishlistText": "Ma liste d'envies",
  "addressBookText": "Carnet d'adresses",
  "accountInformationText": "Information sur le compte",
  "storePaymentText": "MÉTHODES DE PAIEMENT MÉMORISÉES",
  "newsLetter1Text": "ABONNEMENT À LA NEWSLETTER",
  "enterEmailAddress": "Entrez l’adresse e-mail",
  "enterConfirmEmailAddress": "Entrez ConfirmerAdresse e-mail",
  "enterPhoneNumber": "Entrez le numéro de téléphone",
  "enterValidEmailAddress": "Entrez une adresse e-mail valide",
  "confirmEmailNotMatch":
      "Confirmer que l’adresse e-mail ne correspond pas à l’adresse e-mail",
  "phoneNumberIsRequired": "Le numéro de téléphone est obligatoire",
  "phoneNumberIsNotValid": "Le numéro de téléphone n’est pas valide",
  "gstIdentificationNumber":
      "Le numéro d’identification de la TPS n’est pas valide. Il devrait être dans ce format 11AAAAA1111Z1A1",
  "emailRequired": "L’adresse e-mail est obligatoire",
  "invalidEmail": "E-mail non valide",
  "confirmEmailIsRequired": "Confirmer que l’adresse e-mail est requise",
  "confirmEmailShouldBeMatchWithEmail":
      "Confirmer que l’e-mail doit correspondre à l’e-mail",
  "youHaveReachedYourMaximumLimit":
      "Vous avez atteint votre limite maximale de caractères autorisés",
  "passwordIsRequired": "Le mot de passe est requis",
  "successfullyLoggedOut": "Vous avez été déconnecté avec succès",
  "emailAddress": "Adresse e-mail",
  "enterEmailToTrackRequest.":
      "Veuillez entrer votre adresse e-mail pour suivre votre demande.",
  "firstName": "Prénom",
  "lastName": "Nom",
  "dateOfBirth.": "Date de naissance",
  "dateOfMarriage": "Anniversaire de mariage",
  "signUpForNewsletter": "Inscrivez-vous à la newsletter",
  "email": "Messagerie électronique",
  "password": "Mot de passe",
  "confirmPassword": "Confirmer le mot de passe",
  "typesOfEnquiry": "Types de demandes de renseignements",
  "confirmPasswordIsRequired.": "ConfirmPassword est requis",
  "orderDetails": "Détails de la commande",
  "noDataAvailable": "Aucune donnée disponible",
  "myAccount": "Mon compte",
  "mrs": "Madame.",
  "communicationPrefences.": "Préférences de communication",
  "subscribeNewsletters": "Abonnez-vous aux newsletters ounass..",
  "aboutUs": "Qui sommes-nous",
  "sms": "SMS",
  "save": "Sauvegarder",
  "tearmsAndCondition": "TERMES ET CONDITIONS",
  "subscribeOffersAndMore":
      "Abonnez-vous pour être le premier avec nos nouveautés, nos collections exclusives, nos offres et plus encore.",
  "ourServices": "Nos services",
  "delivery": "Livraison",
  "ourWebsite": "Notre site web",
  "addToCart": "Ajouter au panier",
  "subscribe": "S’inscrire",
  "productDetails": "Détails du produit",
  "priceMatch": "Correspondance des prix",
  "composition": "Composition",
  "color": "Couleur",
  "chooseAnOption": "Choisissez une option...",
  "buyNow": "Acheter maintenant",
  "notifyMeWhenThisProductIsInStock1":
      "Informez-moi lorsque ce produit est en stock",
  "yourBestPriceAlways": "Votre meilleur prix - toujours.",
  "IfYourPreferredItemIsLowerMsg":
      "Si votre article préféré est à un prix inférieur dans tout autre magasin à l'heure actuelle, nous égalerons le prix et vous offrirons 10% de crédit de magasin supplémentaire pour votre prochain achat.",
  "simplyLetUsKnowByClickingHere": "Faites-le nous savoir en cliquant ici.",
  "alreadyMadeYourPurchase": "Déjà fait votre achat.",
  "dontWorryLetUsKnowByClickingMsg":
      "Ne vous inquiétez pas, faites-le nous savoir en cliquant ici et nous, notre équipe de support client, vous rembourserons la différence si l'achat a été effectué dans les 30 derniers jours.",
  "pleaseSeeFAQsByClickingHere": "Veuillez consulter les FAQ en cliquant ici",
  "filter": "Filtre",
  "sort": "Trier",
  "sortBy": "Trier par",
  "noProductsFound": "Aucun produit trouvé",
  "createTicket": "Créer un billet",
  "more": "& Plus...",
  "bgbp": "GBP",
  "findBrand": "Trouver des marques",
  "itSeemsWeHaveNothingToShowFor": "Il semble que nous n'avons rien à montrer",
  "ifYouWouldLikeToHaveMoreInformationAbout":
      "Si vous souhaitez avoir plus d'informations sur",
  "thenPleaseCreateATicket": "Alors veuillez créer un billet",
  "contactInformation": "Coordonnées",
  "edit": "Éditer",
  "changePassword": "Changer le mot de passe",
  "youHaveNoProductsInYourWishList":
      "Vous n'avez pas de produits dans votre liste de souhaits.",
  "toBbeUpdated": "À mettre à jour",
  "youHaveNoSavedAddressAddnewAddressToContinueWithCheckout":
      "Vous n'avez pas d'adresse enregistrée Ajouter une nouvelle adresse pour continuer avec le paiement",
  "shipHere": "Expédier ici",
  "enterFirstName": "Entrez votre prénom",
  "enterLastName": "Entrer le nom de famille",
  "enterStreetAddress1": "Entrez l'adresse de la rue 1",
  "streetAddress1": "adresse 1",
  "enterStreetAdress2": "Entrez Street Adress 2",
  "streetAddress2": "Adresse de la rue 2",
  "enterStreetAddress3": "Entrez l'adresse de la rue 3",
  "streetAddress3": "Adresse de la rue 3",
  "enterCityName": "Entrez le nom de la ville",
  "city": "Ville",
  "country": "Pays",
  "enterZipPostalCode": "Entrez le code postal zip",
  "zipPostalCode": "Zip / code postal",
  "stateProvince": "État / province",
  "enterStateProvince": "Entrez l'État / la province",
  "emailAddressRequired": "Adresse mail: (requis",
  "cancelCoupon": "Annuler le coupon",
  "apply": "Appliquer",
  "viewCouponList": "Voir la liste des coupons",
  "coupons": "Coupons",
  "changeLanguageAndCurrency": "Changer la langue et la monnaie",
  "youHaveNoOrders": "Vous n'avez pas de commandes",
  "youHaveNoTickets": "Vous n'avez pas de billets",
  "category": "Catégorie",
  "createNewTicket": "Créer un nouveau billet",
  "positiveImpactSustainability": "Impact positif + durabilité",
  "thereAreStillMoreThanMSG":
      "Il y a encore plus d'un milliard de personnes dans le monde vivant dans l'extrême pauvreté avec moins de 1,25 \$ par jour. Rien qu'en Thaïlande, plus d'un million de membres des tribus Hill existent en marge de la société - nié citoyenneté, exclu du marché du travail officiel et vulnérable à l'exploitation et à la traite.",
  "atYellowLeafHammocksMsg":
      "Chez Yellow Leaf Hamacs, nous pensons que la création d'emplois éthique est une solution à long terme stimulante à l'extrême pauvreté.",
  "insteadOfOrganizingMsg":
      "Au lieu d'organiser un patchwork de dons de bienfaisance pour fournir de l'eau, de la nutrition, des vêtements, etc., nous travaillons directement avec les familles pour construire une stratégie complète, digne et à long terme vers un avenir meilleur. Les causes derrière la pauvreté systémique sont compliquées, mais la stabilité financière à long terme est à portée de main.",
  "toPutItSimplyMsg":
      "Pour le dire simplement: en nous concentrant sur les moyens de subsistance, nous pouvons couper l'homme du milieu, mettre de l'argent directement entre les mains de mères intelligentes + ingénieuses et permettre aux familles de s'attaquer à leurs propres problèmes (sans être soumis à l'ordre du jour de quelqu'un d'autre).",
  "acrossThreeWeavingCommunitiesMsg":
      "Dans trois communautés de tissage, nous travaillons à créer des emplois pour les mères et à construire une base pour une transformation de la communauté positive. Grâce à un travail de tissage flexible et sûr de «salaire de prospérité», nos artisans sont capables de lever leur famille de la pauvreté et de l'esclavage de la dette à la classe moyenne.",
  "creatingJobsForWomenMsg":
      "** Créer des emplois pour les femmes est particulièrement important pour la transformation de la communauté - la recherche montre que les femmes dépenseront jusqu'à 90% de leurs gains sur la santé, la nutrition et l'éducation de leur famille. Transformer les femmes en soutiens de famille améliore leur statut dans la communauté, renforce l'estime de soi et leur permet de mettre en commun les ressources pour améliorer les infrastructures.",
  "theFoundationForABrighterFuter": "La fondation pour un futur plus brillant",
  "theSecurityOfAStableMsg":
      "La sécurité d'une source de revenus stable et croissante a eu un impact énorme sur le village. Les Mlabri ont pu démarrer une école et construire un centre communautaire pour le tissage et la socialisation. Ils ont créé l'un des premiers fonds de chômage de la Thaïlande. Avec une puissance économique accrue, ils ont réussi à faire pression pour la citoyenneté et les droits civils, qu'ils ont été accordés pour la première fois en 2001. Le tissage de hamac est un travail flexible, idéal pour les mères qui peuvent travailler à domicile et faire leurs propres horaires. Malheureusement, sans accès aux marchés mondiaux, la demande de hamacs s'est limitée à la saison du tourisme thaïlandais et il n'y avait aucun moyen d'assurer l'emploi toute l'année.",
  "spreadingLastingChangeTheHammockRrevolution":
      "Répartir le changement durable: la rrévolution du hamac",
  "thisIsAboutWhereMsg":
      "C'est là où Yellow Leaf rejoint l'histoire! Au cours des dernières années, nous avons travaillé pour développer des canaux de vente cohérents, établir des partenariats internationaux et stabiliser les opérations au sein des villages.",
  "corollaryEconomicMsg":
      "Les opportunités économiques corollaires, comme un bureau de poste, la préparation des aliments et la culture durable du café ont vu le jour pour employer ceux qui ne sont pas tissés. Notre partenariat avec Kiva a stimulé une formation financière et une planification financière, de nombreux tisserands ouvrant des comptes bancaires pour la première fois de leur vie!",
  "wWithOurGrowthMsg":
      "Avec notre croissance qui continue de s'accélérer, nous serons non seulement en mesure d'employer tous les tisserands MLABRI toute l'année, mais nous pourrons également continuer à se développer et à fournir une formation et un emploi continu aux communautés de tribu des collines dans la région environnante. Jusqu'à ce que les travaux de tissage et les emplois durables soient disponibles dans toute la région, les pratiques agricoles destructrices se poursuivront et le cycle d'exploitation de la servitude sous contrat ne prendra pas vraiment fin.",
  "throughTheEstablishmentMsg":
      "Grâce à la création de Yellow Leaf en tant que marque mondiale de style de vie, les villages Hill Tribe avec lesquels nous nous associons pourront soutenir cet impact positif et continuer à jeter les bases d'un avenir meilleur.",
  "enterWebsite": "Entrez le site Web",
  "enterPostCode": "Entrez le code postal",
  "thankYouForYourInterest":
      "Merci de votre intérêt à travailler avec des marques-marques",
  "oneOfOurTeamMembersWillBeInTouchSoon":
      "Un des membres de notre équipe sera bientôt en contact",
  "forAnyAdditionalQueriesPleaseWriteTo ":
      "Pour toute question supplémentaire, veuillez écrire à",
  "theProductIsOutOfStock": "Le produit est en rupture de stock.",
  "whateverYourQueryUseTheContactFormBelowMsg":
      "Quelle que soit votre requête. Utilisez le formulaire de contact ci-dessous pour entrer dans le tactile-ourteam est prêt à aider 24 * 7",
  "enterSubject": "Entrer le sujet",
  "enterSomeText": "Entrez du texte",
  "enterDetailsBelowToSend":
      "Entrez les détails ci-dessous pour envoyer un code de coupon de 10% à votre ami",
  "enterFriendName": "Entrez le nom de l'ami",
  "friendFirstName": "Prénom ami",
  "enterFirstEmailAddress": "Entrez la première adresse e-mail",
  "friendEmailAddress": "Adresse e-mail d'ami",
  "enterFirstPhoneNumber": "Entrez le premier numéro de téléphone",
  "friendPhoneNumber": "Numéro de téléphone d'ami",
  "register": "S'inscrire",
  "dateOfBirthIsRequired": "Dateofbirth est requis",
  "marriageAnniversaryIsRequired": "L'anniversaire du mariage est requis",
  "surnameIsRequired": "Le nom de famille est requis",
  "date": "Date",
  "showDialog": "Afficher le dialogue",
  "removeProduct": "Supprimer le produit",
  "areYouSureWantToRemoveThisProductFromCart":
      "Êtes-vous sûr de vouloir retirer ce produit du panier?",
  "yes": "OUI",
  "no": "NON",
  "addToWishlist": "Ajouter à la liste de souhaits",
  "onceYouAddThisProductToWishlistThenItWillBeRemoveFromAart":
      "Une fois que vous aurez ajouté ce produit à la liste de souhaits, il sera retiré du panier",
  "ok": "D'ACCORD",
  "nouHaveNoItemsInYourShoppingCart":
      "Vous n'avez pas d'articles dans votre panier.",
  "Discount": "Remise",
  "enterCouponCode": "Entrer le code de réduction",
  "removeCoupon": "Supprimer le coupon",
  "availableCouponList": "Liste des coupons disponibles",
  "allCouponsList": "Tous les coupons Liste",
  "addProductToYourWishList": "Ajouter un produit à votre liste de souhaits",
  "configurable": "configurable",
  "Missing": "Disparu",
  "Amount": "Montant",
  "Balance": "Solde",
  "Remarks": "Remarques",
  "myAddresses": "Mes adresses",
  "noAddressFound": "Aucune adresse trouvée",
  "addAddress": "Ajoutez l'adresse",
  "updateAddress": "Adresse de mise à jour",
  "expectedShipmentDate": "Date d'expédition attendue",
  "brandNameIsRequired": "Le nom de marque est requis",
  "styleIsRequired": "Le style est requis",
  "keywordIsRequired": "Un mot-clé est requis",
  "remarkIsRequired": "Une remarque est requise",
  "couponId": "Id de coupon",
  "couponName": "Nom de coupon",
  "expireAt": "Expirer",
  "noCouponsFound": "Aucun coupons trouvé!",
  "yourRequestHasBeenReceived": "Votre demande a été reçue.",
  "youCanViewYourRequestsatMyTickets":
      "Vous pouvez consulter vos demandes à mes billets",
  "incorrectPassword": "Mot de passe incorrect",
  "thePasswordYouenteredisincorrectPleasetryagain":
      "Le mot de passe que vous avez entré est incorrect. Veuillez réessayer",
  "registeredCustomers": "Clients enregistrés",
  "ifYouHaveAnAccountSignInWithYourEmailAddress":
      "Si vous avez un compte, connectez-vous à votre adresse e-mail",
  "pleaseEnterOrderNumberToTrackYourOrder":
      "Veuillez saisir le numéro de commande pour suivre votre commande.",
  "enterOrderNumber": "Entrez le numéro de commande",
  "enteryOurOrderNumberHere": "Entrez votre numéro de commande ici",
  "howDoIFindMyOrderReference": "Comment trouver ma référence de commande?",
  "passwordRegExp":
      "Le mot de passe doit comporter au moins 8 caractères et contenir un mélange de lettres majuscules et minuscules, au moins un numéro et un caractère spécial (par exemple ,! @ #?).",
  "nylonMessengerBackpackMsg":
      "Sac à dos en nylon messager par Balenziaga, fermeture avant avec crochet, poignée supérieure, bretelles réglables, poche zippée de patch avant avec logo de contraste, crochets comme éléments décoratifs.",
  "priceMatchTicket": "Billet de match de prix",
  "enterAddress3": "Entrez l'adresse 3",
  "enterCity": "Entrer dans la ville",
  "pleaseTryWithAnotherEmaiAddressMsg":
      "Veuillez essayer avec une autre adresse e-mail ou écrire à nous à care@brandslabels.com pour obtenir de l'aide.",
  "Alert": "Alerte",
  "requiredVal": "est requis",
  "mustbeof": "doit être de",
  "digits": "chiffres",
  "mustbeanumberExample100": "doit être un nombre. Exemple: 100",
  "character": "personnage",
  "isinvalid": "est invalide!",
  "mustbemorethan2characters": "Doit être plus de 2 caractères",
  "entervalid": "Entrer valide",
  "musthaveatleast2characters": "Doit avoir au moins 2 caractères",
  "confirmpasswordshouldbematchwithpassword":
      "Confirmer le mot de passe devrait correspondre avec le mot de passe",
  "pleaseenterPassword": "Veuillez entrer le mot de passe",
  "mustbemorethan8characters": "Doit être plus de 8 caractères",
  "mobileisRequired": "Le mobile est requis",
  "mobilenumbermust10digits": "Le numéro de mobile doit 10 chiffres",
  "mobileNumbermustbedigits": "Le numéro de mobile doit être des chiffres",
  "yearmustbenumberonly": "L'année doit être uniquement",
  "establishedYearisRequired": "L'année établie est requise",
  "yearmustbebetween1850and": "L'année doit être entre 1850 et",
  "licenseNoisRequired": "La licence n ° est requise",
  "numberofemployeeisRequired": "Le nombre d'employés est requis",
  "numberofemployeeisnotmorethan9999":
      "Le nombre d'employés ne dépasse pas 9999",
  "numberofemployeemustbedigits": "Le nombre d'employés doit être des chiffres",
  "dateisRequired": "La date est requise",
  "pleaseentervaliddate": "Veuillez saisir la date valide",
  "licenseIssuingAuthorityisRequired":
      "L'autorité émettrice de licence est requise",
  "licenseIssuingAuthoritymustbeazandAZ":
      "L'autorité de délivrance de licence doit être A-Z et A-Z",
  "firstNameIsRequired": "Le prénom est requis",
  "lastNameIsRequired": "Le nom de famille est requis",
  "imageUrlIsRequired": "Le lien d'image est requis",
  "enterValidText": "Entrez le texte valide",
  "pleaseCheckYourInternetConnection":
      "S'il vous plait, vérifiez votre connexion internet!",
  "searchForPiesSushiTacos": "Rechercher des tartes, des sushis, des tacos ...",
  "enterSurname": "Entrer le nom de famille",
  "enterStreetAddress": "Entrez l'adresse de la rue",
  "addNew": "Ajouter un nouveau",
  "enterAddress1": "Entrez l'adresse 1",
  "enterAddress2": "Entrez l'adresse 2",
  "noBrandFound": "Aucune marque trouvée",
  "COUPONAPPLIEDSUCCESSFULLYYOUSAVED":
      "Le coupon s'est appliqué avec succès. TU AS SAUVEGARDÉ",
  "ONTHISORDER": "Sur cette commande",
  "areYouSureYouWantToRemove": "Êtes-vous sûr de vouloir désinstaller",
  "couponCode": "Code de coupon?",
  "cancel": "Annuler",
  "itSeemsLikeWeHaveNothingToShowForThisBrand":
      "Il semble que nous n'avons rien à montrer pour cette marque",
  "ifyouwouldlikeUsSendYouTheCollectionFrom":
      "Si vous souhaitez que nous vous envoyions la collection de",
  "plsCreateATicketBelow": "Pls. Créer un billet ci-dessous",
  "itSeemsLikeWeHaveNothingToShowForThisCategory":
      "Il semble que nous n'avons rien à montrer pour cette catégorie",
  "enterName": "Entrez le nom",
  "description": "La description",
};
