const Map<String, String> it = {
  "language": "inglese",
  "appNameText": "Marchi ed etichette",
  "aboutUsText": "Chi siamo",
  "aboutUsTitle": 'SIAMO MARCHI E ETICHETTE',
  "aboutUsContain": 'ESPLORA 100 MIGLIORI MARCHE DEL MONDO',
  "aboutUsContain1":
      'BRANDS & LABELS È UNA MASSIMA DESTINAZIONE DELLA MODA DI LUSSO ONLINE CON 5 MILIONI DI VISITATORI AL MESE E SPEDIZIONI IN TUTTO IL MONDO.',
  "aboutUsContain2":
      '''IL SITO PRESENTA LA MIGLIORE SELEZIONE DEI MIGLIORI DESIGNER AFFIDATI E GIOVANI TALENTI EMERGENTI. BRANDLABELS NASCE A FIRENZE NEI PRIMI ANNI '30, CON L'APERTURA DEL CONCEPT STORE DELL'AZIENDA IN VIA ROMA. ONLINE DAL 1999 L'AZIENDA ATTRIBUISCE IL 90% DEI RICAVI TOTALI ALLE VENDITE ONLINE. AD OGGI RIMANE UN'AZIENDA FAMIGLIARE AL 100% PRIVATA, CON IL NIPOTE DEL FONDATORE, ANDREA PANCONESI IN QUALITÀ DI AD E SUA FIGLIA, ANNAGRETA PANCONESI COME DIRETTORE CREATIVO.''',
  "aboutUsContain3":
      'IL SITO OFFRE UNA VASTA SCELTA DI ABBIGLIAMENTO, SCARPE, BORSE, ACCESSORI, INTERNI PER LA CASA DI LUSSO E BELLEZZA, CON PRODOTTI A DISPOSIZIONE PER UOMO, DONNA E BAMBINO DEI DESIGNER PIÙ PRESTIGIOSI COME BALENCIAGA, VETEMENTS, OFF-WHITE, J.W. ANDERSON, BALMAIN, DOLCE & GABBANA, GUCCI, SAINT LAURENT, VALENTINO, GIVENCHY, LOEWE, JACQUEMUS E ALTRI.',
  "aboutUsContain4":
      '''ATTUALMENTE SONO 200 PERSONE DA 15 PAESI DIVERSI CHE LAVORANO PER PRODURRE E MANTENERE MARCHIE. IL SITO E' DISPONIBILE IN 9 LINGUE: INGLESE, ITALIANO, TEDESCO, CINESE, RUSSO, SPAGNOLO, FRANCESE, COREANO E GIAPPONESE. IL SITO E' REALIZZATO INTERAMENTE IN HOUSE, CON L'UFFICIO DI FIRENZE CHE SI OCCUPA DI PROGETTAZIONE GRAFICA, IT, SERVIZIO CLIENTI, MARKETING E UFFICI ACQUISTI. GLI STILISTI E LA STAMPA OPERANO DALL'UFFICIO BRANDLABELS NELLA CAPITALE MONDIALE DELLA MODA – MILANO.''',
  "aboutUsContain5":
      'TUTTI GLI ORDINI VENGONO SPEDITI IN TUTTO IL MONDO DALLA SEDE DEI MARCHI ETICHETTE IN SCATOLE PREPARATE CON LA MASSIMA CURA E UTILIZZANO I MIGLIORI MATERIALI, DALLE BORSE PER SCARPE FIRMATE AL NASTRO PERSONALIZZATO.',
  "aboutUsContain6":
      'BRANDLABELS HA AVUTO 1,5 MILIONI DI VISITATORI UNICI ACCESSO AL SITO NEL 2008 E È CRESCITA A 53 MILIONI DI VISITATORI UNICI NEL 2017. OLTRE IL 15% DELLE VENDITE ONLINE VENGONO GENERATE DAGLI STATI UNITI, SEGUITI DA GERMANIA, REGNO UNITO, ITALIA, CINA E FRANCIA.',
  "aboutUsContain7":
      'BRANDLABELS SUPERA I CONFINI DEL LUXURY RETAIL LANDSCAPE SIA ON CHE OFFLINE CON UNA SCELTA DI SERVIZI ESCLUSIVI E INIZIATIVE DI MARCHIO TRA CUI BUY IT FIRST, LUXURY CLUB, SNEAKERS CLUB, LVR PRIVILEGE E LVR EDITION.',
  "profile": "Profilo",
  "firstNameText": "Nome di battesimo",
  "lastNameText": "Cognome",
  "emailText": "E-mail",
  "ContactNoText": "Contatto n.",
  "websiteUrlText": "URL del sito",
  "cityText": "Città",
  "countryText": "Paese",
  "postCodeText": "Codice postale",
  "socialLinksText": "Collegamenti sociali",
  "facebookText": "Facebook",
  "instagramText": "Instagram",
  "twitterText": "Twitter",
  "youtubeText": "Youtube",
  "linkendinText": "Linkendin",
  "pinterestText": "Pinterest",
  "followersText": "Seguaci",
  "mr": "Mr.",
  "letsText": "Andiamo",
  "orderIdTitle": '''Il tuo ordine n. è: ''',
  "orderDateTitle": '''Data dell'ordine: 15 settembre 2021''',
  "orderNumberTitle": '''NUMERO D'ORDINE: ''',
  "orderConfirm": "GRAZIE PER IL VOSTRO ACQUISTO!",
  "name": "NOME",
  "sku": "SKU",
  "price": "PREZZO",
  "qty": "QTÀ",
  "subTotal": "TOTALE PARZIALE",
  "action": "AZIONE",
  "addressBook": "Rubrica",
  "billing": "Fatturazione",
  "shipping": "Spedizione",
  "orderContain":
      '''Ti invieremo un'e-mail di conferma dell'ordine con i dettagli e le informazioni di tracciamento.''',
  "referFriendText": "Segnala amico",
  "returnsRefundsText": "Resi e rimborsi",
  "faqText": "FAQ",
  "contactText": "Contatto",
  "socialText": "Sociale",
  "companyText": "Azienda",
  "myOrders": "i miei ordini",
  "myOrderImage": "Immagine",
  "productName": "nome del prodotto",
  "quantity": "Qtà",
  "status": "Stato",
  "paymentMethod": " Metodo di pagamento",
  "shippingAddress": "indirizzo di spedizione",
  "billingAddress": "Indirizzo Di Fatturazione",
  "continueShopping": "Continua a fare acquisti",
  "generalAndOrderEnquiriesText": "RICHIESTE GENERALI E DEGLI ORDINI",
  "gdpText": "PIL",
  "engText": "ING",
  "nameText": "Nome*",
  "surNameText": "Cognome*",
  "emailAddressText": "Indirizzo e-mail*",
  "confirmEmailAddressText": "Conferma l'indirizzo e-mail*",
  "subjectText": "Argomento*",
  "phoneNumberText": "Numero di telefono",
  "whatsOnYourMindText": "Cos'hai in mente?*",
  "queryDescription":
      "Qualunque sia la tua domanda, usa il modulo di contatto qui sotto per metterti in contatto, il nostro team è pronto ad aiutarti 24 ore su 24, 7 giorni su 7",
  "submitText": "INVIA",
  "typeOfEnquiryText": "Tipo di richiesta*",
  "registeredCustomersText": "Clienti registrati",
  "signInDescriptionText":
      "Se hai un account, accedi con il tuoindirizzo email.",
  "forgotYourPasswordText": "Hai dimenticato la password?",
  "signInText": "Registrazione",
  "newCustomersText": "nuovi clienti",
  "newCustomersDescriptionText":
      "La creazione di un account ha molti vantaggi:\ncontrolla più velocemente, mantieni più di un indirizzo,\ntieni traccia degli ordini e altro ancora.",
  "createAccountText": "Creare un account",
  "aboutProjectNameText": "Informazioni su marchi ed etichette",
  "helpAndInformationText": "Aiuto e informazioni",
  "moreFromProjectText": "Altro da Marchi ed etichette",
  "newsLetterText": "Lettera di notizie",
  "subscribeText": "sottoscrivi",
  "passwordText": "Parola d'ordine",
  "homeText": "Casa",
  "searchText": "Ricerca",
  "designersText": "Designer",
  "wishListText": "Lista dei desideri",
  "loginText": "Login",
  "myAccountText": "Il mio conto",
  "yourEmailText": "La tua email",
  "checkoutText": "Guardare",
  "purchaseText":
      "Inserisci i tuoi dettagli qui sotto per completare l'acquisto",
  "shippingAddressText": "indirizzo di spedizione",
  "shippingMethodText": "metodo di spedizione",
  "paymentMethodText": "Metodo di pagamento",
  "orderSummaryText": "Riepilogo ordine",
  "addressText":
      "admin admintast prodotto, prodotto di prova, prodotto di prova prodotto di prova, b12345 302006Russia 1234567890",
  "newAddressText": "Nuovo indirizzo",
  "itemInCartText": "Articolo nel carrello",
  "qtyText": "Qtà",
  "applyDiscountCodeText": "Applicare il codice sconto",
  "enterDiscountCodeText": "Inserisci il codice sconto",
  "applyDiscountText": "Applicare lo sconto",
  "orderTotalText": "Ordine totale",
  "orderCommentText": "Commento dell'ordine",
  "placeOrderText": "INVIA ORDINE",
  "myOrdersText": "I MIEI ORDINI",
  "myWishlistText": "La mia lista dei desideri",
  "addressBookText": "Rubrica",
  "accountInformationText": "Informazioni account",
  "storePaymentText": "METODI DI PAGAMENTO MEMORIZZATI",
  "newsLetter1Text": "ABBONAMENTI ALLA NEWSLETTER",
  "enterEmailAddress": "Inserisci l'indirizzo email",
  "enterConfirmEmailAddress": "Inserisci l'indirizzo email di conferma",
  "enterPhoneNumber": "Inserisci il numero di telefono",
  "enterValidEmailAddress": "Inserisci un indirizzo email valido",
  "confirmEmailNotMatch":
      "Conferma che l'e-mail non corrisponde all'indirizzo e-mail",
  "phoneNumberIsRequired": "Il numero di telefono è obbligatorio",
  "phoneNumberIsNotValid": "Il numero di telefono non è valido",
  "gstIdentificationNumber":
      "Il numero di identificazione GST non è valido. Dovrebbe essere in questo formato 11AAAAA1111Z1A1",
  "emailRequired": "L'email è obbligatoria",
  "invalidEmail": "Email non valida",
  "confirmEmailIsRequired": "Conferma che l'email è obbligatoria",
  "confirmEmailShouldBeMatchWithEmail":
      "Conferma che l'email deve corrispondere all'email",
  "youHaveReachedYourMaximumLimit":
      "Hai raggiunto il limite massimo di caratteri consentiti",
  "passwordIsRequired": "La password è obbligatoria",
  "successfullyLoggedOut": "Sei stato disconnesso con successo",
  "emailAddress": "Indirizzo e-mail",
  "enterEmailToTrackRequest.":
      "Inserisci la tua email per tenere traccia della tua richiesta.",
  "firstName": "Nome di battesimo",
  "lastName": "Cognome",
  "dateOfBirth.": "Data di nascita",
  "dateOfMarriage": "Anniversario di matrimonio",
  "signUpForNewsletter": "Iscriviti alla newsletter",
  "email": "E-mail",
  "password": "Parola d’ordine",
  "confirmPassword": "Conferma password",
  "typesOfEnquiry": "Tipi di richiesta",
  "confirmPasswordIsRequired.": "ConfirmPassword è obbligatorio",
  "orderDetails": "Dettagli dell'ordine",
  "noDataAvailable": "Nessun dato disponibile",
  "myAccount": "Il mio account",
  "mrs": "Signora.",
  "communicationPrefences.": "Preferenze di comunicazione",
  "subscribeNewsletters": "Iscriviti alla newsletter di ounass..",
  "aboutUs": "Chi Siamo",
  "sms": "SMS",
  "save": "Salvare",
  "tearmsAndCondition": "TERMINI E CONDIZIONI",
  "subscribeOffersAndMore":
      "Iscriviti per essere il primo con i nostri nuovi arrivi, collezioni esclusive, offerte e altro ancora.",
  "ourServices": "I nostri servizi",
  "delivery": "Consegna",
  "ourWebsite": "Il nostro sito web",
  "addToCart": "Aggiungi al carrello",
  "subscribe": "Abbonarsi",
  "productDetails": "Dettagli del prodotto",
  "priceMatch": "Corrispondenza dei prezzi",
  "composition": "Composizione",
  "color": "Colore",
  "chooseAnOption": "Scegli un'opzione...",
  "buyNow": "Acquista ora",
  "notifyMeWhenThisProductIsInStock1":
      "Avvisami quando questo prodotto e 'disponibile",
  "yourBestPriceAlways": "Il tuo miglior prezzo - sempre.",
  "IfYourPreferredItemIsLowerMsg":
      "Se il tuo articolo preferito ha un prezzo più basso in qualsiasi altro negozio al momento attuale, corrisponderemo al prezzo e ti offriremo il 10% di credito aggiuntivo per il tuo prossimo acquisto.",
  "simplyLetUsKnowByClickingHere":
      "Facci semplicemente sapere facendo clic qui.",
  "alreadyMadeYourPurchase": "Ha già fatto il tuo acquisto.",
  "dontWorryLetUsKnowByClickingMsg":
      "Non preoccuparti facci sapere facendo clic qui e noi il nostro team di assistenza clienti ti rimborserà la differenza se l'acquisto è stato effettuato negli ultimi 30 giorni.",
  "pleaseSeeFAQsByClickingHere":
      "Si prega di consultare le FAQ facendo clic qui",
  "filter": "Filtro",
  "sort": "Ordinare",
  "sortBy": "Ordina per",
  "noProductsFound": "Nessun prodotto trovato",
  "createTicket": "Crea ticket",
  "more": "& Di più...",
  "bgbp": "Sterlina inglese",
  "findBrand": "Trova marchi",
  "itSeemsWeHaveNothingToShowFor": "Sembra che non abbiamo nulla da mostrare",
  "ifYouWouldLikeToHaveMoreInformationAbout":
      "Se desideri avere maggiori informazioni su",
  "thenPleaseCreateATicket": "Quindi si prega di creare un biglietto",
  "contactInformation": "Informazioni sui contatti",
  "edit": "Modificare",
  "changePassword": "Cambia la password",
  "youHaveNoProductsInYourWishList":
      "Non hai prodotti nella tua lista dei desideri.",
  "toBbeUpdated": "Essere aggiornato",
  "youHaveNoSavedAddressAddnewAddressToContinueWithCheckout":
      "Non hai un indirizzo salvato Aggiungi nuovo indirizzo per continuare con il checkout",
  "shipHere": "Spesa qui",
  "enterFirstName": "Immettere il nome",
  "enterLastName": "Immettere il cognome",
  "enterStreetAddress1": "Inserisci l'indirizzo di strada 1",
  "streetAddress1": "Indirizzo 1",
  "enterStreetAdress2": "Inserisci Street Address 2",
  "streetAddress2": "Indirizzo di strada 2",
  "enterStreetAddress3": "Inserisci l'indirizzo di strada 3",
  "streetAddress3": "Indirizzo di strada 3",
  "enterCityName": "Immettere il nome della città",
  "city": "Città",
  "country": "Paese",
  "enterZipPostalCode": "Immettere il codice postale zip",
  "zipPostalCode": "Zip / Codice postale",
  "stateProvince": "Stato/Provincia",
  "enterStateProvince": "Entra in stato/provincia",
  "emailAddressRequired": "Indirizzo e -mail richiesto",
  "cancelCoupon": "Annulla coupon",
  "apply": "Applicare",
  "viewCouponList": "Visualizza elenco coupon",
  "coupons": "Coupon",
  "changeLanguageAndCurrency": "Cambia lingua e valuta",
  "youHaveNoOrders": "Non hai ordini",
  "youHaveNoTickets": "Non hai biglietti",
  "category": "Categoria",
  "createNewTicket": "Crea nuovo biglietto",
  "positiveImpactSustainability": "Impatto positivo + sostenibilità",
  "thereAreStillMoreThanMSG":
      "Ci sono ancora più di un miliardo di persone in tutto il mondo che vivono in estrema povertà con meno di \$ 1,25 al giorno. Solo nella Thailandia, esistono più di un milione di membri di tribù Hill ai margini della società - negato la cittadinanza, escluso dal mercato del lavoro formale e vulnerabile allo sfruttamento e al traffico.",
  "atYellowLeafHammocksMsg":
      "Alle amache gialle crediamo che la creazione di posti di lavoro etica sia una soluzione a lungo termine a lungo termine alla povertà estrema.",
  "insteadOfOrganizingMsg":
      "Invece di organizzare un patchwork di donazioni di beneficenza per fornire acqua, nutrizione, abbigliamento, ecc., Stiamo lavorando direttamente con le famiglie per costruire una strategia completa, dignitosa e a lungo termine verso un futuro più luminoso. Le cause alla base della povertà sistemica sono complicate, ma la stabilità finanziaria a lungo termine è a portata di mano.",
  "toPutItSimplyMsg":
      "Per dirla semplicemente: concentrandoci sul sostentamento, possiamo ritagliare l'uomo di mezzo, ottenere denaro direttamente nelle mani di madri intelligenti + intraprendenti e consentire alle famiglie di affrontare i propri problemi (senza essere soggetti all'agenda di chiunque altro).",
  "acrossThreeWeavingCommunitiesMsg":
      "\"In tre comunità di tessitura, stiamo lavorando per creare posti di lavoro per le madri e costruire una base per una trasformazione positiva della comunità. Attraverso un lavoro di tessitura flessibile e sicuro per la \"\"prosperità\"\", i nostri artigiani sono in grado di sollevare le loro famiglie dalla povertà e dalla schiavitù del debito alla classe media.\"",
  "creatingJobsForWomenMsg":
      "** La creazione di posti di lavoro per le donne è particolarmente importante per la trasformazione della comunità: la ricerca mostra che le donne spenderanno fino al 90% dei loro guadagni in materia di salute, alimentazione e istruzione delle loro famiglie. Trasformare le donne in capofamiglia migliora il loro status nella comunità, costruisce l'autostima e consente loro di raggruppare le risorse per migliorare le infrastrutture.",
  "theFoundationForABrighterFuter": "La base per un futro più luminoso",
  "theSecurityOfAStableMsg":
      "La sicurezza di una fonte di entrate in crescita stabile ha avuto un impatto enorme sul villaggio. I Mlabri sono stati in grado di iniziare una scuola e costruire un centro comunitario per la tessitura e la socializzazione. Hanno istituito uno dei primi fondi di disoccupazione della Thailandia. Con un maggiore potere economico, hanno fatto pressioni con successo per la cittadinanza e i diritti civili, che sono stati concessi per la prima volta nel 2001. La tessitura delle amache è un lavoro flessibile, ideale per le madri che possono lavorare da casa e fare i loro programmi. Sfortunatamente, senza accesso ai mercati globali, la domanda di amache era limitata alla stagione del turismo tailandese e non c'era modo di garantire un lavoro tutto l'anno.",
  "spreadingLastingChangeTheHammockRrevolution":
      "Diffusione del cambiamento duraturo: The Hammock Rrevolution",
  "thisIsAboutWhereMsg":
      "Si tratta di dove la foglia gialla si unisce alla storia! Negli ultimi anni abbiamo lavorato per sviluppare canali di vendita coerenti, costruire partenariati internazionali e stabilizzare le operazioni all'interno dei villaggi.",
  "corollaryEconomicMsg":
      "Le opportunità economiche corollari, come un ufficio postale, la preparazione alimentare e l'agricoltura del caffè sostenibile, sono sorte per impiegare coloro che non sono intrecciati. La nostra partnership con KIVA ha stimolato la formazione finanziaria e la pianificazione finanziaria, con molti tessitori che aprono i conti bancari per la prima volta nella loro vita!",
  "wWithOurGrowthMsg":
      "Con la nostra crescita che continua ad accelerare, non solo saremo in grado di impiegare tutti i tessitori di Mlabri tutto l'anno, saremo anche in grado di continuare ad espandere e fornire formazione e lavoro in corso alle comunità di Tribe Hill nella regione circostante. Fino a quando i lavori di tessitura e lavori sostenibili saranno disponibili in tutta l'area, le pratiche agricole distruttive continueranno e il ciclo di sfruttamento della servitù indenturata non finirà veramente.",
  "throughTheEstablishmentMsg":
      "Attraverso l'istituzione di foglie gialle come marchio di stile di vita globale, i villaggi della Tribù Hill con cui collaboriamo saranno in grado di sostenere questo impatto positivo e continuare a gettare le basi per un futuro più luminoso.",
  "enterWebsite": "Inserisci il sito web",
  "enterPostCode": "Immettere il codice postale",
  "thankYouForYourInterest":
      "Grazie per il tuo interesse a lavorare con Brands Labels",
  "oneOfOurTeamMembersWillBeInTouchSoon":
      "Uno dei membri del nostro team sarà presto in contatto",
  "forAnyAdditionalQueriesPleaseWriteTo ":
      "Per qualsiasi domanda aggiuntiva, scrivi a",
  "theProductIsOutOfStock": "Il prodotto è esaurito.",
  "whateverYourQueryUseTheContactFormBelowMsg":
      "Qualunque sia la tua domanda. Utilizzare il modulo di contatto sottostante per entrare in touch-ourteam è pronto per aiutare 24*7",
  "enterSubject": "Immettere il soggetto",
  "enterSomeText": "Immettere un po 'di testo",
  "enterDetailsBelowToSend":
      "Inserisci i dettagli di seguito per inviare un codice coupon al 10% al tuo amico",
  "enterFriendName": "Immettere il nome dell'amico",
  "friendFirstName": "Nome amico",
  "enterFirstEmailAddress": "Inserisci il primo indirizzo email",
  "friendEmailAddress": "Indirizzo e -mail amico",
  "enterFirstPhoneNumber": "Immettere il primo numero di telefono",
  "friendPhoneNumber": "Numero di telefono amico",
  "register": "Registrati",
  "dateOfBirthIsRequired": "È richiesto dateOfbirth",
  "marriageAnniversaryIsRequired": "È richiesto l'anniversario del matrimonio",
  "surnameIsRequired": "È richiesto il cognome",
  "date": "Data",
  "showDialog": "Mostra il dialogo",
  "removeProduct": "Rimuovere il prodotto",
  "areYouSureWantToRemoveThisProductFromCart":
      "Sei sicuro di rimuovere questo prodotto dal carrello?",
  "yes": "SÌ",
  "no": "NO",
  "addToWishlist": "Aggiungi alla lista dei desideri",
  "onceYouAddThisProductToWishlistThenItWillBeRemoveFromAart":
      "Una volta aggiunto questo prodotto a Wish Elist, verrà rimosso dal carrello",
  "ok": "OK",
  "nouHaveNoItemsInYourShoppingCart": "Non ci sono articoli nel tuo carrello.",
  "Discount": "Sconto",
  "enterCouponCode": "Immettere il codice coupon",
  "removeCoupon": "Rimuovere il coupon",
  "availableCouponList": "Elenco coupon disponibile",
  "allCouponsList": "Tutti gli elenchi di coupon",
  "addProductToYourWishList":
      "Aggiungi il prodotto alla tua lista dei desideri",
  "configurable": "configurabile",
  "Missing": "Mancante",
  "Amount": "Quantità",
  "Balance": "Equilibrio",
  "Remarks": "Osservazioni",
  "myAddresses": "I miei indirizzi",
  "noAddressFound": "Nessun indirizzo trovato",
  "addAddress": "Aggiungi indirizzo",
  "updateAddress": "Indirizzo di aggiornamento",
  "expectedShipmentDate": "Data di spedizione prevista",
  "brandNameIsRequired": "È richiesto il marchio",
  "styleIsRequired": "È richiesto lo stile",
  "keywordIsRequired": "È richiesta la parola chiave",
  "remarkIsRequired": "È richiesta l'osservazione",
  "couponId": "Coupon ID",
  "couponName": "Nome coupon",
  "expireAt": "Scadere a",
  "noCouponsFound": "Nessun coupon trovato!",
  "yourRequestHasBeenReceived": "La tua richiesta è stata ricevuta.",
  "youCanViewYourRequestsatMyTickets":
      "Puoi visualizzare le tue richieste sui miei biglietti",
  "incorrectPassword": "Password errata",
  "thePasswordYouenteredisincorrectPleasetryagain":
      "La password che hai inserito è errata. Per favore riprova",
  "registeredCustomers": "Clienti registrati",
  "ifYouHaveAnAccountSignInWithYourEmailAddress":
      "Se hai un account, accedi al tuo indirizzo email",
  "pleaseEnterOrderNumberToTrackYourOrder":
      "Inserisci il numero dell'ordine per tenere traccia del tuo ordine.",
  "enterOrderNumber": "Immettere il numero dell'ordine",
  "enteryOurOrderNumberHere": "Inserisci il tuo numero di ordine qui",
  "howDoIFindMyOrderReference": "Come trovo il mio riferimento all'ordine?",
  "passwordRegExp":
      "La password deve essere lunga almeno 8 caratteri e contenere una miscela di lettere maiuscole e minuscole, almeno un numero e un carattere speciale (ad esempio ,! @ #?).",
  "nylonMessengerBackpackMsg":
      "Lo zaino in nylon Messenger di Balenziaga, chiusura anteriore con gancio, maniglia superiore, spalline regolabili, tasca con zip con patch anteriore con logo a contrasto, ganci come elementi decorativi.",
  "priceMatchTicket": "Bicket per corrispondenza dei prezzi",
  "enterAddress3": "Immettere l'indirizzo 3",
  "enterCity": "Entra in città",
  "pleaseTryWithAnotherEmaiAddressMsg":
      "Prova con un altro indirizzo e -mail o scrivi a care@brandslabels.com per ulteriore assistenza.",
  "Alert": "Mettere in guardia",
  "requiredVal": "è obbligatorio",
  "mustbeof": "deve essere di",
  "digits": "cifre",
  "mustbeanumberExample100": "deve essere un numero. Esempio: 100",
  "character": "carattere",
  "isinvalid": "è invalido!",
  "mustbemorethan2characters": "Deve essere più di 2 caratteri",
  "entervalid": "Immettere valido",
  "musthaveatleast2characters": "Deve avere almeno 2 caratteri",
  "confirmpasswordshouldbematchwithpassword":
      "Confermare che la password dovrebbe essere abbinata alla password",
  "pleaseenterPassword": "Per favore, inserisci la password",
  "mustbemorethan8characters": "Deve essere più di 8 caratteri",
  "mobileisRequired": "È richiesto il cellulare",
  "mobilenumbermust10digits": "Il numero di cellulare deve 10 cifre",
  "mobileNumbermustbedigits": "Il numero di cellulare deve essere cifre",
  "yearmustbenumberonly": "L'anno deve essere solo numero",
  "establishedYearisRequired": "È richiesto l'anno stabilito",
  "yearmustbebetween1850and": "L'anno deve essere tra il 1850 e",
  "licenseNoisRequired": "È richiesta la licenza no",
  "numberofemployeeisRequired": "È richiesto il numero di dipendenti",
  "numberofemployeeisnotmorethan9999":
      "Il numero di dipendenti non è più di 9999",
  "numberofemployeemustbedigits": "Il numero di dipendenti deve essere cifre",
  "dateisRequired": "È richiesta la data",
  "pleaseentervaliddate": "Inserisci la data valida",
  "licenseIssuingAuthorityisRequired":
      "È richiesta l'autorità di rilascio della licenza",
  "licenseIssuingAuthoritymustbeazandAZ":
      "L'autorità di rilascio della licenza deve essere A-Z e A-Z",
  "firstNameIsRequired": "È richiesto il nome",
  "lastNameIsRequired": "È richiesto cognome",
  "imageUrlIsRequired": "È richiesto il collegamento dell'immagine",
  "enterValidText": "Immettere il testo valido",
  "pleaseCheckYourInternetConnection":
      "Per favore controlla la tua connessione Internet!",
  "searchForPiesSushiTacos": "Cerca torte, sushi, tacos ...",
  "enterSurname": "Immettere il cognome",
  "enterStreetAddress": "Inserisci l'indirizzo di strada",
  "addNew": "Aggiungere nuova",
  "enterAddress1": "Immettere l'indirizzo 1",
  "enterAddress2": "Immettere l'indirizzo 2",
  "noBrandFound": "Nessun marchio trovato",
  "COUPONAPPLIEDSUCCESSFULLYYOUSAVED":
      "Coupon applicato con successo. HAI SALVATO",
  "ONTHISORDER": "Su questo ordine",
  "areYouSureYouWantToRemove": "Sei sicuro di voler rimuovere",
  "couponCode": "codice coupon?",
  "cancel": "Annulla",
  "itSeemsLikeWeHaveNothingToShowForThisBrand":
      "Sembra che non abbiamo nulla da mostrare per questo marchio",
  "ifyouwouldlikeUsSendYouTheCollectionFrom":
      "Se desideri che ti mandassimo la collezione da",
  "plsCreateATicketBelow": "pls. Crea un biglietto qui sotto",
  "itSeemsLikeWeHaveNothingToShowForThisCategory":
      "Sembra che non abbiamo nulla da mostrare per questa categoria",
  "enterName": "Inserisci il nome",
  "description": "Descrizione",
};
