const Map<String, String> ja = {
  "language": "英語",
  "appNameText": "ブランドとラベル",
  "aboutUsText": "私たちに関しては",
  "aboutUsTitle": '私たちはブランドとラベルです',
  "aboutUsContain": '100年代の世界最高のブランドを探索する',
  "aboutUsContain1":
      'ブランドとラベルは、月に500万人の訪問者がおり、世界中に出荷されている、オンラインの高級ファッションの目的地です。',
  "aboutUsContain2":
      'このウェブサイトは、若くて新しい才能と同様に、トップの確立されたデザイナーの最高の選択を特徴とします。 BRANDSLABELSは、1930年代初頭にフィレンツェで設立され、ROMA経由で同社のエポニムコンセプトストアがオープンしました。オンライン1999年以来、同社は総収益の90％をオンライン販売に帰属させています。今日まで、それは100％個人所有の家族経営であり、創設者の孫であり、アンドレア・パンコネージがCEOを務め、彼の娘であるアナグレタ・パンコネージがクリエイティブディレクターを務めています。',
  "aboutUsContain3":
      'このサイトでは、衣料品、靴、バッグ、アクセサリー、高級住宅のインテリア、ビューティーを幅広く取り揃えており、バレンシアガ、ベテメント、オフホワイトなどの最も有名なデザイナーの男性、女性、子供向けの製品を取り揃えています。 ANDERSON、BALMAIN、DOLCE＆GABBANA、GUCCI、SAINT LAURENT、VALENTINO、GIVENCHY、LOEWE、JACQUEMUSなど。',
  "aboutUsContain4":
      '現在、ブランドラベルの生産と維持に取り組んでいる15の異なる国から200人の人々がいます。このサイトは、英語、イタリア語、ドイツ語、中国語、ロシア語、スペイン語、フランス語、韓国語、日本語の9つの言語で利用できます。このサイトは完全に社内で作成されており、フローレンスオフィスにはグラフィックデザイン、IT、カスタマーサービス、マーケティングおよび購入部門があります。スタイリストとプレスチームは、世界のファッションの都–ミラノのブランドラベルオフィスから運営されています。',
  "aboutUsContain5":
      'すべての注文は、署名シューバッグからパーソナライズされたリボンまで、最大限の注意を払って準備され、最高の素材を使用したボックスのブランドラベル本社から世界中に発送されます。',
  "aboutUsContain6":
      'BRANDSLABELSは、2008年に150万人のユニークな訪問者がサイトにアクセスし、2017年には5300万人のユニークな訪問者に成長しました。オンライン販売の15％以上が米国から生成され、ドイツ、英国、イタリア、中国、フランスがそれに続きます。',
  "aboutUsContain7":
      'BRANDSLABELSは、LUXURY RETAILの景観の境界をオンラインとオフラインの両方で推進し、独占的なサービスと、最初に購入する、LUXURY CLUB、SNEAKERS CLUB、LVR PRIVILEGE、LVREDITIONSを含む商標イニシアチブを提供します。',
  "profile": "プロフィール",
  "firstNameText": "ファーストネーム",
  "lastNameText": "苗字",
  "emailText": "Eメール",
  "ContactNoText": "連絡先番号。",
  "websiteUrlText": "ウェブサイトのURL",
  "cityText": "市",
  "countryText": "国",
  "postCodeText": "郵便番号",
  "socialLinksText": "ソーシャルリンク",
  "facebookText": "フェイスブック",
  "instagramText": "インスタグラム",
  "twitterText": "ツイッター",
  "youtubeText": "Youtube",
  "linkendinText": "リンケンディン",
  "pinterestText": "Pinterest",
  "followersText": "フォロワー",
  "mr": "氏。",
  "letsText": "さあ行こう",
  "orderIdTitle": '''ご注文番号：''',
  "orderDateTitle": '注文日：2021年9月15日',
  "orderNumberTitle": '注文番号：',
  "orderConfirm": "ご購入いただきありがとうございます！",
  "name": "名前",
  "sku": "SKU",
  "price": "価格",
  "qty": "数量",
  "subTotal": "小計",
  "action": "アクション",
  "addressBook": "住所録",
  "billing": "請求する",
  "shipping": "運送",
  "orderContain": '詳細と追跡情報が記載された注文確認メールをお送りします。',
  "referFriendText": "友達を紹介する",
  "returnsRefundsText": "返品と返金",
  "faqText": "よくある質問",
  "contactText": "連絡先",
  "socialText": "社交",
  "companyText": "会社",
  "myOrders": "私の注文",
  "myOrderImage": "画像",
  "productName": "商品名",
  "quantity": "数量",
  "status": "スターテス",
  "paymentMethod": " 支払方法",
  "shippingAddress": "お届け先の住所",
  "billingAddress": "請求先住所",
  "continueShopping": "ショッピングを続ける",
  "generalAndOrderEnquiriesText": "一般および注文に関するお問い合わせ",
  "gdpText": "GDP",
  "engText": "ENG",
  "nameText": "名前*",
  "surNameText": "姓*",
  "emailAddressText": "電子メールアドレス*",
  "confirmEmailAddressText": "メールアドレスを確認*",
  "subjectText": "主題*",
  "phoneNumberText": "電話番号",
  "whatsOnYourMindText": "何を考えているの？*",
  "queryDescription":
      "ご質問が何であれ、以下のお問い合わせフォームを使用してご連絡ください。私たちのチームは24時間年中無休でサポートいたします。",
  "submitText": "参加する",
  "typeOfEnquiryText": "お問い合わせの種類*",
  "registeredCustomersText": "登録済みの客",
  "signInDescriptionText": "アカウントをお持ちの場合は、\nemailアドレスでサインインしてください。",
  "forgotYourPasswordText": "パスワードをお忘れですか？",
  "signInText": "サインイン",
  "newCustomersText": "新しいお客様",
  "newCustomersDescriptionText":
      "アカウントを作成することには多くの利点があります： nより速くチェックアウトし、複数の住所を保持し、\n注文を追跡します。",
  "createAccountText": "アカウントを作成する",
  "aboutProjectNameText": "ブランドとラベルについて",
  "helpAndInformationText": "ヘルプと情報",
  "moreFromProjectText": "Brands＆Labelsのその他のアイテム",
  "newsLetterText": "ニュースレター",
  "subscribeText": "購読",
  "passwordText": "パスワード",
  "homeText": "家",
  "searchText": "検索",
  "designersText": "デザイナー",
  "wishListText": "ウィッシュリスト",
  "loginText": "ログイン",
  "myAccountText": "マイアカウント",
  "yourEmailText": "あなたのEメール",
  "checkoutText": "チェックアウト",
  "purchaseText": "購入を完了するには、以下に詳細を入力してください",
  "shippingAddressText": "お届け先の住所",
  "shippingMethodText": "配送方法",
  "paymentMethodText": "支払方法",
  "orderSummaryText": "注文の概要",
  "addressText": "admin admintast製品、テスト製品、テスト製品テスト製品、b12345302006ロシア1234567890",
  "newAddressText": "新しいアドレス",
  "itemInCartText": "カート内のアイテム",
  "qtyText": "数量",
  "applyDiscountCodeText": "割引コードを適用する",
  "enterDiscountCodeText": "割引コードを入力してください",
  "applyDiscountText": "割引を適用する",
  "orderTotalText": "注文合計",
  "orderCommentText": "注文コメント",
  "placeOrderText": "注文する",
  "myOrdersText": "私の注文",
  "myWishlistText": "私のウィッシュリスト",
  "addressBookText": "住所録",
  "accountInformationText": "口座情報",
  "storePaymentText": "保管された支払い方法",
  "newsLetter1Text": "ニュースレターの購読",
  "enterEmailAddress": "メールアドレスを入力",
  "enterConfirmEmailAddress": "確認用メールアドレスを入力",
  "enterPhoneNumber": "電話番号を入力",
  "enterValidEmailAddress": "有効なメールアドレスを入力",
  "confirmEmailNotMatch": "メールアドレスが一致しないことを確認する",
  "phoneNumberIsRequired": "電話番号は必須です",
  "phoneNumberIsNotValid": "電話番号が無効です",
  "gstIdentificationNumber": "GST識別番号が無効です。この11AAAAA1111Z1A1形式である必要があります",
  "emailRequired": "メールアドレスは必須です",
  "invalidEmail": "無効な電子メール",
  "confirmEmailIsRequired": "メールアドレスの確認が必要です",
  "confirmEmailShouldBeMatchWithEmail": "メールがメールと一致することを確認する",
  "youHaveReachedYourMaximumLimit": "許可される文字数の上限に達しました",
  "passwordIsRequired": "パスワードが必要です",
  "successfullyLoggedOut": "正常にログアウトされました",
  "emailAddress": "メルアド",
  "enterEmailToTrackRequest.": "あなたの要求を追跡するためにあなたの電子メールを入力してください。",
  "firstName": "名前",
  "lastName": "名字",
  "dateOfBirth.": "生年月日",
  "dateOfMarriage": "結婚記念日",
  "signUpForNewsletter": "ニュースレターにサインアップ",
  "email": "電子メール",
  "password": "パスワード",
  "confirmPassword": "パスワードの確認",
  "typesOfEnquiry": "お問い合わせの種類",
  "confirmPasswordIsRequired.": "パスワードの確認が必要です",
  "orderDetails": "注文の詳細",
  "noDataAvailable": "利用可能なデータがありません",
  "myAccount": "マイアカウント",
  "mrs": "さん。",
  "communicationPrefences.": "通信設定",
  "subscribeNewsletters": "ounassニュースレターを購読する..",
  "aboutUs": "我々について",
  "sms": "ティッカー",
  "save": "セーブ",
  "tearmsAndCondition": "条件",
  "subscribeOffersAndMore": "新着商品、限定コレクション、オファーなどを最初に購読してください。",
  "ourServices": "当社のサービス",
  "delivery": "配達",
  "ourWebsite": "当社のウェブサイト",
  "addToCart": "カートに追加",
  "subscribe": "購読する",
  "productDetails": "製品概要",
  "priceMatch": "プライスマッチ",
  "composition": "組成",
  "color": "色",
  "chooseAnOption": "オプションを選択してください...",
  "buyNow": "今買う",
  "notifyMeWhenThisProductIsInStock1": "この製品が在庫しているときに私に通知してください",
  "yourBestPriceAlways": "あなたの最高の価格 - 常に。",
  "IfYourPreferredItemIsLowerMsg":
      "お好みのアイテムが当時の他の店で価格が低い場合は、価格と一致し、次の購入のために10％の追加ストアクレジットを提供します。",
  "simplyLetUsKnowByClickingHere": "ここをクリックしてお知らせください。",
  "alreadyMadeYourPurchase": "すでに購入しました。",
  "dontWorryLetUsKnowByClickingMsg":
      "ここをクリックして私たちに知らせてはいけません。私たちのカスタマーサポートチームは、過去30日以内に購入が行われた場合に違いを返金します。",
  "pleaseSeeFAQsByClickingHere": "ここをクリックして、FAQSを参照してください",
  "filter": "フィルター",
  "sort": "選別",
  "sortBy": "並び替え",
  "noProductsFound": "製品は見つかりません",
  "createTicket": "チケットを作成します",
  "more": "＆ もっと...",
  "bgbp": "英ポンド",
  "findBrand": "ブランドを見つけます",
  "itSeemsWeHaveNothingToShowFor": "私たちには何も見せないようです",
  "ifYouWouldLikeToHaveMoreInformationAbout": "詳細情報をご希望の場合",
  "thenPleaseCreateATicket": "次に、チケットを作成してください",
  "contactInformation": "連絡先",
  "edit": "編集",
  "changePassword": "パスワードを変更する",
  "youHaveNoProductsInYourWishList": "ウィッシュリストには製品がありません。",
  "toBbeUpdated": "更新されます",
  "youHaveNoSavedAddressAddnewAddressToContinueWithCheckout":
      "保存されたアドレスがありませんチェックアウトを続行するために新しいアドレスを追加する新しいアドレスを追加します",
  "shipHere": "ここに出荷します",
  "enterFirstName": "名を入力します",
  "enterLastName": "姓を入力します",
  "enterStreetAddress1": "Astrest Address 1を入力します",
  "streetAddress1": "住所1",
  "enterStreetAdress2": "Street Adress 2を入力します",
  "streetAddress2": "路上住所2",
  "enterStreetAddress3": "Astrest Address 3を入力してください",
  "streetAddress3": "路上住所3",
  "enterCityName": "都市名を入力してください",
  "city": "街",
  "country": "国",
  "enterZipPostalCode": "zip郵便コードを入力します",
  "zipPostalCode": "zip/郵便番号",
  "stateProvince": "州/州",
  "enterStateProvince": "州/州に入ります",
  "emailAddressRequired": "メールアドレスが必要です",
  "cancelCoupon": "クーポンをキャンセルします",
  "apply": "申し込み",
  "viewCouponList": "クーポンリストを表示します",
  "coupons": "クーポン",
  "changeLanguageAndCurrency": "言語と通貨を変更します",
  "youHaveNoOrders": "注文はありません",
  "youHaveNoTickets": "チケットはありません",
  "category": "カテゴリー",
  "createNewTicket": "新しいチケットを作成します",
  "positiveImpactSustainability": "プラスの影響 +持続可能性",
  "thereAreStillMoreThanMSG":
      "1日あたり1.25ドル未満で極度の貧困の中で生きている世界中の10億人以上の人々がいます。タイだけでも、社会の縁に100万人以上のヒル部族のメンバーが存在します - 市民権を拒否し、正式な雇用市場から締め出され、搾取と人身売買に対して脆弱です。",
  "atYellowLeafHammocksMsg": "黄色の葉のハンモックでは、倫理的雇用創出は極度の貧困に対する長期的な解決策であると考えています。",
  "insteadOfOrganizingMsg":
      "水、栄養、衣服などを提供するために慈善寄付のパッチワークを組織する代わりに、私たちは家族と直接協力して、より明るい未来に向けて包括的で威厳のある長期的な戦略を構築しています。体系的な貧困の背後にある原因は複雑ですが、長期的な財政的安定性は手の届く範囲です。",
  "toPutItSimplyMsg":
      "簡単に言えば、生計に焦点を合わせることで、中間人を切り取り、賢く +機知に富んだ母親の手に直接お金を稼ぎ、家族が自分の問題に取り組むことができます（他の人の議題の対象なしに）。",
  "acrossThreeWeavingCommunitiesMsg":
      "3つの織物コミュニティにまたがって、私たちは母親のために雇用を創出し、積極的なコミュニティ変革の基盤を構築するために取り組んでいます。私たちの職人は、柔軟で安全な「繁栄賃金」織りの仕事を通じて、家族を貧困や債務奴隷制から中流階級に引き上げることができます。",
  "creatingJobsForWomenMsg":
      "**女性の雇用を創出することは、コミュニティの変革にとって特に重要です - 研究は、女性が家族の健康、栄養、教育に収益の最大90％を費やすことを示しています。女性を稼ぎ手に変えることで、コミュニティでの地位が向上し、自尊心を構築し、リソースをプールしてインフラストラクチャを改善できます。",
  "theFoundationForABrighterFuter": "明るい未来の基礎",
  "theSecurityOfAStableMsg":
      "安定した成長する収益源の安全性は、村に多大な影響を与えました。 Mlabriは学校を始めて、織りと社交のためのコミュニティセンターを建設することができました。彼らはタイの最初の失業基金の1つを設立しました。経済力の向上により、彼らは2001年に最初に付与された市民権と公民権に成功しました。ハンモックウィービングは柔軟な仕事であり、自宅で仕事をして自分のスケジュールを作ることができる母親に最適です。残念ながら、グローバル市場へのアクセスがなければ、ハンモックの需要はタイの観光シーズンに限定されており、一年中雇用を確保する方法はありませんでした。",
  "spreadingLastingChangeTheHammockRrevolution": "拡散する永続的な変化：ハンモックの革命",
  "thisIsAboutWhereMsg":
      "これは、イエローリーフがストーリーに参加する場所についてです！過去数年にわたり、私たちは一貫した販売チャネルの開発、国際的なパートナーシップの構築、村内の事業の安定化に取り組んできました。",
  "corollaryEconomicMsg":
      "郵便局、食品の準備、持続可能なコーヒー農業などの帰結経済的機会が生まれてきました。 Kivaとのパートナーシップは、財政的訓練と財務計画に拍車をかけ、多くの織工が人生で初めて銀行口座を開設しました！",
  "wWithOurGrowthMsg":
      "私たちの成長が加速し続けているので、私たちは一年中すべてのMLABRIウィーバーを採用できるだけでなく、周辺地域のヒル部族コミュニティにトレーニングと継続的な雇用を拡大し、継続的な雇用を提供し続けることができます。織りの仕事と持続可能な仕事が地域全体で利用できるようになるまで、破壊的な農業慣行は継続され、年季奉仕の搾取的なサイクルは真に終わりません。",
  "throughTheEstablishmentMsg":
      "グローバルなライフスタイルブランドとしてイエローリーフを設立することにより、私たちが提携しているヒル部族の村は、この前向きな影響を維持し、より明るい未来の基盤を築き続けることができます。",
  "enterWebsite": "ウェブサイトを入力してください",
  "enterPostCode": "郵便番号を入力します",
  "thankYouForYourInterest": "ブランドラベルと協力してくれてありがとう",
  "oneOfOurTeamMembersWillBeInTouchSoon": "私たちのチームメンバーの一人はすぐに連絡を取ります",
  "forAnyAdditionalQueriesPleaseWriteTo ": "追加のクエリについては、書いてください",
  "theProductIsOutOfStock": "製品は在庫がありません。",
  "whateverYourQueryUseTheContactFormBelowMsg":
      "あなたの質問が何であれ。以下の連絡先フォームを使用して、タッチオーストムを入手する準備ができています24*7を支援する準備ができています",
  "enterSubject": "件名を入力します",
  "enterSomeText": "いくつかのテキストを入力してください",
  "enterDetailsBelowToSend": "以下の詳細を入力して、10％のクーポンコードを友達に送信します",
  "enterFriendName": "友達名を入力してください",
  "friendFirstName": "友達の名",
  "enterFirstEmailAddress": "最初のメールアドレスを入力します",
  "friendEmailAddress": "友達のメールアドレス",
  "enterFirstPhoneNumber": "最初の電話番号を入力します",
  "friendPhoneNumber": "友達の電話番号",
  "register": "登録",
  "dateOfBirthIsRequired": "DateOfBirthが必要です",
  "marriageAnniversaryIsRequired": "結婚記念日が必要です",
  "surnameIsRequired": "姓が必要です",
  "date": "日にち",
  "showDialog": "ダイアログを表示します",
  "removeProduct": "製品を削除します",
  "areYouSureWantToRemoveThisProductFromCart": "この製品をカートから取り外したいですか？",
  "yes": "はい",
  "no": "いいえ",
  "addToWishlist": "ほしい物リストに追加する",
  "onceYouAddThisProductToWishlistThenItWillBeRemoveFromAart":
      "この製品をウィッシュリストに追加すると、カートから削除されます",
  "ok": "わかった",
  "nouHaveNoItemsInYourShoppingCart": "ショッピングカートにはアイテムがありません。",
  "Discount": "割引",
  "enterCouponCode": "クーポンコードを入力してください",
  "removeCoupon": "クーポンを削除します",
  "availableCouponList": "利用可能なクーポンリスト",
  "allCouponsList": "すべてのクーポンリスト",
  "addProductToYourWishList": "ウィッシュリストに製品を追加します",
  "configurable": "設定可能",
  "Missing": "ない",
  "Amount": "額",
  "Balance": "バランス",
  "Remarks": "備考",
  "myAddresses": "私の住所",
  "noAddressFound": "住所は見つかりません",
  "addAddress": "アドレスを追加します",
  "updateAddress": "アドレスを更新します",
  "expectedShipmentDate": "予想出荷日",
  "brandNameIsRequired": "ブランド名が必要です",
  "styleIsRequired": "スタイルが必要です",
  "keywordIsRequired": "キーワードが必要です",
  "remarkIsRequired": "発言が必要です",
  "couponId": "クーポンID",
  "couponName": "クーポン名",
  "expireAt": "で期限切れになります",
  "noCouponsFound": "クーポンは見つかりません！",
  "yourRequestHasBeenReceived": "あなたの要求が受け取られました。",
  "youCanViewYourRequestsatMyTickets": "あなたは私のチケットであなたのリクエストを見ることができます",
  "incorrectPassword": "パスワードが正しくありません",
  "thePasswordYouenteredisincorrectPleasetryagain":
      "あなたの入力したパスワードに誤りがあります。もう一度やり直してください",
  "registeredCustomers": "登録済みの客",
  "ifYouHaveAnAccountSignInWithYourEmailAddress":
      "アカウントがある場合は、メールアドレスにサインインしてください",
  "pleaseEnterOrderNumberToTrackYourOrder": "注文番号を入力して、注文を追跡してください。",
  "enterOrderNumber": "注文番号を入力します",
  "enteryOurOrderNumberHere": "ここから注文番号を入力してください",
  "howDoIFindMyOrderReference": "注文参照を見つけるにはどうすればよいですか？",
  "passwordRegExp":
      "パスワードの長さは少なくとも8文字で、大文字と小文字の両方の文字、少なくとも1つの数字と1つの特殊文字（！ @＃？）の両方の混合物が含まれている必要があります。",
  "nylonMessengerBackpackMsg":
      "Nylon Messenger Backpack by Balenziaga、フック付きフロントクロージャー、トップハンドル、調整可能なショルダーストラップ、コントラストロゴ付きのフロントパッチジップポケット、装飾的な要素としてのフック。",
  "priceMatchTicket": "価格マッチチケット",
  "enterAddress3": "アドレス3を入力します",
  "enterCity": "都市に入ります",
  "pleaseTryWithAnotherEmaiAddressMsg":
      "別のメールアドレスを試してみるか、CARE@brandslabels.comでお問い合わせください。",
  "Alert": "アラート",
  "requiredVal": "必要とされている",
  "mustbeof": "ある必要があります",
  "digits": "数字",
  "mustbeanumberExample100": "数字でなければなりません。例：100",
  "character": "キャラクター",
  "isinvalid": "無効です！",
  "mustbemorethan2characters": "2文字以上である必要があります",
  "entervalid": "有効な入力を入力します",
  "musthaveatleast2characters": "少なくとも2文字が必要です",
  "confirmpasswordshouldbematchwithpassword": "パスワードをパスワードと一致させることを確認してください",
  "pleaseenterPassword": "パスワードを入力してください",
  "mustbemorethan8characters": "8文字以上でなければなりません",
  "mobileisRequired": "モバイルが必要です",
  "mobilenumbermust10digits": "携帯電話番号は10桁でなければなりません",
  "mobileNumbermustbedigits": "携帯電話番号は数字でなければなりません",
  "yearmustbenumberonly": "年は番号のみでなければなりません",
  "establishedYearisRequired": "確立された年が必要です",
  "yearmustbebetween1850and": "年は1850年からでなければなりません",
  "licenseNoisRequired": "ライセンス番号が必要です",
  "numberofemployeeisRequired": "従業員の数が必要です",
  "numberofemployeeisnotmorethan9999": "従業員の数は9999以下です",
  "numberofemployeemustbedigits": "従業員の数は数字でなければなりません",
  "dateisRequired": "日付が必要です",
  "pleaseentervaliddate": "有効な日付を入力してください",
  "licenseIssuingAuthorityisRequired": "ライセンス発行機関が必要です",
  "licenseIssuingAuthoritymustbeazandAZ": "ライセンス発行機関は、A-ZおよびA-Zでなければなりません",
  "firstNameIsRequired": "名が必要です",
  "lastNameIsRequired": "姓が必要です",
  "imageUrlIsRequired": "画像リンクが必要です",
  "enterValidText": "有効なテキストを入力します",
  "pleaseCheckYourInternetConnection": "インターネット接続を確認してください！",
  "searchForPiesSushiTacos": "パイ、寿司、タコスを検索...",
  "enterSurname": "姓を入力してください",
  "enterStreetAddress": "Astressアドレスを入力してください",
  "addNew": "新しく追加する",
  "enterAddress1": "アドレス1を入力します",
  "enterAddress2": "アドレス2を入力します",
  "noBrandFound": "ブランドは見つかりません",
  "COUPONAPPLIEDSUCCESSFULLYYOUSAVED": "クーポンは正常に適用されました。あなたは保存した",
  "ONTHISORDER": "この注文について",
  "areYouSureYouWantToRemove": "本当に捨ててもいいのかい",
  "couponCode": "クーポンコード？",
  "cancel": "キャンセル",
  "itSeemsLikeWeHaveNothingToShowForThisBrand": "このブランドには何も見せないようです",
  "ifyouwouldlikeUsSendYouTheCollectionFrom": "あなたが私たちにあなたにコレクションを送ってほしいなら",
  "plsCreateATicketBelow": "pls。以下にチケットを作成します",
  "itSeemsLikeWeHaveNothingToShowForThisCategory": "このカテゴリには何も表示しないようです",
  "enterName": "名前を入力",
  "description": "説明",
};
