const Map<String, String> ko = {
  "language": "영어",
  "appNameText": "브랜드 및 레이블",
  "aboutUsText": "회사 소개",
  "aboutUsTitle": '우리는 브랜드 및 레이블입니다',
  "aboutUsContain": '100년대 세계 최고의 브랜드를 살펴보세요',
  "aboutUsContain1":
      '브랜드 및 레이블은 월 500만 방문자와 전 세계 배송이 가능한 최고의 온라인 럭셔리 패션 목적지입니다.',
  "aboutUsContain2":
      '이 웹사이트는 젊고 유망한 인재들 뿐만 아니라 최고의 확립된 디자이너들의 베스트 셀렉션을 제공합니다. BRANDSLABELS는 1930년대 초 피렌체에서 VIA ROMA에 회사의 이름을 딴 컨셉 스토어를 열면서 설립되었습니다. 1999년부터 온라인으로 이 회사는 총 수익의 90%를 온라인 판매에 기여하고 있습니다. 오늘날까지 창립자의 손자 Andrea Panconesi가 CEO로, 그의 딸 ANNAGRETA PANCONESI가 크리에이티브 디렉터로 활동하는 100% 개인 소유 가족 사업으로 남아 있습니다.',
  "aboutUsContain3":
      '이 사이트는 BALENCIAGA, J.W.WWETEMENTS, J.W.VETEMENTS와 같은 가장 유명한 디자이너의 남성, 여성 및 어린이를 위한 제품과 함께 의류, 신발, 가방, 액세서리, 고급스러운 홈 인테리어 및 미용에 대한 다양한 선택을 제공합니다. Anderson, BALMAIN, DOLCE & GABBANA, GUCCI, SAINT LAURENT, VALENTINO, GIVENCHY, LOEWE, JACQUEMUS 등.',
  "aboutUsContain4":
      '현재 15개국에서 200명의 사람들이 브랜드 라벨을 생산하고 유지하기 위해 일하고 있습니다. 사이트는 영어, 이탈리아어, 독일어, 중국어, 러시아어, 스페인어, 프랑스어, 한국어 및 일본어의 9개 언어로 제공됩니다. 이 사이트는 피렌체 사무실 주택 그래픽 디자인, IT, 고객 서비스, 마케팅 및 구매 부서와 함께 사내에서 완전히 만들어졌습니다. 스타일리스트와 언론팀은 세계 패션의 중심지인 밀라노에 있는 브랜드 레이블 사무실에서 근무합니다.',
  "aboutUsContain5":
      '모든 주문은 브랜드 라벨 본부에서 시그니처 신발 가방에서 맞춤형 리본에 이르기까지 최대한 주의를 기울여 준비하고 최고의 재료를 사용하는 상자에 담아 전 세계로 배송됩니다.',
  "aboutUsContain6":
      '브랜드 레이블은 2008년에 150만 명의 고유 방문자가 사이트에 액세스했으며 2017년에는 5,300만 명의 고유 방문자로 성장했습니다. 온라인 판매의 15% 이상이 미국, 프랑스, ​​독일, 뒤를 이어',
  "aboutUsContain7":
      'BRANDSLABELS는 BUY IT FIRST, LUXURY CLUB, SNEAKERS CLUB, LVR PRIVILE을 포함한 일련의 독점 서비스 및 상표 이니셔티브를 통해 온/오프라인 모두에서 럭셔리 소매 환경의 경계를 넓힙니다.',
  "profile": "프로필",
  "firstNameText": "이름",
  "lastNameText": "성",
  "emailText": "이메일",
  "ContactNoText": "연락처",
  "websiteUrlText": "웹 사이트 주소",
  "cityText": "도시",
  "countryText": "국가",
  "postCodeText": "우편번호",
  "socialLinksText": "소셜 링크",
  "facebookText": "페이스북",
  "instagramText": "인스 타 그램",
  "twitterText": "트위터",
  "youtubeText": "유튜브",
  "linkendinText": "린켄딘",
  "pinterestText": "핀터레스트",
  "followersText": "팔로워",
  "mr": "씨.",
  "letsText": "갑시다",
  "orderIdTitle": '''주문 번호: ''',
  "orderDateTitle": '주문 날짜: 2021년 9월 15일',
  "orderNumberTitle": '주문 번호: ',
  "orderConfirm": "구입 주셔서 감사합니다!",
  "name": "이름",
  "sku": "SKU",
  "price": "가격",
  "qty": "수량",
  "subTotal": "소계",
  "action": "동작",
  "addressBook": "주소록",
  "billing": "청구",
  "shipping": "배송",
  "orderContain": '세부 정보 및 추적 정보가 포함된 주문 확인 이메일을 보내드립니다.',
  "referFriendText": "친구 추천",
  "returnsRefundsText": "반품 및 환불",
  "faqText": "자주하는 질문",
  "contactText": "연락하다",
  "socialText": "사회의",
  "companyText": "회사",
  "myOrders": "내 주문",
  "myOrderImage": "영상",
  "productName": "상품명",
  "quantity": "수량",
  "status": "상태",
  "paymentMethod": " 지불 방법",
  "shippingAddress": "배송 주소",
  "billingAddress": "청구 지 주소",
  "continueShopping": "쇼핑을 계속",
  "generalAndOrderEnquiriesText": "일반 및 주문 문의",
  "gdpText": "GDP",
  "engText": "영어",
  "nameText": "이름*",
  "surNameText": "성*",
  "emailAddressText": "이메일 주소*",
  "confirmEmailAddressText": "이메일 주소 확인*",
  "subjectText": "주제*",
  "phoneNumberText": "전화 번호",
  "whatsOnYourMindText": "무슨 생각이 드니?*",
  "queryDescription":
      "문의 사항이 무엇이든 아래 연락처 양식을 사용하여 연락하십시오.저희 팀이 연중무휴 24시간 도움을 드릴 준비가 되어 있습니다.",
  "submitText": "제출하다",
  "typeOfEnquiryText": "문의 유형*",
  "registeredCustomersText": "등록된 고객",
  "signInDescriptionText": "계정이 있으면\ne메일 주소로 로그인하세요.",
  "forgotYourPasswordText": "비밀번호를 잊어 버렸습니까?",
  "signInText": "로그인",
  "newCustomersText": "신규 고객",
  "newCustomersDescriptionText":
      "계정을 만들면\n더 빠르게 체크아웃하고, 두 개 이상의 주소를 유지하고,\n주문을 추적하는 등 많은 이점이 있습니다.",
  "createAccountText": "계정 만들기",
  "aboutProjectNameText": "브랜드 및 레이블 정보",
  "helpAndInformationText": "도움말 및 정보",
  "moreFromProjectText": "Brands&Labels에서 더 많은 것",
  "newsLetterText": "뉴스 레터",
  "subscribeText": "구독하다",
  "passwordText": "비밀번호",
  "homeText": "집",
  "searchText": "검색",
  "designersText": "디자이너",
  "wishListText": "위시리스트",
  "loginText": "로그인",
  "myAccountText": "내 계정",
  "yourEmailText": "귀하의 이메일",
  "checkoutText": "점검",
  "purchaseText": "구매를 완료하려면 아래에 세부 정보를 입력하십시오",
  "shippingAddressText": "배송 주소",
  "shippingMethodText": "배송 방법",
  "paymentMethodText": "지불 방법",
  "orderSummaryText": "주문 요약",
  "addressText":
      "admin admintast 제품, 테스트 제품, 테스트 제품 테스트 제품, b12345 302006Russia 1234567890",
  "newAddressText": "새 주소",
  "itemInCartText": "장바구니에 담긴 상품",
  "qtyText": "수량",
  "applyDiscountCodeText": "할인 코드 적용",
  "enterDiscountCodeText": "할인 코드 입력",
  "applyDiscountText": "할인 적용",
  "orderTotalText": "주문 합계",
  "orderCommentText": "주문 코멘트",
  "placeOrderText": "주문하기",
  "myOrdersText": "내 주문",
  "myWishlistText": "내 위시리스트",
  "addressBookText": "주소록",
  "accountInformationText": "계정 정보",
  "storePaymentText": "저장된 결제 방법",
  "newsLetter1Text": "뉴스레터 구독",
  "enterEmailAddress": "이메일 주소 입력",
  "enterConfirmEmailAddress": "확인 이메일 주소 입력",
  "enterPhoneNumber": "전화번호 입력",
  "enterValidEmailAddress": "유효한 이메일 주소 입력",
  "confirmEmailNotMatch": "이메일이 이메일 주소와 일치하지 않는지 확인",
  "phoneNumberIsRequired": "전화번호는 필수 항목입니다.",
  "phoneNumberIsNotValid": "전화번호가 올바르지 않습니다.",
  "gstIdentificationNumber":
      "GST 식별 번호가 올바르지 않습니다. 이 11AAAAA1111Z1A1 형식이어야 합니다.",
  "emailRequired": "이메일은 필수 항목입니다.",
  "invalidEmail": "유효하지 않은 이메일",
  "confirmEmailIsRequired": "이메일 필수 확인",
  "confirmEmailShouldBeMatchWithEmail": "이메일이 이메일과 일치해야 하는지 확인",
  "youHaveReachedYourMaximumLimit": "허용되는 최대 문자 제한에 도달했습니다.",
  "passwordIsRequired": "비밀번호가 필요합니다.",
  "successfullyLoggedOut": "성공적으로 로그아웃되었습니다.",
  "emailAddress": "이메일 주소",
  "enterEmailToTrackRequest.": "요청을 추적하려면 이메일을 입력하십시오.",
  "firstName": "이름",
  "lastName": "성",
  "dateOfBirth.": "생년월일",
  "dateOfMarriage": "결혼 기념일",
  "signUpForNewsletter": "뉴스레터 신청",
  "email": "이메일",
  "password": "암호",
  "confirmPassword": "비밀번호 확인",
  "typesOfEnquiry": "문의 유형",
  "confirmPasswordIsRequired.": "암호 확인이 필요합니다.",
  "orderDetails": "주문 세부 정보",
  "noDataAvailable": "사용 가능한 데이터 없음",
  "myAccount": "내 계정",
  "mrs": "님.",
  "communicationPrefences.": "통신 기본 설정",
  "subscribeNewsletters": "ounass 뉴스 레터를 구독하십시오 ..",
  "aboutUs": "우리에 관해서",
  "sms": "문자",
  "save": "구해내다",
  "tearmsAndCondition": "조항과 조건",
  "subscribeOffersAndMore": "우리의 새로운 도착, 독점 컬렉션, 제안 등으로 첫 번째가 되십시오.",
  "ourServices": "우리의 서비스",
  "delivery": "배달",
  "ourWebsite": "우리의 웹 사이트",
  "addToCart": "장바구니에 넣기",
  "subscribe": "구독하다",
  "productDetails": "제품 정보",
  "priceMatch": "가격 일치",
  "composition": "구성",
  "color": "색",
  "chooseAnOption": "옵션을 선택하세요...",
  "buyNow": "지금 구매하십시오",
  "notifyMeWhenThisProductIsInStock1": "이 제품이 재고가있을 때 알려주십시오",
  "yourBestPriceAlways": "당신의 최고의 가격 - 항상.",
  "IfYourPreferredItemIsLowerMsg":
      "선호하는 품목이 현재 시간에 다른 상점에서 가격이 낮은 경우 가격과 일치하고 다음 구매에 대해 10% 추가 상점 크레딧을 제공합니다.",
  "simplyLetUsKnowByClickingHere": "여기를 클릭하여 알려주십시오.",
  "alreadyMadeYourPurchase": "이미 구매했습니다.",
  "dontWorryLetUsKnowByClickingMsg":
      "걱정하지 마시고 여기를 클릭하여 알려주십시오. 지난 30일 이내에 구매한 경우 고객 지원 팀에서 차액을 환불해 드립니다.",
  "pleaseSeeFAQsByClickingHere": "여기를 클릭하여 FAQ를 참조하십시오",
  "filter": "필터",
  "sort": "종류",
  "sortBy": "정렬 기준",
  "noProductsFound": "제품이 발견되지 않았습니다",
  "createTicket": "티켓을 만듭니다",
  "more": "& 더...",
  "bgbp": "GBP",
  "findBrand": "브랜드를 찾으십시오",
  "itSeemsWeHaveNothingToShowFor": "우리에게는 아무것도 보여주지 않는 것 같습니다",
  "ifYouWouldLikeToHaveMoreInformationAbout": "더 많은 정보를 원한다면",
  "thenPleaseCreateATicket": "그런 다음 티켓을 만드십시오",
  "contactInformation": "연락처 정보",
  "edit": "편집하다",
  "changePassword": "비밀번호를 변경하십시오",
  "youHaveNoProductsInYourWishList": "위시리스트에 제품이 없습니다.",
  "toBbeUpdated": "업데이트 할",
  "youHaveNoSavedAddressAddnewAddressToContinueWithCheckout":
      "저장된 주소가 없습니다. 체크 아웃을 계속할 새 주소 추가",
  "shipHere": "여기 배송",
  "enterFirstName": "이름을 입력하십시오",
  "enterLastName": "성을 입력하십시오",
  "enterStreetAddress1": "거리 주소 1을 입력하십시오",
  "streetAddress1": "거리 주소 1",
  "enterStreetAdress2": "Street Adress 2를 입력하십시오",
  "streetAddress2": "거리 주소 2",
  "enterStreetAddress3": "거리 주소 3을 입력하십시오",
  "streetAddress3": "거리 주소 3",
  "enterCityName": "도시 이름을 입력하십시오",
  "city": "도시",
  "country": "국가",
  "enterZipPostalCode": "지퍼 우편 번호를 입력하십시오",
  "zipPostalCode": "지퍼/우편 번호",
  "stateProvince": "주/지방",
  "enterStateProvince": "주/주를 입력하십시오",
  "emailAddressRequired": "이메일 주소가 필요합니다",
  "cancelCoupon": "쿠폰을 취소하십시오",
  "apply": "적용하다",
  "viewCouponList": "쿠폰 목록을 봅니다",
  "coupons": "쿠폰",
  "changeLanguageAndCurrency": "언어와 통화를 변경하십시오",
  "youHaveNoOrders": "당신은 명령이 없습니다",
  "youHaveNoTickets": "티켓이 없습니다",
  "category": "범주",
  "createNewTicket": "새 티켓을 만드십시오",
  "positiveImpactSustainability": "긍정적 인 영향 + 지속 가능성",
  "thereAreStillMoreThanMSG":
      "하루에 1.25 달러 미만의 극심한 빈곤에 처한 세계에있는 10 억 명이 넘는 사람들이 여전히 있습니다. 태국에서만 힐 부족의 백만 명이 넘는 힐 부족이 사회의 여백에 존재합니다. 거부 된 시민권, 공식적인 직업 시장에서 폐쇄되고 착취와 인신 매매에 취약합니다.",
  "atYellowLeafHammocksMsg":
      "노란 잎 해먹에서 우리는 윤리적 인 일자리 창출이 극심한 빈곤에 대한 장기적인 해결책이라고 생각합니다.",
  "insteadOfOrganizingMsg":
      "물, 영양, 의류 등을 제공하기 위해 자선 기부 패치를 조직하는 대신, 우리는 가족과 직접 협력하여 더 밝은 미래를 향한 포괄적이고 위엄있는 장기 전략을 세우고 있습니다. 체계적인 빈곤의 원인은 복잡하지만 장기적인 재무 안정성은 도달 할 수 있습니다.",
  "toPutItSimplyMsg":
      "간단히 말해서 : 생계에 집중함으로써, 우리는 중간 남자를 잘라 내고, Smart + Rouberceful Mothers의 손에 직접 돈을 벌고, 가족이 자신의 문제를 해결할 수 있도록 권한을 부여 할 수 있습니다 (다른 사람의 의제에 영향을받지 않고).",
  "acrossThreeWeavingCommunitiesMsg":
      "\"3 개의 직조 공동체에서 우리는 어머니를위한 일자리를 창출하고 긍정적 인 공동체 변화를위한 토대를 구축하기 위해 노력하고 있습니다. 유연하고 안전한 \"\"번영 임금\"\"직조 작업을 통해 우리의 장인들은 빈곤과 부채 노예에서 중산층으로 가족을 높일 수 있습니다.\"",
  "creatingJobsForWomenMsg":
      "** 여성을위한 일자리 창출은 특히 지역 사회 변화에 중요합니다. 연구에 따르면 여성은 가족의 건강, 영양 및 교육에 최대 90%를 소비 할 것입니다. 여성을 빵가수로 바꾸면 지역 사회에서의 지위가 향상되고 자존감을 키우며 인프라를 개선하기 위해 자원을 풀 수 있습니다.",
  "theFoundationForABrighterFuter": "더 밝은 냄새를위한 기초",
  "theSecurityOfAStableMsg":
      "안정되고 성장하는 수익원의 보안은 마을에 엄청난 영향을 미쳤습니다. Mlabri는 학교를 시작하고 직조 및 사교를위한 커뮤니티 센터를 건설 할 수있었습니다. 그들은 태국 최초의 실업 기금 중 하나를 설립했습니다. 경제력이 증가함에 따라 그들은 2001 년에 처음 부여 된 시민권과 시민권을 위해 로비를 성공적으로 로비했습니다. Hammock Weaving은 유연한 일이며 집에서 일하고 일정을 만들 수있는 어머니에게 이상적입니다. 불행히도, 글로벌 시장에 접근 할 수 없다면 해먹에 대한 수요는 태국 관광 시즌으로 제한되었으며 연중 고용을 보장 할 방법이 없었습니다.",
  "spreadingLastingChangeTheHammockRrevolution":
      "지속적인 변화 확산 : Hammock Rrevolution",
  "thisIsAboutWhereMsg":
      "이것은 노란 잎이 이야기에 합류하는 곳입니다! 지난 몇 년 동안 우리는 일관된 판매 채널을 개발하고 국제 파트너십을 구축하며 마을 내에서 운영을 안정화하기 위해 노력해 왔습니다.",
  "corollaryEconomicMsg":
      "우체국, 음식 준비 및 지속 가능한 커피 농업과 같은 관상 경제 기회는 직조하지 않는 사람들을 고용하기 위해 생겨났습니다. Kiva와의 파트너십은 재무 교육 및 재무 계획을 자극했습니다.",
  "wWithOurGrowthMsg":
      "우리의 성장이 계속 가속화되면서, 우리는 일년 내내 모든 mlabri 위버를 고용 할 수있을뿐만 아니라 주변 지역의 Hill Tribe 커뮤니티에 계속 확장하고 훈련 및 지속적인 고용을 제공 할 수있을 것입니다. 해당 지역 전체에서 직조 작업과 지속 가능한 일자리를 구할 때까지 파괴적인 농업 관행이 계속 될 것이며 계약 된 종의 착취주기는 진정으로 끝나지 않을 것입니다.",
  "throughTheEstablishmentMsg":
      "우리가 파트너 관계를 맺은 Hill Tribe Villages는 글로벌 라이프 스타일 브랜드로서 Yellow Leaf를 설립함으로써 이러한 긍정적 인 영향을 유지하고 더 밝은 미래를위한 기초를 계속 만들 수 있습니다.",
  "enterWebsite": "웹 사이트를 입력하십시오",
  "enterPostCode": "우편 번호를 입력하십시오",
  "thankYouForYourInterest": "브랜드 라벨과의 협력에 관심을 가져 주셔서 감사합니다",
  "oneOfOurTeamMembersWillBeInTouchSoon": "우리 팀원 중 한 명이 곧 연락 할 것입니다.",
  "forAnyAdditionalQueriesPleaseWriteTo ": "추가 쿼리는 다음에 작성하십시오",
  "theProductIsOutOfStock": "제품은 재고가 없습니다.",
  "whateverYourQueryUseTheContactFormBelowMsg":
      "쿼리가 무엇이든. 아래의 연락처 양식을 사용하여 터치를 시작하십시오.",
  "enterSubject": "주제를 입력하십시오",
  "enterSomeText": "텍스트를 입력하십시오",
  "enterDetailsBelowToSend": "친구에게 10% 쿠폰 코드를 보내려면 아래 세부 정보를 입력하십시오.",
  "enterFriendName": "친구 이름을 입력하십시오",
  "friendFirstName": "친구 이름",
  "enterFirstEmailAddress": "첫 번째 이메일 주소를 입력하십시오",
  "friendEmailAddress": "친구 이메일 주소",
  "enterFirstPhoneNumber": "첫 번째 전화 번호를 입력하십시오",
  "friendPhoneNumber": "친구 전화 번호",
  "register": "등록하다",
  "dateOfBirthIsRequired": "날짜가 필요합니다",
  "marriageAnniversaryIsRequired": "결혼 기념일이 필요합니다",
  "surnameIsRequired": "성이 필요합니다",
  "date": "날짜",
  "showDialog": "대화 상자 표시",
  "removeProduct": "제품을 제거하십시오",
  "areYouSureWantToRemoveThisProductFromCart": "CART 에서이 제품을 제거 하시겠습니까?",
  "yes": "예",
  "no": "아니",
  "addToWishlist": "위시리스트에 추가하십시오",
  "onceYouAddThisProductToWishlistThenItWillBeRemoveFromAart":
      "이 제품을 위시리스트에 추가하면 카트에서 제거됩니다.",
  "ok": "확인",
  "nouHaveNoItemsInYourShoppingCart": "쇼핑 카트에는 품목이 없습니다.",
  "Discount": "할인",
  "enterCouponCode": "쿠폰 코드를 입력하십시오",
  "removeCoupon": "쿠폰을 제거하십시오",
  "availableCouponList": "사용 가능한 쿠폰 목록",
  "allCouponsList": "모든 쿠폰 목록",
  "addProductToYourWishList": "위시리스트에 제품을 추가하십시오",
  "configurable": "구성 가능",
  "Missing": "잃어버린",
  "Amount": "양",
  "Balance": "균형",
  "Remarks": "발언",
  "myAddresses": "내 주소",
  "noAddressFound": "주소가 발견되지 않았습니다",
  "addAddress": "주소를 추가하십시오",
  "updateAddress": "업데이트 주소",
  "expectedShipmentDate": "예상 배송 일",
  "brandNameIsRequired": "브랜드 이름이 필요합니다",
  "styleIsRequired": "스타일이 필요합니다",
  "keywordIsRequired": "키워드가 필요합니다",
  "remarkIsRequired": "비고가 필요합니다",
  "couponId": "쿠폰 ID",
  "couponName": "쿠폰 이름",
  "expireAt": "만료",
  "noCouponsFound": "쿠폰을 찾지 못했습니다!",
  "yourRequestHasBeenReceived": "귀하의 요청이 접수되었습니다.",
  "youCanViewYourRequestsatMyTickets": "내 티켓에서 요청을 볼 수 있습니다",
  "incorrectPassword": "잘못된 비밀번호",
  "thePasswordYouenteredisincorrectPleasetryagain":
      "입력 한 암호가 잘못되었습니다. 다시 시도하십시오",
  "registeredCustomers": "등록 된 고객",
  "ifYouHaveAnAccountSignInWithYourEmailAddress": "계정이있는 경우 이메일 주소로 로그인하십시오.",
  "pleaseEnterOrderNumberToTrackYourOrder": "주문을 추적하려면 주문 번호를 입력하십시오.",
  "enterOrderNumber": "주문 번호를 입력하십시오",
  "enteryOurOrderNumberHere": "여기에 주문 번호를 입력하십시오",
  "howDoIFindMyOrderReference": "주문 참조는 어떻게 찾습니까?",
  "passwordRegExp":
      "비밀번호의 길이는 8 자 이상이어야하며 대문자와 소문자의 혼합물, 최소 1 개의 숫자와 하나의 특수 문자 (예 :! @ #?)가 포함되어 있습니다.",
  "nylonMessengerBackpackMsg":
      "Balenziaga의 나일론 메신저 백팩, 후크가있는 전면 클로저, 상단 핸들, 조절 가능한 어깨 끈, 대비 로고가있는 전면 패치 지퍼 포켓, 장식 요소로 후크.",
  "priceMatchTicket": "가격 경기 티켓",
  "enterAddress3": "주소 3을 입력하십시오",
  "enterCity": "도시에 들어갑니다",
  "pleaseTryWithAnotherEmaiAddressMsg":
      "추가 지원을 위해 다른 이메일 주소로 시도하거나 Care@brandslabels.com으로 편지를 보내주십시오.",
  "Alert": "알리다",
  "requiredVal": "필요합니다",
  "mustbeof": "해야합니다",
  "digits": "숫자",
  "mustbeanumberExample100": "숫자 여야합니다. 예 : 100",
  "character": "캐릭터",
  "isinvalid": "유효하지 않다!",
  "mustbemorethan2characters": "2 자 이상이어야합니다",
  "entervalid": "유효한 입력",
  "musthaveatleast2characters": "2 개 이상의 문자가 있어야합니다",
  "confirmpasswordshouldbematchwithpassword": "비밀번호는 암호와 일치해야합니다",
  "pleaseenterPassword": "비밀번호를 입력 해주세요",
  "mustbemorethan8characters": "8 자 이상이어야합니다",
  "mobileisRequired": "모바일이 필요합니다",
  "mobilenumbermust10digits": "휴대폰 번호는 10 자리 숫자가 있어야합니다",
  "mobileNumbermustbedigits": "휴대폰 번호는 숫자 여야합니다",
  "yearmustbenumberonly": "연도는 숫자 전용이어야합니다",
  "establishedYearisRequired": "설립 된 연도가 필요합니다",
  "yearmustbebetween1850and": "연도는 1850 년에서이어야합니다",
  "licenseNoisRequired": "라이센스 번호가 필요합니다",
  "numberofemployeeisRequired": "직원 수가 필요합니다",
  "numberofemployeeisnotmorethan9999": "직원 수는 9999를 넘지 않습니다",
  "numberofemployeemustbedigits": "직원 수는 숫자 여야합니다",
  "dateisRequired": "날짜가 필요합니다",
  "pleaseentervaliddate": "유효한 날짜를 입력하십시오",
  "licenseIssuingAuthorityisRequired": "라이센스 발행 기관이 필요합니다",
  "licenseIssuingAuthoritymustbeazandAZ": "라이센스 발급 기관은 A-Z 및 A-Z 여야합니다",
  "firstNameIsRequired": "이름이 필요합니다",
  "lastNameIsRequired": "성이 필요합니다",
  "imageUrlIsRequired": "이미지 링크가 필요합니다",
  "enterValidText": "유효한 텍스트를 입력하십시오",
  "pleaseCheckYourInternetConnection": "인터넷 연결을 확인하십시오!",
  "searchForPiesSushiTacos": "파이, 초밥, 타코 검색 ...",
  "enterSurname": "성을 입력하십시오",
  "enterStreetAddress": "거리 주소를 입력하십시오",
  "addNew": "새로운 걸 더하다",
  "enterAddress1": "주소 1을 입력하십시오",
  "enterAddress2": "주소 2를 입력하십시오",
  "noBrandFound": "발견 된 브랜드가 없습니다",
  "COUPONAPPLIEDSUCCESSFULLYYOUSAVED": "쿠폰이 성공적으로 적용되었습니다. 당신은 저장했습니다",
  "ONTHISORDER": "이 순서에서",
  "areYouSureYouWantToRemove": "제거하고 싶습니까?",
  "couponCode": "쿠폰 코드?",
  "cancel": "취소",
  "itSeemsLikeWeHaveNothingToShowForThisBrand":
      "이 브랜드에 대해 아무것도 보여줄 것이없는 것 같습니다.",
  "ifyouwouldlikeUsSendYouTheCollectionFrom": "당신이 우리가 당신에게 컬렉션을 보내고 싶다면",
  "plsCreateATicketBelow": "pls. 아래 티켓을 만듭니다",
  "itSeemsLikeWeHaveNothingToShowForThisCategory":
      "이 카테고리에 대해 보여줄 것이없는 것 같습니다.",
  "enterName": "이름을 입력하시오",
  "description": "설명",
};
