const Map<String, String> nl = {
  "language": "Engels",
  "appNameText": "Merken en labels",
  "aboutUsText": "Over ons",
  "aboutUsTitle": 'WIJ ZIJN MERK & LABELS',
  "aboutUsContain": '''ONTDEK 100'S VAN DE BESTE MERKEN VAN DE WERELD''',
  "aboutUsContain1":
      'BRANDS & LABELS IS EEN TOP ONLINE LUXE MODEBESTEMMING MET 5 MILJOEN BEZOEKERS PER MAAND EN WERELDWIJDE VERZENDING.',
  "aboutUsContain2":
      'DE WEBSITE HEEFT DE BESTE SELECTIE VAN DE BESTE ONTWERPERS EN JONGE OPKOMENDE TALENTEN. BRANDSLABELS WERD BEGIN 1930 IN FLORENCE OPGERICHT MET DE OPENING VAN DE EPONIEM CONCEPT STORE VAN HET BEDRIJF AAN VIA ROMA. ONLINE SINDS 1999 SCHRIJFT HET BEDRIJF 90% VAN DE TOTALE INKOMSTEN TOE AAN ONLINE VERKOOP. TOT DEZE DAG BLIJFT HET EEN 100% PRIVÉ-EIGEN FAMILIEBEDRIJF, MET DE KLEINZOON VAN DE OPRICHTER, ANDREA PANCONESI ALS CEO EN ZIJN DOCHTER, ANNAGRETA PANCONESI ALS CREATIEF DIRECTEUR.',
  "aboutUsContain3":
      'DE SITE BIEDT EEN BREDE SELECTIE AAN KLEDING, SCHOENEN, TASSEN, ACCESSOIRES, LUXE INTERIEURS EN SCHOONHEID, MET PRODUCTEN BESCHIKBAAR VOOR MANNEN, VROUWEN EN KINDEREN VAN DE MEEST PRESTIGIEUZE ONTWERPERS ZOALS BALENCIAGA, VETEMENTS, OFF-WHITE, J.W. ANDERSON, BALMAIN, DOLCE & GABBANA, GUCCI, SAINT LAURENT, VALENTINO, GIVENCHY, LOEWE, JACQUEMUS EN MEER.',
  "aboutUsContain4":
      'ER ZIJN MOMENTEEL 200 MENSEN UIT 15 VERSCHILLENDE LANDEN DIE ZICH WERKEN AAN HET PRODUCEREN EN ONDERHOUDEN VAN MERKLABELS. DE SITE IS BESCHIKBAAR IN 9 TALEN: ENGELS, ITALIAANS, DUITS, CHINEES, RUSSISCH, SPAANS, FRANS, KOREAANS EN JAPANS. DE SITE IS VOLLEDIG IN-HUIS GEMAAKT, MET DE AFDELINGEN VAN HET KANTOOR FLORENCE HOUSING GRAFISCH ONTWERP, IT, KLANTENSERVICE, MARKETING EN INKOOP. DE STYLISTS EN PERSTEAMS OPEREREN VANUIT HET BRANDSLABELS-BUREAU IN DE FASHION HOOFDSTAD VAN DE WERELD - MILAAN.',
  "aboutUsContain5":
      'ALLE BESTELLINGEN WORDEN WERELDWIJD VERZONDEN VANAF HET HOOFDKANTOOR VAN DE MERKEN LABELS IN DOZEN DIE MET MAXIMALE ZORG ZIJN BEREID EN DE BESTE MATERIALEN GEBRUIKEN, VAN DE HANDTEKENDE SCHOENZAKJES TOT HET GEPERSONALISEERDE LINT.',
  "aboutUsContain6":
      'MERKSLABELS HADDEN IN 2008 1,5 MILJOEN UNIEKE BEZOEKERS TOEGANG TOT DE SITE EN IS IN 2017 GEGROEID TOT 53 MILJOEN UNIEKE BEZOEKERS. MEER DAN 15% VAN DE ONLINE VERKOOP WORDT GEGENEREERD UIT DE VERENIGDE STATEN, GEVOLGD DOOR DUITSLAND, VK, ITALI, CHINA EN FRANKRIJK.',
  "aboutUsContain7":
      'MERKSLABELS VERSCHRIJVEN DE GRENZEN VAN HET LUXE RETAILLANDSCHAP, ZOWEL ONLINE ALS OFFLINE MET EEN REEKS AAN EXCLUSIEVE DIENSTEN EN HANDELSMERKINITIATIEVEN, WAARONDER BUY IT FIRST, LUXURY CLUB, SNEAKERS CLUB, LVR PRIVILEGE EN LVR EDITIONS.',
  "profile": "Profiel",
  "firstNameText": "Voornaam",
  "lastNameText": "Achternaam",
  "emailText": "E-mail",
  "ContactNoText": "Contactnr.",
  "websiteUrlText": "Website URL",
  "cityText": "Stad",
  "countryText": "Land",
  "postCodeText": "Postcode",
  "socialLinksText": "Sociale links",
  "facebookText": "Facebook",
  "instagramText": "Instagram",
  "twitterText": "Twitter",
  "youtubeText": "Youtube",
  "linkendinText": "Linkendin",
  "pinterestText": "Pinterest",
  "followersText": "Volgers",
  "mr": "Dhr.",
  "letsText": "Laten we gaan",
  "orderIdTitle": '''Uw bestelling # is: ''',
  "orderDateTitle": 'Besteldatum: 15 september 2021',
  "orderNumberTitle": 'BESTELNUMMER: ',
  "orderConfirm": "DANK VOOR UW AANKOOP!",
  "name": "NAAM",
  "sku": "Artikelnummer",
  "price": "PRIJS",
  "qty": "AANTAL",
  "subTotal": "Subtotal",
  "action": "ACTIE",
  "addressBook": "Adresboek",
  "billing": "Facturering",
  "shipping": "Verzending",
  "orderContain":
      'We sturen je een orderbevestiging met details en trackinginformatie.',
  "referFriendText": "Verwijs vriend",
  "returnsRefundsText": "Retourneren & Terugbetalingen",
  "faqText": "FAQ",
  "contactText": "Contact",
  "socialText": "sociaal",
  "companyText": "Bedrijf",
  "myOrders": "mijn bestellingen",
  "myOrderImage": "Afbeelding",
  "productName": "productnaam",
  "quantity": "aantal",
  "status": "Toestand",
  "paymentMethod": " Betalingswijze",
  "shippingAddress": "Verzendingsadres",
  "billingAddress": "factuur adres",
  "continueShopping": "Doorgaan met winkelen",
  "generalAndOrderEnquiriesText": "ALGEMENE & BESTELLINGEN",
  "gdpText": "BBP",
  "engText": "NL",
  "nameText": "Naam*",
  "surNameText": "Achternaam*",
  "emailAddressText": "E-mailadres*",
  "confirmEmailAddressText": "Bevestig dit Email adres*",
  "subjectText": "Onderwerp*",
  "phoneNumberText": "Telefoonnummer",
  "whatsOnYourMindText": "Waar denk je aan?*",
  "queryDescription":
      "Wat uw vraag ook is, gebruik het onderstaande contactformulier om contact met ons op te nemen. Ons team staat 24/7 voor u klaar",
  "submitText": "INDIENEN",
  "typeOfEnquiryText": "Soort aanvraag*",
  "registeredCustomersText": "geregistreerde klanten",
  "signInDescriptionText":
      "Als je een account hebt, log dan in met je\nemailadres.",
  "forgotYourPasswordText": "Uw wachtwoord vergeten?",
  "signInText": "Aanmelden",
  "newCustomersText": "nieuwe klanten",
  "newCustomersDescriptionText":
      "Het aanmaken van een account heeft veel voordelen:\nsnel uitchecken, meer dan één adres bewaren,\nbestellingen volgen en meer.",
  "createAccountText": "Account aanmaken",
  "aboutProjectNameText": "Over merken en labels",
  "helpAndInformationText": "Hulp en informatie",
  "moreFromProjectText": "Meer van Brands&Labels",
  "newsLetterText": "Nieuwsbrief",
  "subscribeText": "Abonneren",
  "passwordText": "Wachtwoord",
  "homeText": "Thuis",
  "searchText": "Zoekopdracht",
  "designersText": "Ontwerpers",
  "wishListText": "Verlanglijst",
  "loginText": "Log in",
  "myAccountText": "Mijn rekening",
  "yourEmailText": "Jouw email",
  "checkoutText": "Uitchecken",
  "purchaseText": "Voer hieronder uw gegevens in om uw aankoop te voltooien:",
  "shippingAddressText": "Verzendingsadres",
  "shippingMethodText": "Verzendmethode:",
  "paymentMethodText": "Betalingswijze",
  "orderSummaryText": "overzicht van de bestelling",
  "addressText":
      "admin admintast product, testproduct, testproduct testproduct, b12345 302006Rusland 1234567890",
  "newAddressText": "Nieuw adres",
  "itemInCartText": "Artikel in winkelwagen",
  "qtyText": "aantal",
  "applyDiscountCodeText": "Kortingscode toepassen",
  "enterDiscountCodeText": "Voer kortingscode in",
  "applyDiscountText": "Korting toepassen",
  "orderTotalText": "totale bestelling",
  "orderCommentText": "Bestelling Opmerking",
  "placeOrderText": "PLAATS BESTELLING",
  "myOrdersText": "MIJN BESTELLINGEN",
  "myWishlistText": "Mijn wenslijst",
  "addressBookText": "Adresboek",
  "accountInformationText": "Account Informatie",
  "storePaymentText": "OPGESLAGEN BETAALMETHODEN",
  "newsLetter1Text": "NIEUWSBRIEF ABONNEMENTEN",
  "enterEmailAddress": "E-mailadres invoeren",
  "enterConfirmEmailAddress": "Voer ConfirmEmail Address in",
  "enterPhoneNumber": "Voer telefoonnummer in",
  "enterValidEmailAddress": "Voer een geldig e-mailadres in",
  "confirmEmailNotMatch": "Bevestig e-mail komt niet overeen met e-mailadres",
  "phoneNumberIsRequired": "Telefoonnummer is vereist",
  "phoneNumberIsNotValid": "Telefoonnummer is niet geldig",
  "gstIdentificationNumber":
      "GST-identificatienummer is niet geldig. Het moet in dit 11AAAAA1111Z1A1 formaat zijn",
  "emailRequired": "E-mail is vereist",
  "invalidEmail": "Ongeldig e-mailadres",
  "confirmEmailIsRequired": "E-mail bevestigen is vereist",
  "confirmEmailShouldBeMatchWithEmail":
      "Bevestig dat e-mail moet overeenkomen met e-mail",
  "youHaveReachedYourMaximumLimit":
      "Je hebt je maximale limiet van toegestane tekens bereikt",
  "passwordIsRequired": "Wachtwoord is vereist",
  "successfullyLoggedOut": "U bent succesvol uitgelogd",
  "emailAddress": "E-mailadres",
  "enterEmailToTrackRequest.":
      "Voer uw e-mailadres in om uw verzoek te volgen.",
  "firstName": "Voornaam",
  "lastName": "Achternaam",
  "dateOfBirth.": "Geboortedatum",
  "dateOfMarriage": "Huwelijksverjaardag",
  "signUpForNewsletter": "Schrijf je in voor de nieuwsbrief",
  "email": "E-mail",
  "password": "Wachtwoord",
  "confirmPassword": "Bevestig wachtwoord",
  "typesOfEnquiry": "Soorten vragen",
  "confirmPasswordIsRequired.": "ConfirmPassword is vereist",
  "orderDetails": "Bestel details",
  "noDataAvailable": "Geen gegevens beschikbaar",
  "myAccount": "Mijn account",
  "mrs": "Mevrouw.",
  "communicationPrefences.": "Communicatievoorkeuren",
  "subscribeNewsletters": "Abonneer u op ounass nieuwsbrieven..",
  "aboutUs": "Informatie",
  "sms": "Sms",
  "save": "Redden",
  "tearmsAndCondition": "ALGEMENE VOORWAARDEN",
  "subscribeOffersAndMore":
      "Schrijf je in om als eerste te arriveren met onze nieuwkomers, exclusieve collecties, aanbiedingen en meer.",
  "ourServices": "Onze diensten",
  "delivery": "Levering",
  "ourWebsite": "Onze Website",
  "addToCart": "Voeg toe aan winkelwagen",
  "subscribe": "Abonneren",
  "productDetails": "Productdetails",
  "priceMatch": "Prijs match",
  "composition": "Compositie",
  "color": "Kleur",
  "chooseAnOption": "Kies een optie...",
  "buyNow": "Nu kopen",
  "notifyMeWhenThisProductIsInStock1":
      "Stel me op de hoogte wanneer dit product op voorraad is",
  "yourBestPriceAlways": "Uw beste prijs - altijd.",
  "IfYourPreferredItemIsLowerMsg":
      "Als uw gewenste item op het huidige tijdstip goedkoper is geprijsd in een andere winkel, zullen we de prijs matchen en u 10% extra winkelkrediet bieden voor uw volgende aankoop.",
  "simplyLetUsKnowByClickingHere":
      "Laat het ons gewoon weten door hier te klikken.",
  "alreadyMadeYourPurchase": "Al uw aankoop gedaan.",
  "dontWorryLetUsKnowByClickingMsg":
      "Maak je geen zorgen, laat het ons weten door hier te klikken en wij, ons klantenondersteuningsteam zal u het verschil terugbetalen als de aankoop binnen de afgelopen 30 dagen is gedaan.",
  "pleaseSeeFAQsByClickingHere":
      "Zie de veelgestelde vragen door hier te klikken",
  "filter": "Filter",
  "sort": "Soort",
  "sortBy": "Sorteer op",
  "noProductsFound": "Geen producten gevonden",
  "createTicket": "Creëer ticket",
  "more": "& Meer...",
  "bgbp": "GBP",
  "findBrand": "Zoek merken",
  "itSeemsWeHaveNothingToShowFor":
      "Het lijkt erop dat we niets te laten zien hebben",
  "ifYouWouldLikeToHaveMoreInformationAbout":
      "Als u meer informatie wilt hebben",
  "thenPleaseCreateATicket": "Maak dan een ticket aan",
  "contactInformation": "Contactgegevens",
  "edit": "Bewerk",
  "changePassword": "Verander wachtwoord",
  "youHaveNoProductsInYourWishList":
      "U hebt geen producten in uw verlanglijstje.",
  "toBbeUpdated": "Om bij te worden bijgewerkt",
  "youHaveNoSavedAddressAddnewAddressToContinueWithCheckout":
      "U hebt geen opgeslagen adres Voeg nieuw adres toe om door te gaan met het afrekenen",
  "shipHere": "Scheep hier",
  "enterFirstName": "Vul voornaam in",
  "enterLastName": "Voer achternaam in",
  "enterStreetAddress1": "Voer straatadres in",
  "streetAddress1": "Straatnaam 1",
  "enterStreetAdress2": "Voer straatadres in 2 in",
  "streetAddress2": "Straatadres 2",
  "enterStreetAddress3": "Voer straatadres in",
  "streetAddress3": "Straatadres 3",
  "enterCityName": "Voer de stadsnaam in",
  "city": "Stad",
  "country": "Land",
  "enterZipPostalCode": "Voer de zip -postcode in",
  "zipPostalCode": "Zip/postcode",
  "stateProvince": "Staat/provincie",
  "enterStateProvince": "Betreed de staat/provincie",
  "emailAddressRequired": "E-mailadres: (Verplicht",
  "cancelCoupon": "Annuleer de coupon",
  "apply": "Van toepassing zijn",
  "viewCouponList": "Bekijk de couponlijst",
  "coupons": "Coupons",
  "changeLanguageAndCurrency": "Verander taal en valuta",
  "youHaveNoOrders": "Je hebt geen bestellingen",
  "youHaveNoTickets": "Je hebt geen kaartjes",
  "category": "Categorie",
  "createNewTicket": "Maak een nieuw ticket",
  "positiveImpactSustainability": "Positieve impact + duurzaamheid",
  "thereAreStillMoreThanMSG":
      "Er zijn nog steeds meer dan een miljard mensen rond de wereld die in extreme armoede leven op minder dan \$ 1,25 per dag. Alleen al in Thailand bestaan ​​er meer dan een miljoen leden van Hill Tribes in de marge van de samenleving - ontkend burgerschap, buitengesloten van de formele arbeidsmarkt en kwetsbaar voor uitbuiting en mensenhandel.",
  "atYellowLeafHammocksMsg":
      "Bij gele bladhangmatten geloven we dat het creëren van ethische banen een empowerment is voor langdurige oplossing voor extreme armoede.",
  "insteadOfOrganizingMsg":
      "In plaats van een lappendeken van liefdadigheidsdonaties te organiseren om water, voeding, kleding, enz. Te bieden, werken we rechtstreeks samen met gezinnen om een ​​uitgebreide, waardige, langetermijnstrategie op te bouwen naar een betere toekomst. De oorzaken achter systemische armoede zijn ingewikkeld, maar de financiële stabiliteit op lange termijn is binnen handbereik.",
  "toPutItSimplyMsg":
      "Simpel gezegd: door ons te concentreren op middelen van bestaan, kunnen we de middelste man uitsnijden, geld rechtstreeks in handen krijgen van slimme + vindingrijke moeders en gezinnen in staat stellen hun eigen problemen aan te pakken (zonder onderworpen te zijn aan de agenda van iemand anders).",
  "acrossThreeWeavingCommunitiesMsg":
      "\"In drie wevende gemeenschappen werken we om banen voor moeders te creëren en een basis te leggen voor positieve gemeenschapstransformatie. Door flexibel, veilig \"\"welvaartsloon\"\" weven werk, kunnen onze ambachtslieden hun families ophalen van armoede en schuldenslavernij naar de middenklasse.\"",
  "creatingJobsForWomenMsg":
      "** Het creëren van banen voor vrouwen is vooral belangrijk voor gemeenschapstransformatie - onderzoek toont aan dat vrouwen tot 90% van hun inkomsten zullen uitgeven aan de gezondheid, voeding en onderwijs van hun families. Het veranderen van vrouwen in kostwinners verbetert hun status in de gemeenschap, bouwt zelfrespect op en stelt hen in staat middelen te bundelen om de infrastructuur te verbeteren.",
  "theFoundationForABrighterFuter": "De basis voor een helderdere mutter",
  "theSecurityOfAStableMsg":
      "De veiligheid van een stabiele, groeiende inkomstenbron had een enorme impact op het dorp. De Mlabri konden een school starten en een gemeenschapscentrum bouwen voor weven en socialiseren. Ze vestigden een van de eerste werkloosheidsfondsen van Thailand. Met een verhoogde economische macht lobbyden ze met succes voor burgerschap en burgerrechten, die ze voor het eerst werden verleend in 2001. Hangmatweven is flexibel werk, ideaal voor moeders die vanuit huis kunnen werken en hun eigen schema's kunnen maken. Helaas was de vraag naar hangmatten zonder toegang tot de wereldmarkten beperkt tot het Thaise toeristische seizoen en was er geen manier om het hele jaar door te zorgen.",
  "spreadingLastingChangeTheHammockRrevolution":
      "Verspreiding van duurzame verandering: de hangmat -revolutie",
  "thisIsAboutWhereMsg":
      "Dit gaat over waar Yellow Leaf lid wordt van het verhaal! In de afgelopen jaren hebben we gewerkt om consistente verkoopkanalen te ontwikkelen, internationale partnerschappen op te bouwen en activiteiten in de dorpen te stabiliseren.",
  "corollaryEconomicMsg":
      "Corollary economische kansen, zoals een postkantoor, voedselbereiding en duurzame koffielandbouw, zijn ontstaan ​​om mensen in dienst te nemen die niet weven. Onze samenwerking met Kiva heeft de financiële training en financiële planning gestimuleerd, met veel wevers die bankrekeningen voor het eerst in hun leven openen!",
  "wWithOurGrowthMsg":
      "Omdat onze groei blijft versnellen, zullen we niet alleen het hele jaar door alle Mlabri-wevers kunnen gebruiken, we kunnen ook blijven uitbreiden en training en voortdurende werkgelegenheid bieden aan Hill Tribe Communities in de omliggende regio. Totdat het weven van werk en duurzame banen in het hele gebied beschikbaar zijn, zullen destructieve landbouwpraktijken doorgaan en zal de uitbuitingscyclus van contractarbeid niet echt eindigen.",
  "throughTheEstablishmentMsg":
      "Door de oprichting van Yellow Leaf als een wereldwijd lifestyle -merk, zullen de Hill Tribe -dorpen waarmee we samenwerken in staat zijn om deze positieve impact te behouden en de basis te blijven leggen voor een betere toekomst.",
  "enterWebsite": "Voer de website in",
  "enterPostCode": "Voer de postcode in",
  "thankYouForYourInterest":
      "Bedankt voor je interesse in het werken met merken-labels",
  "oneOfOurTeamMembersWillBeInTouchSoon":
      "Een van onze teamleden zal binnenkort contact opnemen",
  "forAnyAdditionalQueriesPleaseWriteTo ": "Voor extra vragen kunt u schrijven",
  "theProductIsOutOfStock": "Het product is niet op voorraad.",
  "whateverYourQueryUseTheContactFormBelowMsg":
      "Wat uw vraag ook is. Gebruik het onderstaande contactformulier om in Touch-Ourteam te komen, is klaar om te helpen 24*7",
  "enterSubject": "Betreden",
  "enterSomeText": "Voer wat tekst in",
  "enterDetailsBelowToSend":
      "Voer hieronder de details in om een ​​couponcode van 10% naar uw vriend te sturen",
  "enterFriendName": "Voer de vriendennaam in",
  "friendFirstName": "Vriend voornaam",
  "enterFirstEmailAddress": "Voer het eerste e -mailadres in",
  "friendEmailAddress": "Vriend -e -mailadres",
  "enterFirstPhoneNumber": "Voer het eerste telefoonnummer in",
  "friendPhoneNumber": "Telefoonnummer van vrienden",
  "register": "Register",
  "dateOfBirthIsRequired": "Datumofbirth is vereist",
  "marriageAnniversaryIsRequired": "Huwelijksverjaardag is vereist",
  "surnameIsRequired": "Achternaam is vereist",
  "date": "Datum",
  "showDialog": "Toon dialoogvenster",
  "removeProduct": "Verwijder product",
  "areYouSureWantToRemoveThisProductFromCart":
      "Wilt u dit product zeker uit de winkelwagen verwijderen?",
  "yes": "JA",
  "no": "NEE",
  "addToWishlist": "Toevoegen aan verlanglijst",
  "onceYouAddThisProductToWishlistThenItWillBeRemoveFromAart":
      "Zodra u dit product aan de verlanglijstje toevoegt, wordt het uit de winkelwagen verwijderd",
  "ok": "Oké",
  "nouHaveNoItemsInYourShoppingCart":
      "Je hebt geen items in je winkelwagentje.",
  "Discount": "Korting",
  "enterCouponCode": "Vul couponcode in",
  "removeCoupon": "Verwijder de coupon",
  "availableCouponList": "Beschikbare couponlijst",
  "allCouponsList": "Alle couponslijst",
  "addProductToYourWishList": "Voeg product toe aan uw verlanglijstje",
  "configurable": "configureerbaar",
  "Missing": "Missend",
  "Amount": "Hoeveelheid",
  "Balance": "Evenwicht",
  "Remarks": "Opmerkingen",
  "myAddresses": "Mijn adressen",
  "noAddressFound": "Geen adres gevonden",
  "addAddress": "Voeg adres toe",
  "updateAddress": "Update adres",
  "expectedShipmentDate": "Verwachte verzenddatum",
  "brandNameIsRequired": "Merknaam is vereist",
  "styleIsRequired": "Stijl is vereist",
  "keywordIsRequired": "Trefwoord is vereist",
  "remarkIsRequired": "Opmerking is vereist",
  "couponId": "Coupon -ID",
  "couponName": "Couponnaam",
  "expireAt": "Verslaan bij",
  "noCouponsFound": "Geen coupons gevonden!",
  "yourRequestHasBeenReceived": "Je verzoek is ontvangen.",
  "youCanViewYourRequestsatMyTickets":
      "U kunt uw verzoeken op mijn tickets bekijken",
  "incorrectPassword": "Incorrect wachtwoord",
  "thePasswordYouenteredisincorrectPleasetryagain":
      "Het wachtwoord dat u heeft ingevoerd, is onjuist. Probeer het opnieuw",
  "registeredCustomers": "geregistreerde klanten",
  "ifYouHaveAnAccountSignInWithYourEmailAddress":
      "Als u een account heeft, log dan in met uw e -mailadres",
  "pleaseEnterOrderNumberToTrackYourOrder":
      "Voer het bestelnummer in om uw bestelling bij te houden.",
  "enterOrderNumber": "Voer het bestelnummer in",
  "enteryOurOrderNumberHere": "Voer hier uw bestelnummer in",
  "howDoIFindMyOrderReference": "Hoe vind ik mijn bestelreferentie?",
  "passwordRegExp":
      "Het wachtwoord moet minimaal 8 tekens lang zijn en een combinatie van zowel hoofdletters als kleine letters bevatten, ten minste één nummer en één speciaal teken (bijv.,! @ #?).",
  "nylonMessengerBackpackMsg":
      "Nylon messenger rugzak van balenziaga, voorsluiting met haak, bovenste handgreep, verstelbare schouderbanden, voorste patch ritssluiting met contrastlogo, haken als decoratieve elementen.",
  "priceMatchTicket": "Prijs match ticket",
  "enterAddress3": "Voer adres 3 in",
  "enterCity": "Betreed de stad",
  "pleaseTryWithAnotherEmaiAddressMsg":
      "Probeer het met een ander e -mailadres of schrijf ons op care@brandslabels.com voor verdere hulp.",
  "Alert": "Alert",
  "requiredVal": "Is benodigd",
  "mustbeof": "moet van zijn",
  "digits": "cijfers",
  "mustbeanumberExample100": "moet een nummer zijn. Voorbeeld: 100",
  "character": "karakter",
  "isinvalid": "is ongeldig!",
  "mustbemorethan2characters": "Moet meer dan 2 tekens zijn",
  "entervalid": "Voer geldig in",
  "musthaveatleast2characters": "Moet minimaal 2 tekens hebben",
  "confirmpasswordshouldbematchwithpassword":
      "Bevestig het wachtwoord moet overeenkomen met het wachtwoord",
  "pleaseenterPassword": "Voer wachtwoord in alstublieft",
  "mustbemorethan8characters": "Moet meer dan 8 tekens zijn",
  "mobileisRequired": "Mobiel is vereist",
  "mobilenumbermust10digits": "Mobiel nummer moet 10 cijfers",
  "mobileNumbermustbedigits": "Mobiel nummer moet cijfers zijn",
  "yearmustbenumberonly": "Het jaar moet alleen nummer zijn",
  "establishedYearisRequired": "Gevestigd jaar is vereist",
  "yearmustbebetween1850and": "Jaar moet tussen 1850 en",
  "licenseNoisRequired": "Licentie nee is vereist",
  "numberofemployeeisRequired": "Aantal werknemers is vereist",
  "numberofemployeeisnotmorethan9999":
      "Aantal werknemers is niet meer dan 9999",
  "numberofemployeemustbedigits": "Aantal werknemers moet cijfers zijn",
  "dateisRequired": "Datum is vereist",
  "pleaseentervaliddate": "Voer de geldige datum in",
  "licenseIssuingAuthorityisRequired":
      "Licentie -uitgevende autoriteit is vereist",
  "licenseIssuingAuthoritymustbeazandAZ":
      "Licentie-uitgevende autoriteit moet A-Z en A-Z zijn",
  "firstNameIsRequired": "Voornaam is verplicht",
  "lastNameIsRequired": "Achternaam is vereist",
  "imageUrlIsRequired": "Afbeelding link is vereist",
  "enterValidText": "Voer geldige tekst in",
  "pleaseCheckYourInternetConnection": "Controleer uw internetverbinding!",
  "searchForPiesSushiTacos": "Zoek naar taarten, sushi, taco's ...",
  "enterSurname": "Voer straatadres in",
  "enterStreetAddress": "Voer straatadres in",
  "addNew": "Voeg nieuw toe",
  "enterAddress1": "Voer adres 1 in",
  "enterAddress2": "Voer adres 2 in",
  "noBrandFound": "Geen merk gevonden",
  "COUPONAPPLIEDSUCCESSFULLYYOUSAVED": "Coupon met succes toegepast. JIJ REDDE",
  "ONTHISORDER": "Bij deze bestelling",
  "areYouSureYouWantToRemove": "Weet je zeker dat je wilt verwijderen",
  "couponCode": "coupon code?",
  "cancel": "Annuleren",
  "itSeemsLikeWeHaveNothingToShowForThisBrand":
      "Het lijkt erop dat we niets te tonen hebben voor dit merk",
  "ifyouwouldlikeUsSendYouTheCollectionFrom":
      "Als je wilt dat we je de collectie van sturen",
  "plsCreateATicketBelow": "aub. Maak hieronder een ticket",
  "itSeemsLikeWeHaveNothingToShowForThisCategory":
      "Het lijkt erop dat we niets te tonen hebben voor deze categorie",
  "enterName": "Voer naam in",
  "description": "Beschrijving",
};
