const Map<String, String> ru = {
  "language": "английский",
  "appNameText": "Бренды и лейблы",
  "aboutUsText": "О нас",
  "aboutUsTitle": 'МЫ БРЕНД И ЭТИКЕТКИ',
  "aboutUsContain": 'ИЗУЧИТЕ 100 ЛУЧШИХ МИРОВЫХ БРЕНДОВ',
  "aboutUsContain1":
      'BRANDS & LABELS — ЛУЧШИЙ ОНЛАЙН-НАПРАВЛЕНИЕ ДЛЯ ПРОДАЖИ РОСКОШНОЙ МОДЫ С 5 МИЛЛИОНАМИ ПОСЕТИТЕЛЕЙ В МЕСЯЦ И ДОСТАВКОЙ ПО ВСЕМУ МИРУ.',
  "aboutUsContain2":
      'НА ВЕБ-САЙТЕ ПРЕДСТАВЛЕНА ЛУЧШАЯ ПОДБОРКА ИЗВЕСТНЫХ ДИЗАЙНЕРОВ, А ТАКЖЕ МОЛОДЫХ ТАЛАНТОВ. BRANDSLABELS БЫЛА ОСНОВАНА ВО ФЛОРЕНЦИИ В НАЧАЛЕ 1930-Х ГОДОВ, С ОТКРЫТИЕМ ЭПОНИМНОГО КОНЦЕПЦИОННОГО МАГАЗИНА КОМПАНИИ НА VIA ROMA. ОНЛАЙН С 1999 ГОДА КОМПАНИЯ ОТНОСИТ 90% ОБЩЕГО ДОХОДА НА ОНЛАЙН-ПРОДАЖИ. НА СЕГОДНЯ ЭТО ОСТАЕТСЯ 100% ЧАСТНЫМ СЕМЕЙНЫМ БИЗНЕСОМ, С ВНУКОМ ОСНОВАТЕЛЯ, АНДРЕА ПАНКОНЕЗИ, ДЕЙСТВУЮЩИМ В КАЧЕСТВЕ ГЕНЕРАЛЬНОГО ДИРЕКТОРА И ЕГО ДОЧЬЮ, АННАГРЕТА ПАНКОНЕЗИ, В КАЧЕСТВЕ КРЕАТИВНОГО ДИРЕКТОРА.',
  "aboutUsContain3":
      'САЙТ ПРЕДЛАГАЕТ ШИРОКИЙ ВЫБОР ОДЕЖДЫ, ОБУВИ, СУМОК, АКСЕССУАРОВ, РОСКОШНЫХ ИНТЕРЬЕРОВ ДЛЯ ДОМА И КРАСОТЫ, ТОВАРЫ ДЛЯ МУЖЧИН, ЖЕНЩИН И ДЕТЕЙ ОТ НАИБОЛЕЕ ПРЕСТИЖНЫХ ДИЗАЙНЕРОВ, ТАКИХ, КАК BALENCIAGA, VETEMENTS, OFF-WHITE, J.W. ANDERSON, BALMAIN, DOLCE & GABBANA, GUCCI, SAINT LAURENT, VALENTINO, GIVENCHY, LOEWE, JACQUEMUS И ДРУГИЕ.',
  "aboutUsContain4":
      'В НАСТОЯЩЕЕ ВРЕМЯ 200 ЧЕЛОВЕК ИЗ 15 РАЗНЫХ СТРАН РАБОТАЮТ НАД ПРОИЗВОДСТВОМ И ПОДДЕРЖАНИЕМ БРЕНДОВ. САЙТ ДОСТУПЕН НА 9 ЯЗЫКАХ: АНГЛИЙСКОМ, ИТАЛЬЯНСКОМ, НЕМЕЦКОМ, КИТАЙСКОМ, РУССКОМ, ИСПАНСКОМ, ФРАНЦУЗСКОМ, КОРЕЙСКОМ И ЯПОНСКОМ. САЙТ СОЗДАЕТСЯ ПОЛНОСТЬЮ СОБСТВЕННО, С ОТДЕЛАМИ ГРАФИЧЕСКОГО ДИЗАЙНА, ИТ, ОБСЛУЖИВАНИЯ КЛИЕНТОВ, МАРКЕТИНГА И ЗАКУПОК. СТИЛИСТЫ И ПРЕСС-КОМАНДЫ РАБОТАЮТ В ОФИСЕ BRANDSLABELS В СТОЛИЦЕ МИРА МОДЫ – МИЛАНЕ.',
  "aboutUsContain5":
      'ВСЕ ЗАКАЗЫ ДОСТАВЛЯЮТСЯ ПО ВСЕМУ МИРУ ИЗ ШТАБ-КВАРТИРЫ BRANDS LABELS В КОРОБКАХ, КОТОРЫЕ ПОДГОТОВЛЕНЫ С МАКСИМАЛЬНОЙ ТЩАТЕЛЬНОСТЬЮ И С ИСПОЛЬЗОВАНИЕМ ЛУЧШИХ МАТЕРИАЛОВ, ОТ ФИРМЕННЫХ СУМОК ДЛЯ ОБУВИ ДО ИНДИВИДУАЛЬНОЙ ЛЕНТЫ.',
  "aboutUsContain6":
      'В 2008 ГОДУ НА САЙТ BRANDSLABELS ПОСЕТИЛИ 1,5 МИЛЛИОНА УНИКАЛЬНЫХ ПОСЕТИТЕЛЕЙ, а В 2017 ГОДУ УНИКАЛЬНЫЕ ПОСЕТИТЕЛИ ВЫРОСЛИ ДО 53 МИЛЛИОНОВ. БОЛЕЕ 15% ОНЛАЙН-ПРОДАЖ ОСУЩЕСТВЛЯЕТСЯ ИЗ СОЕДИНЕННЫХ ШТАТОВ, ЗА КОТОРЫМИ ЗАНИМАЮТСЯ ГЕРМАНИЯ, ВЕЛИКОБРИТАНИЯ, ИТАЛИЯ, КИТАЙ И ФРАНЦИЯ.',
  "aboutUsContain7":
      'BRANDSLABELS РАЗДВИГАЕТ ГРАНИЦЫ РОЗНИЧНОЙ ПРОДАЖИ РОСКОШНОЙ ПРОДАЖИ КАК ОНЛАЙН, И ОНЛАЙН, ПРЕДЛАГАЯ МНОЖЕСТВО ЭКСКЛЮЗИВНЫХ УСЛУГ И ИНИЦИАТИВ ТОРГОВЫХ МАРОК, ВКЛЮЧАЯ BUY IT FIRST, LUXURY CLUB, SNEAKERS CLUB, LVR PRIVILEGE И LVR EDITIONS.',
  "profile": "Профиль",
  "firstNameText": "Имя",
  "lastNameText": "Фамилия",
  "emailText": "Эл. адрес",
  "ContactNoText": "Контактный номер",
  "websiteUrlText": "ссылка на сайт",
  "cityText": "Город",
  "countryText": "Страна",
  "postCodeText": "Почтовый индекс",
  "socialLinksText": "Социальные ссылки",
  "facebookText": "Фейсбук",
  "instagramText": "Инстаграм",
  "twitterText": "Твиттер",
  "youtubeText": "YouTube",
  "linkendinText": "Линкендин",
  "pinterestText": "Пинтерест",
  "followersText": "Последователи",
  "mr": "Г-н.",
  "letsText": "Пойдем",
  "orderIdTitle": '''Ваш заказ №: ''',
  "orderDateTitle": 'Дата заказа: 15 сентября 2021 г.',
  "orderNumberTitle": 'НОМЕР ЗАКАЗА: ',
  "orderConfirm": "СПАСИБО ЗА ПОКУПКУ!",
  "name": "ИМЯ",
  "sku": "Артикул",
  "price": "ЦЕНА",
  "qty": "КОЛ-ВО",
  "subTotal": "ПРОМЕЖУТОЧНЫЙ ИТОГ",
  "action": "ДЕЙСТВИЕ",
  "addressBook": "Адресная книга",
  "billing": "Выставление счетов",
  "shipping": "Перевозки",
  "orderContain":
      'Мы отправим вам подтверждение заказа по электронной почте с деталями и информацией для отслеживания.',
  "referFriendText": "Пригласить друга",
  "returnsRefundsText": "Возвраты и возмещения",
  "faqText": "Вопросы-Ответы",
  "contactText": "Контакт",
  "socialText": "Социальное",
  "companyText": "Компания",
  "myOrders": "мои заказы",
  "myOrderImage": "Изображение",
  "productName": "наименование товара",
  "quantity": "Кол-во",
  "status": "Положение дел",
  "paymentMethod": " Способ оплаты",
  "shippingAddress": "адреса доставки",
  "billingAddress": "Адрес для выставления счета",
  "continueShopping": "Продолжить покупки",
  "generalAndOrderEnquiriesText": "ОБЩИЕ ЗАПРОСЫ И ЗАКАЗЫ",
  "gdpText": "ВВП",
  "engText": "АНГЛ",
  "nameText": "Имя*",
  "surNameText": "Фамилия*",
  "emailAddressText": "Адрес электронной почты*",
  "confirmEmailAddressText": "Подтвердите адрес электронной почты*",
  "subjectText": "Тема*",
  "phoneNumberText": "Телефонный номер",
  "whatsOnYourMindText": "О чем ты думаешь?*",
  "queryDescription":
      "Каким бы ни был ваш запрос, используйте контактную форму ниже, чтобы связаться с нами. Наша команда готова помочь 24/7.",
  "submitText": "ПРЕДСТАВИТЬ",
  "typeOfEnquiryText": "Тип запроса*",
  "registeredCustomersText": "Зарегистрированные клиенты",
  "signInDescriptionText":
      "Если у вас есть учетная запись, войдите, используя свой\nemail адрес.",
  "forgotYourPasswordText": "Забыли Ваш пароль?",
  "signInText": "Войти",
  "newCustomersText": "новые клиенты",
  "newCustomersDescriptionText":
      "Создание учетной записи имеет много преимуществ:\nбыстрее оформить заказ, сохранить несколько адресов,\nотслеживать заказы и многое другое.",
  "createAccountText": "Завести аккаунт",
  "aboutProjectNameText": "О брендах и лейблах",
  "helpAndInformationText": "Помощь и информация",
  "moreFromProjectText": "Еще от Brands&Labels",
  "newsLetterText": "Новостная рассылка",
  "subscribeText": "Подписаться",
  "passwordText": "Пароль",
  "homeText": "Дома",
  "searchText": "Поиск",
  "designersText": "Дизайнеры",
  "wishListText": "Список желаний",
  "loginText": "Авторизоваться",
  "myAccountText": "Мой счет",
  "yourEmailText": "Ваш адрес электронной почты",
  "checkoutText": "Проверить",
  "purchaseText":
      "Пожалуйста, введите свои данные ниже, чтобы завершить покупку",
  "shippingAddressText": "адреса доставки",
  "shippingMethodText": "способ доставки",
  "paymentMethodText": "Способ оплаты",
  "orderSummaryText": "итог заказа",
  "addressText":
      "admin admintast product, test product, test product test product, b12345 302006Россия 1234567890",
  "newAddressText": "Новый адрес",
  "itemInCartText": "Товар в корзине",
  "qtyText": "Кол-во",
  "applyDiscountCodeText": "Применить код скидки",
  "enterDiscountCodeText": "Введите код скидки",
  "applyDiscountText": "Применить скидку",
  "orderTotalText": "Весь заказ",
  "orderCommentText": "Комментарий к заказу",
  "placeOrderText": "РАЗМЕСТИТЬ ЗАКАЗ",
  "myOrdersText": "МОИ ЗАКАЗЫ",
  "myWishlistText": "Мой список пожеланий",
  "addressBookText": "Адресная книга",
  "accountInformationText": "Информация об аккаунте",
  "storePaymentText": "СОХРАНЕННЫЕ СПОСОБЫ ОПЛАТЫ",
  "newsLetter1Text": "ПОДПИСКА НА РАССЫЛКУ",
  "enterEmailAddress": "Введите адрес электронной почты",
  "enterConfirmEmailAddress":
      "Введите адрес электронной почты для подтверждения",
  "enterPhoneNumber": "Введите номер телефона",
  "enterValidEmailAddress": "Введите действительный адрес электронной почты",
  "confirmEmailNotMatch":
      "Подтверждение соответствия адреса электронной почты адресу электронной почты",
  "phoneNumberIsRequired": "Номер телефона обязателен",
  "phoneNumberIsNotValid": "Недопустимый номер телефона",
  "gstIdentificationNumber":
      "Идентификационный номер GST недействителен. Он должен быть в этом формате 11AAAAA1111Z1A1",
  "emailRequired": "Адрес электронной почты обязателен",
  "invalidEmail": "Недопустимый адрес электронно",
  "confirmEmailIsRequired":
      "Подтвердите, что адрес электронной почты обязателен",
  "confirmEmailShouldBeMatchWithEmail":
      "Подтвердите, что адрес электронной почты должен совпадать с адресом электронной почты",
  "youHaveReachedYourMaximumLimit":
      "Вы достигли максимально допустимого количества символов",
  "passwordIsRequired": "Пароль обязателен",
  "successfullyLoggedOut": "Вы успешно вышли из системы",
  "emailAddress": "Адрес электронной почты",
  "enterEmailToTrackRequest.":
      "Пожалуйста, введите свой адрес электронной почты, чтобы отслеживать ваш запрос.",
  "firstName": "Имя",
  "lastName": "Фамилия",
  "dateOfBirth.": "Дата рождения",
  "dateOfMarriage": "Годовщина бракосочетания",
  "signUpForNewsletter": "Подписаться на рассылку новостей",
  "email": "Отправить по электронной почте",
  "password": "Пароль",
  "confirmPassword": "Подтвердите пароль",
  "typesOfEnquiry": "Типы запросов",
  "confirmPasswordIsRequired.": "ПодтверждениеПароль обязательный",
  "orderDetails": "Детали заказа",
  "noDataAvailable": "Данные отсутствуют",
  "myAccount": "Мой аккаунт",
  "mrs": "Госпожа.",
  "communicationPrefences.": "Настройки связи",
  "subscribeNewsletters": "Подпишитесь на новостную рассылку ounass..",
  "aboutUs": "О нас",
  "sms": "СМС",
  "save": "Спасать",
  "tearmsAndCondition": "УСЛОВИЯ И ПОЛОЖЕНИЯ",
  "subscribeOffersAndMore":
      "Подпишитесь, чтобы быть первыми с нашими новыми поступлениями, эксклюзивными коллекциями, предложениями и многим другим.",
  "ourServices": "Наши услуги",
  "delivery": "Доставка",
  "ourWebsite": "Наш веб-сайт",
  "addToCart": "Добавить в корзину",
  "subscribe": "Подписываться",
  "productDetails": "Сведения о продукте",
  "priceMatch": "Соответствие цен",
  "composition": "Состав",
  "color": "Цвет",
  "chooseAnOption": "Выберите вариант...",
  "yourBestPriceAlways": "Ваша лучшая цена - всегда.",
  "IfYourPreferredItemIsLowerMsg":
      "Если ваш предпочтительный товар будет ниже в любом другом магазине в текущее время, мы будем соответствовать цене и предложим вам 10% дополнительный кредит магазина для вашей следующей покупки.",
  "simplyLetUsKnowByClickingHere": "Просто дайте нам знать, нажав здесь.",
  "alreadyMadeYourPurchase": "Уже совершил вашу покупку.",
  "dontWorryLetUsKnowByClickingMsg":
      "Не волнуйтесь, дайте нам знать, нажав здесь, и мы, наша команда поддержки клиентов, вернем вам разницу, если покупка была сделана в течение последних 30 дней.",
  "pleaseSeeFAQsByClickingHere":
      "Пожалуйста, смотрите часто задаваемые вопросы, нажав здесь",
  "filter": "Фильтр",
  "sort": "Сортировать",
  "sortBy": "Сортировать по",
  "noProductsFound": "Не найдено продуктов",
  "createTicket": "Создать билет",
  "more": "& Более...",
  "bgbp": "Фунт стерлингов",
  "findBrand": "Найти бренды",
  "itSeemsWeHaveNothingToShowFor": "Кажется, нам нечего показать",
  "ifYouWouldLikeToHaveMoreInformationAbout":
      "Если вы хотите получить больше информации о",
  "thenPleaseCreateATicket": "Тогда, пожалуйста, создайте билет",
  "contactInformation": "Контакты",
  "edit": "Редактировать",
  "changePassword": "Изменить пароль",
  "youHaveNoProductsInYourWishList":
      "У вас нет продуктов в вашем списке желаний.",
  "toBbeUpdated": "Быть обновленным",
  "youHaveNoSavedAddressAddnewAddressToContinueWithCheckout":
      "У вас нет сохраненного адреса добавить новый адрес, чтобы продолжить заказа с проверкой",
  "shipHere": "Корабль здесь",
  "enterFirstName": "Введите имя",
  "enterLastName": "Введите фамилию",
  "enterStreetAddress1": "Введите адрес улицы 1",
  "streetAddress1": "Улица 1",
  "enterStreetAdress2": "Введите уличный адрес 2",
  "streetAddress2": "Уличный адрес 2",
  "enterStreetAddress3": "Введите адрес улицы 3",
  "streetAddress3": "Уличный адрес 3",
  "enterCityName": "Введите название города",
  "city": "Город",
  "country": "Страна",
  "enterZipPostalCode": "Введите почтовый код ZIP",
  "zipPostalCode": "Zip/почтовый код",
  "stateProvince": "Государство/провинция",
  "enterStateProvince": "Войти в государство/провинцию",
  "emailAddressRequired": "Требуется адрес электронной почты",
  "cancelCoupon": "Отменить купон",
  "apply": "Подать заявление",
  "viewCouponList": "Просмотреть список купонов",
  "coupons": "купоны",
  "changeLanguageAndCurrency": "Изменение языка и валюты",
  "youHaveNoOrders": "У тебя нет заказов",
  "youHaveNoTickets": "У тебя нет билетов",
  "category": "Категория",
  "createNewTicket": "Создайте новый билет",
  "positiveImpactSustainability": "Положительное влияние + устойчивость",
  "thereAreStillMoreThanMSG":
      "По -прежнему существует более миллиардов человек, живущих в крайней нищете менее чем на 1,25 доллара в день. Только в Таиланде на полях общества существует более миллиона членов Хилл -племен - отказавшись в гражданстве, выключенном от официального рынка труда и уязвимым для эксплуатации и торговли людьми.",
  "atYellowLeafHammocksMsg":
      "В гамаках желтых листьев мы считаем, что этическое создание рабочих мест является расширением возможностей долгосрочного решения для крайней нищеты.",
  "insteadOfOrganizingMsg":
      "Вместо того, чтобы организовать лоскутное одеяло благотворительных пожертвований для обеспечения воды, питания, одежды и т. Д., Мы работаем напрямую с семьями, чтобы создать комплексную, достойную, долгосрочную стратегию в направлении более яркого будущего. Причины системной бедности сложны, но долгосрочная финансовая стабильность находится в пределах досягаемости.",
  "toPutItSimplyMsg":
      "Проще говоря: сосредоточив внимание на средствах к существованию, мы можем вырезать среднего человека, получить деньги непосредственно в руки умных + находчивых матерей и дают семьям решать свои собственные проблемы (не подвергаясь чьей -либо повестке дня).",
  "acrossThreeWeavingCommunitiesMsg":
      "В трех ткацких сообществах мы работаем над созданием рабочих мест для матерей и создаем основу для позитивной трансформации сообщества. Благодаря гибкой, безопасной ткачественной работе «Процвета по заработной плате» наши ремесленники могут поднять свои семьи из бедности и рабства долгов в средний класс.",
  "creatingJobsForWomenMsg":
      "** Создание рабочих мест для женщин особенно важно для трансформации сообщества - исследования показывают, что женщины проведут до 90% своих доходов на здоровье, питание и образование своих семей. Превращение женщин в кормильцы улучшает свой статус в обществе, создает самооценку и позволяет им объединять ресурсы для улучшения инфраструктуры.",
  "theFoundationForABrighterFuter": "Фонд для более яркого фута",
  "theSecurityOfAStableMsg":
      "Безопасность стабильного, растущего источника доходов оказала огромное влияние на деревню. Млабри смог начать школу и построить общественный центр для ткачества и общения. Они создали один из первых средств по безработице в Таиланде. Благодаря увеличению экономической власти они успешно лоббировали гражданство и гражданские права, которые они впервые были предоставлены в 2001 году. Протекание гамака является гибкой работой, идеально подходящей для матерей, которые могут работать из дома и делать свои собственные графики. К сожалению, без доступа к мировым рынкам спрос на гамаки ограничивался тайским туристическим сезоном, и не было никакого способа обеспечить круглогодичную занятость.",
  "spreadingLastingChangeTheHammockRrevolution":
      "Распространение длительных изменений: rrevolution гамака",
  "thisIsAboutWhereMsg":
      "Это о том, где присоединяется желтый лист! За последние несколько лет мы работали над разработкой последовательных каналов продаж, строительство международных партнерских отношений и стабилизировали операции в деревнях.",
  "corollaryEconomicMsg":
      "Экономические возможности для следствия, такие как почтовое отделение, приготовление пищи и устойчивое ведение кофе, возникли для использования тех, кто не плетение. Наше партнерство с Kiva стимулировало финансовое обучение и финансовое планирование, и многие ткачи открыли банковские счета впервые в своей жизни!",
  "wWithOurGrowthMsg":
      "В связи с тем, что наш рост продолжает ускоряться, мы не только сможем использовать все ткачи Mlabri круглый год, но и продолжим расширять и проводить обучение и постоянную работу в общинах племени Hill в окружающем регионе. До тех пор, пока в этом районе не будут доступны ткацкие работы и устойчивые рабочие места, разрушительные сельскохозяйственные практики будут продолжаться, и эксплуатационный цикл нанятого рабства не закончится.",
  "throughTheEstablishmentMsg":
      "Благодаря созданию желтого листа в качестве мирового бренда образа жизни, деревни Hill Tribe, с которыми мы сотрудничаем, смогут поддерживать это положительное влияние и продолжать закладывать основу для более светлого будущего.",
  "enterWebsite": "Введите веб -сайт",
  "enterPostCode": "Введите почтовый код",
  "thankYouForYourInterest": "Спасибо за ваш интерес к работе с брендами",
  "oneOfOurTeamMembersWillBeInTouchSoon":
      "Один из членов нашей команды скоро свяжется с",
  "forAnyAdditionalQueriesPleaseWriteTo ":
      "Для любых дополнительных запросов, пожалуйста, напишите",
  "theProductIsOutOfStock": "Продукт нет в наличии.",
  "whateverYourQueryUseTheContactFormBelowMsg":
      "Какой бы ни был ваш запрос. Используйте контактную форму ниже, чтобы попасть в Touch-ourteam, готов помочь 24*7",
  "enterSubject": "Введите предмет",
  "enterSomeText": "Введите немного текста",
  "enterDetailsBelowToSend":
      "Введите данные ниже, чтобы отправить код купона 10% своему другу",
  "enterFriendName": "Введите имя друга",
  "friendFirstName": "Друг Имя",
  "enterFirstEmailAddress": "Введите первый адрес электронной почты",
  "friendEmailAddress": "Друг адрес электронной почты",
  "enterFirstPhoneNumber": "Введите первый номер телефона",
  "friendPhoneNumber": "Друг номер телефона",
  "register": "регистр",
  "dateOfBirthIsRequired": "ДАТА ОФОНА ТРЕБУЕТСЯ",
  "marriageAnniversaryIsRequired": "Требуется годовщина брака",
  "surnameIsRequired": "Фамилия требуется",
  "date": "Свидание",
  "showDialog": "Показать диалог",
  "removeProduct": "Удалить продукт",
  "areYouSureWantToRemoveThisProductFromCart":
      "Вы уверены, что хотите удалить этот продукт из корзины?",
  "yes": "ДА",
  "no": "НЕТ",
  "addToWishlist": "Добавить в список желаний",
  "onceYouAddThisProductToWishlistThenItWillBeRemoveFromAart":
      "Как только вы добавите этот продукт в список желаний, он будет удален из корзины",
  "ok": "ХОРОШО",
  "nouHaveNoItemsInYourShoppingCart": "У вас нет предметов в вашей корзине.",
  "Discount": "Скидка",
  "enterCouponCode": "Введите код купона",
  "removeCoupon": "Удалить купон",
  "availableCouponList": "Доступный список купонов",
  "allCouponsList": "Список всех купонов",
  "addProductToYourWishList": "Добавьте продукт в свой список желаний",
  "configurable": "настраивается",
  "Missing": "Отсутствующий",
  "Amount": "Количество",
  "Balance": "Остаток средств",
  "Remarks": "Замечания",
  "myAddresses": "Мои адреса",
  "noAddressFound": "Никакого адреса не найдено",
  "addAddress": "Добавить адрес",
  "updateAddress": "Обновление адреса",
  "expectedShipmentDate": "Ожидаемая дата отгрузки",
  "brandNameIsRequired": "Требуется торговая марка",
  "styleIsRequired": "Стиль требуется",
  "keywordIsRequired": "Требуется ключевое слово",
  "remarkIsRequired": "Замечание требуется",
  "couponId": "Идентификатор купона",
  "couponName": "Название купона",
  "expireAt": "Истекает в",
  "noCouponsFound": "Купонов не найдено!",
  "yourRequestHasBeenReceived": "Ваш запрос был получен.",
  "youCanViewYourRequestsatMyTickets":
      "Вы можете просмотреть свои запросы на моих билетах",
  "incorrectPassword": "Неверный пароль",
  "thePasswordYouenteredisincorrectPleasetryagain":
      "Введенный вами пароль неверен. Пожалуйста, попробуйте еще раз",
  "registeredCustomers": "Зарегистрированные клиенты",
  "ifYouHaveAnAccountSignInWithYourEmailAddress":
      "Если у вас есть учетная запись, войдите в систему с адресом электронной почты",
  "pleaseEnterOrderNumberToTrackYourOrder":
      "Пожалуйста, введите номер заказа, чтобы отслеживать ваш заказ.",
  "enterOrderNumber": "Введите номер заказа",
  "enteryOurOrderNumberHere": "Введите номер свой заказ здесь",
  "howDoIFindMyOrderReference": "Как мне найти ссылку на заказ?",
  "passwordRegExp":
      "Пароль должен быть не менее 8 символов в длину и содержать смесь как прописных, так и строчных букв, по крайней мере одного числа и одного специального символа (например,! @ #?).",
  "nylonMessengerBackpackMsg":
      "Рюкзак Nylon Messenger от Balenziaga, переднее закрытие с крючком, верхняя ручка, регулируемые плечевые ремни, передний патч -карман с логотипом контрастного, крючки в качестве декоративных элементов.",
  "priceMatchTicket": "Билет в соответствии с ценой",
  "enterAddress3": "Введите адрес 3",
  "enterCity": "Войти в город",
  "pleaseTryWithAnotherEmaiAddressMsg":
      "Пожалуйста, попробуйте другой адрес электронной почты или напишите нам по адресу care@brandslabels.com для получения дополнительной помощи.",
  "Alert": "Тревога",
  "requiredVal": "требуется для",
  "mustbeof": "Должно быть",
  "digits": "цифры",
  "mustbeanumberExample100": "должно быть числом. Пример: 100",
  "character": "персонаж",
  "isinvalid": "является недействительным!",
  "mustbemorethan2characters": "должно быть более 2 символов",
  "entervalid": "Введите действительный",
  "musthaveatleast2characters": "Должен иметь как минимум 2 символа",
  "confirmpasswordshouldbematchwithpassword":
      "Подтвердите пароль должен соответствовать паролю",
  "pleaseenterPassword": "Пожалуйста введите пароль",
  "mustbemorethan8characters": "Должно быть более 8 символов",
  "mobileisRequired": "Мобильный телефон требуется",
  "mobilenumbermust10digits": "Мобильный номер должен 10 цифр",
  "mobileNumbermustbedigits": "Мобильный номер должен быть цифрами",
  "yearmustbenumberonly": "Год должен быть только номер",
  "establishedYearisRequired": "Требуется установленный год",
  "yearmustbebetween1850and": "Год должен быть между 1850 году и",
  "licenseNoisRequired": "Лицензия НЕТ ТРЕБУЕТСЯ",
  "numberofemployeeisRequired": "Требуется количество сотрудников",
  "numberofemployeeisnotmorethan9999": "Количество сотрудников не более 9999",
  "numberofemployeemustbedigits": "Количество сотрудников должно быть цифрами",
  "dateisRequired": "Дата требуется",
  "pleaseentervaliddate": "Пожалуйста, введите действительную дату",
  "licenseIssuingAuthorityisRequired":
      "Требуется полномочия по выдаче лицензий",
  "licenseIssuingAuthoritymustbeazandAZ":
      "Орган по выдаче лицензий должен быть A-Z и A-Z",
  "firstNameIsRequired": "Имя требуется",
  "lastNameIsRequired": "Фамилия требуется",
  "imageUrlIsRequired": "Ссылка на изображение требуется",
  "enterValidText": "Введите допустимый текст",
  "pleaseCheckYourInternetConnection":
      "Пожалуйста, проверьте подключение к интернету!",
  "searchForPiesSushiTacos": "Ищите пироги, суши, тако ...",
  "enterSurname": "Введите фамилию",
  "enterStreetAddress": "Введите адрес улицы",
  "addNew": "Добавить новое",
  "enterAddress1": "Введите адрес 1",
  "enterAddress2": "Введите адрес 2",
  "noBrandFound": "Бренда не найдено",
  "COUPONAPPLIEDSUCCESSFULLYYOUSAVED": "Купон применяется успешно. Вы спасли",
  "ONTHISORDER": "В этом порядке",
  "areYouSureYouWantToRemove": "Вы уверены, что хотите удалить",
  "couponCode": "код купона?",
  "cancel": "Отмена",
  "itSeemsLikeWeHaveNothingToShowForThisBrand":
      "Кажется, что нам нечего показать для этого бренда",
  "ifyouwouldlikeUsSendYouTheCollectionFrom":
      "Если вы хотите, чтобы мы отправили вам коллекцию из",
  "plsCreateATicketBelow": "плс. Создайте билет ниже",
  "itSeemsLikeWeHaveNothingToShowForThisCategory":
      "Кажется, что нам нечего показать для этой категории",
  "enterName": "Введите имя",
  "description": "Описание",
};
