const Map<String, String> ar = {
  "language": "إنجليزي",
  "appNameText": "فاخر منفرد",
  "aboutUsText": "معلومات عنا",
  "referFriendText": "ادع صديق",
  "returnsRefundsText": "العوائد والمردودات",
  "faqText": "التعليمات",
  "contactText": "اتصل",
  "socialText": "اجتماعي",
  "companyText": "شركة",
  "freuentlyAskedQueText": "أسئلة مكررة",
  "shopAndPlaceOrder": "كيف تتسوق وتضع طلب؟",
  "accountToPlaceOrderQues": "هل أحتاج إلى حساب لتقديم طلب؟",
  "accountToPlaceOrderAns":
      "لا ، كل ما تحتاجه هو عنوان بريد إلكتروني. نوصيك بالتسجيل للحصول على حساب لبدء إضافة قطع إلى قائمة الرغبات الخاصة بك ، ولكن يمكنك أيضًا تقديم الطلبات وتتبعها كضيف والاشتراك في الوقت الذي يناسبك.",
  "createNewCustomerAccountText": "إنشاء حساب عميل جديد",
  "emailAddressText": "عنوان بريد الكتروني",
  "confirmEmailAddressText": "أكد عنوانك الإلكتروني",
  "passwordText": "كلمة المرور",
  "confirmPasswordText": "تأكيد كلمة المرور",
  "firstNameText": "الاسم الأول",
  "lastNameText": "الكنية",
  "dateOfBirthText": "تاريخ الميلاد",
  "marriageAnniversaryText": "ذكرى الزواج",
  "signUpForNewsLetterText": "الاشتراك في النشرة الإخبارية",
  "registerWithFacebookText": "سجل مع الفيسبوك",
  "createAnAccountText": "إنشاء حساب",
  "customerLoginText": "تسجيل دخول العميل",
  "signInText": "تسجيل الدخول",
  "forgotYourPasswordText": "نسيت رقمك السري؟",
  "loginWithFacebookText": "تسجيل الدخول باستخدام الفيسبوك",
  "newCustomersText": "زبائن الجدد",
  "newCustomersDescriptionText":
      "إنشاء حساب له فوائد عديدة:  n تحقق بشكل أسرع ، واحتفظ بأكثر من عنوان ،  n تتبع الطلبات والمزيد.",
  "homeText": "الصفحة الرئيسية",
  "searchText": "بحث",
  "designersText": "المصممين",
  "wishListText": "قائمة الرغبات",
  "loginText": "تسجيل الدخول",
  "myAccountText": "حسابي",
  "subscribeText": "الإشتراك",
  "yourEmailText": "بريدك الالكتروني",
  "checkoutText": "الدفع",
  "purchaseText": "الرجاء إدخال التفاصيل الخاصة بك أدناه لإكمال عملية الشراء",
  "shippingAddressText": "عنوان الشحن",
  "shippingMethodText": "طريقة الشحن",
  "paymentMethodText": "طريقة الدفع او السداد",
  "orderSummaryText": "ملخص الطلب",
  "itemInCartText": "عنصر في عربة التسوق",
  "qtyText": "الكمية",
  "emailText": "بريد الالكتروني",
  "createCheckoutText": "يمكنك إنشاء حساب بعد الخروج.",
  "streetAddressText": "عنوان الشارع",
  "cityText": "مدينة",
  "unitedKingdomText": "المملكة المتحدة",
  "stateText": "الولاية / المقاطعة",
  "zipCodeText": "الرمز البريدي / الرمز البريدي",
  "phoneNumberText": "رقم التليفون",
  "priceText": "السعر",
  "titleText": "لقب",
  "carrierTitleText": "عنوان الناقل",
  "viewDetailText": "عرض التفاصيل",
  "applyDiscountCodeText": "تطبيق كود الخصم",
  "enterDiscountCodeText": "أدخل رمز الخصم",
  "applyText": "تطبيق",
  "cartSubTotalText": "مجموع سلة التسوق",
  "orderCommentText": "طلب التعليق",
  "placeOrderText": "مكان الامر",
  "myOrdersText": "طلباتي",
  "myWishlistText": "قائمة امنياتي",
  "addressBookText": "دليل العناوين",
  "accountInformationText": "معلومات الحساب",
  "storePaymentText": "طرق الدفع المخزنة",
  "newsLetterText": "اشتراك الرسائل الإخبارية",
};
