const Map<String, String> de = {
  "language": "Englisch",
  "appNameText": "Solo-Luxus",
  "aboutUsText": "Über uns",
  "referFriendText": "Freund empfehlen",
  "returnsRefundsText": "Rückgabe & Erstattung",
  "faqText": "Faq",
  "contactText": "Kontakt",
  "socialText": "Sozial",
  "companyText": "Gesellschaft",
  "freuentlyAskedQueText": "Häufig gestellte Fragen",
  "shopAndPlaceOrder": "Wie kaufe ich ein und gebe eine Bestellung auf?",
  "accountToPlaceOrderQues":
      "Benötige ich ein Konto, um eine Bestellung aufzugeben?",
  "accountToPlaceOrderAns":
      "Nein, Sie benötigen lediglich eine E-Mail-Adresse. Wir empfehlen Ihnen, sich für ein Konto zu registrieren, um mit dem Hinzufügen von Artikeln zu Ihrer Wunschliste zu beginnen, aber Sie können auch Bestellungen als Gast aufgeben und verfolgen und sich zu einem für Sie passenden Zeitpunkt anmelden.",
  "createNewCustomerAccountText": "NEUES KUNDENKONTO ERSTELLEN",
  "emailAddressText": "E-Mail-Addresse",
  "confirmEmailAddressText": "e-Mail-Adresse bestätigen",
  "passwordText": "Passwort",
  "confirmPasswordText": "Bestätige das Passwort",
  "firstNameText": "Vorname",
  "lastNameText": "Familienname, Nachname",
  "dateOfBirthText": "Geburtsdatum",
  "marriageAnniversaryText": "Hochzeitstag",
  "signUpForNewsLetterText": "Anmeldung für Newsletter",
  "registerWithFacebookText": "Registrieren Sie sich bei Facebook",
  "createAnAccountText": "EIN KONTO ERSTELLEN",
  "customerLoginText": "Kundenlogin",
  "signInText": "Anmelden",
  "forgotYourPasswordText": "Haben Sie Ihr Passwort vergessen?",
  "loginWithFacebookText": "Mit Facebook einloggen",
  "newCustomersText": "neue Kunden",
  "newCustomersDescriptionText":
      "Das Erstellen eines Kontos hat viele Vorteile:\nBezahle schneller, behalte mehr als eine Adresse,\nverfolge Bestellungen und mehr.",
  "homeText": "Zuhause",
  "searchText": "Suche",
  "designersText": "Designer",
  "wishListText": "Wunschzettel",
  "loginText": "Anmeldung",
  "myAccountText": "Mein Konto",
  "subscribeText": "ABONNIEREN",
  "yourEmailText": "Deine E-Mail",
  "checkoutText": "Kasse",
  "purchaseText":
      "Bitte geben Sie unten Ihre Daten ein, um Ihren Kauf abzuschließen",
  "shippingAddressText": "Lieferanschrift",
  "shippingMethodText": "Versandart",
  "paymentMethodText": "Zahlungsmethode",
  "orderSummaryText": "Bestellübersicht",
  "itemInCartText": "Artikel im Warenkorb",
  "qtyText": "Menge",
  "emailText": "Email",
  "createCheckoutText": "Sie können nach der Kasse ein Konto erstellen.",
  "streetAddressText": "Adresse",
  "cityText": "Stadt",
  "unitedKingdomText": "Vereinigtes Königreich",
  "stateText": "Staat/Provinz",
  "zipCodeText": "Postleitzahl",
  "phoneNumberText": "Telefonnummer",
  "priceText": "Preis",
  "titleText": "Titel",
  "carrierTitleText": "Trägertitel",
  "viewDetailText": "Details anzeigen",
  "applyDiscountCodeText": "Rabattcode anwenden",
  "enterDiscountCodeText": "RABATTCODE EINGEBEN",
  "applyText": "ANWENDEN",
  "cartSubTotalText": "Warenkorb Zwischensumme",
  "orderCommentText": "Kommentar bestellen",
  "placeOrderText": "BESTELLUNG AUFGEBEN",
  "myOrdersText": "MEINE BESTELLUNGEN",
  "myWishlistText": "Meine Wunschliste",
  "addressBookText": "Adressbuch",
  "accountInformationText": "Kontoinformationen",
  "storePaymentText": "GESPEICHERTE ZAHLUNGSARTEN",
  "newsLetterText": "NEWSLETTER-ABOS",
};
