const Map<String, String> en = {
  "language": "English",
  "appNameText": "Solo Luxury",
  "orderConfirm": "Thank You For Your Purchase!",
  "orderIdTitle": '''Your order # is:''',
  "orderDateTitle": 'Order Date: ',
  "expectedShippingDate": "Expected Shipment Date:",
  "subTotal": "Subtotal",
  "orderContain":
      'We’ll email you an order confirmation with details and tracking info.',
  "returnPolicyTitle": "Return Policy",
  "faqTitle": "Frequently Asked Questions",
  "refundTitle": "Refunds",
  "addToCart": "Add To Cart",
  "soldOut": "Sold  Out",
  "notifyMe": "Notify Me When Available",
  "appnameText": "AVOIR CHIC",
  "wishList": "Wishlist",
  "addAll": "Add All",
  "addAddressText": "Add Address",
  "returnProcessTitle": "Return Process",
  "customisedTitle": "Customised, Pre-Owend & Vintage Items",
  "howToReturnTitle": "How To Return",
  "returnPolicyContain1":
      "Returned Items Must Comply With Our Returns Policy:\n",
  "returnPolicyContain2":
      'Items must be returned unworn, undamaged and unused, with all tags attached and the original packaging included.',
  "returnPolicyContain3":
      'Footwear and accessories must be returned with the original branded boxes and dust bags, where provided, and placed inside a protective outer box for shipping.',
  "returnPolicyContain4":
      'When trying on footwear, please take care not to mark the soles or damage the shoe box.',
  "returnPolicyContain5":
      'If an item has a Avoirchic security tag or brand tag attached, it must be returned with the tag in its original.',
  "returnPolicyContain6":
      'Beauty and cosmetic products must be returned unopened and unused, with the seals of any packaging still intact.',
  "returnPolicyContain7":
      'Hosiery, lingerie and swimwear items must be returned with the hygiene seals attached and in unopened and undamaged product packaging, where applicable.',
  "returnPolicyContain8":
      'Lingerie and swimwear must only be tried on over your own undergarments. We will not accept any returns that have been worn or are soiled.',
  "returnPolicyContain9":
      'Face masks must be returned unworn in their original, unopened and undamaged product packaging. Jewellery must be returned in the same condition it arrived in, including all branded packaging and documents provided with it.',
  "returnPolicyContain10":
      "Please take care when trying on your purchases and return them in the same condition you received them. Any returns that do not meet our policy will not be accepted.\n",
  "returnPolicyContain11":
      "If you placed an order as a guest, you can start your return here. To return or cancel an item that has been made to your specifications, please view our ‘ Customised Items’ section below for further information.",
  "details": "Details",
  "menText": "Men",
  "womenText": "Women",
  "kidsText": "Kids",
  "description": "More Information",
  "estimatedDelivery": "Estimated Delivery",
  "guaranteedDelivery": "Guaranteed Delivery : Nov 04 - Nov 11",
  "sizeChart": "Size Chart",
  "size": "Size",
  "addTOCart": "Add To Cart",
  "addToWishlist": "Add To Wishlist",
  "sizeChartText": "Size Chart",
  "whyVeraLusso": "WHY VERALUSSO",
  "knowMore": "Know More",
  "recommendation": "Recommendation",
  "recentlyViewed": "Recently Viewed",
  "aboutUsText": "About us",
  "newsLettersContain": "You Aren't Subscribed To\nOur Newsletter.",
  "edit": "EDIT",
  "newsLetters": "Newsletter",
  "manageAddresses": "Manage Addresses",
  "defaultBillingAddress": "Default Billing Address",
  "editAddress": "Edit Address",
  "defaultShippingAddress": "Default Shipping Address",
  "aboutUsTitle":
      "AVOIRCHIC IS A TOP ONLINE LUXURY FASHION DESTINATION WITH 5 MILLION VISITORS PER MONTH AND WORLDWIDE SHIPPING.",
  "aboutUsContain":
      '''The website features the best selection of the top established designers as well as young emerging talents. Brandslabels was founded in Florence in the early 1930s, with the opening of the company’s eponymous concept store on Via Roma. Online since 1999, the company attributes 90% of total revenue to online sales. To this day it remains a 100% privately owned family business, with the founder’s grandson, Andrea Panconesi acting as CEO and his daughter, Annagreta Panconesi as Creative Director.''',
  "aboutUsContain1":
      'The site offers a wide selection of clothing, shoes, bags, accessories, luxury home interiors and beauty, with products available for men, women and kids from the most prestigious designers such as Balenciaga, Vetements, Off-White, J.W. Anderson,Balmain, Dolce & Gabbana, Gucci, Saint Laurent, Valentino, Givenchy, Loewe, Jacquemus and more.',
  "aboutUsContain2":
      'There are currently 200 people from 15 different countries that work to produce and maintain Brandslabels. The site is available in 9 languages: English, Italian, German, Chinese, Russian, Spanish, French, Korean and Japanese. The site is created entirely in-house, with the Florence office housing graphic design, IT, customer service, marketing and buying departments. The stylists and press teams operate from the Brandslabels office in the fashion capital of the world – Milan.',
  "aboutUsContain3":
      'All orders are shipped worldwide from the Brandslabels headquarters in boxes that are prepared with maximum care and use the finest materials, from the signature shoe bags to the personalized ribbon.',
  "aboutUsContain4":
      'Brandslabels had 1.5 million unique visitors access the site in 2008 and has grown to 53 million unique visitors in 2017. More than 15% of online sales are generated from the United States, followed by Germany, UK, Italy, China and France.',
  "aboutUsContain5":
      'Brandslabels pushes the boundaries of the luxury retail landscape both on and offline with an array of exclusive services and trademark initiatives including Buy It First, Luxury Club,Sneakers Club, LVR Privilege and LVR Editions.',
  "profile": "Profile",
  "firstNameText": "First Name",
  "lastNameText": "Last Name",
  "emailText": "E-mail",
  "ContactNoText": "Contact no.",
  "websiteUrlText": "Website URL",
  "cityText": "City",
  "countryText": "Country",
  "postCodeText": "Post Code",
  "socialLinksText": "Social links",
  "facebookText": "Facebook",
  "instagramText": "Instagram",
  "twitterText": "Twitter",
  "youtubeText": "Youtube",
  "linkendinText": "Linkendin",
  "pinterestText": "Pinterest",
  "followersText": "Followers",
  "mr": "Mr.",
  "letsText": "Let’s Go",
  "referFriendText": "Refer Friend",
  "workedOnText": "Projects worked on",
  "returnsRefundsText": "Returns & Refunds",
  "faqText": "FAQ",
  "contactText": "Contact",
  "socialText": "Social",
  "companyText": "Company",
  "contactUs": "Contact Us",
  "myOrders": "My Orders",
  "myOrderImage": "Image",
  "productName": "Product Name",
  "sku": "SKU",
  "price": "Price",
  "quantity": "Qty",
  "status": "Status",
  "action": "Action",
  "paymentMethod": "Payment Method",
  "shippingAddress": "Shipping Address",
  "shippingText": "Shipping",
  "billingAddress": "Billing Address",
  "billingTxet": "Billing",
  "shipHereText": "Ship Here",
  "saveInAddressBookText": "Save in address book",
  "continueShopping": "Continue Shopping",
  "contactInfo": "Contact Information",
  "accountInfo": "Account Information",
  "changePassword": "Change Password",
  "newsletters": "Newsletters",
  "myAccountContain": "You aren't subscribed to\nour newsletter.",
  "addressBook": "Address Book",
  "billing": "Billing",
  "shipping": "Shipping",
  "freuentlyAskedQueText": "Frequently Asked Questions",
  "shopAndPlaceOrder": "How to shop & place an order?",
  "accountToPlaceOrderQues": "Do I need an account to place an order?",
  "accountToPlaceOrderAns":
      "No, all you need is an email address. We recommend that you register for an account to start adding pieces to your Wishlist, but, you can also place and track orders as a guest and signup at a time that suits you.",
  "createNewCustomerAccountText": "Create New Customer Account",
  "emailAddressText": "Email Address",
  "confirmEmailAddressText": "Confirm Email Address",
  "passwordText": "Password",
  "confirmPasswordText": "Confirm Password",
  "dateOfBirthText": "Date of Birth",
  "marriageAnniversaryText": "Marriage Anniversary",
  "signUpForNewsLetterText": "Sign Up For Newsletter",
  "registerWithFacebookText": "Register With Facebook",
  "createAnAccountText": "Create an Account",
  "customerLoginText": "Customer Login",
  "signInText": "Sign in",
  "forgotYourPasswordText": "Forgot Your Password?",
  "loginWithFacebookText": "Login With Facebook",
  "newCustomersText": "New Customers",
  "newCustomersDescriptionText":
      "Creating an account has many benefits:\ncheck out faster, keep more than one address,\ntrack orders and more.",
  "affiliateProgramTitleText": "AVOIR CHIC AFFILIATE PROGRAM",
  "whoAreWeLookingTitleText": "Who are we looking for?",
  "whoAreWeLookingDescriptionOneText":
      "Do you have a fashion-forward, luxury oriented website, blog, social media profile that is trend savvy with an international outlook? Is your focus fashion, lifestyle, beauty and design? If so, we are looking for you!\n\nJoin our global Affiliate Program and you will have the opportunity to earn a commission every time your visitors purchase from AVOIR CHIC.",
  "whatCanYouExpectTitleText": "What can you expect?",
  "expectRuleOneText": "Commission on all approved net sales",
  "expectRuleTwoText": "45 days cookie window",
  "expectRuleThreeText": "Data feed updated multiple times per day",
  "expectRuleFourText":
      "Access to customized banners, textlinks, deeplinks and our datafeed in 9 languages (English, Italian, French, German, Korean, Spanish, Chinese,Russian & Japanese)",
  "expectRuleFiveText":
      "The possibility to customize feeds into all world currencies",
  "promoteSoloQuestionText":
      "How can you promote AVOIR CHIC (as an affiliate)?",
  "promoteSoloAnswerOneText":
      "Creating high-quality and engaging content that mirrors the style of AVOIR CHIC",
  "promoteSoloAnswerTwoText":
      "Featuring our content, banners and links for multiple categories and events on your website and social media channels",
  "promoteSoloAnswerThreeText":
      "Promoting the benefits that our customers love",
  "promoteSoloAnswerFourText":
      "A selection of continuously updated articles from the best brands",
  "promoteSoloAnswerFiveText":
      "Free returns with no added taxes for the US, Canada, the UK and ",
  "howApplyTitleText": "How to apply?",
  "howApplyAnswerOneText":
      "Email us the name and URL of your website, blog or social media profile and your main markets. We’ll review your site and get back to you with further information on how to join the affiliate program.\n\nPlease note that all applications are manually evaluated and processing may take up to 10 days.\n\nIf you feel your application has been wrongfully declined please contact affiliates@avoirchic.com and a member of the team will address your concerns.",
  "visitorMonthHintText": "Select Unique Visitors/Month",
  "viewsMonthHintText": "Select Page Views/Month",
  "cityHintText": "City",
  "countryHintText": "Country",
  "addressOneText": "Street Address 1",
  "addressTwoText": "Street Address 2",
  "addressText": "Address",
  "letsGoText": "Let's Go",
  "contactNoText": "Contact no.",
  "homeText": "Home",
  "searchText": "Search",
  "designersText": "Designers",
  "wishListText": "WishList",
  "loginText": "Login",
  "myAccountText": "My Account",
  "subscribeText": "Subscreibe",
  "yourEmailText": "Your E-Mail",
  "checkoutText": "Checkout",
  "purchaseText": "Please Enter Your Details Below To Complete Your Purchase",
  "shippingAddressText": "Shipping Address",
  "shippingMethodText": "Shipping Method",
  "paymentMethodText": "Payment Method",
  "orderSummaryText": "Order Summary",
  "itemInCartText": "Item in Cart",
  "qtyText": "Qty",
  "createCheckoutText": "You can create an account after checkout.",
  "streetAddressText": "Street Address",
  "unitedKingdomText": "United Kingdom",
  "stateText": "State/Province",
  "zipCodeText": "Zip/Postal Code",
  "phoneNumberText": "Phone Number",
  "priceText": "Price",
  "titleText": "Title",
  "carrierTitleText": "Carrier Title",
  "viewDetailText": "View Details",
  "applyDiscountCodeText": "Apply Discount Code",
  "enterDiscountCodeText": "Enter Discount Code",
  "applyText": "APPLY",
  "cartSubTotalText": "Cart Subtotal",
  "orderCommentText": "Order Comment",
  "placeOrderText": "Place Order",
  "myOrdersText": "My Orders",
  "myWishlistText": "My Wish List",
  "addressBookText": "Address Book",
  "accountInformationText": "Account Information",
  "storePaymentText": "Stored Payment Methods",
  "newsLetterText": "NEWSLETTER SUBSCRIPTIONS",
  "selectLangCurrText": "Select Language & Currency",
  "promoCode": "Promo Code",
  "enterCode": "Enter Promo Code",
  "selectLangCurrDescText":
      "Please choose from the following Language and currency options available in your country Language",
  "saveText": "Save",
  "cancelText": "Cancel",
  "languageText": "Language",
  "currencyText": "Currency",
  "accessYourAccountDetailsText": "Access your account details and rewards",
  "signUpText": "Sign Up",
  "loginMyAccountText": "Login",
  "myOrderText": "My Orders",
  "myTicketsText": "My Tickets",
  "trackOrderText": "Track Order",
  "careersText": "Careers",
  "helpTheNeedyText": "Help The Needy",
  "secureShoppingText": "Secure Shopping",
  "influencerRegistrationText": "Influencer Registration",
  "affiliateText": "Affiliate Program",
  "advancedSearchText": "Advanced Search",
  "privacyPolicyText": "Privacy Policy",
  "termsConditionsText": "Terms & Conditions",
  "aboutText": "About",
  "aboutUsMyAccountText": "About Us",
  "referFriendMyAccountText": "Refer Friend",
  "returnsText": "Returns And Refunds",
  "contactUsText": "Contact Us",
  "faqMyAccountText": "Faq",
  "liveChatText": "Live Chat",
  "startChatText": "Start the chat",
  "accountText": "Account",
  "spreadTheWorldText": "Spread The World & Earn Discounts",
  "shippingReturnText": "Shipping Return",
  "improveLivesText": "Improve Lives",
  "welcometoChatText": "Welcome to our LiveChat!",
  "fillTheFormText": "Please fill in the form below before starting the chat.",
  "nameChatText": "Name",
  "deliveryText": "Delivery",
  "ordersText": "Order",
  "paymentText": "Payment",
  "productText": "Product",
  "promotionText": "Promotion",
  "returnsContactText": "Returns",
  "technicalText": "Technical",
  "typeOfEnquiryText": "Type Of Enquiry",
  "surNameText": "Surname",
  "confirmEmailText": "Confirm Email",
  "subjectText": "Subject",
  "whatsonyourmindText": "What's On Your Mind?",
  "submitText": "Submit",
  "filtersText": "Filters",
  "colorText": "Color",
  "brandText": "Brand",
  "sizeText": "Size",
  "applyFilterText": "Apply",
  "policyHomeText": "Home",
  "policyText": "Privacy Policy",
  "policyHeadingText": "AvoirChic Group Privacy Policy",
  "specialSizeCompanyText": "Company",
  "specialSizeContactText": "Contact",
  "specialSizeOtherText": "Other",
  "specialSizeSubscribeToNewsletterText": "SUBSCRIBE TO OUR NEWSLETTER",
  "specialSizeEmailAddressText": "Email Address",
  "specialSizeSubscribeText": "SUBSCRIBE",
  "specialSizeRequestsText": "Special Size Requests",
  "specialSizeEnterEmailText": "Enter Email",
  "specialSizeSelectSizeText": "Select Size",
  "specialSizeSubmitText": "Submit",
  "forgetPassword": "Forgot Your Password?",
  "backToSignInScreen": "Back to sign in screen",
  "forgetPasswordContain":
      "We Have Sent You A Password Reset Link\n This Link Is Valid For 2 Hours \n If You Did Not Make This Request\n You Can Ignore This Email \n Please Check Your Spam Folder\n If You Do Not Receive The Email \n For Any Assistance Please",
  "enterYourEmailText": "Enter your email",
  "idText": "ID",
  "actionText": "Action",
  "subscribeToOurText": "Subscribe to our Newsletter",
  "OtherText": "Other",
  "youaddCartText": "You have added",
  "youaddCartEndText": "to your shopping cart.",
  "viewCartText": "Go To The Cart",
  "continueShoppingText": "Continue Shopping",
  "checkYourOrderText": "Check your order",
  "shoppingCartText": "Shopping Crat",
  "subTotalText": "Subtotal",
  "updateCartText": "Update Cart",
  "enterDiscountText": "Enter Discount Code",
  "supportCharityText": "SUPPORT A CHARITY WITH YOUR DONATION",
  "charityDescriptionText":
      "15% of The Order Value Will Be Donated By Avoirchic For Donations.",
  "donateNowText": "PLEASE CLICK HERE TO DONATE NOW",
  "cartSummaryText": "Cart Summary",
  "subtotalSpaceText": "Sub Total",
  "taxText": "Tax",
  "orderTotalText": "Order Total",
  "processCheckOutText": "Process Checkout",
  "multipleAddressCheckoutText": "CHECK OUT WITH MULTIPLE ADDRESSES",
  "saveAddressText": "Save Address",
  "viewWishListText": "View WishList",
  "logOutText": "Log Out",
  "findBrandsText": "Find Brands",
  "reasonReturnText": "Reason to return",
  "returnItemText": "Return ltem",
  "returnText": "Return",
  "returnRequestText": "Return Request Received",
  "teamSoloLuxuryText": "Team Solo Luxury.",
  "wehaveRecivedText":
      "We have received your request and your request Id is - Please Check the status of your request at @@@@. contact us at care@sololuxury.com - for any query with regards to request.",
  "newAddressText": "New Address",
  "myBillingShipAddressSameText":
      "My Billing and Shipping Address are the same",
  "testDonationText": "Test Donation",
  "youAddedTestText":
      "You Added Test Donation Your Shopping Cart.\nThe Page Will Be Refreshed.",
  "chooseYourOwmText": "Choose Your Own Amount GBP(minimum €1)",
  "theSelectedAmountText":
      "The Selected Amount Will Be Added To Your\nShopping Cart.",
  "iwantToDonateText": "I Want To Donate This Amount",
  "e5Text": "€ 5",
  "e10Text": "€ 10",
  "e15Text": "€ 15",
  "e20Text": "€ 20",
  "e25Text": "€ 25",
  "gbpText": "GBP",
  "cartContain1": "Support a Charity With Your Donation",
  "cartContain2":
      "15% Of The Order Value Will Be Donated By\nAvoirchic For Donations.",
  "cartContain3": "Please click here to donate now.",
  "cartContain4": "I WANT TO DONATE",
  "cartContain5": "Check Out with Multiple Addresses",
  "myCouponsText": "My Coupons",
  "creating": "Creating",
  "searchCountry": "Search country",
  "storeCreditText": "My Store Credit",
  "expectedDate": 'Expected Shipment Date',
  "orderDate": 'Order Date',
  "accountDoesNotExist": "Account Does Not Exist",
  "forgotPasswordWrongEmailStart": "There is no Account Associated",
  "forgotPasswordWrongEmailEnd": "you need any further assistance please",
  "WriteAt": "Write To Us At",
  "reasonCancelText": "Reason To Cancel",
  "cancelItemText": "Cancel Item",
  "trackYourTicketByEmail": "Track Your Ticket By Email",
  "trackYourRequests": "Track Your Requests",
  "with": "With",
  "pleaseCheckYourInbox": "Please Check Your Inbox",
  "track_your_order": "Track Your Order",
  "thankYou": "Thank You",
  "notifyMeWhenThisProductIsInStock":
      "We Will Inform You Once The Product Is In Stock. You Can Also View The Status Of Your Request On",
  "myTicket": "My Tickets."
};
