const Map<String, String> es = {
  "language": "inglés",
  "appNameText": "Solo de lujo",
  "aboutUsText": "Sobre nosotros",
  "referFriendText": "Recomendar amigo",
  "returnsRefundsText": "Devoluciones y reembolsos",
  "faqText": "Preguntas más frecuentes",
  "contactText": "Contacto",
  "socialText": "Social",
  "companyText": "Compañía",
  "freuentlyAskedQueText": "Preguntas frecuentes",
  "shopAndPlaceOrder": "¿Cómo comprar y hacer un pedido?",
  "accountToPlaceOrderQues": "¿Necesito una cuenta para hacer un pedido?",
  "accountToPlaceOrderAns":
      "No, todo lo que necesita es una dirección de correo electrónico. Le recomendamos que se registre para obtener una cuenta para comenzar a agregar piezas a su Lista de deseos, pero también puede realizar y realizar un seguimiento de los pedidos como invitado y registrarse en el momento que más le convenga.",
  "createNewCustomerAccountText": "CREAR NUEVA CUENTA DE CLIENTE",
  "emailAddressText": "Dirección de correo electrónico",
  "confirmEmailAddressText": "Confirmar el correo",
  "passwordText": "Clave",
  "confirmPasswordText": "Confirmar contraseña",
  "firstNameText": "Primer nombre",
  "lastNameText": "Apellido",
  "dateOfBirthText": "Fecha de nacimiento",
  "marriageAnniversaryText": "Aniversario de boda",
  "signUpForNewsLetterText": "Regístrese para recibir el boletín",
  "registerWithFacebookText": "Regístrese con Facebook",
  "createAnAccountText": "CREA UNA CUENTA",
  "customerLoginText": "Inicio de sesión del cliente",
  "signInText": "Registrarse",
  "forgotYourPasswordText": "¿Olvidaste tu contraseña?",
  "loginWithFacebookText": "Iniciar sesión con Facebook",
  "newCustomersText": "nuevos clientes",
  "newCustomersDescriptionText":
      "Crear una cuenta tiene muchos beneficios:\npague más rápido, mantenga más de una dirección,\nseguimiento de pedidos y más.",
  "homeText": "Casa",
  "searchText": "Búsqueda",
  "designersText": "Diseñadores",
  "wishListText": "lista de deseos",
  "loginText": "Acceso",
  "myAccountText": "Mi cuenta",
  "subscribeText": "SUSCRIBIR",
  "yourEmailText": "Tu correo electrónico",
  "checkoutText": "Verificar",
  "purchaseText": "Ingrese sus datos a continuación para completar su compra",
  "shippingAddressText": "Dirección de envío",
  "shippingMethodText": "Método de envío",
  "paymentMethodText": "Método de pago",
  "orderSummaryText": "Resumen del pedido",
  "itemInCartText": "Artículo en el carrito",
  "qtyText": "Cantidad",
  "emailText": "Correo electrónico",
  "createCheckoutText":
      "Puede crear una cuenta después de finalizar la compra.",
  "streetAddressText": "Dirección",
  "cityText": "Ciudad",
  "unitedKingdomText": "Reino Unido",
  "stateText": "Provincia del estado",
  "zipCodeText": "Código postal",
  "phoneNumberText": "Número de teléfono",
  "priceText": "Precio",
  "titleText": "Título",
  "carrierTitleText": "Título del transportista",
  "viewDetailText": "Ver detalles",
  "applyDiscountCodeText": "Aplicar código de descuento",
  "enterDiscountCodeText": "INTRODUZCA EL CÓDIGO DE DESCUENTO",
  "applyText": "APLICAR",
  "cartSubTotalText": "Subtotal del carrito",
  "orderCommentText": "Comentario del pedido",
  "placeOrderText": "REALIZAR PEDIDO",
  "myOrdersText": "MIS ORDENES",
  "myWishlistText": "Mi lista de deseos",
  "addressBookText": "Directorio",
  "accountInformationText": "Información de la cuenta",
  "storePaymentText": "MÉTODOS DE PAGO ALMACENADOS",
  "newsLetterText": "SUSCRIPCIONES A LOS BOLETINES",
};
