const Map<String, String> fr = {
  "language": "Anglais",
  "appNameText": "Luxe en solitaire",
  "aboutUsText": "À propos de nous",
  "referFriendText": "Référez un ami",
  "returnsRefundsText": "Retours et remboursements",
  "faqText": "FAQ",
  "contactText": "Contact",
  "socialText": "Social",
  "companyText": "Compagnie",
  "freuentlyAskedQueText": "Questions fréquemment posées",
  "shopAndPlaceOrder": "Comment magasiner et passer une commande?",
  "accountToPlaceOrderQues":
      "Ai-je besoin d'un compte pour passer une commande?",
  "accountToPlaceOrderAns":
      "Non, tout ce dont vous avez besoin est une adresse e-mail. Nous vous recommandons de créer un compte pour commencer à ajouter des pièces à votre liste de souhaits, mais vous pouvez également passer et suivre des commandes en tant qu'invité et vous inscrire au moment qui vous convient.",
  "createNewCustomerAccountText": "CRÉER UN NOUVEAU COMPTE CLIENT",
  "emailAddressText": "Adresse e-mail",
  "confirmEmailAddressText": "Confirmez votre adresse email",
  "passwordText": "Mot de passe",
  "confirmPasswordText": "Confirmez le mot de passe",
  "firstNameText": "Prénom",
  "lastNameText": "Nom de famille",
  "dateOfBirthText": "Date de naissance",
  "marriageAnniversaryText": "Anniversaire de mariage",
  "signUpForNewsLetterText": "S'inscrire aux Newsletters",
  "registerWithFacebookText": "Inscrivez-vous avec Facebook",
  "createAnAccountText": "CRÉER UN COMPTE",
  "customerLoginText": "Connexion client",
  "signInText": "S'identifier",
  "forgotYourPasswordText": "Mot de passe oublié?",
  "loginWithFacebookText": "Se connecter avec Facebook",
  "newCustomersText": "nouveaux clients",
  "newCustomersDescriptionText":
      "La création d'un compte présente de nombreux avantages :\npaiement plus rapide, conservation de plusieurs adresses,\nsuivi des commandes, etc.",
  "homeText": "Maison",
  "searchText": "Rechercher",
  "designersText": "Créateurs",
  "wishListText": "Liste de souhaits",
  "loginText": "Connexion",
  "myAccountText": "Mon compte",
  "subscribeText": "S'ABONNER",
  "yourEmailText": "Votre e-mail",
  "checkoutText": "Vérifier",
  "purchaseText":
      "Veuillez entrer vos coordonnées ci-dessous pour finaliser votre achat",
  "shippingAddressText": "Adresse de livraison",
  "shippingMethodText": "Mode de livraison",
  "paymentMethodText": "Mode de paiement",
  "orderSummaryText": "Récapitulatif de la commande",
  "itemInCartText": "Article dans le panier",
  "qtyText": "Qté",
  "emailText": "E-mail",
  "createCheckoutText": "Vous pouvez créer un compte après le paiement.",
  "streetAddressText": "Adresse de la rue",
  "cityText": "Ville",
  "unitedKingdomText": "Royaume-Uni",
  "stateText": "État/Province",
  "zipCodeText": "Zip / code postal",
  "phoneNumberText": "Numéro de téléphone",
  "priceText": "Prix",
  "titleText": "Titre",
  "carrierTitleText": "Titre du transporteur",
  "viewDetailText": "Voir les détails",
  "applyDiscountCodeText": "Appliquer le code de réduction",
  "enterDiscountCodeText": "ENTRER LE CODE DE RÉDUCTION",
  "applyText": "APPLIQUER",
  "cartSubTotalText": "Sous-total du panier",
  "orderCommentText": "Commentaire de la commande",
  "placeOrderText": "PASSER LA COMMANDE",
  "myOrdersText": "MES COMMANDES",
  "myWishlistText": "Ma liste d'envies",
  "addressBookText": "Carnet d'adresses",
  "accountInformationText": "Information sur le compte",
  "storePaymentText": "MÉTHODES DE PAIEMENT MÉMORISÉES",
  "newsLetterText": "ABONNEMENT À LA NEWSLETTER",
};
