const Map<String, String> it = {
  "language": "inglese",
  "appNameText": "Lusso da solista",
  "aboutUsText": "Chi siamo",
  "referFriendText": "Segnala amico",
  "returnsRefundsText": "Resi e rimborsi",
  "faqText": "FAQ",
  "contactText": "Contatto",
  "socialText": "Sociale",
  "companyText": "Azienda",
  "freuentlyAskedQueText": "Domande frequenti",
  "shopAndPlaceOrder": "Come acquistare e effettuare un ordine?",
  "accountToPlaceOrderQues":
      "Ho bisogno di un account per effettuare un ordine?",
  "accountToPlaceOrderAns":
      "No, tutto ciò che serve è un indirizzo email. Ti consigliamo di registrare un account per iniziare ad aggiungere pezzi alla tua lista dei desideri, ma puoi anche effettuare e monitorare gli ordini come ospite e iscriverti all'orario che preferisci.",
  "createNewCustomerAccountText": "CREA UN NUOVO ACCOUNT CLIENTE",
  "emailAddressText": "Indirizzo e-mail",
  "confirmEmailAddressText": "Conferma l'indirizzo e-mail",
  "passwordText": "Parola d'ordine",
  "confirmPasswordText": "Conferma password",
  "firstNameText": "Nome di battesimo",
  "lastNameText": "Cognome",
  "dateOfBirthText": "Data di nascita",
  "marriageAnniversaryText": "Anniversario di matrimonio",
  "signUpForNewsLetterText": "Iscriviti alla Newsletter",
  "registerWithFacebookText": "Registrati con Facebook",
  "createAnAccountText": "CREARE UN ACCOUNT",
  "customerLoginText": "accesso cliente",
  "signInText": "Registrazione",
  "forgotYourPasswordText": "Hai dimenticato la password?",
  "loginWithFacebookText": "Fai il login con facebook",
  "newCustomersText": "nuovi clienti",
  "newCustomersDescriptionText":
      "La creazione di un account ha molti vantaggi:\ncontrolla più velocemente, mantieni più di un indirizzo,\ntieni traccia degli ordini e altro ancora.",
  "homeText": "Casa",
  "searchText": "Ricerca",
  "designersText": "Designer",
  "wishListText": "Lista dei desideri",
  "loginText": "Login",
  "myAccountText": "Il mio conto",
  "subscribeText": "SOTTOSCRIVI",
  "yourEmailText": "La tua email",
  "checkoutText": "Guardare",
  "purchaseText":
      "Inserisci i tuoi dettagli qui sotto per completare l'acquisto",
  "shippingAddressText": "indirizzo di spedizione",
  "shippingMethodText": "metodo di spedizione",
  "paymentMethodText": "Metodo di pagamento",
  "orderSummaryText": "Riepilogo ordine",
  "itemInCartText": "Articolo nel carrello",
  "qtyText": "Qtà",
  "emailText": "E-mail",
  "createCheckoutText": "Puoi creare un account dopo il checkout.",
  "streetAddressText": "Indirizzo",
  "cityText": "Città",
  "unitedKingdomText": "Regno Unito",
  "stateText": "Stato/Provincia",
  "zipCodeText": "Zip / Codice postale",
  "phoneNumberText": "Numero di telefono",
  "priceText": "Prezzo",
  "titleText": "Titolo",
  "carrierTitleText": "Titolo del vettore",
  "viewDetailText": "Visualizza dettagli",
  "applyDiscountCodeText": "Applicare il codice sconto",
  "enterDiscountCodeText": "INSERIRE IL CODICE SCONTO",
  "applyText": "APPLICARE",
  "cartSubTotalText": "Subtotale del carrello",
  "orderCommentText": "Commento dell'ordine",
  "placeOrderText": "INVIA ORDINE",
  "myOrdersText": "I MIEI ORDINI",
  "myWishlistText": "La mia lista dei desideri",
  "addressBookText": "Rubrica",
  "accountInformationText": "Informazioni account",
  "storePaymentText": "METODI DI PAGAMENTO MEMORIZZATI",
  "newsLetterText": "ABBONAMENTI ALLA NEWSLETTER",
};
