const Map<String, String> ko = {
  "language": "영어",
  "appNameText": "솔로 럭셔리",
  "aboutUsText": "회사 소개",
  "referFriendText": "친구 추천",
  "returnsRefundsText": "반품 및 환불",
  "faqText": "자주하는 질문",
  "contactText": "연락하다",
  "socialText": "사회의",
  "companyText": "회사",
  "freuentlyAskedQueText": "자주 묻는 질문",
  "shopAndPlaceOrder": "쇼핑 및 주문은 어떻게 하나요?",
  "accountToPlaceOrderQues": "주문하려면 계정이 필요합니까?",
  "accountToPlaceOrderAns":
      "아니요, 이메일 주소만 있으면 됩니다. 위시리스트에 제품을 추가하려면 계정에 등록하는 것이 좋지만, 원하는 시간에 게스트로 주문하고 등록할 수도 있습니다.",
  "createNewCustomerAccountText": "새 고객 계정 만들기",
  "emailAddressText": "이메일 주소",
  "confirmEmailAddressText": "이메일 주소 확인",
  "passwordText": "비밀번호",
  "confirmPasswordText": "비밀번호 확인",
  "firstNameText": "이름",
  "lastNameText": "성",
  "dateOfBirthText": "생일",
  "marriageAnniversaryText": "결혼 기념일",
  "signUpForNewsLetterText": "뉴스레터 신청",
  "registerWithFacebookText": "페이스북에 등록",
  "createAnAccountText": "계정 만들기",
  "customerLoginText": "고객 로그인",
  "signInText": "로그인",
  "forgotYourPasswordText": "비밀번호를 잊어 버렸습니까?",
  "loginWithFacebookText": "페이스북으로 로그인",
  "newCustomersText": "신규 고객",
  "newCustomersDescriptionText":
      "계정을 만들면\n더 빠르게 체크아웃하고, 두 개 이상의 주소를 유지하고,\n주문을 추적하는 등 많은 이점이 있습니다.",
  "homeText": "집",
  "searchText": "검색",
  "designersText": "디자이너",
  "wishListText": "위시리스트",
  "loginText": "로그인",
  "myAccountText": "내 계정",
  "subscribeText": "구독하다",
  "yourEmailText": "귀하의 이메일",
  "checkoutText": "점검",
  "purchaseText": "구매를 완료하려면 아래에 세부 정보를 입력하십시오",
  "shippingAddressText": "배송 주소",
  "shippingMethodText": "배송 방법",
  "paymentMethodText": "지불 방법",
  "orderSummaryText": "주문 요약",
  "itemInCartText": "장바구니에 담긴 상품",
  "qtyText": "수량",
  "emailText": "이메일",
  "createCheckoutText": "결제 후 계정을 생성할 수 있습니다.",
  "streetAddressText": "주소",
  "cityText": "도시",
  "unitedKingdomText": "영국",
  "stateText": "시/도",
  "zipCodeText": "우편번호",
  "phoneNumberText": "전화 번호",
  "priceText": "가격",
  "titleText": "제목",
  "carrierTitleText": "운송업체 제목",
  "viewDetailText": "세부 정보보기",
  "applyDiscountCodeText": "할인 코드 적용",
  "enterDiscountCodeText": "할인 코드 입력",
  "applyText": "적용하다",
  "cartSubTotalText": "장바구니 소계",
  "orderCommentText": "주문 코멘트",
  "placeOrderText": "주문하기",
  "myOrdersText": "내 주문",
  "myWishlistText": "내 위시리스트",
  "addressBookText": "주소록",
  "accountInformationText": "계정 정보",
  "storePaymentText": "저장된 결제 방법",
  "newsLetterText": "뉴스레터 구독",
};
