const Map<String, String> nl = {
  "language": "Engels",
  "appNameText": "Individuele luxe",
  "aboutUsText": "Over ons",
  "referFriendText": "Verwijs vriend",
  "returnsRefundsText": "Retourneren & Terugbetalingen",
  "faqText": "FAQ",
  "contactText": "Contact",
  "socialText": "sociaal",
  "companyText": "Bedrijf",
  "freuentlyAskedQueText": "Veel Gestelde Vragen",
  "shopAndPlaceOrder": "Hoe winkelen en een bestelling plaatsen?",
  "accountToPlaceOrderQues":
      "Heb ik een account nodig om een ​​bestelling te plaatsen?",
  "accountToPlaceOrderAns":
      "Nee, je hebt alleen een e-mailadres nodig. We raden je aan om je te registreren voor een account om stukken aan je verlanglijstje toe te voegen, maar je kunt ook als gast bestellingen plaatsen en volgen en je aanmelden op een tijdstip dat jou uitkomt.",
  "createNewCustomerAccountText": "MAAK EEN NIEUWE KLANTENACCOUNT",
  "emailAddressText": "E-mailadres",
  "confirmEmailAddressText": "Bevestig dit Email adres",
  "passwordText": "Wachtwoord",
  "confirmPasswordText": "bevestig wachtwoord",
  "firstNameText": "Voornaam",
  "lastNameText": "Achternaam",
  "dateOfBirthText": "Geboortedatum",
  "marriageAnniversaryText": "Trouwdag",
  "signUpForNewsLetterText": "Aanmelden voor Nieuwsbrief",
  "registerWithFacebookText": "Registreer met Facebook",
  "createAnAccountText": "ACCOUNT AANMAKEN",
  "customerLoginText": "Klant login",
  "signInText": "Aanmelden",
  "forgotYourPasswordText": "Uw wachtwoord vergeten?",
  "loginWithFacebookText": "Inloggen met Facebook",
  "newCustomersText": "nieuwe klanten",
  "newCustomersDescriptionText":
      "Het aanmaken van een account heeft veel voordelen:\nsnel uitchecken, meer dan één adres bewaren,\nbestellingen volgen en meer.",
  "homeText": "Thuis",
  "searchText": "Zoekopdracht",
  "designersText": "Ontwerpers",
  "wishListText": "Verlanglijst",
  "loginText": "Log in",
  "myAccountText": "Mijn rekening",
  "subscribeText": "ABONNEREN",
  "yourEmailText": "Jouw email",
  "checkoutText": "Uitchecken",
  "purchaseText": "Voer hieronder uw gegevens in om uw aankoop te voltooien:",
  "shippingAddressText": "Verzendingsadres",
  "shippingMethodText": "Verzendmethode:",
  "paymentMethodText": "Betalingswijze",
  "orderSummaryText": "overzicht van de bestelling",
  "itemInCartText": "Artikel in winkelwagen",
  "qtyText": "aantal",
  "emailText": "E-mail",
  "createCheckoutText": "Na het afrekenen kun je een account aanmaken.",
  "streetAddressText": "Adres",
  "cityText": "Stad",
  "unitedKingdomText": "Verenigd Koninkrijk",
  "stateText": "Staat/Provincie",
  "zipCodeText": "Postcode/postcode",
  "phoneNumberText": "Telefoonnummer",
  "priceText": "Prijs",
  "titleText": "Titel",
  "carrierTitleText": "Titel van vervoerder",
  "viewDetailText": "Details bekijken",
  "applyDiscountCodeText": "Kortingscode toepassen",
  "enterDiscountCodeText": "VOER KORTINGSCODE IN",
  "applyText": "VAN TOEPASSING ZIJN",
  "cartSubTotalText": "Subtotaal winkelwagen",
  "orderCommentText": "Bestelling Opmerking",
  "placeOrderText": "PLAATS BESTELLING",
  "myOrdersText": "MIJN BESTELLINGEN",
  "myWishlistText": "Mijn wenslijst",
  "addressBookText": "Adresboek",
  "accountInformationText": "Account Informatie",
  "storePaymentText": "OPGESLAGEN BETAALMETHODEN",
  "newsLetterText": "NIEUWSBRIEF ABONNEMENTEN",
};
