const Map<String, String> ru = {
  "language": "английский",
  "appNameText": "соло роскошь",
  "aboutUsText": "О нас",
  "referFriendText": "Пригласить друга",
  "returnsRefundsText": "Возвраты и возмещения",
  "faqText": "Вопросы-Ответы",
  "contactText": "Контакт",
  "socialText": "Социальное",
  "companyText": "Компания",
  "freuentlyAskedQueText": "Часто задаваемые вопросы",
  "shopAndPlaceOrder": "Как купить и сделать заказ?",
  "accountToPlaceOrderQues":
      "Нужна ли мне учетная запись для размещения заказа?",
  "accountToPlaceOrderAns":
      "Нет, все, что вам нужно, это адрес электронной почты. Мы рекомендуем вам зарегистрировать учетную запись, чтобы начать добавлять товары в свой список желаний, но вы также можете размещать и отслеживать заказы в качестве гостя и регистрироваться в удобное для вас время.",
  "createNewCustomerAccountText": "СОЗДАТЬ НОВЫЙ КЛИЕНТСКИЙ СЧЕТ",
  "emailAddressText": "Адрес электронной почты",
  "confirmEmailAddressText": "Подтвердите адрес электронной почты",
  "passwordText": "Пароль",
  "confirmPasswordText": "Подтвердить Пароль",
  "firstNameText": "Имя",
  "lastNameText": "Фамилия",
  "dateOfBirthText": "Дата рождения",
  "marriageAnniversaryText": "Годовщина свадьбы",
  "signUpForNewsLetterText": "Подписаться на рассылку",
  "registerWithFacebookText": "Зарегистрируйтесь через Facebook",
  "createAnAccountText": "ЗАВЕСТИ АККАУНТ",
  "customerLoginText": "Вход для клиентов",
  "signInText": "Войти",
  "forgotYourPasswordText": "Забыли Ваш пароль?",
  "loginWithFacebookText": "Войти с Facebook",
  "newCustomersText": "новые клиенты",
  "newCustomersDescriptionText":
      "Создание учетной записи имеет много преимуществ:\nбыстрее оформить заказ, сохранить несколько адресов,\nотслеживать заказы и многое другое.",
  "homeText": "Дома",
  "searchText": "Поиск",
  "designersText": "Дизайнеры",
  "wishListText": "Список желаний",
  "loginText": "Авторизоваться",
  "myAccountText": "Мой счет",
  "subscribeText": "ПОДПИСЫВАТЬСЯ",
  "yourEmailText": "Ваш адрес электронной почты",
  "checkoutText": "Проверить",
  "purchaseText":
      "Пожалуйста, введите свои данные ниже, чтобы завершить покупку",
  "shippingAddressText": "адреса доставки",
  "shippingMethodText": "способ доставки",
  "paymentMethodText": "Способ оплаты",
  "orderSummaryText": "итог заказа",
  "itemInCartText": "Товар в корзине",
  "qtyText": "Кол-во",
  "emailText": "Эл. адрес",
  "createCheckoutText":
      "Вы можете создать учетную запись после оформления заказа.",
  "streetAddressText": "Адрес улицы",
  "cityText": "Город",
  "unitedKingdomText": "Соединенное Королевство",
  "stateText": "Штат/провинция",
  "zipCodeText": "Почтовый индекс",
  "phoneNumberText": "Телефонный номер",
  "priceText": "Цена",
  "titleText": "Заголовок",
  "carrierTitleText": "Название перевозчика",
  "viewDetailText": "Посмотреть детали",
  "applyDiscountCodeText": "Применить код скидки",
  "enterDiscountCodeText": "ВВЕДИТЕ КОД СКИДКИ",
  "applyText": "ПРИМЕНЯТЬ",
  "cartSubTotalText": "Корзина",
  "orderCommentText": "Комментарий к заказу",
  "placeOrderText": "РАЗМЕСТИТЬ ЗАКАЗ",
  "myOrdersText": "МОИ ЗАКАЗЫ",
  "myWishlistText": "Мой список пожеланий",
  "addressBookText": "Адресная книга",
  "accountInformationText": "Информация об аккаунте",
  "storePaymentText": "СОХРАНЕННЫЕ СПОСОБЫ ОПЛАТЫ",
  "newsLetterText": "ПОДПИСКА НА РАССЫЛКУ",
};
