const Map<String, String> ar = {
  "language": "إنجليزي",
  "appNameText": "Suv n Nat",
  "aboutUsText": "معلومات عنا",
  "aboutUsTitle":
      "SUV & NAT هي أفضل وجهة للأزياء الفاخرة عبر الإنترنت مع 5 ملايين زائر شهريًا والشحن في جميع أنحاء العالم.",
  "aboutUsContain":
      'يتميز الموقع بأفضل اختيار لأفضل المصممين الراسخين بالإضافة إلى المواهب الناشئة الشابة. تأسست شركة Brandslabels في فلورنسا في أوائل الثلاثينيات من القرن الماضي ، مع افتتاح متجر مفهوم باسم الشركة في شارع Via Roma. عبر الإنترنت منذ عام 1999 ، تنسب الشركة 90٪ من إجمالي الإيرادات إلى المبيعات عبر الإنترنت. حتى يومنا هذا ، لا تزال شركة عائلية مملوكة للقطاع الخاص بنسبة 100٪ ، حيث يتولى حفيد المؤسس ، أندريا بانكونيسي ، منصب الرئيس التنفيذي وابنته ، أناغريتا بانكونيزي ، مديرة إبداعية.',
  "aboutUsContain1":
      'يقدم الموقع مجموعة واسعة من الملابس والأحذية والحقائب والإكسسوارات والديكورات المنزلية الفاخرة والجمال ، مع منتجات متاحة للرجال والنساء والأطفال من أشهر المصممين مثل Balenciaga و Vetements و Off-White و J.W. Anderson و Balmain و Dolce & Gabbana و Gucci و Saint Laurent و Valentino و Givenchy و Loewe و Jacquemus والمزيد.',
  "aboutUsContain2":
      'يوجد حاليًا 200 شخص من 15 دولة مختلفة يعملون على إنتاج العلامات التجارية وصيانتها. الموقع متاح بـ 9 لغات: الإنجليزية والإيطالية والألمانية والصينية والروسية والإسبانية والفرنسية والكورية واليابانية. تم إنشاء الموقع داخليًا بالكامل ، من خلال مكتب فلورنسا للتصميم الجرافيكي وتكنولوجيا المعلومات وخدمة العملاء والتسويق والشراء. يعمل المصممون والفرق الصحفية من مكتب Suvandnats في عاصمة الموضة في العالم - ميلان.',
  "aboutUsContain3":
      'يتم شحن جميع الطلبات في جميع أنحاء العالم من المقر الرئيسي لشركة Suvandnats في صناديق يتم إعدادها بأقصى قدر من العناية واستخدام أفضل المواد ، من أكياس الأحذية المميزة إلى الشريط المخصص.',
  "aboutUsContain4":
      'استقبل Suvandnats 1.5 مليون زائر فريد للموقع في عام 2008 ونما إلى 53 مليون زائر فريد في عام 2017. يتم إنشاء أكثر من 15 ٪ من المبيعات عبر الإنترنت من الولايات المتحدة ، تليها ألمانيا والمملكة المتحدة وإيطاليا والصين وفرنسا.',
  "aboutUsContain5":
      'تدفع Suvandnats حدود مشهد البيع بالتجزئة الفاخرة سواء عبر الإنترنت أو خارجها من خلال مجموعة من الخدمات الحصرية ومبادرات العلامات التجارية بما في ذلك Buy It First و Luxury Club و Sneakers Club و LVR Privilege و LVR Editions.',
  "profile": "حساب تعريفي",
  "firstNameText": "الاسم الأول",
  "lastNameText": "الكنية",
  "emailText": "بريد الالكتروني",
  "ContactNoText": "رقم الاتصال.",
  "websiteUrlText": "رابط الموقع",
  "cityText": "مدينة",
  "countryText": "دولة",
  "postCodeText": "الرمز البريدي",
  "socialLinksText": "روابط اجتماعية",
  "facebookText": "فيسبوك",
  "instagramText": "انستغرام",
  "twitterText": "تويتر",
  "youtubeText": "موقع يوتيوب",
  "linkendinText": "لينكيندين",
  "pinterestText": "بينتيريست",
  "followersText": "متابعون",
  "mr": "السيد.",
  "letsText": "دعنا نذهب",
  "orderIdTitle": 'رقم طلبك هو: ',
  "orderDateTitle": 'تاريخ الطلب: 8 سبتمبر 2021',
  "orderExpectedSDTitle": 'تاريخ الشحن المتوقع ',
  "orderConfirm": "شكرا لك على الشراء!",
  "name": "اسم",
  "image": "صورة",
  "price": "السعر",
  "qty": "الكمية",
  "subTotal": "المجموع الفرعي",
  "billingAddress": "عنوان وصول الفواتير",
  "shippingAddress": "عنوان الشحن",
  "paymentMethod": "طريقة الدفع او السداد",
  "cashOnDelivery": "الدفع عند الاستلام",
  "continueShopping": "مواصلة التسوق",
  "trackYourOrder": "أتبع طلبك",
  "orderContain":
      'سنرسل إليك رسالة إلكترونية لتأكيد الطلب مع التفاصيل ومعلومات التتبع.',
  "referFriendText": "ادع صديق",
  "returnsRefundsText": "العوائد والمردودات",
  "faqText": "التعليمات",
  "contactText": "اتصل",
  "socialText": "اجتماعي",
  "companyText": "شركة",
  "contactUs": "اتصل بنا",
  "myOrders": "طلباتي",
  "myOrderImage": "صورة",
  "productName": "اسم المنتج",
  "sku": "SKU",
  "quantity": "الكمية",
  "status": "حالة",
  "action": "عمل",
  "createNewCustomerAccountText": "إنشاء حساب عميل جديد",
  "emailAddressText": "عنوان بريد الكتروني",
  "confirmEmailAddressText": "أكد عنوانك الإلكتروني",
  "passwordText": "كلمة المرور",
  "confirmPasswordText": "تأكيد كلمة المرور",
  "dateOfBirthText": "تاريخ الميلاد",
  "marriageAnniversaryText": "ذكرى الزواج",
  "signUpForNewsLetterText": "الاشتراك في النشرة الإخبارية",
  "registerWithFacebookText": "سجل مع الفيسبوك",
  "createAnAccountText": "إنشاء حساب",
  "registeredCustomersText": "العملاء المسجلين",
  "signInDescriptionText":
      "إذا كان لديك حساب ، قم بتسجيل الدخول باستخدام \n عنوان بريدك الإلكتروني.",
  "forgotYourPasswordText": "نسيت رقمك السري؟",
  "signInText": "تسجيل الدخول",
  "newCustomersText": "زبائن الجدد",
  "newCustomersDescriptionText":
      "إنشاء حساب له فوائد عديدة: \n تحقق بشكل أسرع ، واحتفظ بأكثر من عنوان ، \n تتبع الطلبات والمزيد.",
  "createAccountText": "إنشاء حساب",
  "aboutProjectNameText": "حول العلامات التجارية والتسميات",
  "helpAndInformationText": "المساعدة والمعلومات",
  "moreFromProjectText": "المزيد من العلامات التجارية والتسميات",
  "newsLetterText": "النشرة الإخبارية",
  "subscribeText": "الإشتراك",
  "loginWithFacebookText": "تسجيل الدخول باستخدام الفيسبوك",
  "suvAndNatHeaderText": "ابحث عن أرخص ، سوف نتحمل هذا السعر",
  "homeText": "الصفحة الرئيسية",
  "searchText": "بحث",
  "designersText": "المصممين",
  "wishListText": "قائمة الرغبات",
  "loginText": "تسجيل الدخول",
  "myAccountText": "حسابي",
  "checkoutText": "الدفع",
  "shippingAddressText": "عنوان الشحن",
  "shippingMethodText": "طريقة الشحن",
  "paymentMethodText": "طريقة الدفع او السداد",
  "orderSummaryText": "ملخص الطلب",
  "createCheckoutText": "يمكنك إنشاء حساب بعد الخروج.",
  "stLineText": "عنوان الشارع: الخط",
  "indiaText": "الهند",
  "regionText": "الرجاء تحديد منطقة أو ولاية أو مقاطعة",
  "zipCodeText": "الرمز البريدي / الرمز البريدي",
  "phoneNumberText": "رقم التليفون",
  "qtyText": "الكمية",
  "enterDiscountCodeText": "أدخل رمز الخصم",
  "applyText": "تطبيق",
  "placeOrderText": "مكان الامر",
  "myOrdersText": "طلباتي",
  "myWishlistText": "قائمة امنياتي",
  "addressBookText": "دليل العناوين",
  "accountInformationText": "معلومات الحساب",
  "storePaymentText": "طرق الدفع المخزنة",
  "news1LetterText": "اشتراك الرسائل الإخبارية",
  "affiliateProgramText": "إنضم لبرنامج",
};
