const Map<String, String> cn = {
  "language": "英语",
  "appNameText": "苏文纳特",
  "aboutUsText": "关于我们",
  "aboutUsTitle": "SUV & NAT 是一个顶级的在线豪华时尚目的地，每月有 500 万游客，并在全球范围内运送。",
  "aboutUsContain":
      '''该网站精选了顶级设计师和年轻的新兴人才。 Brandslabels 于 1930 年代初在佛罗伦萨成立，该公司的同名概念店在 Via Roma 开业。自 1999 年以来，该公司将 90% 的总收入归功于在线销售。直到今天，它仍然是一个 100% 私有的家族企业，创始人的孙子 Andrea Panconesi 担任首席执行官，他的女儿 Annagreta Panconesi 担任创意总监。''',
  "aboutUsContain1":
      '该网站提供各种服装、鞋子、包包、配饰、豪华家居内饰和美容产品，其中包括来自 Balenciaga、Vetements、Off-White、J.W. 等最负盛名设计师的男士、女士和儿童产品。 Anderson、Balmain、Dolce & Gabbana、Gucci、Saint Laurent、Valentino、Givenchy、Loewe、Jacquemus 等等。',
  "aboutUsContain2":
      '目前有来自 15 个不同国家的 200 人致力于生产和维护 Brandslabels。该网站提供 9 种语言版本：英语、意大利语、德语、中文、俄语、西班牙语、法语、韩语和日语。该网站完全由内部创建，佛罗伦萨办公室设有平面设计、IT、客户服务、营销和采购部门。造型师和新闻团队在世界时尚之都——米兰的 Suvandnats 办公室工作。',
  "aboutUsContain3":
      '所有订单均从 Suvandnats 总部装在经过精心准备并使用最优质材料的盒子中运送到世界各地，从标志性鞋袋到个性化丝带，应有尽有。',
  "aboutUsContain4":
      'Suvandnats 在 2008 年有 150 万独立访问者访问该网站，并在 2017 年增长到 5300 万独立访问者。超过 15% 的在线销售来自美国，其次是德国、英国、意大利、中国和法国。',
  "aboutUsContain5":
      'Suvandnats 通过一系列独家服务和商标计划，包括 Buy It First、Luxury Club、Sneakers Club、LVR Privilege 和 LVR Editions，在线上和线下推动奢侈品零售领域的发展。',
  "profile": "轮廓",
  "firstNameText": "名",
  "lastNameText": "姓",
  "emailText": "电子邮件",
  "ContactNoText": "联系方式。",
  "websiteUrlText": "网址",
  "cityText": "城市",
  "countryText": "国家",
  "postCodeText": "邮政编码",
  "socialLinksText": "社交链接",
  "facebookText": "Facebook",
  "instagramText": "Instagram",
  "twitterText": "推特",
  "youtubeText": "YouTube",
  "linkendinText": "林肯",
  "pinterestText": "Pinterest",
  "followersText": "追随者",
  "mr": "Mr.先生。",
  "letsText": "我们走吧",
  "orderIdTitle": '''您的订单#是：''',
  "orderDateTitle": '订购日期：2021 年 9 月 8 日',
  "orderExpectedSDTitle": '预计发货日期：',
  "orderConfirm": "感谢您的购买！",
  "name": "姓名",
  "image": "图片",
  "price": "价钱",
  "qty": "QTY数量",
  "subTotal": "小计",
  "billingAddress": "帐单地址",
  "shippingAddress": "送货地址",
  "paymentMethod": "付款方法",
  "cashOnDelivery": "货到付款",
  "continueShopping": "继续购物",
  "trackYourOrder": "追踪您的订单",
  "orderContain": '我们将通过电子邮件向您发送包含详细信息和跟踪信息的订单确认信息。',
  "referFriendText": "推荐朋友",
  "returnsRefundsText": "退货和退款",
  "faqText": "常问问题",
  "contactText": "接触",
  "socialText": "社会的",
  "companyText": "公司",
  "contactUs": "联系我们",
  "myOrders": "我的订单",
  "myOrderImage": "图片",
  "productName": "产品名称",
  "sku": "SKU库存单位",
  "quantity": "数量",
  "status": "状态",
  "action": "行动",
  "createNewCustomerAccountText": "创建新客户帐户",
  "emailAddressText": "电子邮件地址",
  "confirmEmailAddressText": "确认电邮地址",
  "passwordText": "密码",
  "confirmPasswordText": "确认密码",
  "dateOfBirthText": "出生日期",
  "marriageAnniversaryText": "结婚周年",
  "signUpForNewsLetterText": "订阅时事通讯",
  "registerWithFacebookText": "注册脸书",
  "createAnAccountText": "创建一个帐户",
  "registeredCustomersText": "注册客户",
  "signInDescriptionText": "如果您有帐户，请使用您的\nemail 地址登录。",
  "forgotYourPasswordText": "忘记密码了吗？",
  "signInText": "登入",
  "newCustomersText": "新客户",
  "newCustomersDescriptionText": "创建帐户有很多好处：\n结账速度更快、保留多个地址、\n跟踪订单等等。",
  "createAccountText": "创建一个帐户",
  "aboutProjectNameText": "关于品牌和标签",
  "helpAndInformationText": "帮助和信息",
  "moreFromProjectText": "更多来自品牌和标签",
  "newsLetterText": "通讯",
  "subscribeText": "订阅",
  "loginWithFacebookText": "使用 Facebook 登录",
  "suvAndNatHeaderText": "找到更便宜的，我们会打败那个价格",
  "homeText": "家",
  "searchText": "搜索",
  "designersText": "设计师",
  "wishListText": "愿望清单",
  "loginText": "登录",
  "myAccountText": "我的账户",
  "checkoutText": "退房",
  "shippingAddressText": "送货地址",
  "shippingMethodText": "邮寄方式",
  "paymentMethodText": "付款方法",
  "orderSummaryText": "订单摘要",
  "createCheckoutText": "您可以在结帐后创建一个帐户。",
  "stLineText": "街道地址：线",
  "indiaText": "印度",
  "regionText": "请选择地区、州或省",
  "zipCodeText": "邮编/邮政编码",
  "phoneNumberText": "电话号码",
  "qtyText": "数量",
  "enterDiscountCodeText": "输入折扣码",
  "applyText": "申请",
  "placeOrderText": "下订单",
  "myOrdersText": "我的订单",
  "myWishlistText": "我的收藏",
  "addressBookText": "地址簿",
  "accountInformationText": "帐户信息",
  "storePaymentText": "存储的付款方式",
  "news1LetterText": "通讯订阅",
  "affiliateProgramText": "会员计划",
};
