const Map<String, String> de = {
  "language": "Englisch",
  "appNameText": "Geländewagen n Nat",
  "aboutUsText": "Über uns",
  "aboutUsTitle":
      "SUV & NAT IST MIT 5 MILLIONEN BESUCHERN PRO MONAT UND WELTWEITEM VERSAND EIN TOP-ONLINE-LUXUSMODE-ZIEL.",
  "aboutUsContain":
      '„Die Website bietet die beste Auswahl der besten etablierten Designer sowie junger aufstrebender Talente. Brandslabels wurde Anfang der 1930er Jahre in Florenz mit der Eröffnung des gleichnamigen Concept Stores in der Via Roma gegründet. Seit 1999 online, schreibt das Unternehmen 90 % des Gesamtumsatzes dem Online-Verkauf zu. Bis heute ist es ein zu 100 % in Privatbesitz befindliches Familienunternehmen mit Andrea Panconesi, dem Enkel des Gründers, als CEO und seiner Tochter Annagreta Panconesi als Creative Director.“',
  "aboutUsContain1":
      'Die Website bietet eine große Auswahl an Kleidung, Schuhen, Taschen, Accessoires, Luxus-Wohninterieur und Schönheit, mit Produkten für Männer, Frauen und Kinder von den renommiertesten Designern wie Balenciaga, Vetements, Off-White, J.W. Anderson, Balmain, Dolce & Gabbana, Gucci, Saint Laurent, Valentino, Givenchy, Loewe, Jacquemus und mehr.',
  "aboutUsContain2":
      'Derzeit arbeiten 200 Mitarbeiter aus 15 verschiedenen Ländern an der Herstellung und Pflege von Brandslabels. Die Seite ist in 9 Sprachen verfügbar: Englisch, Italienisch, Deutsch, Chinesisch, Russisch, Spanisch, Französisch, Koreanisch und Japanisch. Die Website wird vollständig intern erstellt, wobei das Büro in Florenz Grafikdesign, IT, Kundendienst, Marketing und Einkaufsabteilungen beherbergt. Die Stylisten und Presseteams arbeiten vom Suvandnats-Büro in der Modehauptstadt der Welt – Mailand.',
  "aboutUsContain3":
      'Alle Bestellungen werden weltweit von der Suvandnats-Zentrale in Kartons versandt, die mit größter Sorgfalt vorbereitet werden und die besten Materialien verwenden, von den charakteristischen Schuhbeuteln bis zum personalisierten Band.',
  "aboutUsContain4":
      'Suvandnats verzeichnete im Jahr 2008 1,5 Millionen Einzelbesucher, die auf die Website zugegriffen haben, und ist 2017 auf 53 Millionen Einzelbesucher angewachsen. Mehr als 15 % der Online-Verkäufe werden in den Vereinigten Staaten generiert, gefolgt von Deutschland, Großbritannien, Italien, China und Frankreich.',
  "aboutUsContain5":
      'Suvandnats erweitert die Grenzen der Luxus-Einzelhandelslandschaft sowohl online als auch offline mit einer Reihe exklusiver Dienstleistungen und Markeninitiativen, darunter Buy It First, Luxury Club, Sneaker Club, LVR Privilege und LVR Editions.',
  "profile": "Profil",
  "firstNameText": "Vorname",
  "lastNameText": "Familienname, Nachname",
  "emailText": "Email",
  "ContactNoText": "Kontakt-Nr.",
  "websiteUrlText": "Webadresse",
  "cityText": "Stadt",
  "countryText": "Land",
  "postCodeText": "Postleitzahl",
  "socialLinksText": "Soziale Verbindungen",
  "facebookText": "Facebook",
  "instagramText": "Instagram",
  "twitterText": "Twitter",
  "youtubeText": "Youtube",
  "linkendinText": "Linkendin",
  "pinterestText": "Pinterest",
  "followersText": "Anhänger",
  "mr": "Herr.",
  "letsText": "Lass uns gehen",
  "orderIdTitle": '''Ihre Bestellnummer lautet: ''',
  "orderDateTitle": 'Bestelldatum: 8. September 2021',
  "orderExpectedSDTitle": 'Voraussichtliches Versanddatum: ',
  "orderConfirm": "DANKE FÜR IHREN EINKAUF!",
  "name": "NAME",
  "image": "BILD",
  "price": "PREIS",
  "qty": "Menge",
  "subTotal": "ZWISCHENSUMME",
  "billingAddress": "Rechnungsadresse",
  "shippingAddress": "Lieferanschrift",
  "paymentMethod": "Zahlungsmethode",
  "cashOnDelivery": "Barzahlung bei Lieferung",
  "continueShopping": "MIT DEM EINKAUFEN FORTFAHREN",
  "trackYourOrder": "VERFOLGEN SIE IHRE BESTELLUNG",
  "orderContain":
      'Wir senden Ihnen eine Bestellbestätigung mit Details und Tracking-Informationen per E-Mail.',
  "referFriendText": "Freund empfehlen",
  "returnsRefundsText": "Rückgabe & Erstattung",
  "faqText": "FAQ",
  "contactText": "Kontakt",
  "socialText": "Sozial",
  "companyText": "Gesellschaft",
  "contactUs": "Kontaktiere uns",
  "myOrders": "Meine Bestellungen",
  "myOrderImage": "Bild",
  "productName": "Produktname",
  "sku": "Artikelnummer",
  "quantity": "Menge",
  "status": "Status",
  "action": "Aktion",
  "createNewCustomerAccountText": "Neues Kundenkonto erstellen",
  "emailAddressText": "E-Mail-Addresse",
  "confirmEmailAddressText": "e-Mail-Adresse bestätigen",
  "passwordText": "Passwort",
  "confirmPasswordText": "Bestätige das Passwort",
  "dateOfBirthText": "Geburtsdatum",
  "marriageAnniversaryText": "Hochzeitstag",
  "signUpForNewsLetterText": "Anmeldung für Newsletter",
  "registerWithFacebookText": "Registrieren Sie sich bei Facebook",
  "createAnAccountText": "EIN KONTO ERSTELLEN",
  "registeredCustomersText": "Registrierte Kunden",
  "signInDescriptionText":
      "Wenn Sie ein Konto haben, melden Sie sich mit Ihrer\nE-Mail-Adresse an.",
  "forgotYourPasswordText": "Haben Sie Ihr Passwort vergessen?",
  "signInText": "Anmelden",
  "newCustomersText": "neue Kunden",
  "newCustomersDescriptionText":
      "Das Erstellen eines Kontos hat viele Vorteile:\nBezahle schneller, behalte mehr als eine Adresse,\nverfolge Bestellungen und mehr.",
  "createAccountText": "Ein Konto erstellen",
  "aboutProjectNameText": "Über Marken und Labels",
  "helpAndInformationText": "Hilfe und Informationen",
  "moreFromProjectText": "Mehr von Brands&Labels",
  "newsLetterText": "Newsletter",
  "subscribeText": "Abonnieren",
  "loginWithFacebookText": "Mit Facebook einloggen",
  "suvAndNatHeaderText": "FINDEN SIE ES BILLIGER, WIR SCHLAGEN DIESEN PREIS",
  "homeText": "Zuhause",
  "searchText": "Suche",
  "designersText": "Designer",
  "wishListText": "Wunschzettel",
  "loginText": "Anmeldung",
  "myAccountText": "Mein Konto",
  "checkoutText": "Kasse",
  "shippingAddressText": "Lieferanschrift",
  "shippingMethodText": "Versandart",
  "paymentMethodText": "Zahlungsmethode",
  "orderSummaryText": "Bestellübersicht",
  "createCheckoutText": "Sie können nach der Kasse ein Konto erstellen.",
  "stLineText": "Straße: Linie",
  "indiaText": "Indien",
  "regionText":
      "Bitte wählen Sie eine Region, ein Bundesland oder eine Provinz aus",
  "zipCodeText": "Postleitzahl",
  "phoneNumberText": "Telefonnummer",
  "qtyText": "Menge",
  "enterDiscountCodeText": "Rabattcode eingeben",
  "applyText": "Anwenden",
  "placeOrderText": "BESTELLUNG AUFGEBEN",
  "myOrdersText": "MEINE BESTELLUNGEN",
  "myWishlistText": "Meine Wunschliste",
  "addressBookText": "Adressbuch",
  "accountInformationText": "Kontoinformationen",
  "storePaymentText": "GESPEICHERTE ZAHLUNGSARTEN",
  "news1LetterText": "NEWSLETTER-ABOS",
  "affiliateProgramText": "Partnerprogramm",
};
