const Map<String, String> en = {
  "language": "English",
  "appNameText": "Suv&Nat",
  "faqTitle": "Frequently Asked Questions",
  "charityTitle": "Shop More consciously",
  "charityContain1": "Every Purchase you Make Will Help Buld a Childs Future.",
  "charityContain2":
      "Sun & Nat - Works actively to help change the world and every purchase you make on our site helps us do the same. We have partnered with a few charities and would like your suggestions to add the charities and causes which you feel need our help and those which can make a difference to people lives.",
  "charityContain3":
      "Sun & Nat will donate 3% of the proceeds of every sale to a charity that you choose or to one on our list if you do not choose one. You can further help with donating any additional amount at the checkout.",
  "charityContain4":
      "If you choose to add 10 dollars we will add further 10 dollars as our contribution in additional to our initial 3% ( subject to a maximum of 10% of the order value).",
  "charityContain5":
      "Every cent is accounted for and our team works hard to ensure that the money reaches in the right hands.",
  "charityContain6":
      "We update you every step of the way so you can be satisfied when your contributions has changed and improved lives.",
  "menText": "Men",
  "womenText": "Women",
  "kidsText": "Kids",
  "details": "Details",
  "wishList": "WISHLIST",
  "addAll": "ADD ALL",
  "description": "Description",
  "estimatedDelivery": "Estimated Delivery",
  "guaranteedDelivery": "Guaranteed Delivery : Nov 04 - Nov 11",
  "sizeChart": "Size Chart",
  "size": "Size",
  "addTOCart": "Add To Cart",
  "addToWishlist": "Add To Wishlist",
  "whyVeraLusso": "WHY VERALUSSO",
  "knowMore": "Know More",
  "recommendation": "Recommendation",
  "recentlyViewed": "Recently Viewed",
  "returnPolicyTitle": "Return Policy",
  "refundTitle": "Refunds",
  "returnProcessTitle": "Return Process",
  "customisedTitle": "Customised, Pre-owned & Vintage Items",
  "howToReturnTitle": "How To Return",
  "returnPolicyContain1":
      "Returned items must comply with our returns policy:\n",
  "returnPolicyContain2":
      'Items must be returned unworn, undamaged and unused, with all tags attached and the original packaging included.',
  "returnPolicyContain3":
      'Footwear and accessories must be returned with the original branded boxes and dust bags, where provided, and placed inside a protective outer box for shipping.',
  "returnPolicyContain4":
      'When trying on footwear, please take care not to mark the soles or damage the shoe box.',
  "returnPolicyContain5":
      'If an item has a Avoirchic security tag or brand tag attached, it must be returned with the tag in its original.',
  "returnPolicyContain6":
      'Beauty and cosmetic products must be returned unopened and unused, with the seals of any packaging still intact.',
  "returnPolicyContain7":
      'Hosiery, lingerie and swimwear items must be returned with the hygiene seals attached and in unopened and undamaged product packaging, where applicable.',
  "returnPolicyContain8":
      'Lingerie and swimwear must only be tried on over your own undergarments. We will not accept any returns that have been worn or are soiled.',
  "returnPolicyContain9":
      'Face masks must be returned unworn in their original, unopened and undamaged product packaging. Jewellery must be returned in the same condition it arrived in, including all branded packaging and documents provided with it.',
  "returnPolicyContain10":
      "Please take care when trying on your purchases and return them in the same condition you received them. Any returns that do not meet our policy will not be accepted.\n",
  "returnPolicyContain11":
      "If you placed an order as a guest, you can start your return here. To return or cancel an item that has been made to your specifications, please view our ‘ Customised Items’ section below for further information.",
  "aboutUsText": "About Us",
  "aboutUsTitle":
      "SUV & NAT IS A TOP ONLINE LUXURY FASHION DESTINATION WITH 5 MILLION VISITORS PER MONTH AND WORLDWIDE SHIPPING.",
  "aboutUsContain":
      '''The website features the best selection of the top established designers as well as young emerging talents. Brandslabels was founded in Florence in the early 1930s, with the opening of the company’s eponymous concept store on Via Roma. Online since 1999, the company attributes 90% of total revenue to online sales. To this day it remains a 100% privately owned family business, with the founder’s grandson, Andrea Panconesi acting as CEO and his daughter, Annagreta Panconesi as Creative Director.''',
  "aboutUsContain1":
      'The site offers a wide selection of clothing, shoes, bags, accessories, luxury home interiors and beauty, with products available for men, women and kids from the most prestigious designers such as Balenciaga, Vetements, Off-White, J.W. Anderson,Balmain, Dolce & Gabbana, Gucci, Saint Laurent, Valentino, Givenchy, Loewe, Jacquemus and more.',
  "aboutUsContain2":
      'There are currently 200 people from 15 different countries that work to produce and maintain Brandslabels. The site is available in 9 languages: English, Italian, German, Chinese, Russian, Spanish, French, Korean and Japanese. The site is created entirely in-house, with the Florence office housing graphic design, IT, customer service, marketing and buying departments. The stylists and press teams operate from the Suvandnats office in the fashion capital of the world – Milan.',
  "aboutUsContain3":
      'All orders are shipped worldwide from the Suvandnats headquarters in boxes that are prepared with maximum care and use the finest materials, from the signature shoe bags to the personalized ribbon.',
  "aboutUsContain4":
      'Suvandnats had 1.5 million unique visitors access the site in 2008 and has grown to 53 million unique visitors in 2017. More than 15% of online sales are generated from the United States, followed by Germany, UK, Italy, China and France.',
  "aboutUsContain5":
      'Suvandnats pushes the boundaries of the luxury retail landscape both on and offline with an array of exclusive services and trademark initiatives including Buy It First, Luxury Club,Sneakers Club, LVR Privilege and LVR Editions.',
  "profile": "Profile",
  "newsLettersContain": "You Aren't Subscribed To\nOur Newsletter.",
  "edit": "Edit",
  "newsLetters": "Newsletter",
  "manageAddresses": "Manage Addresses",
  "defaultBillingAddress": "Default Billing Address",
  "editAddress": "Edit Address",
  "defaultShippingAddress": "Default Shipping Address",
  "firstNameText": "First Name",
  "lastNameText": "Last Name",
  "emailText": "E-mail",
  "ContactNoText": "Contact no.",
  "websiteUrlText": "Website URL",
  "cityText": "City",
  "countryText": "Country",
  "postCodeText": "Post Code",
  "socialLinksText": "Social links",
  "facebookText": "Facebook",
  "instagramText": "Instagram",
  "twitterText": "Twitter",
  "youtubeText": "Youtube",
  "linkendinText": "Linkendin",
  "pinterestText": "Pinterest",
  "followersText": "Followers",
  "mr": "Mr.",
  "letsText": "Let’s Go",
  "orderIdTitle": '''Your order # is: ''',
  "orderDateTitle": 'Order Date: ',
  "orderExpectedSDTitle": 'Expected Shipment Date: ',
  "orderConfirm": "Thank You For Your Purchase!",
  "name": "Name",
  "image": "Image",
  "price": "Price",
  "qty": "Qty",
  "subTotal": "Subtotal",
  "billingAddress": "Billing Address",
  "shippingAddress": "Shipping Address",
  "paymentMethod": "Payment Method",
  "cashOnDelivery": "Cash On Delivery",
  "continueShopping": "Continue Shopping",
  "trackYourOrder": "Track Your Order",
  "orderContain":
      'We’ll email you an order confirmation with details and tracking info.',
  "myOrdersText": "My Orders",
  "myWishlistText": "My Wish List",
  "addressBookText": "Address Book",
  "accountInformationText": "Account Information",
  "myTicketsText": "My Tickets",
  "myAccountText": "My Account",
  "contactInfo": "Contact Information",
  "newsletters": "Newsletters",
  "myAccountContain": "You aren't subscribed to\nour newsletter.",
  "addressBook": "Address Book",
  "billing": "Billing",
  "shipping": "Shipping",
  "referFriendText": "Refer Friend",
  "returnsRefundsText": "Returns & Refunds",
  "faqText": "FAQ",
  "contactText": "Contact",
  "socialText": "Social",
  "companyText": "Company",
  "contactUs": "Contact Us",
  "myOrders": "My Orders",
  "myOrderImage": "Image",
  "productName": "Product Name",
  "sku": "SKU",
  "quantity": "Qty",
  "status": "Status",
  "action": "Action",
  "createNewCustomerAccountText": "Create New Customer Account",
  "emailAddressText": "Email Address",
  "confirmEmailAddressText": "Confirm Email Address",
  "passwordText": "Password",
  "confirmPasswordText": "Confirm Password",
  "dateOfBirthText": "Date of Birth",
  "marriageAnniversaryText": "Marriage Anniversary",
  "signUpForNewsLetterText": "Sign Up For Newsletter",
  "registerWithFacebookText": "Register With Facebook",
  "createAnAccountText": "Create An Account",
  "registeredCustomersText": "Registered Customers",
  "signInDescriptionText":
      "If you have an account, sign in with your\nemail address.",
  "forgotYourPasswordText": "Forgot Your Password?",
  "signInText": "Sign In",
  "newCustomersText": "New Customers",
  "newCustomersDescriptionText":
      "Creating An Account Has Many Benefits:\nCheck Out Faster, Keep More Than One Address,\nTrack Orders And More.",
  "createAccountText": "Create An Account",
  "aboutProjectNameText": "About Brands and Labels",
  "helpAndInformationText": "Help and Information",
  "moreFromProjectText": "More from Brands&Labels",
  "newsLetterText": "NewsLetter",
  "subscribeText": "Subscribe",
  "loginWithFacebookText": "Login With Facebook",
  "suvAndNatHeaderText": "FIND IT CHEAPER, WE'LL BEAT THAT PRICE",
  "affiliateProgramTitleText": "SUV&NAT AFFILIATE PROGRAM",
  "whoAreWeLookingTitleText": "Who are we looking for?",
  "whoAreWeLookingDescriptionOneText":
      "Do you have a fashion-forward, luxury oriented website, blog, social media profile that is trend savvy with an international outlook? Is your focus fashion, lifestyle, beauty and design? If so, we are looking for you!\n\nJoin our global Affiliate Program and you will have the opportunity to earn a commission every time your visitors purchase from SUV&NAT.",
  "whatCanYouExpectTitleText": "What can you expect?",
  "expectRuleOneText": "Commission on all approved net sales",
  "expectRuleTwoText": "45 days cookie window",
  "expectRuleThreeText": "Data feed updated multiple times per day",
  "expectRuleFourText":
      "Access to customized banners, textlinks, deeplinks and our datafeed in 9 languages (English, Italian, French, German, Korean, Spanish, Chinese,Russian & Japanese)",
  "expectRuleFiveText":
      "The possibility to customize feeds into all world currencies",
  "promoteSoloQuestionText": "How can you promote SUV&NAT (as an affiliate)?",
  "promoteSoloAnswerOneText":
      "Creating high-quality and engaging content that mirrors the style of SOLO",
  "promoteSoloAnswerTwoText":
      "Featuring our content, banners and links for multiple categories and events on your website and social media channels",
  "promoteSoloAnswerThreeText":
      "Promoting the benefits that our customers love",
  "promoteSoloAnswerFourText":
      "A selection of continuously updated articles from the best brands",
  "promoteSoloAnswerFiveText":
      "Free returns with no added taxes for the US, Canada, the UK and ",
  "howApplyTitleText": "How to apply?",
  "howApplyAnswerOneText":
      "Email us the name and URL of your website, blog or social media profile and your main markets. We’ll review your site and get back to you with further information on how to join the affiliate program.\n\nPlease note that all applications are manually evaluated and processing may take up to 10 days.\n\nIf you feel your application has been wrongfully declined please contact affiliates@suv&nut.com and a member of the team will address your concerns.",
  "visitorMonthHintText": "Select Unique Visitors/Month",
  "viewsMonthHintText": "Select Page Views/Month",
  "cityHintText": "City",
  "countryHintText": "Country",
  "addressOneText": "Street Address 1",
  "addressTwoText": "Street Address 2",
  "addressText": "Address",
  "letsGoText": "Let's Go",
  "accessYourAccountDetailsText": "Access your account details and rewards",
  "signUpText": "Sign Up",
  "loginMyAccountText": "Login",
  "myOrderText": "My Orders",
  "trackOrderText": "Track Order",
  "careersText": "Careers",
  "helpTheNeedyText": "Help The Needy",
  "secureShoppingText": "Secure Shopping",
  "influencerRegistrationText": "Influencer Registration",
  "affiliateText": "Affiliate Program",
  "advancedSearchText": "Advanced Search",
  "privacyPolicyText": "Privacy Policy",
  "termsConditionsText": "Terms & Conditions",
  "aboutText": "About",
  "aboutUsMyAccountText": "About Us",
  "referFriendMyAccountText": "Refer Friend",
  "returnsText": "Returns And Refunds",
  "contactUsText": "Contact Us",
  "faqMyAccountText": "Faq",
  "liveChatText": "Live Chat",
  "startChatText": "Start the chat",
  "accountText": "Account",
  "newsletterText": "Newsletter",
  "phoneText": "Phone",
  "additionalAdressEntriesText": "Additional address entries",
  "addNewText": "Add New",
  "findCheaperText": "FIND IT CHEAPER, WE’LL BEAT THAT PRICE.",
  "chooseCountryText": "Choose Your Country",
  "saveAddressText": "Save Address",
  "yourAppExpericanceText": "Your app experience is set to",
  "indiaText": "INDIA (IND) - ENGLISH (IND)",
  "englishIsAlsoText":
      "ENGLISH is also available in your\nlocation. Would you like to change?",
  "noThanksText": "No, Thanks",
  "changeText": "CHANGE",
  "myWidhListText": "My Wish List",
  "accountInfoText": "Account Information",
  "storePaymentText": "Store Payment Methods",
  "newsletterSubText": "Newsletter Subscriptions",
  "checkYourOrderText": "Check your order",
  "enterYourOrderText":
      "Enter your order reference and email address below to see your order details. From there you can check its shipping status,cancel items or make a return.",
  "howDoIFindText": "How do i find my",
  "orderRefernceText": "Order reference?",
  "submitText": "Submit",
  "homeText": "Home",
  "searchText": "Search",
  "designersText": "Designers",
  "wishListText": "WishList",
  "loginText": "Login",
  "checkoutText": "Checkout",
  "shippingAddressText": "Shipping Address",
  "shippingMethodText": "Shipping Method",
  "paymentMethodText": "Payment Method",
  "orderSummaryText": "Order Summary",
  "createCheckoutText": "You can create an account after checkout.",
  "stLineText": "Street Address: Line",
  "regionText": "Please select a region, state or province",
  "zipCodeText": "Zip/Postal Code",
  "phoneNumberText": "Phone Number",
  "qtyText": "Qty",
  "enterDiscountCodeText": "Enter Discount Code",
  "applyText": "Apply",
  "placeOrderText": "Place Order",
  "news1LetterText": "NEWSLETTER SUBSCRIPTIONS",
  "welcometoChatText": "Welcome to our LiveChat!",
  "fillTheFormText":
      "Please fill in the form below before \nstarting the chat.",
  "nameChatText": "Name",
  "deliveryText": "Delivery",
  "ordersText": "Order",
  "paymentText": "Payment",
  "productText": "Product",
  "promotionText": "Promotion",
  "returnsContactText": "Returns",
  "technicalText": "Technical",
  "typeOfEnquiryText": "Type Of Enquiry",
  "surNameText": "Surname",
  "confirmEmailText": "Confirm Email",
  "subjectText": "Subject",
  "whatsonyourmindText": "What's On Your Mind?",
  "selectLangCurrText": "Select Language & Currency",
  "selectLangCurrDescText":
      "Please choose from the following Language and currency options available in your country Language",
  "saveText": "Save",
  "cancelText": "Cancel",
  "languageText": "Language",
  "currencyText": "Currency",
  "findinCheaperText": "FIND IT CHEAPER, WE’LL BEAT THAT PRICE.",
  "unitedKingdomText": "UNITED KINGDOM",
  "gdpText": "GDP",
  "englishText": "ENGLISH",
  "findBrandsText": "Find Brands",
  "priceText": "Price",
  "filtersText": "Filters",
  "colorText": "Color",
  "brandText": "Brand",
  "sizeText": "Size",
  "applyFilterText": "Apply",
  "viewCartText": "View Cart",
  "continueShoppingText": "Continue Shopping",
  "findItText": "FIND IT CHEAPER, WE'LL BEAT THAT PRICE.",
  "shippingCartText": "Shopping Cart",
  "itemText": "Item",
  "summaryText": "Summary",
  "applyDiscountText": "Apply Discount",
  "updateText": "Update Cart",
  "enterDiscountText": "Enter discount code",
  "subtotalText": "Subtotal",
  "taxText": "Tax",
  "orderText": "Order Total",
  "forgetPassword": "Forgot Your Password?",
  "resetPassword": "Reset My Password",
  "forgetPassword1": "Enter email address to receive a password reset link.",
  "backToSignInScreen": "Back to sign in screen",
  "forgetPasswordContain":
      "If There Is A Account Associated With (Test @suvandnat.com) We Will Send You A Email With The Instructions To Reset Your Password.If You Need Any Further Assistance Pls",
  "policyHomeText": "HOME",
  "policyText": "PRIVACY POLICY",
  "logOutText": "LogOut",
  "viewWishListText": "View WishList",
  "reasonReturnText": "Reason to return",
  "returnItemText": "Return ltem",
  "policyHeadingText": "Suv & Nut Group Privacy Policy",
  "returnText": "Return",
  "returnRequestText": "Return Request Received",
  "teamSoloLuxuryText": "Team Solo Luxury.",
  "saveInAddressBookText": "Save In Address Book",
  "shipHereText": "Ship Here",
  "notifyMe": "Notify Me When Available",
  "youaddCartText": "You added",
  "youaddCartEndText": "to your shopping cart.",
  "specialSizeRequestsText": "Special Size Requests",
  "specialSizeEnterEmailText": "Enter Email",
  "specialSizeSelectSizeText": "Select Size",
  "updateAddressText": "Update Address",
  "specialSizeSubmitText": "Submit",
  "wehaveRecivedText":
      "We have received your request and your request Id is - Please Check the status of your request at @@@@. contact us at care@sololuxury.com - for any query with regards to request.",
  "newAddressText": "New Address",
  "myBillingShipAddressSameText":
      "My Billing and Shipping Address are the same",
  "testDonationText": "Test Donation",
  "youAddedTestText":
      "You added Test Donation your shopping cart.\nThe page will be refreshed.",
  "chooseYourOwmText": "Choose your own Amount GBP(minimum €1)",
  "theSelectedAmountText":
      "The selected amount will be added to your\nshopping cart.",
  "iwantToDonateText": "i want to donate this amount",
  "e5Text": "€ 5",
  "e10Text": "€ 10",
  "e15Text": "€ 15",
  "e20Text": "€ 20",
  "e25Text": "€ 25",
  "gbpText": "GBP",
  "cartContain1": "Support a Charity With Your Donation",
  "cartContain2":
      "15% of the order value will be donated by\nSuv & Nat for donations.",
  "cartContain3": "Please Click Here To Donate Now.",
  "cartContain4": "I Want To Donate",
  "cartContain5": "Check Out with Multiple Addresses",
  "affiliateProgramText": "Affiliate Program",
  "forgotPasswordWrongEmailEnd": "you need any further assistance please",
  "WriteAt": "Write to us at",
  "forgotPasswordWrongEmailStart": "There is no Account Associated",
  "accountDoesNotExist": "Account Does Not Exist",
  "searchCountry": "Search country",
  "sizeChartText": "Size Chart",
  "idText": "Id",
  "nameText": "Name",
  "actionText": "Action",
  "reasonCancelText": "Reason to cancel",
  "cancelItemText": "cancel item",
  "thankYou": "Thank You",
  "notifyMeWhenThisProductIsInStock":
      "We Will Inform You Once The Product Is In Stock. You Can Also View The Status Of Your Request On",
  "myTicket": "My Tickets.",
  "priceMatch": "Price Match"
};
