const Map<String, String> es = {
  "language": "inglés",
  "appNameText": "todoterreno y nacional",
  "aboutUsText": "Sobre nosotros",
  "aboutUsTitle":
      "SUV & NAT ES UN PRINCIPAL DESTINO DE MODA DE LUJO EN LÍNEA CON 5 MILLONES DE VISITANTES AL MES Y ENVÍOS A TODO EL MUNDO.",
  "aboutUsContain":
      '''El sitio web presenta la mejor selección de los mejores diseñadores establecidos, así como jóvenes talentos emergentes. Brandslabels se fundó en Florencia a principios de la década de 1930, con la apertura de la tienda conceptual homónima de la empresa en Via Roma. En línea desde 1999, la empresa atribuye el 90% de los ingresos totales a las ventas en línea. Hasta el día de hoy, sigue siendo una empresa familiar 100% privada, con el nieto del fundador, Andrea Panconesi, como director ejecutivo y su hija, Annagreta Panconesi, como directora creativa.''',
  "aboutUsContain1":
      'El sitio ofrece una amplia selección de ropa, zapatos, bolsos, accesorios, interiores de lujo para el hogar y belleza, con productos disponibles para hombres, mujeres y niños de los diseñadores más prestigiosos como Balenciaga, Vetements, Off-White, J.W. Anderson, Balmain, Dolce & Gabbana, Gucci, Saint Laurent, Valentino, Givenchy, Loewe, Jacquemus y más.',
  "aboutUsContain2":
      'Actualmente hay 200 personas de 15 países diferentes que trabajan para producir y mantener Brandslabels. El sitio está disponible en 9 idiomas: inglés, italiano, alemán, chino, ruso, español, francés, coreano y japonés. El sitio se crea completamente internamente, con la oficina de Florencia que alberga los departamentos de diseño gráfico, TI, servicio al cliente, marketing y compras. Los estilistas y los equipos de prensa operan desde la oficina de Suvandnats en la capital mundial de la moda: Milán.',
  "aboutUsContain3":
      'Todos los pedidos se envían a todo el mundo desde la sede de Suvandnats en cajas que se preparan con el máximo cuidado y utilizan los mejores materiales, desde las exclusivas bolsas para zapatos hasta la cinta personalizada.',
  "aboutUsContain4":
      'Suvandnats tuvo 1,5 millones de visitantes únicos que accedieron al sitio en 2008 y creció a 53 millones de visitantes únicos en 2017. Más del 15 % de las ventas en línea se generan en los Estados Unidos, seguido de Alemania, el Reino Unido, Italia, China y Francia.',
  "aboutUsContain5":
      'Suvandnats supera los límites del panorama minorista de lujo tanto en línea como fuera de línea con una variedad de servicios exclusivos e iniciativas de marcas registradas que incluyen Buy It First, Luxury Club, Sneakers Club, LVR Privilege y LVR Editions.',
  "profile": "Perfil",
  "firstNameText": "Primer nombre",
  "lastNameText": "Apellido",
  "emailText": "Correo electrónico",
  "ContactNoText": "Número de contacto",
  "websiteUrlText": "URL del sitio web",
  "cityText": "Ciudad",
  "countryText": "País",
  "postCodeText": "Código postal",
  "socialLinksText": "Vínculos sociales",
  "facebookText": "Facebook",
  "instagramText": "Instagram",
  "twitterText": "Gorjeo",
  "youtubeText": "YouTube",
  "linkendinText": "Linkendín",
  "pinterestText": "Pinterest",
  "followersText": "Seguidores",
  "mr": "Señor.",
  "letsText": "Vamos",
  "orderIdTitle": 'Su orden # es: ',
  "orderDateTitle": 'Fecha de pedido: 8 de septiembre de 2021',
  "orderExpectedSDTitle": 'Fecha de envío prevista: ',
  "orderConfirm": "¡GRACIAS POR SU COMPRA!",
  "name": "NOMBRE",
  "image": "IMAGEN",
  "price": "PRECIO",
  "qty": "CANTIDAD",
  "subTotal": "TOTAL PARCIAL",
  "billingAddress": "Dirección de Envio",
  "shippingAddress": "Dirección de envío",
  "paymentMethod": "Método de pago",
  "cashOnDelivery": "Contrareembolso",
  "continueShopping": "SEGUIR COMPRANDO",
  "trackYourOrder": "RASTREA TU ORDEN",
  "orderContain":
      'Le enviaremos por correo electrónico una confirmación del pedido con los detalles y la información de seguimiento.',
  "referFriendText": "Recomendar amigo",
  "returnsRefundsText": "Devoluciones y reembolsos",
  "faqText": "Preguntas más frecuentes",
  "contactText": "Contacto",
  "socialText": "Social",
  "companyText": "Compañía",
  "contactUs": "Contáctenos",
  "myOrders": "Mis ordenes",
  "myOrderImage": "Imagen",
  "productName": "nombre del producto",
  "sku": "SKU",
  "quantity": "Cantidad",
  "status": "Estado",
  "action": "Acción",
  "createNewCustomerAccountText": "Crear nueva cuenta de cliente",
  "emailAddressText": "Dirección de correo electrónico",
  "confirmEmailAddressText": "Confirmar el correo",
  "passwordText": "Clave",
  "confirmPasswordText": "Confirmar contraseña",
  "dateOfBirthText": "Fecha de nacimiento",
  "marriageAnniversaryText": "Aniversario de boda",
  "signUpForNewsLetterText": "Regístrese para recibir el boletín",
  "registerWithFacebookText": "Regístrese con Facebook",
  "createAnAccountText": "CREA UNA CUENTA",
  "registeredCustomersText": "Clientes Registrados",
  "signInDescriptionText":
      "Si tiene una cuenta, inicie sesión con su\ndirección de correo electrónico.",
  "forgotYourPasswordText": "¿Olvidaste tu contraseña?",
  "signInText": "Iniciar sesión",
  "newCustomersText": "nuevos clientes",
  "newCustomersDescriptionText":
      "Crear una cuenta tiene muchos beneficios:\npague más rápido, mantenga más de una dirección,\nseguimiento de pedidos y más.",
  "createAccountText": "Crea una cuenta",
  "aboutProjectNameText": "Sobre Marcas y Etiquetas",
  "helpAndInformationText": "Ayuda e Información",
  "moreFromProjectText": "Más de Marcas y Etiquetas",
  "newsLetterText": "Boletin informativo",
  "subscribeText": "Suscribir",
  "loginWithFacebookText": "Iniciar sesión con Facebook",
  "suvAndNatHeaderText": "ENCUÉNTRALO MÁS BARATO, TE MEJORAMOS ESE PRECIO",
  "homeText": "Casa",
  "searchText": "Búsqueda",
  "designersText": "Diseñadores",
  "wishListText": "lista de deseos",
  "loginText": "Acceso",
  "myAccountText": "Mi cuenta",
  "checkoutText": "Verificar",
  "shippingAddressText": "Dirección de envío",
  "shippingMethodText": "Método de envío",
  "paymentMethodText": "Método de pago",
  "orderSummaryText": "Resumen del pedido",
  "createCheckoutText":
      "Puede crear una cuenta después de finalizar la compra.",
  "stLineText": "Dirección de la calle: Línea",
  "indiaText": "India",
  "regionText": "Seleccione una región, estado o provincia",
  "zipCodeText": "Código postal",
  "phoneNumberText": "Número de teléfono",
  "qtyText": "Cantidad",
  "enterDiscountCodeText": "Introduzca el código de descuento",
  "applyText": "Aplicar",
  "placeOrderText": "REALIZAR PEDIDO",
  "myOrdersText": "MIS ORDENES",
  "myWishlistText": "Mi lista de deseos",
  "addressBookText": "Directorio",
  "accountInformationText": "Información de la cuenta",
  "storePaymentText": "MÉTODOS DE PAGO ALMACENADOS",
  "news1LetterText": "SUSCRIPCIONES A LOS BOLETINES",
  "affiliateProgramText": "programa de afiliación",
};
