const Map<String, String> fr = {
  "language": "Anglais",
  "appNameText": "SUV et Nat",
  "aboutUsText": "À propos de nous",
  "aboutUsTitle":
      "SUV & NAT EST UNE DESTINATION DE MODE DE LUXE EN LIGNE AVEC 5 MILLIONS DE VISITEURS PAR MOIS ET DES LIVRAISONS DANS LE MONDE ENTIER.",
  "aboutUsContain":
      '''Le site Web présente la meilleure sélection des meilleurs designers établis ainsi que de jeunes talents émergents. Brandslabels a été fondée à Florence au début des années 1930, avec l'ouverture du concept store éponyme de l'entreprise sur la Via Roma. En ligne depuis 1999, l'entreprise attribue 90 % de son chiffre d'affaires total aux ventes en ligne. À ce jour, elle reste une entreprise familiale 100 % privée, avec le petit-fils du fondateur, Andrea Panconesi, en tant que PDG et sa fille, Annagreta Panconesi, en tant que directrice de la création.''',
  "aboutUsContain1":
      'Le site propose une large sélection de vêtements, chaussures, sacs, accessoires, intérieurs de maison de luxe et beauté, avec des produits disponibles pour hommes, femmes et enfants des créateurs les plus prestigieux tels que Balenciaga, Vetements, Off-White, J.W. Anderson, Balmain, Dolce & Gabbana, Gucci, Saint Laurent, Valentino, Givenchy, Loewe, Jacquemus et plus encore.',
  "aboutUsContain2":
      'Actuellement, 200 personnes de 15 pays différents travaillent à la production et à la maintenance des Brandslabels. Le site est disponible en 9 langues : anglais, italien, allemand, chinois, russe, espagnol, français, coréen et japonais. Le site est entièrement créé en interne, avec le bureau de Florence abritant les départements de conception graphique, informatique, service client, marketing et achats. Les stylistes et les équipes de presse opèrent depuis le bureau Suvandnats dans la capitale mondiale de la mode - Milan.',
  "aboutUsContain3":
      'Toutes les commandes sont expédiées dans le monde entier depuis le siège de Suvandnats dans des boîtes préparées avec le plus grand soin et utilisant les meilleurs matériaux, des sacs à chaussures emblématiques au ruban personnalisé.',
  "aboutUsContain4":
      '''Suvandnats comptait 1,5 million de visiteurs uniques sur le site en 2008 et est passé à 53 millions de visiteurs uniques en 2017. Plus de 15 % des ventes en ligne sont générées aux États-Unis, suivis de l'Allemagne, du Royaume-Uni, de l'Italie, de la Chine et de la France.''',
  "aboutUsContain5":
      '''Suvandnats repousse les limites du paysage de la vente au détail de luxe à la fois en ligne et hors ligne avec une gamme de services exclusifs et d'initiatives de marque, notamment Buy It First, Luxury Club, Sneakers Club, LVR Privilege et LVR Editions.''',
  "profile": "Profil",
  "firstNameText": "Prénom",
  "lastNameText": "Nom de famille",
  "emailText": "E-mail",
  "ContactNoText": "N° de contact",
  "websiteUrlText": "URL de site web",
  "cityText": "Ville",
  "countryText": "De campagne",
  "postCodeText": "Code postal",
  "socialLinksText": "Liens sociaux",
  "facebookText": "Facebook",
  "instagramText": "Instagram",
  "twitterText": "Twitter",
  "youtubeText": "Youtube",
  "linkendinText": "Linkendin",
  "pinterestText": "Pinterest",
  "followersText": "Suiveurs",
  "mr": "Mr.Monsieur.",
  "letsText": "Allons-y",
  "orderIdTitle": '''Votre numéro de commande est : ''',
  "orderDateTitle": 'Date de commande : 8 septembre 2021',
  "orderExpectedSDTitle": '''Date d'expédition prévue : ''',
  "orderConfirm": "MERCI POUR VOTRE ACHAT!",
  "name": "NAMENOM",
  "image": "IMAGEIMAGE",
  "price": "PRICELE PRIX",
  "qty": "QTYQTÉ",
  "subTotal": "TOTAL",
  "billingAddress": "Adresse de facturation",
  "shippingAddress": "Adresse de livraison",
  "paymentMethod": "Mode de paiement",
  "cashOnDelivery": "Paiement à la livraison",
  "continueShopping": "CONTINUER VOS ACHATS",
  "trackYourOrder": "SUIVRE VOTRE COMMANDE",
  "orderContain":
      'Nous vous enverrons par e-mail une confirmation de commande avec les détails et les informations de suivi.',
  "referFriendText": "Référez un ami",
  "returnsRefundsText": "Retours et remboursements",
  "faqText": "FAQ",
  "contactText": "Contact",
  "socialText": "Social",
  "companyText": "Compagnie",
  "contactUs": "Nous contacter",
  "myOrders": "Mes commandes",
  "myOrderImage": "Image",
  "productName": "Nom du produit",
  "sku": "SKUUGS",
  "quantity": "Qté",
  "status": "Statut",
  "action": "action",
  "createNewCustomerAccountText": "Créer un nouveau compte client",
  "emailAddressText": "Adresse e-mail",
  "confirmEmailAddressText": "Confirmez votre adresse email",
  "passwordText": "Mot de passe",
  "confirmPasswordText": "Confirmez le mot de passe",
  "dateOfBirthText": "Date de naissance",
  "marriageAnniversaryText": "Anniversaire de mariage",
  "signUpForNewsLetterText": "S'inscrire aux Newsletters",
  "registerWithFacebookText": "Inscrivez-vous avec Facebook",
  "createAnAccountText": "CRÉER UN COMPTE",
  "registeredCustomersText": "Clients enregistrés",
  "signInDescriptionText":
      "Si vous avez un compte, connectez-vous avec votre\nadresse e-mail.",
  "forgotYourPasswordText": "Mot de passe oublié?",
  "signInText": "S'identifier",
  "newCustomersText": "nouveaux clients",
  "newCustomersDescriptionText":
      "La création d'un compte présente de nombreux avantages :\npaiement plus rapide, conservation de plusieurs adresses,\nsuivi des commandes, etc.",
  "createAccountText": "Créer un compte",
  "aboutProjectNameText": "À propos des marques et labels",
  "helpAndInformationText": "Aide et informations",
  "moreFromProjectText": "Plus de Brands&Labels",
  "newsLetterText": "Bulletin",
  "subscribeText": "S'abonner",
  "loginWithFacebookText": "Se connecter avec Facebook",
  "suvAndNatHeaderText": "TROUVEZ-LE MOINS CHER, NOUS BATTONS CE PRIX",
  "homeText": "Maison",
  "searchText": "Rechercher",
  "designersText": "Créateurs",
  "wishListText": "Liste de souhaits",
  "loginText": "Connexion",
  "myAccountText": "Mon compte",
  "checkoutText": "Vérifier",
  "shippingAddressText": "Adresse de livraison",
  "shippingMethodText": "Mode de livraison",
  "paymentMethodText": "Mode de paiement",
  "orderSummaryText": "Récapitulatif de la commande",
  "createCheckoutText": "Vous pouvez créer un compte après le paiement.",
  "stLineText": "Adresse municipale : ligne",
  "indiaText": "Inde",
  "regionText": "Veuillez sélectionner une région, un état ou une province",
  "zipCodeText": "Zip / code postal",
  "phoneNumberText": "Numéro de téléphone",
  "qtyText": "Qté",
  "enterDiscountCodeText": "Entrez le code de réduction",
  "applyText": "Appliquer",
  "placeOrderText": "PASSER LA COMMANDE",
  "myOrdersText": "MES COMMANDES",
  "myWishlistText": "Ma liste d'envies",
  "addressBookText": "Carnet d'adresses",
  "accountInformationText": "Information sur le compte",
  "storePaymentText": "MÉTHODES DE PAIEMENT MÉMORISÉES",
  "news1LetterText": "ABONNEMENT À LA NEWSLETTER",
  "affiliateProgramText": "Programme d'affiliation",
};
