const Map<String, String> it = {
  "language": "inglese",
  "appNameText": "Suv n Nat",
  "aboutUsText": "Chi siamo",
  "aboutUsTitle":
      "SUV & NAT È UNA MASSIMA DESTINAZIONE DELLA MODA DI LUSSO ONLINE CON 5 MILIONI DI VISITATORI AL MESE E SPEDIZIONI IN TUTTO IL MONDO.",
  "aboutUsContain":
      '''Il sito web presenta la migliore selezione dei migliori designer affermati e giovani talenti emergenti. Brandslabels nasce a Firenze nei primi anni '30, con l'apertura dell'omonimo concept store in Via Roma. Online dal 1999, l'azienda attribuisce il 90% dei ricavi totali alle vendite online. Ad oggi rimane un'azienda familiare al 100% privata, con il nipote del fondatore, Andrea Panconesi in qualità di CEO e sua figlia, Annagreta Panconesi come Direttore Creativo.''',
  "aboutUsContain1":
      '''Il sito offre un'ampia selezione di abbigliamento, scarpe, borse, accessori, interni di lusso per la casa e bellezza, con prodotti disponibili per uomo, donna e bambino dei designer più prestigiosi come Balenciaga, Vetements, Off-White, J.W. Anderson, Balmain, Dolce & Gabbana, Gucci, Saint Laurent, Valentino, Givenchy, Loewe, Jacquemus e altri.''',
  "aboutUsContain2":
      '''Attualmente ci sono 200 persone provenienti da 15 paesi diversi che lavorano per produrre e mantenere le etichette dei marchi. Il sito è disponibile in 9 lingue: inglese, italiano, tedesco, cinese, russo, spagnolo, francese, coreano e giapponese. Il sito è realizzato interamente in house, con la sede di Firenze che ospita gli uffici di progettazione grafica, IT, customer service, marketing e buying. Gli stilisti ei team stampa operano dall'ufficio Suvandnats nella capitale mondiale della moda – Milano.''',
  "aboutUsContain3":
      'Tutti gli ordini vengono spediti in tutto il mondo dalla sede di Suvandnats in scatole preparate con la massima cura e utilizzando i migliori materiali, dalle esclusive borse per scarpe al nastro personalizzato.',
  "aboutUsContain4":
      'Suvandnats ha avuto 1,5 milioni di visitatori unici che hanno avuto accesso al sito nel 2008 ed è cresciuto fino a raggiungere i 53 milioni di visitatori unici nel 2017. Oltre il 15% delle vendite online è generato dagli Stati Uniti, seguiti da Germania, Regno Unito, Italia, Cina e Francia.',
  "aboutUsContain5":
      'Suvandnats spinge i confini del panorama del retail di lusso sia online che offline con una serie di servizi esclusivi e iniziative di marchio tra cui Buy It First, Luxury Club,Sneakers Club, LVR Privilege e LVR Editions.',
  "profile": "Profilo",
  "firstNameText": "Nome di battesimo",
  "lastNameText": "Cognome",
  "emailText": "E-mail",
  "ContactNoText": "Contatto n.",
  "websiteUrlText": "URL del sito",
  "cityText": "Città",
  "countryText": "Paese",
  "postCodeText": "Codice postale",
  "socialLinksText": "Collegamenti sociali",
  "facebookText": "Facebook",
  "instagramText": "Instagram",
  "twitterText": "Twitter",
  "youtubeText": "Youtube",
  "linkendinText": "Linkendin",
  "pinterestText": "Pinterest",
  "followersText": "Seguaci",
  "mr": "Sig.",
  "letsText": "Andiamo",
  "orderIdTitle": '''Il tuo ordine n. è: ''',
  "orderDateTitle": '''Data dell'ordine: 8 settembre 2021''',
  "orderExpectedSDTitle": 'Data di spedizione prevista: ',
  "orderConfirm": "GRAZIE PER IL VOSTRO ACQUISTO!",
  "name": "NOME",
  "image": "IMMAGINE",
  "price": "PREZZO",
  "qty": "QTÀ",
  "subTotal": "TOTALE PARZIALE",
  "billingAddress": "Indirizzo Di Fatturazione",
  "shippingAddress": "indirizzo di spedizione",
  "paymentMethod": "Metodo di pagamento",
  "cashOnDelivery": "Pagamento alla consegna",
  "continueShopping": "CONTINUA A FARE ACQUISTI",
  "trackYourOrder": "RINTRACCIA IL TUO ORDINE",
  "orderContain":
      '''Ti invieremo un'e-mail di conferma dell'ordine con i dettagli e le informazioni di tracciamento.''',
  "referFriendText": "Segnala amico",
  "returnsRefundsText": "Resi e rimborsi",
  "faqText": "FAQ",
  "contactText": "Contatto",
  "socialText": "Sociale",
  "companyText": "Azienda",
  "contactUs": "Contattaci",
  "myOrders": "i miei ordini",
  "myOrderImage": "Immagine",
  "productName": "nome del prodotto",
  "sku": "SKU",
  "quantity": "Qtà",
  "status": "Stato",
  "action": "Azione",
  "createNewCustomerAccountText": "Crea un nuovo account cliente",
  "emailAddressText": "Indirizzo e-mail",
  "confirmEmailAddressText": "Conferma l'indirizzo e-mail",
  "passwordText": "Parola d'ordine",
  "confirmPasswordText": "Conferma password",
  "dateOfBirthText": "Data di nascita",
  "marriageAnniversaryText": "Anniversario di matrimonio",
  "signUpForNewsLetterText": "Iscriviti alla Newsletter",
  "registerWithFacebookText": "Registrati con Facebook",
  "createAnAccountText": "CREARE UN ACCOUNT",
  "registeredCustomersText": "Clienti registrati",
  "signInDescriptionText":
      "Se hai un account, accedi con il tuoindirizzo email.",
  "forgotYourPasswordText": "Hai dimenticato la password?",
  "signInText": "Registrazione",
  "newCustomersText": "nuovi clienti",
  "newCustomersDescriptionText":
      "La creazione di un account ha molti vantaggi:\ncontrolla più velocemente, mantieni più di un indirizzo,\ntieni traccia degli ordini e altro ancora.",
  "createAccountText": "Creare un account",
  "aboutProjectNameText": "Informazioni su marchi ed etichette",
  "helpAndInformationText": "Aiuto e informazioni",
  "moreFromProjectText": "Altro da Marchi ed etichette",
  "newsLetterText": "Lettera di notizie",
  "subscribeText": "sottoscrivi",
  "loginWithFacebookText": "Fai il login con facebook",
  "suvAndNatHeaderText": "TROVALO PIÙ ECONOMICO, BATTEREMO QUEL PREZZO",
  "homeText": "Casa",
  "searchText": "Ricerca",
  "designersText": "Designer",
  "wishListText": "Lista dei desideri",
  "loginText": "Login",
  "myAccountText": "Il mio conto",
  "checkoutText": "Guardare",
  "shippingAddressText": "indirizzo di spedizione",
  "shippingMethodText": "metodo di spedizione",
  "paymentMethodText": "Metodo di pagamento",
  "orderSummaryText": "Riepilogo ordine",
  "createCheckoutText": "Puoi creare un account dopo il checkout.",
  "stLineText": "Indirizzo: Linea",
  "indiaText": "India",
  "regionText": "Seleziona una regione, uno stato o una provincia",
  "zipCodeText": "Zip / Codice postale",
  "phoneNumberText": "Numero di telefono",
  "qtyText": "Qtà",
  "enterDiscountCodeText": "Inserisci il codice sconto",
  "applyText": "Applicare",
  "placeOrderText": "INVIA ORDINE",
  "myOrdersText": "I MIEI ORDINI",
  "myWishlistText": "La mia lista dei desideri",
  "addressBookText": "Rubrica",
  "accountInformationText": "Informazioni account",
  "storePaymentText": "METODI DI PAGAMENTO MEMORIZZATI",
  "news1LetterText": "ABBONAMENTI ALLA NEWSLETTER",
  "affiliateProgramText": "programma affiliato",
};
