const Map<String, String> ja = {
  "language": "英語",
  "appNameText": "Suv n Nat",
  "aboutUsText": "私たちに関しては",
  "aboutUsTitle":
      "SUV＆NATは、1か月あたり500万人の訪問者がおり、世界中に出荷されている、トップのオンラインラグジュアリーファッションデスティネーションです。",
  "aboutUsContain":
      '「このウェブサイトには、一流のデザイナーと若くて新しい才能の最高のセレクションが掲載されています。 Brandslabelsは、1930年代初頭にフィレンツェで設立され、ローマ通りに同社の名を冠したコンセプトストアがオープンしました。 1999年以来オンラインで、同社は総収益の90％をオンライン販売に帰しています。今日まで、創業者の孫であるAndrea PanconesiがCEOを務め、娘のAnnagreta Panconesiがクリエイティブディレクターを務める、100％個人経営の家族経営の会社です。」',
  "aboutUsContain1":
      'このサイトでは、バレンシアガ、ベテメンツ、オフホワイト、J.W。などの最も有名なデザイナーの男性、女性、子供向けの製品を取り揃え、衣料品、靴、バッグ、アクセサリー、高級インテリア、美容を幅広く取り揃えています。アンダーソン、バルマン、ドルチェ＆ガッバーナ、グッチ、サンローラン、バレンチノ、ジバンシィ、ロエベ、ジャックムスなど。',
  "aboutUsContain2":
      '現在、ブランドラベルの作成と維持に取り組んでいる15か国から200人がいます。このサイトは、英語、イタリア語、ドイツ語、中国語、ロシア語、スペイン語、フランス語、韓国語、日本語の9か国語で利用できます。このサイトは完全に社内で作成されており、フィレンツェのオフィスにはグラフィックデザイン、IT、カスタマーサービス、マーケティング、購入の各部門があります。スタイリストとプレスチームは、世界のファッションの中心地であるミラノにあるSuvandnatsオフィスで活動しています。',
  "aboutUsContain3":
      'すべての注文は、Suvandnats本社から、シグネチャーシューズバッグからパーソナライズされたリボンまで、細心の注意を払って準備され、最高の素材を使用したボックスで世界中に発送されます。',
  "aboutUsContain4":
      'Suvandnatsは2008年に150万人のユニークビジターがサイトにアクセスし、2017年には5300万人のユニークビジターに成長しました。オンライン売上の15％以上が米国からのもので、ドイツ、英国、イタリア、中国、フランスがそれに続きます。',
  "aboutUsContain5":
      'Suvandnatsは、Buy It First、Luxury Club、Sneakers Club、LVR Privilege、LVR Editionsなど、一連の独占的なサービスと商標イニシアチブにより、オンラインとオフラインの両方で高級小売業界の境界を押し広げています。',
  "profile": "プロフィール",
  "firstNameText": "ファーストネーム",
  "lastNameText": "苗字",
  "emailText": "Eメール",
  "ContactNoText": "連絡先番号。",
  "websiteUrlText": "ウェブサイトのURL",
  "cityText": "市",
  "countryText": "国",
  "postCodeText": "郵便番号",
  "socialLinksText": "ソーシャルリンク",
  "facebookText": "フェイスブック",
  "instagramText": "インスタグラム",
  "twitterText": "ツイッター",
  "youtubeText": "Youtube",
  "linkendinText": "リンケンディン",
  "pinterestText": "Pinterest",
  "followersText": "フォロワー",
  "mr": "氏。",
  "letsText": "さあ行こう",
  "orderIdTitle": '''ご注文番号：''',
  "orderDateTitle": '注文日：2021年9月8日',
  "orderExpectedSDTitle": '出荷予定日：',
  "orderConfirm": "ご購入いただきありがとうございます！",
  "name": "名前",
  "image": "画像",
  "price": "価格",
  "qty": "数量",
  "subTotal": "小計",
  "billingAddress": "請求先住所",
  "shippingAddress": "お届け先の住所",
  "paymentMethod": "支払方法",
  "cashOnDelivery": "代金引換",
  "continueShopping": "ショッピングを続ける",
  "trackYourOrder": "注文を追跡する",
  "orderContain": '詳細と追跡情報が記載された注文確認メールをお送りします。',
  "referFriendText": "友達を紹介する",
  "returnsRefundsText": "返品と返金",
  "faqText": "よくある質問",
  "contactText": "連絡先",
  "socialText": "社交",
  "companyText": "会社",
  "contactUs": "お問い合わせ",
  "myOrders": "私の注文",
  "myOrderImage": "画像",
  "productName": "商品名",
  "sku": "SKU",
  "quantity": "数量",
  "status": "スターテス",
  "action": "アクション",
  "createNewCustomerAccountText": "新しい顧客アカウントを作成する",
  "emailAddressText": "電子メールアドレス",
  "confirmEmailAddressText": "メールアドレスを確認",
  "passwordText": "パスワード",
  "confirmPasswordText": "パスワードを認証する",
  "dateOfBirthText": "生年月日",
  "marriageAnniversaryText": "結婚記念日",
  "signUpForNewsLetterText": "ニュースレターにサインアップ",
  "registerWithFacebookText": "Facebookに登録する",
  "createAnAccountText": "アカウントを作成する",
  "registeredCustomersText": "登録済みの客",
  "signInDescriptionText": "アカウントをお持ちの場合は、\nemailアドレスでサインインしてください。",
  "forgotYourPasswordText": "パスワードをお忘れですか？",
  "signInText": "サインイン",
  "newCustomersText": "新しいお客様",
  "newCustomersDescriptionText":
      "アカウントを作成することには多くの利点があります：\nより速くチェックアウトし、複数の住所を保持し、\n注文を追跡します。",
  "createAccountText": "アカウントを作成する",
  "aboutProjectNameText": "ブランドとラベルについて",
  "helpAndInformationText": "ヘルプと情報",
  "moreFromProjectText": "Brands＆Labelsのその他のアイテム",
  "newsLetterText": "ニュースレター",
  "subscribeText": "購読",
  "loginWithFacebookText": "Facebookでログイン",
  "suvAndNatHeaderText": "それをもっと安く見つけてください、私たちはその価格を打ち負かします",
  "homeText": "家",
  "searchText": "検索",
  "designersText": "デザイナー",
  "wishListText": "ウィッシュリスト",
  "loginText": "ログイン",
  "myAccountText": "マイアカウント",
  "checkoutText": "チェックアウト",
  "shippingAddressText": "お届け先の住所",
  "shippingMethodText": "配送方法",
  "paymentMethodText": "支払方法",
  "orderSummaryText": "注文の概要",
  "createCheckoutText": "チェックアウト後にアカウントを作成できます。",
  "stLineText": "住所：Line",
  "indiaText": "インド",
  "regionText": "地域、州、または州を選択してください",
  "zipCodeText": "郵便番号/郵便番号",
  "phoneNumberText": "電話番号",
  "qtyText": "数量",
  "enterDiscountCodeText": "割引コードを入力してください",
  "applyText": "申し込み",
  "placeOrderText": "注文する",
  "myOrdersText": "私の注文",
  "myWishlistText": "私のウィッシュリスト",
  "addressBookText": "住所録",
  "accountInformationText": "口座情報",
  "storePaymentText": "保管された支払い方法",
  "news1LetterText": "ニュースレターの購読",
  "affiliateProgramText": "アフィリエイトプログラム",
};
