const Map<String, String> ko = {
  "language": "영어",
  "appNameText": "수브앤낫",
  "aboutUsText": "회사 소개",
  "aboutUsTitle":
      "SUV & NAT는 월 500만 명의 방문자와 전 세계적으로 배송되는 최고의 온라인 럭셔리 패션 여행지입니다.",
  "aboutUsContain":
      '''웹사이트는 최고의 기성 디자이너와 젊은 신진 재능을 엄선하여 제공합니다. Brandslabels는 1930년대 초 피렌체에서 회사의 이름을 딴 컨셉 스토어를 Via Roma에 오픈하면서 설립되었습니다. 1999년부터 온라인으로 시작한 이 회사는 총 수익의 90%를 온라인 판매로 돌립니다. 오늘날까지 창립자의 손자 Andrea Panconesi가 CEO로, 그의 딸 Annagreta Panconesi가 크리에이티브 디렉터로 활동하는 100% 개인 소유의 가족 기업으로 남아 있습니다.''',
  "aboutUsContain1":
      '이 사이트는 Balenciaga, Vetements, Off-White, J.W. Anderson,Balmain, Dolce & Gabbana, Gucci, Saint Laurent, Valentino, Givenchy, Loewe, Jacquemus 등.',
  "aboutUsContain2":
      '현재 15개국에서 200명이 Brandslabels를 생산하고 유지하기 위해 일하고 있습니다. 이 사이트는 영어, 이탈리아어, 독일어, 중국어, 러시아어, 스페인어, 프랑스어, 한국어 및 일본어의 9개 언어로 제공됩니다. 이 사이트는 그래픽 디자인, IT, 고객 서비스, 마케팅 및 구매 부서가 있는 Florence 사무실과 함께 완전히 사내에서 만들어졌습니다. 스타일리스트와 언론팀은 세계 패션의 중심지인 밀라노에 있는 Suvandnats 사무실에서 일합니다.',
  "aboutUsContain3":
      '모든 주문은 Suvandnats 본사에서 시그니처 신발 가방에서 맞춤형 리본에 이르기까지 최고의 자재를 사용하여 최대한 주의를 기울여 준비된 상자에 담아 전 세계로 배송됩니다.',
  "aboutUsContain4":
      'Suvandnats는 2008년에 150만 명의 고유 방문자가 사이트에 액세스했으며 2017년에는 5300만 명의 고유 방문자로 성장했습니다. 온라인 판매의 15% 이상이 미국에서 발생하고 독일, 영국, 이탈리아, 중국 및 프랑스가 그 뒤를 잇습니다.',
  "aboutUsContain5":
      'Suvandnats는 Buy It First, Luxury Club, Sneakers Club, LVR Privilege 및 LVR Edition을 포함한 일련의 독점 서비스 및 상표 이니셔티브를 통해 온/오프라인 모두에서 럭셔리 소매 환경의 경계를 확장합니다.',
  "profile": "프로필",
  "firstNameText": "이름",
  "lastNameText": "성",
  "emailText": "이메일",
  "ContactNoText": "연락처",
  "websiteUrlText": "웹 사이트 주소",
  "cityText": "도시",
  "countryText": "국가",
  "postCodeText": "우편번호",
  "socialLinksText": "소셜 링크",
  "facebookText": "페이스북",
  "instagramText": "인스 타 그램",
  "twitterText": "트위터",
  "youtubeText": "유튜브",
  "linkendinText": "린켄딘",
  "pinterestText": "핀터레스트",
  "followersText": "팔로워",
  "mr": "씨.",
  "letsText": "갑시다",
  "orderIdTitle": '''주문 번호: ''',
  "orderDateTitle": '주문 날짜: 2021년 9월 8일',
  "orderExpectedSDTitle": '예상 배송 날짜: ',
  "orderConfirm": "구입 주셔서 감사합니다!",
  "name": "이름",
  "image": "영상",
  "price": "가격",
  "qty": "수량",
  "subTotal": "소계",
  "billingAddress": "청구 지 주소",
  "shippingAddress": "배송 주소",
  "paymentMethod": "지불 방법",
  "cashOnDelivery": "현금 배달",
  "continueShopping": "쇼핑을 계속",
  "trackYourOrder": "주문 추적",
  "orderContain": '세부 정보 및 추적 정보가 포함된 주문 확인 이메일을 보내드립니다.',
  "referFriendText": "친구 추천",
  "returnsRefundsText": "반품 및 환불",
  "faqText": "자주하는 질문",
  "contactText": "연락하다",
  "socialText": "사회의",
  "companyText": "회사",
  "contactUs": "문의하기",
  "myOrders": "내 주문",
  "myOrderImage": "영상",
  "productName": "상품명",
  "sku": "SKU",
  "quantity": "수량",
  "status": "상태",
  "action": "동작",
  "createNewCustomerAccountText": "새 고객 계정 만들기",
  "emailAddressText": "이메일 주소",
  "confirmEmailAddressText": "이메일 주소 확인",
  "passwordText": "비밀번호",
  "confirmPasswordText": "비밀번호 확인",
  "dateOfBirthText": "생일",
  "marriageAnniversaryText": "결혼 기념일",
  "signUpForNewsLetterText": "뉴스레터 신청",
  "registerWithFacebookText": "페이스북에 등록",
  "createAnAccountText": "계정 만들기",
  "registeredCustomersText": "등록된 고객",
  "signInDescriptionText": "계정이 있으면\ne메일 주소로 로그인하세요.",
  "forgotYourPasswordText": "비밀번호를 잊어 버렸습니까?",
  "signInText": "로그인",
  "newCustomersText": "신규 고객",
  "newCustomersDescriptionText":
      "계정을 만들면\n더 빠르게 체크아웃하고, 두 개 이상의 주소를 유지하고,\n주문을 추적하는 등 많은 이점이 있습니다.",
  "createAccountText": "계정 만들기",
  "aboutProjectNameText": "브랜드 및 레이블 정보",
  "helpAndInformationText": "도움말 및 정보",
  "moreFromProjectText": "Brands&Labels에서 더 많은 것",
  "newsLetterText": "뉴스 레터",
  "subscribeText": "구독하다",
  "loginWithFacebookText": "페이스북으로 로그인",
  "suvAndNatHeaderText": "더 저렴하게 찾아보세요, 우리는 그 가격을 이길 것입니다",
  "homeText": "집",
  "searchText": "검색",
  "designersText": "디자이너",
  "wishListText": "위시리스트",
  "loginText": "로그인",
  "myAccountText": "내 계정",
  "checkoutText": "점검",
  "shippingAddressText": "배송 주소",
  "shippingMethodText": "배송 방법",
  "paymentMethodText": "지불 방법",
  "orderSummaryText": "주문 요약",
  "createCheckoutText": "결제 후 계정을 생성할 수 있습니다.",
  "stLineText": "주소: 라인",
  "indiaText": "인도",
  "regionText": "지역, 주 또는 도를 선택하세요.",
  "zipCodeText": "우편번호",
  "phoneNumberText": "전화 번호",
  "qtyText": "수량",
  "enterDiscountCodeText": "할인 코드 입력",
  "applyText": "적용하다",
  "placeOrderText": "주문하기",
  "myOrdersText": "내 주문",
  "myWishlistText": "내 위시리스트",
  "addressBookText": "주소록",
  "accountInformationText": "계정 정보",
  "storePaymentText": "저장된 결제 방법",
  "news1LetterText": "뉴스레터 구독",
  "affiliateProgramText": "제휴 프로그램",
};
