const Map<String, String> nl = {
  "language": "Engels",
  "appNameText": "Suv n Nat",
  "aboutUsText": "Over ons",
  "aboutUsTitle":
      "SUV & NAT IS EEN TOP ONLINE LUXE MODEBESTEMMING MET 5 MILJOEN BEZOEKERS PER MAAND EN WERELDWIJDE VERZENDING.",
  "aboutUsContain":
      '''De website bevat de beste selectie van de beste gevestigde ontwerpers en jonge opkomende talenten. Brandslabels werd begin jaren dertig in Florence opgericht met de opening van de gelijknamige conceptstore van het bedrijf aan de Via Roma. Online sinds 1999 schrijft het bedrijf 90% van de totale omzet toe aan online verkopen. Tot op de dag van vandaag is het een 100% particulier familiebedrijf, met de kleinzoon van de oprichter, Andrea Panconesi als CEO en zijn dochter, Annagreta Panconesi als creatief directeur.''',
  "aboutUsContain1":
      'De site biedt een brede selectie van kleding, schoenen, tassen, accessoires, luxe interieurs en beauty, met producten voor mannen, vrouwen en kinderen van de meest prestigieuze ontwerpers zoals Balenciaga, Vetements, Off-White, J.W. Anderson, Balmain, Dolce & Gabbana, Gucci, Saint Laurent, Valentino, Givenchy, Loewe, Jacquemus en meer.',
  "aboutUsContain2":
      'Op dit moment werken 200 mensen uit 15 verschillende landen aan het produceren en onderhouden van Brandslabels. De site is beschikbaar in 9 talen: Engels, Italiaans, Duits, Chinees, Russisch, Spaans, Frans, Koreaans en Japans. De site is volledig in eigen beheer gemaakt, met de afdelingen grafisch ontwerp, IT, klantenservice, marketing en inkoop in Florence. De stylisten en persteams opereren vanuit het Suvandnats-kantoor in de modehoofdstad van de wereld - Milaan.',
  "aboutUsContain3":
      'Alle bestellingen worden wereldwijd verzonden vanuit het hoofdkantoor van Suvandnats in dozen die met maximale zorg zijn voorbereid en de beste materialen gebruiken, van de kenmerkende schoenentassen tot het gepersonaliseerde lint.',
  "aboutUsContain4":
      'Suvandnats had in 2008 1,5 miljoen unieke bezoekers op de site en is in 2017 gegroeid tot 53 miljoen unieke bezoekers. Meer dan 15% van de online verkopen wordt gegenereerd in de Verenigde Staten, gevolgd door Duitsland, het VK, Italië, China en Frankrijk.',
  "aboutUsContain5":
      'Suvandnats verlegt de grenzen van het luxe retaillandschap, zowel online als offline met een scala aan exclusieve diensten en handelsmerkinitiatieven, waaronder Buy It First, Luxury Club, Sneakers Club, LVR Privilege en LVR Editions.',
  "profile": "Profiel",
  "firstNameText": "Voornaam",
  "lastNameText": "Achternaam",
  "emailText": "E-mail",
  "ContactNoText": "Contactnr.",
  "websiteUrlText": "Website URL",
  "cityText": "Stad",
  "countryText": "Land",
  "postCodeText": "Postcode",
  "socialLinksText": "Sociale links",
  "facebookText": "Facebook",
  "instagramText": "Instagram",
  "twitterText": "Twitter",
  "youtubeText": "Youtube",
  "linkendinText": "Linkendin",
  "pinterestText": "Pinterest",
  "followersText": "Volgers",
  "mr": "Dhr.",
  "letsText": "Laten we gaan",
  "orderIdTitle": '''Uw bestelling # is: ''',
  "orderDateTitle": 'Besteldatum: 8 september 2021',
  "orderExpectedSDTitle": 'Verwachte verzenddatum: ',
  "orderConfirm": "DANK VOOR UW AANKOOP!",
  "name": "NAAM",
  "image": "AFBEELDING",
  "price": "PRIJS",
  "qty": "AANTAL",
  "subTotal": "SUBTOTAAL",
  "billingAddress": "factuur adres",
  "shippingAddress": "Verzendingsadres",
  "paymentMethod": "Betalingswijze",
  "cashOnDelivery": "Rembours",
  "continueShopping": "DOORGAAN MET WINKELEN",
  "trackYourOrder": "VOLG JE BESTELLING",
  "orderContain":
      'We sturen je een orderbevestiging met details en trackinginformatie.',
  "referFriendText": "Verwijs vriend",
  "returnsRefundsText": "Retourneren & Terugbetalingen",
  "faqText": "FAQ",
  "contactText": "Contact",
  "socialText": "sociaal",
  "companyText": "Bedrijf",
  "contactUs": "Neem contact op",
  "myOrders": "mijn bestellingen",
  "myOrderImage": "Afbeelding",
  "productName": "productnaam",
  "sku": "Artikelnummer",
  "quantity": "aantal",
  "status": "Toestand",
  "action": "Actie",
  "createNewCustomerAccountText": "Nieuw klantaccount aanmaken",
  "emailAddressText": "E-mailadres",
  "confirmEmailAddressText": "Bevestig dit Email adres",
  "passwordText": "Wachtwoord",
  "confirmPasswordText": "bevestig wachtwoord",
  "dateOfBirthText": "Geboortedatum",
  "marriageAnniversaryText": "Trouwdag",
  "signUpForNewsLetterText": "Aanmelden voor Nieuwsbrief",
  "registerWithFacebookText": "Registreer met Facebook",
  "createAnAccountText": "ACCOUNT AANMAKEN",
  "registeredCustomersText": "geregistreerde klanten",
  "signInDescriptionText":
      "Als je een account hebt, log dan in met je\nemailadres.",
  "forgotYourPasswordText": "Uw wachtwoord vergeten?",
  "signInText": "Aanmelden",
  "newCustomersText": "nieuwe klanten",
  "newCustomersDescriptionText":
      "Het aanmaken van een account heeft veel voordelen:\nsnel uitchecken, meer dan één adres bewaren,\nbestellingen volgen en meer.",
  "createAccountText": "Account aanmaken",
  "aboutProjectNameText": "Over merken en labels",
  "helpAndInformationText": "Hulp en informatie",
  "moreFromProjectText": "Meer van Brands&Labels",
  "newsLetterText": "Nieuwsbrief",
  "subscribeText": "Abonneren",
  "loginWithFacebookText": "Inloggen met Facebook",
  "suvAndNatHeaderText": "VIND HET GOEDKOPER, WE VERLATEN DIE PRIJS",
  "homeText": "Thuis",
  "searchText": "Zoekopdracht",
  "designersText": "Ontwerpers",
  "wishListText": "Verlanglijst",
  "loginText": "Log in",
  "myAccountText": "Mijn rekening",
  "checkoutText": "Uitchecken",
  "shippingAddressText": "Verzendingsadres",
  "shippingMethodText": "Verzendmethode:",
  "paymentMethodText": "Betalingswijze",
  "orderSummaryText": "overzicht van de bestelling",
  "createCheckoutText": "Na het afrekenen kun je een account aanmaken.",
  "stLineText": "Straat Adres: Lijn",
  "indiaText": "India",
  "regionText": "Selecteer een regio, staat of provincie",
  "zipCodeText": "Postcode/postcode",
  "phoneNumberText": "Telefoonnummer",
  "qtyText": "aantal",
  "enterDiscountCodeText": "Voer kortingscode in",
  "applyText": "Van toepassing zijn",
  "placeOrderText": "PLAATS BESTELLING",
  "myOrdersText": "MIJN BESTELLINGEN",
  "myWishlistText": "Mijn wenslijst",
  "addressBookText": "Adresboek",
  "accountInformationText": "Account Informatie",
  "storePaymentText": "OPGESLAGEN BETAALMETHODEN",
  "news1LetterText": "NIEUWSBRIEF ABONNEMENTEN",
  "affiliateProgramText": "Affiliate-programma",
};
