const Map<String, String> ru = {
  "language": "английский",
  "appNameText": "внедорожник и нат",
  "aboutUsText": "О нас",
  "aboutUsTitle":
      "SUV & NAT — ЛУЧШИЙ ОНЛАЙН-МОДНЫЙ МАГАЗИН РОСКОШИ С 5 МИЛЛИОНАМИ ПОСЕТИТЕЛЕЙ В МЕСЯЦ И ДОСТАВКОЙ ПО ВСЕМУ МИРУ.",
  "aboutUsContain":
      '''На веб-сайте представлен лучший выбор известных дизайнеров, а также молодых талантов. Brandslabels была основана во Флоренции в начале 1930-х годов с открытием одноименного концептуального магазина компании на Виа Рома. Работая в сети с 1999 года, компания приписывает 90% общего дохода онлайн-продажам. По сей день это остается на 100% частным семейным бизнесом, в котором внук основателя Андреа Панконези выступает в качестве генерального директора, а его дочь Аннагрета Панконези — в качестве креативного директора».''',
  "aboutUsContain1":
      'Сайт предлагает широкий выбор одежды, обуви, сумок, аксессуаров, роскошных предметов интерьера и косметики для мужчин, женщин и детей от самых престижных дизайнеров, таких как Balenciaga, Vetements, Off-White, J.W. Андерсон, Balmain, Dolce & Gabbana, Gucci, Saint Laurent, Valentino, Givenchy, Loewe, Jacquemus и другие.',
  "aboutUsContain2":
      'В настоящее время 200 человек из 15 разных стран работают над созданием и обслуживанием Brandslabels. Сайт доступен на 9 языках: английском, итальянском, немецком, китайском, русском, испанском, французском, корейском и японском. Сайт создан полностью собственными силами, в офисе во Флоренции находятся отделы графического дизайна, информационных технологий, обслуживания клиентов, маркетинга и закупок. Стилисты и пресс-служба работают в офисе Suvandnats в столице мира моды – Милане.',
  "aboutUsContain3":
      'Все заказы отправляются по всему миру из штаб-квартиры Suvandnats в коробках, которые готовятся с максимальной тщательностью и с использованием лучших материалов, от фирменных сумок для обуви до персонализированной ленты.',
  "aboutUsContain4":
      'В 2008 году на сайт Suvandnats заходили 1,5 миллиона уникальных посетителей, а в 2017 году число уникальных посетителей выросло до 53 миллионов. Более 15% онлайн-продаж приходится на США, за которыми следуют Германия, Великобритания, Италия, Китай и Франция.',
  "aboutUsContain5":
      'Suvandnats раздвигает границы розничной торговли предметами роскоши как онлайн, так и офлайн, предлагая множество эксклюзивных услуг и торговых марок, включая Buy It First, Luxury Club, Sneakers Club, LVR Privilege и LVR Editions.',
  "profile": "Профиль",
  "firstNameText": "Имя",
  "lastNameText": "Фамилия",
  "emailText": "Эл. адрес",
  "ContactNoText": "Контактный номер",
  "websiteUrlText": "ссылка на сайт",
  "cityText": "Город",
  "countryText": "Страна",
  "postCodeText": "Почтовый индекс",
  "socialLinksText": "Социальные ссылки",
  "facebookText": "Фейсбук",
  "instagramText": "Инстаграм",
  "twitterText": "Твиттер",
  "youtubeText": "YouTube",
  "linkendinText": "Линкендин",
  "pinterestText": "Пинтерест",
  "followersText": "Последователи",
  "mr": "Г-н.",
  "letsText": "Пойдем",
  "orderIdTitle": 'Ваш заказ №: ',
  "orderDateTitle": 'Дата заказа: 8 сентября 2021 г.',
  "orderExpectedSDTitle": 'Ожидаемая дата отгрузки: .',
  "orderConfirm": "СПАСИБО ЗА ПОКУПКУ!",
  "name": "ИМЯ",
  "image": "ИЗОБРАЖЕНИЕ",
  "price": "ЦЕНА",
  "qty": "КОЛ-ВО",
  "subTotal": "ПРОМЕЖУТОЧНЫЙ ИТОГ",
  "billingAddress": "Адрес для выставления счета",
  "shippingAddress": "адреса доставки",
  "paymentMethod": "Способ оплаты",
  "cashOnDelivery": "Оплата при доставке",
  "continueShopping": "ПРОДОЛЖИТЬ ПОКУПКИ",
  "trackYourOrder": "ОТСЛЕДИТЬ ВАШ ЗАКАЗ",
  "orderContain":
      'Мы отправим вам подтверждение заказа по электронной почте с деталями и информацией для отслеживания.',
  "referFriendText": "Пригласить друга",
  "returnsRefundsText": "Возвраты и возмещения",
  "faqText": "Вопросы-Ответы",
  "contactText": "Контакт",
  "socialText": "Социальное",
  "companyText": "Компания",
  "contactUs": "Связаться с нами",
  "myOrders": "мои заказы",
  "myOrderImage": "Изображение",
  "productName": "наименование товара",
  "sku": "Артикул",
  "quantity": "Кол-во",
  "status": "Положение дел",
  "action": "Действие",
  "createNewCustomerAccountText": "Создать новую учетную запись клиента",
  "emailAddressText": "Адрес электронной почты",
  "confirmEmailAddressText": "Подтвердите адрес электронной почты",
  "passwordText": "Пароль",
  "confirmPasswordText": "Подтвердить Пароль",
  "dateOfBirthText": "Дата рождения",
  "marriageAnniversaryText": "Годовщина свадьбы",
  "signUpForNewsLetterText": "Подписаться на рассылку",
  "registerWithFacebookText": "Зарегистрируйтесь через Facebook",
  "createAnAccountText": "ЗАВЕСТИ АККАУНТ",
  "registeredCustomersText": "Зарегистрированные клиенты",
  "signInDescriptionText":
      "Если у вас есть учетная запись, войдите, используя свой\nemail адрес.",
  "forgotYourPasswordText": "Забыли Ваш пароль?",
  "signInText": "Войти",
  "newCustomersText": "новые клиенты",
  "newCustomersDescriptionText":
      "Создание учетной записи имеет много преимуществ:\nбыстрее оформить заказ, сохранить несколько адресов,\nотслеживать заказы и многое другое.",
  "createAccountText": "Завести аккаунт",
  "aboutProjectNameText": "О брендах и лейблах",
  "helpAndInformationText": "Помощь и информация",
  "moreFromProjectText": "Еще от Brands&Labels",
  "newsLetterText": "Новостная рассылка",
  "subscribeText": "Подписаться",
  "loginWithFacebookText": "Войти с Facebook",
  "suvAndNatHeaderText": "НАЙДИТЕ ДЕШЕВЛЕ, МЫ СНИЖЕМ ЭТУ ЦЕНУ",
  "homeText": "Дома",
  "searchText": "Поиск",
  "designersText": "Дизайнеры",
  "wishListText": "Список желаний",
  "loginText": "Авторизоваться",
  "myAccountText": "Мой счет",
  "checkoutText": "Проверить",
  "shippingAddressText": "адреса доставки",
  "shippingMethodText": "способ доставки",
  "paymentMethodText": "Способ оплаты",
  "orderSummaryText": "итог заказа",
  "createCheckoutText":
      "Вы можете создать учетную запись после оформления заказа.",
  "stLineText": "Улица Адрес: Линия",
  "indiaText": "Индия",
  "regionText": "Выберите регион, штат или провинцию",
  "zipCodeText": "Почтовый индекс",
  "phoneNumberText": "Телефонный номер",
  "qtyText": "Кол-во",
  "enterDiscountCodeText": "Введите код скидки",
  "applyText": "Применять",
  "placeOrderText": "РАЗМЕСТИТЬ ЗАКАЗ",
  "myOrdersText": "МОИ ЗАКАЗЫ",
  "myWishlistText": "Мой список пожеланий",
  "addressBookText": "Адресная книга",
  "accountInformationText": "Информация об аккаунте",
  "storePaymentText": "СОХРАНЕННЫЕ СПОСОБЫ ОПЛАТЫ",
  "news1LetterText": "ПОДПИСКА НА РАССЫЛКУ",
  "affiliateProgramText": "Партнерская программа",
};
