include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**]
  language:
    strict-casts: true
    strict-inference: true

  errors:
    argument_type_not_assignable: error
    avoid_unnecessary_containers: error
    avoid_bool_literals_in_conditional_expressions: error
    avoid_catches_without_on_clauses: warning
    always_declare_return_types: error
    avoid_positional_boolean_parameters: error
    avoid_void_async: error
    avoid_print: warning
    avoid_web_libraries_in_flutter: error
    curly_braces_in_flow_control_structures: warning
    constant_identifier_names: false
    file_names: warning
    invalid_assignment: error
    missing_return: error
    missing_required_param: error
    prefer_if_null_operators: error
    prefer_typing_uninitialized_variables: error
    prefer_is_empty: error
    prefer_interpolation_to_compose_strings: error
    prefer_final_fields: error
    prefer_constructors_over_static_methods: error
    prefer_const_declarations: error
    prefer_const_constructors: error
    prefer_collection_literals: error
    prefer_final_locals: error
    prefer_const_literals_to_create_immutables: error
    prefer_if_elements_to_conditional_expressions: error
    parameter_assignments: error
    type_annotate_public_apis: error
    unnecessary_this: error
    unused_local_variable: error
    unused_import: error
    unused_field: error
